import { DocumentRepository, ProjectRepository, WorkflowPersistenceService } from "@/persistence/database/repositories";
import type { PersistenceDatabase } from "@/persistence/database/types";
import type { SecurityReviewInput } from "@/agents/reviewers/security/contracts";
import { SecurityReviewService } from "@/agents/reviewers/security/service";

export class SecurityReviewOrchestrationService {
  private readonly workflow: WorkflowPersistenceService; private readonly projects: ProjectRepository; private readonly documents: DocumentRepository;
  constructor(private readonly database: PersistenceDatabase, private readonly reviewer = new SecurityReviewService(database)) { this.workflow = new WorkflowPersistenceService(database); this.projects = new ProjectRepository(database); this.documents = new DocumentRepository(database); }
  get reviewerService() { return this.reviewer; }
  async enterReview(input: { projectId: string; projectVersion: number; expectedRowVersion: number; idempotencyKey: string }) { const current = await this.projects.getWithVersion(input.projectId); if (!current || current.project.workflowState === "SECURITY_REVIEW") return { rowVersion: current?.rowVersion ?? input.expectedRowVersion, projectState: "SECURITY_REVIEW" as const }; const transition = await this.workflow.transition({ projectId: input.projectId, projectVersion: input.projectVersion, expectedState: current.project.workflowState === "VALIDATING" ? "VALIDATING" : "CODE_INTEGRATION_REVIEW", expectedRowVersion: input.expectedRowVersion, targetState: "SECURITY_REVIEW", actor: "orchestrator", reason: "Code / Integration Review approved; deterministic security guards and Security Review are required.", idempotencyKey: input.idempotencyKey }); return { rowVersion: transition.rowVersion, projectState: "SECURITY_REVIEW" as const }; }
  async reviewAndRoute(input: SecurityReviewInput, signal?: AbortSignal) { const result = await this.reviewer.review(input, signal); const current = await this.projects.getWithVersion(input.projectId); if (result.verdict !== "APPROVED" || !current || current.project.workflowState !== "SECURITY_REVIEW") return { result, projectState: current?.project.workflowState ?? "SECURITY_REVIEW", rowVersion: current?.rowVersion ?? input.expectedRowVersion }; const transition = await this.workflow.transition({ projectId: input.projectId, projectVersion: input.projectVersion, expectedState: "SECURITY_REVIEW", expectedRowVersion: current.rowVersion, targetState: "VALIDATING", actor: "security-reviewer", reason: "Current Security Review approved the implementation security properties.", idempotencyKey: `${input.idempotencyKey}:approved` }); return { result, projectState: "VALIDATING" as const, rowVersion: transition.rowVersion }; }
  async getCurrentReview(projectId: string, projectVersion: number, sourceChecksum: string, codeIntegrationReviewChecksum: string) { return this.reviewer.getCurrentReview(projectId, projectVersion, sourceChecksum, codeIntegrationReviewChecksum); }
  async getExecutionSummary(projectId: string, projectVersion: number) { return this.documents.get(projectId, projectVersion, "full-execution"); }
}
