import { z } from "zod";
import { ClarificationCategorySchema, ClarificationQuestionIdSchema, RequirementSpecificationSchema, type ClarificationSession } from "@/domain/requirements/schema";
import { WorkflowStateSchema } from "@/domain/project/schema";
import { ProjectOriginSchema } from "@/domain/project/provenance";
import { LanguageObservationSchema, LanguageResolutionSchema, SiteLanguageDecisionSchema, OperatorLanguageSchema } from "@/domain/language/schema";
import { ProjectAssetReferenceSchema } from "@/domain/assets/project";

export const RequirementCategorySchema = z.enum(["project-identity", "business-purpose", "audience", "project-type", "pages", "functionality", "user-roles", "content", "contact", "legal", "languages", "localization", "design", "brand", "logo", "image-sourcing", "authentication", "forms", "email", "database", "storage", "administration", "seo", "integrations", "GitHub", "constraints", "exclusions"]);
export const RequirementClassificationSchema = z.enum(["explicit", "confirmed", "pending-confirmation", "recommendation", "unresolved"]);
export const RequirementEvidenceSchema = z.object({ sourceType: z.enum(["original-prompt", "prior-answer", "supplied-file", "system-default"]), reference: z.string().min(1), excerpt: z.string().min(1) }).strict();
export const ExtractedRequirementSchema = z.object({ key: z.string().min(1), category: RequirementCategorySchema, value: z.string().min(1), classification: RequirementClassificationSchema, evidence: z.array(RequirementEvidenceSchema).min(1), userConfirmed: z.boolean() }).strict();
export type ExtractedRequirement = z.infer<typeof ExtractedRequirementSchema>;
export const LeadAgentInputSchema = z.object({ projectId: z.string().uuid(), projectVersion: z.number().int().positive(), originalPrompt: z.string(), suppliedFiles: z.array(z.object({ path: z.string().min(1), kind: z.string().min(1), sha256: z.string().regex(/^[a-f0-9]{64}$/).optional() }).strict()).default([]), availableAssets: z.array(ProjectAssetReferenceSchema).default([]), knownUserAnswers: z.record(z.string(), z.string()).default({}), currentWorkflowState: WorkflowStateSchema, idempotencyKey: z.string().min(1), operatorLanguage: OperatorLanguageSchema.optional().default("en"), siteLanguage: SiteLanguageDecisionSchema.optional().default("UNRESOLVED"), languageResolution: LanguageResolutionSchema.optional(), projectSlug: z.string().optional(), projectTitle: z.string().optional(), origin: ProjectOriginSchema.optional().default("USER") }).strict();
export type LeadAgentInput = z.input<typeof LeadAgentInputSchema>;
export const LeadAgentAnalysisSchema = z.object({ projectId: z.string().uuid(), projectVersion: z.number().int().positive(), originalPromptChecksum: z.string().regex(/^[a-f0-9]{64}$/), operatorLanguage: OperatorLanguageSchema.default("en"), siteLanguage: SiteLanguageDecisionSchema.default("UNRESOLVED"), languageResolution: LanguageResolutionSchema.optional(), languageObservation: LanguageObservationSchema.optional(), directlyStatedFacts: z.array(ExtractedRequirementSchema), userPreferences: z.array(ExtractedRequirementSchema), inferredRecommendations: z.array(ExtractedRequirementSchema), unresolvedQuestions: z.array(ExtractedRequirementSchema), contradictions: z.array(z.object({ code: z.literal("REQUIREMENT_CONTRADICTION"), subjects: z.array(z.string()).min(2), explanation: z.string().min(1) }).strict()), unsupportedAssumptions: z.array(z.string()), confirmationRequired: z.array(z.string()), provider: z.object({ name: z.string(), model: z.string().nullable(), used: z.boolean(), inputTokens: z.number().int().nonnegative().nullable(), outputTokens: z.number().int().nonnegative().nullable() }).strict() }).strict();
export type LeadAgentAnalysis = z.infer<typeof LeadAgentAnalysisSchema>;
/** Strict provider transport shape. Host-owned project identity and language context are bound by the adapter. */
export const LeadAnalysisProviderOutputSchema = LeadAgentAnalysisSchema.omit({ projectId: true, projectVersion: true, originalPromptChecksum: true, operatorLanguage: true, siteLanguage: true, languageResolution: true, languageObservation: true }).extend({ languageObservation: LanguageObservationSchema.nullable() }).strict();
export type LeadAnalysisProviderOutput = z.infer<typeof LeadAnalysisProviderOutputSchema>;
export const ClarificationPlanSchema = z.object({ projectId: z.string().uuid(), projectVersion: z.number().int().positive(), operatorLanguage: OperatorLanguageSchema.default("en"), questions: z.array(z.object({ id: ClarificationQuestionIdSchema, requirementKey: z.string().min(1), category: ClarificationCategorySchema, question: z.string().min(1), reason: z.string().min(1), blocking: z.boolean(), required: z.boolean(), fingerprint: z.string().min(1) }).strict()), generatedAt: z.string().datetime() }).strict();
export type ClarificationPlan = z.infer<typeof ClarificationPlanSchema>;
/** Strict clarification transport shape. The current project and operator language are host-owned. */
export const ClarificationPlanProviderOutputSchema = ClarificationPlanSchema.omit({ projectId: true, projectVersion: true, operatorLanguage: true }).strict();
export type ClarificationPlanProviderOutput = z.infer<typeof ClarificationPlanProviderOutputSchema>;
export type ClarificationProposalInput = { analysis: LeadAgentAnalysis; session?: ClarificationSession; operatorLanguage: z.infer<typeof OperatorLanguageSchema>; siteLanguage: z.infer<typeof SiteLanguageDecisionSchema>; availableAssets: z.infer<typeof ProjectAssetReferenceSchema>[] };
export const BriefEvidenceSchema = z.object({ field: z.string().min(1), source: z.string().min(1), excerpt: z.string().min(1) }).strict();
export const BriefDraftSchema = z.object({ projectId: z.string().uuid(), projectVersion: z.number().int().positive(), requirements: RequirementSpecificationSchema, facts: z.array(ExtractedRequirementSchema), recommendations: z.array(ExtractedRequirementSchema), unresolvedItems: z.array(z.object({ key: z.string(), description: z.string(), blocking: z.boolean() }).strict()), evidence: z.array(BriefEvidenceSchema), readyForApproval: z.boolean(), blockingReasons: z.array(z.string()), nonBlockingWarnings: z.array(z.string()), briefChecksum: z.string().regex(/^[a-f0-9]{64}$/) }).strict();
export type BriefDraft = z.infer<typeof BriefDraftSchema>;
export const BriefApprovalRequestSchema = z.object({ projectId: z.string().uuid(), projectVersion: z.number().int().positive(), briefChecksum: z.string().regex(/^[a-f0-9]{64}$/), approvedAt: z.string().datetime(), approvedBy: z.string().min(1), approvalNote: z.string().optional(), expectedRowVersion: z.number().int().positive(), idempotencyKey: z.string().min(1) }).strict();
export type BriefApprovalRequest = z.infer<typeof BriefApprovalRequestSchema>;
export const BriefApprovalResultSchema = z.object({ brief: BriefDraftSchema, projectState: z.literal("AWAITING_DESIGN_SELECTION"), rowVersion: z.number().int().positive() }).strict();
export type BriefApprovalResult = z.infer<typeof BriefApprovalResultSchema>;
export const LeadAnalysisResultSchema = z.object({ analysis: LeadAgentAnalysisSchema, clarificationPlan: ClarificationPlanSchema.optional() }).strict();
export type LeadAnalysisResult = z.infer<typeof LeadAnalysisResultSchema>;
export type { ClarificationSession } from "@/domain/requirements/schema";
