import { createHash } from "node:crypto";
import { z } from "zod";
import { ClarificationCategorySchema, RequirementSpecificationSchema, type ClarificationSession } from "@/domain/requirements/schema";
import { canonicalAssetReference, emptyBriefV2Fields, type BriefRequirementEntry, type BriefV2Fields } from "@/domain/requirements/brief";
import { validateBriefContradictions } from "@/domain/requirements/brief-validation";
import { checksumPersistedDocument } from "@/persistence/database/serialization";
import { ClarificationPlanSchema, ExtractedRequirementSchema, LeadAgentAnalysisSchema, type BriefDraft, type ClarificationPlan, type ExtractedRequirement, type LeadAgentAnalysis, type LeadAgentInput } from "./contracts";
import { isWorkflowRequirement } from "./clarification-policy";
import { normalizeSiteLanguage, resolveLanguageAuthority } from "@/domain/language/schema";

const deterministicRunTimestamp = new Date().toISOString();
const now = () => deterministicRunTimestamp;
const hash = (value: string) => createHash("sha256").update(value).digest("hex");
const normalize = (value: string) => value.replace(/\r\n?/g, "\n");
const stableId = (value: string) => { const bytes = Buffer.from(hash(value).slice(0, 32), "hex"); bytes[6] = (bytes[6] & 15) | 80; bytes[8] = (bytes[8] & 63) | 128; const hex = bytes.toString("hex"); return `${hex.slice(0, 8)}-${hex.slice(8, 12)}-${hex.slice(12, 16)}-${hex.slice(16, 20)}-${hex.slice(20)}`; };
const lineValue = (prompt: string, labels: string[]) => prompt.match(new RegExp(`(?:^|\\n)\\s*(?:${labels.join("|")})\\s*[:=-]\\s*([^\\n]+)`, "i"))?.[1]?.trim();
const evidence = (excerpt: string, sourceType: "original-prompt" | "prior-answer" | "supplied-file" | "system-default" = "original-prompt", reference = "prompt") => [{ sourceType, reference, excerpt }];
const extracted = (key: string, category: ExtractedRequirement["category"], value: string, classification: ExtractedRequirement["classification"], source = evidence(value)) => ExtractedRequirementSchema.parse({ key, category, value, classification, evidence: source, userConfirmed: classification === "explicit" || classification === "confirmed" });
const splitPromptClauses = (value: string) => value.split(/[.!?;\n]+/u).map((clause) => clause.trim()).filter(Boolean);
const negativeLanguage = /(?:^|\s)(?:no|not|without|never|do\s+not|don['’]t|forbid\w*|prohibit\w*|kein\w*|keine\w*|ohne|nicht)\b|(?:not|nicht)\s+(?:needed|required|erforderlich|ben\w*|gebraucht)/iu;
const placeholderLanguage = /(?:placeholder|platzhalter|not\s+(?:provided|supplied)|to\s+be\s+supplied|tbd|pending|noch\s+offen|nicht\s+angegeben|\[[^\]]*\])/iu;
const capabilityIsNegated = (prompt: string, capability: RegExp) => splitPromptClauses(prompt).some((clause) => capability.test(clause) && negativeLanguage.test(clause));
const unsupportedClaimIsExplicit = (prompt: string, subject: RegExp) => splitPromptClauses(prompt).some((clause) => subject.test(clause) && !placeholderLanguage.test(clause) && !negativeLanguage.test(clause));

export function analyzePromptDeterministically(input: LeadAgentInput): LeadAgentAnalysis {
  const prompt = normalize(input.originalPrompt); const facts: ExtractedRequirement[] = []; const preferences: ExtractedRequirement[] = []; const recommendations: ExtractedRequirement[] = []; const unresolved: ExtractedRequirement[] = [];
  const resolvedLanguage = resolveLanguageAuthority({ prompt, explicitOperatorLanguage: input.operatorLanguage, explicitSiteLanguage: input.siteLanguage !== "UNRESOLVED" ? input.siteLanguage : undefined });
  const languageResolution = input.languageResolution ?? (input.siteLanguage === "UNRESOLVED" && resolvedLanguage.siteLanguageSource === "INHERITED_OPERATOR"
    ? { ...resolvedLanguage, siteLanguage: "UNRESOLVED" as const, siteLanguageSource: "AMBIGUOUS" as const, status: "AMBIGUOUS" as const }
    : resolvedLanguage);
  const add = (key: string, category: ExtractedRequirement["category"], labels: string[], target = facts) => { const value = lineValue(prompt, labels); if (value) target.push(extracted(key, category, value, "explicit")); };
  add("project-title", "project-identity", ["title", "project name", "name"]); add("business-purpose", "business-purpose", ["purpose", "business purpose", "goal"]); add("target-audience", "audience", ["audience", "target audience", "users"]); add("project-type", "project-type", ["type", "project type"]); add("pages", "pages", ["pages", "routes"]); add("functionality", "functionality", ["functionality", "features", "function"]); add("languages", "languages", ["language", "languages", "locales"]); add("brand", "brand", ["brand", "branding"]); add("logo", "logo", ["logo"]); add("images", "image-sourcing", ["images", "image source", "imagery"]); add("authentication", "authentication", ["authentication", "auth", "accounts"]); add("contact", "contact", ["contact", "contact details"]); add("legal", "legal", ["legal", "legal facts"]); add("acceptance", "constraints", ["acceptance", "done when"]); add("page-content", "content", ["content", "page content", "copy"]);
  if (languageResolution.siteLanguage !== "UNRESOLVED" && languageResolution.siteLanguageSource === "PROMPT_DETECTED" && !facts.some((fact) => fact.key === "languages")) {
    facts.push(extracted("languages", "languages", languageResolution.siteLanguage, "explicit", evidence(languageResolution.siteLanguage, "original-prompt", "site-language")));
  }
  for (const asset of (input.availableAssets ?? []).filter((candidate) => candidate.status === "READY" && candidate.currentness === "CURRENT")) {
    if (asset.category === "LOGO" && !facts.some((fact) => fact.key === "logo")) facts.push(extracted("logo", "logo", "A ready user-supplied logo asset is available.", "explicit", evidence(asset.safeDisplayName, "supplied-file", asset.assetId)));
    if ((asset.category === "IMAGE" || asset.category === "REFERENCE") && !facts.some((fact) => fact.key === "image-source")) facts.push(extracted("image-source", "image-sourcing", "User-supplied project assets are available.", "explicit", evidence(asset.safeDisplayName, "supplied-file", asset.assetId)));
  }
  const explicitAcceptance = lineValue(prompt, ["acceptance", "done when"]);
  if (explicitAcceptance) facts.push(extracted("acceptance", "constraints", `Acceptance: ${explicitAcceptance}`, "explicit"));
  if (/simple|public|marketing|brochure|no auth|without auth/i.test(prompt)) recommendations.push(extracted("authentication", "authentication", "No authentication / guest-first may be appropriate", "recommendation", evidence("deterministic recommendation", "system-default", "policy")));
  const protectedCapability = /\b(?:protected|dashboard|account|saved|private|role|admin|booking|reservation|persist(?:ence)?|database|backend)\b/iu;
  if (protectedCapability.test(prompt) && !capabilityIsNegated(prompt, protectedCapability)) preferences.push(extracted("protected-functionality", "authentication", "Protected or persisted functionality is required", "pending-confirmation"));
  const storageCapability = /\b(?:upload(?:s|ing)?|media\s+library|managed\s+media|storage(?:\s+service)?|medien(?:speicher|verwaltung))\b/iu;
  if (storageCapability.test(prompt) && !capabilityIsNegated(prompt, storageCapability)) preferences.push(extracted("storage", "storage", "Uploads or managed media are required", "pending-confirmation"));
  const emailCapability = /\b(?:email\s+(?:notification|delivery|confirmation|verification|submission)|send\s+(?:an?\s+)?email|smtp|notifications?|benachrichtig(?:ung|ungen)|kontaktformular\s+(?:mit\s+)?(?:email|benachrichtigung))\b|\bcontact\s+form\s+(?:with\s+)?(?:email|notification|submission)\b/iu;
  if (emailCapability.test(prompt) && !capabilityIsNegated(prompt, emailCapability)) preferences.push(extracted("email", "email", "Email or notification behavior is required", "pending-confirmation"));
  if (/all ai|ai-generated/i.test(prompt)) facts.push(extracted("image-source", "image-sourcing", "AI-generated", "explicit")); else if (/user-supplied images?|provided images?/i.test(prompt)) facts.push(extracted("image-source", "image-sourcing", "User-supplied", "explicit"));
  if (/no admin|without admin/i.test(prompt)) facts.push(extracted("administration", "administration", "No administration panel", "explicit")); else if (/admin|manage content|edit content/i.test(prompt)) facts.push(extracted("administration", "administration", "Administration is required", "explicit"));
  if (/images?|photos?|illustrations?|hero/i.test(prompt) && !facts.some((fact) => fact.key === "images")) unresolved.push(extracted("image-source", "image-sourcing", "A project image source is required.", "unresolved"));
  const unsupportedBusinessFact = /\b(?:testimonials?|reviews?|certifications?|licenses?|years?\s+of\s+experience|guarantees?|vat|opening\s+hours|phone\s+numbers?|telephones?)\b/iu;
  const unsupportedAssumptions = unsupportedClaimIsExplicit(prompt, unsupportedBusinessFact) ? ["Business facts require explicit source verification."] : [];
  const contradictionText = [/no authentication.*(dashboard|private|account)/i.test(prompt) ? "Authentication conflicts with protected functionality." : "", /no backend.*(persist|booking|database|upload)/i.test(prompt) ? "Backend requirements conflict with persistence requirements." : "", /user-supplied.*ai-generated|ai-generated.*user-supplied/i.test(prompt) ? "Image source choices conflict." : ""].filter(Boolean);
  const result = { projectId: input.projectId, projectVersion: input.projectVersion, originalPromptChecksum: checksumPersistedDocument(prompt.trim()), operatorLanguage: languageResolution.operatorLanguage, siteLanguage: languageResolution.siteLanguage, languageResolution, languageObservation: { detectedPromptLanguage: languageResolution.detectedPromptLanguage, explicitOperatorLanguage: languageResolution.operatorLanguageSource === "EXPLICIT_OPERATOR" ? languageResolution.operatorLanguage : null, explicitSiteLanguage: languageResolution.siteLanguageSource === "EXPLICIT_SITE" || languageResolution.siteLanguageSource === "PROMPT_DETECTED" ? (languageResolution.siteLanguage === "UNRESOLVED" ? null : languageResolution.siteLanguage) : null }, directlyStatedFacts: facts, userPreferences: preferences, inferredRecommendations: recommendations, unresolvedQuestions: unresolved, contradictions: contradictionText.map((explanation) => ({ code: "REQUIREMENT_CONTRADICTION" as const, subjects: ["prompt", "requirements"], explanation })), unsupportedAssumptions, confirmationRequired: contradictionText, provider: { name: "deterministic-rules", model: null, used: false, inputTokens: null, outputTokens: null } };
  return LeadAgentAnalysisSchema.parse(result);
}

type ClarificationCategory = z.infer<typeof ClarificationCategorySchema>;
const templates: Array<{ key: string; category: ClarificationCategory; question: string; reason: string; blocking: boolean; required: boolean }> = [
  { key: "operator-language", category: "languages", question: "Which language should I use for our conversation and clarification questions?", reason: "The Factory communication language is ambiguous.", blocking: true, required: true },
  { key: "business-purpose", category: "business", question: "What is the primary business purpose of this project?", reason: "The brief needs a confirmed purpose.", blocking: true, required: true },
  { key: "target-audience", category: "audience", question: "Who is the primary target audience?", reason: "Audience affects the brief.", blocking: true, required: true },
  { key: "languages", category: "languages", question: "Which primary language should the customer website use?", reason: "The customer website language is ambiguous.", blocking: true, required: true },
  { key: "pages", category: "pages", question: "Which pages or routes must the project include?", reason: "Page scope is required.", blocking: true, required: true },
  { key: "functionality", category: "functionality", question: "Which user-facing functionality is required?", reason: "Functionality must be explicit.", blocking: true, required: true },
  { key: "contact", category: "contact", question: "What verified contact information should be shown?", reason: "Contact facts cannot be invented.", blocking: true, required: true },
  { key: "image-source", category: "images", question: "How should images be sourced: AI-generated, user-supplied, AI plus user-supplied, placeholders, or custom?", reason: "Image sourcing requires user confirmation.", blocking: true, required: true },
  { key: "logo", category: "brand", question: "Will you supply a logo, and where is its metadata?", reason: "The Factory does not generate logos.", blocking: true, required: true },
  { key: "authentication", category: "authentication", question: "Is authentication required for protected functionality?", reason: "Protected functionality needs an explicit decision.", blocking: true, required: true },
  { key: "storage", category: "storage", question: "Are uploads or managed media storage required?", reason: "Storage is conditional on uploads.", blocking: true, required: true },
  { key: "email", category: "email", question: "What email or notification behavior is required?", reason: "Email behavior must be confirmed.", blocking: true, required: true },
  { key: "administration", category: "administration", question: "Does the project need post-release administration or editable content?", reason: "An admin panel is not added automatically.", blocking: false, required: false },
  { key: "acceptance", category: "constraints", question: "What user-visible acceptance criteria define a successful first release?", reason: "Approval requires acceptance criteria.", blocking: true, required: true },
];

const localizedTemplates: Record<string, Partial<Record<OperatorLanguage, { question: string; reason: string }>>> = {
  "operator-language": { de: { question: "Welche Sprache soll ich für unsere Unterhaltung und die Klärungsfragen verwenden?", reason: "Die Sprache der Factory-Kommunikation ist unklar." }, ru: { question: "На каком языке мне вести наш диалог и задавать уточняющие вопросы?", reason: "Язык общения с Factory не определён." }, uk: { question: "Якою мовою вести наше спілкування та ставити уточнювальні запитання?", reason: "Мова спілкування з Factory не визначена." } },
  "business-purpose": { de: { question: "Was ist der wichtigste geschäftliche Zweck dieses Projekts?", reason: "Für das Briefing wird ein bestätigter Zweck benötigt." }, ru: { question: "Какова основная бизнес-цель этого проекта?", reason: "Для брифа нужна подтверждённая цель." }, uk: { question: "Яка основна бізнес-мета цього проєкту?", reason: "Для брифу потрібна підтверджена мета." } },
  "target-audience": { de: { question: "Wer ist die wichtigste Zielgruppe?", reason: "Die Zielgruppe beeinflusst das Briefing." }, ru: { question: "Кто является основной целевой аудиторией?", reason: "Аудитория влияет на бриф." }, uk: { question: "Хто є основною цільовою аудиторією?", reason: "Аудиторія впливає на бриф." } },
  "languages": { de: { question: "Welche primäre Sprache soll die Kunden-Website verwenden?", reason: "Die Sprache der Kunden-Website ist unklar." }, ru: { question: "Какой основной язык должна использовать клиентская часть сайта?", reason: "Язык клиентского сайта не определён." }, uk: { question: "Яку основну мову має використовувати клієнтський сайт?", reason: "Мова клієнтського сайту не визначена." } },
  "pages": { de: { question: "Welche Seiten oder Routen muss das Projekt enthalten?", reason: "Der Seitenumfang muss festgelegt werden." }, ru: { question: "Какие страницы или маршруты должен содержать проект?", reason: "Нужно определить состав страниц." }, uk: { question: "Які сторінки або маршрути має містити проєкт?", reason: "Потрібно визначити обсяг сторінок." } },
  "functionality": { de: { question: "Welche Funktionen für Nutzer werden benötigt?", reason: "Die Funktionen müssen konkret festgelegt werden." }, ru: { question: "Какие функции для пользователей необходимы?", reason: "Функции должны быть определены явно." }, uk: { question: "Які функції для користувачів потрібні?", reason: "Функції потрібно визначити явно." } },
  "contact": { de: { question: "Welche verifizierten Kontaktdaten sollen angezeigt werden?", reason: "Kontaktdaten dürfen nicht erfunden werden." }, ru: { question: "Какие проверенные контактные данные нужно показать?", reason: "Контактные данные нельзя выдумывать." }, uk: { question: "Які перевірені контактні дані потрібно показати?", reason: "Контактні дані не можна вигадувати." } },
  "image-source": { de: { question: "Wie sollen Bilder bezogen werden: KI-generiert, von Ihnen bereitgestellt, kombiniert, Platzhalter oder individuell?", reason: "Die Bildquelle muss bestätigt werden." }, ru: { question: "Как получать изображения: сгенерировать ИИ, предоставить свои, объединить, использовать плейсхолдеры или заказать индивидуальные?", reason: "Источник изображений нужно подтвердить." }, uk: { question: "Як отримувати зображення: згенеровані ШІ, надані вами, комбіновані, плейсхолдери чи індивідуальні?", reason: "Джерело зображень потрібно підтвердити." } },
  "logo": { de: { question: "Stellen Sie ein Logo bereit, und wo befinden sich seine Metadaten?", reason: "Die Factory erstellt keine Logos." }, ru: { question: "Предоставите ли вы логотип и где находятся его метаданные?", reason: "Factory не создаёт логотипы." }, uk: { question: "Чи надасте ви логотип і де розміщені його метадані?", reason: "Factory не створює логотипи." } },
  "authentication": { de: { question: "Ist für geschützte Funktionen eine Authentifizierung erforderlich?", reason: "Geschützte Funktionen brauchen eine ausdrückliche Entscheidung." }, ru: { question: "Нужна ли аутентификация для защищённых функций?", reason: "Для защищённых функций нужно явное решение." }, uk: { question: "Чи потрібна автентифікація для захищених функцій?", reason: "Для захищених функцій потрібне явне рішення." } },
  "storage": { de: { question: "Werden Uploads oder verwalteter Medienspeicher benötigt?", reason: "Speicher ist von Uploads abhängig." }, ru: { question: "Нужны ли загрузки или управляемое медиахранилище?", reason: "Хранилище зависит от загрузок." }, uk: { question: "Чи потрібні завантаження або кероване медіасховище?", reason: "Сховище залежить від завантажень." } },
  "email": { de: { question: "Welche E-Mail- oder Benachrichtigungsfunktionen werden benötigt?", reason: "Das E-Mail-Verhalten muss bestätigt werden." }, ru: { question: "Какие действия с электронной почтой или уведомлениями нужны?", reason: "Поведение почты нужно подтвердить." }, uk: { question: "Які дії з електронною поштою або сповіщеннями потрібні?", reason: "Поведінку пошти потрібно підтвердити." } },
  "administration": { de: { question: "Benötigt das Projekt nach dem Start eine Verwaltung oder bearbeitbare Inhalte?", reason: "Ein Admin-Bereich wird nicht automatisch ergänzt." }, ru: { question: "Нужны ли проекту администрирование после запуска или редактируемый контент?", reason: "Панель администрирования не добавляется автоматически." }, uk: { question: "Чи потрібні після запуску адміністрування або редагований контент?", reason: "Панель адміністрування не додається автоматично." } },
  "acceptance": { de: { question: "Welche sichtbaren Akzeptanzkriterien definieren eine erfolgreiche erste Version?", reason: "Für die Freigabe werden Akzeptanzkriterien benötigt." }, ru: { question: "Какие видимые для пользователя критерии определяют успешный первый релиз?", reason: "Для утверждения нужны критерии приёмки." }, uk: { question: "Які видимі для користувача критерії визначають успішний перший реліз?", reason: "Для затвердження потрібні критерії приймання." } },
};

type OperatorLanguage = "en" | "de" | "ru" | "uk";
const localized = (template: typeof templates[number], language: string) => localizedTemplates[template.key]?.[language as OperatorLanguage] ?? { question: template.question, reason: template.reason };

export function planClarificationsDeterministically(input: { analysis: LeadAgentAnalysis; session?: ClarificationSession }): ClarificationPlan {
  const { analysis, session } = input; const existing = new Set((session?.questions ?? []).map((question) => question.requirementKey ?? "")); const answered = new Set((session?.answers ?? []).filter((answer) => answer.status !== "unresolved").map((answer) => session?.questions.find((question) => question.id === answer.questionId)?.requirementKey)); const stated = new Set(analysis.directlyStatedFacts.map((fact) => fact.key)); if (analysis.directlyStatedFacts.some((fact) => fact.key === "images" && /ai|user|placeholder|custom/i.test(fact.value))) stated.add("image-source");
  const promptValues = [...analysis.directlyStatedFacts, ...analysis.userPreferences].map((fact) => fact.value).join(" "); const shouldAsk = (template: typeof templates[number]) => { if (existing.has(template.key) || answered.has(template.key) || stated.has(template.key)) return false; if (template.key === "operator-language") return analysis.languageResolution?.operatorLanguageSource === "FALLBACK"; if (template.key === "languages") return analysis.siteLanguage === "UNRESOLVED"; if (template.key === "authentication") return analysis.userPreferences.some((fact) => fact.key === "protected-functionality") || /protected|dashboard|account|private|saved|role/i.test(promptValues); if (template.key === "storage") return analysis.userPreferences.some((fact) => fact.key === "storage"); if (template.key === "email") return analysis.userPreferences.some((fact) => fact.key === "email"); if (template.key === "administration") return /admin|manage|editable|content management/i.test(promptValues); if (template.key === "image-source") return analysis.directlyStatedFacts.some((fact) => fact.key === "images") || analysis.unresolvedQuestions.some((fact) => fact.key === "image-source"); if (template.key === "contact") return analysis.directlyStatedFacts.some((fact) => fact.key === "pages" && /contact/i.test(fact.value)) || analysis.directlyStatedFacts.some((fact) => fact.key === "contact"); return true; };
  const questions = templates.filter(shouldAsk).map((template) => { const copy = localized(template, analysis.operatorLanguage); return { id: stableId(`question:${template.key}`), requirementKey: template.key, category: template.category, question: copy.question, reason: copy.reason, blocking: template.blocking, required: template.required, fingerprint: `v1:${template.category}:${template.key}` }; }); const contradictions = analysis.contradictions.map((contradiction) => ({ id: stableId(`contradiction:${contradiction.explanation}`), requirementKey: `contradiction:${hash(contradiction.explanation).slice(0, 12)}`, category: "constraints" as const, question: `The requirements conflict: ${contradiction.explanation} Which requirement should take precedence?`, reason: "Contradictions cannot be resolved automatically.", blocking: true, required: true, fingerprint: `v1:constraints:${hash(contradiction.explanation)}` })); return ClarificationPlanSchema.parse({ projectId: analysis.projectId, projectVersion: analysis.projectVersion, operatorLanguage: analysis.operatorLanguage, questions: [...questions, ...contradictions], generatedAt: now() });
}

const clarificationToRequirement: Record<ClarificationCategory, ExtractedRequirement["category"]> = { business: "business-purpose", audience: "audience", pages: "pages", functionality: "functionality", content: "content", contact: "contact", legal: "legal", design: "design", brand: "logo", images: "image-sourcing", authentication: "authentication", forms: "forms", email: "email", database: "database", storage: "storage", administration: "administration", GitHub: "GitHub", languages: "languages", localization: "localization", constraints: "constraints" };

const briefEntry = (key: string, statement: string, source: ExtractedRequirement[] = []): BriefRequirementEntry & { key: string; value: string; evidence: ExtractedRequirement["evidence"] } => {
  const value = { id: stableId(`brief:${key}:${statement}`), statement, sourceRefs: source.flatMap((fact) => fact.evidence.map((item) => `${item.sourceType}:${item.reference}`)).slice(0, 8).length ? source.flatMap((fact) => fact.evidence.map((item) => `${item.sourceType}:${item.reference}`)).slice(0, 8) : [`derived:${key}`] } as BriefRequirementEntry & { key: string; value: string; evidence: ExtractedRequirement["evidence"] };
  Object.defineProperties(value, { key: { value: key }, value: { value: statement }, evidence: { value: source.flatMap((fact) => fact.evidence) } });
  return value;
};
const v2FromFacts = (facts: ExtractedRequirement[], values: (category: ExtractedRequirement["category"]) => string[]): BriefV2Fields => {
  const by = (category: ExtractedRequirement["category"]) => facts.filter((fact) => fact.category === category);
  const entries = (category: ExtractedRequirement["category"]) => by(category).map((fact) => briefEntry(fact.key, fact.value, [fact]));
  const allBrand = [...entries("brand"), ...entries("design")];
  const allImages = entries("image-sourcing");
  const formValues = values("forms");
  const constraintValues = values("constraints");
  const seoValues = values("seo");
  const noTransmission = [...values("email"), ...values("database"), ...constraintValues].some((value) => /no transmission|keine.*(?:übermittlung|uebermittlung|übertragung|uebertragung)|frontend.*simulation|simulat/i.test(value));
  const hasForm = formValues.some((value) => !/(?:^|\b)(?:no|without|kein\w*|keine\w*|ohne|nicht)\b[^.!?;\n]*(?:form|formular|contact\s+form|kontaktformular)|(?:form|formular|contact\s+form|kontaktformular)[^.!?;\n]*\b(?:not|nicht)\b/iu.test(value));
  const fields = emptyBriefV2Fields();
  fields.content = entries("content");
  fields.technical = entries("constraints");
  fields.brandVisualRequirements = { ...fields.brandVisualRequirements, brandReferenceUsage: [...entries("brand"), ...entries("logo"), ...entries("image-sourcing")], spacingLayoutDirection: allBrand, visualAntiPatterns: entries("exclusions") };
  fields.assetRequirements = { requiredAssets: entries("logo").map((fact) => ({ reference: canonicalAssetReference(fact.key), role: "logo" as const, usage: fact.value, replacementForbidden: /(?:no|keine|nicht).*(?:replace|replacement|ersetz|fake|falsch)/i.test(fact.value), sourceRefs: fact.evidence.map((item) => `${item.sourceType}:${item.reference}`) })), additionalImagery: { allowed: allImages.length > 0, sourcingPolicy: allImages, realisticProfessional: allImages.some((item) => /realistic|profession|hochwert|realistisch/i.test(item.statement)), avoidArtificialLook: allImages.some((item) => /no cartoon|kein cartoon|no 3d|nicht künstlich|nicht künstlich/i.test(item.statement)) } };
  fields.formBehaviorRequirements = { formPresent: hasForm, validation: hasForm ? "ACTIVE" : "NOT_REQUIRED", successUx: formValues.some((value) => /simulat|frontend.*success|erfolg/i.test(value)) ? "SIMULATED" : hasForm ? "NONE" : "NONE", dataTransmission: hasForm && !noTransmission && values("email").length ? "EMAIL" : "NONE", persistence: hasForm && values("database").length ? "DATABASE" : "NONE", thirdParty: "NONE", privacyCheckbox: formValues.some((value) => /privacy|datenschutz|checkbox|einwill/i.test(value)) ? "REQUIRED" : hasForm ? "OPTIONAL" : "NOT_APPLICABLE", interactionStates: hasForm ? formValues.map((value) => briefEntry("form", value, by("forms"))) : [] };
  fields.uxResponsiveRequirements = { mobileFirst: constraintValues.some((value) => /mobile|responsive|mobil/i.test(value)), responsiveBehavior: [...entries("design"), ...constraintValues.filter((value) => /responsive|mobile|mobil/i.test(value)).map((value) => briefEntry("responsive", value))], stickyMobileCta: constraintValues.some((value) => /sticky.*cta|mobile.*cta/i.test(value)), smoothScroll: constraintValues.some((value) => /smooth scroll|sanft.*scroll/i.test(value)), reducedMotion: constraintValues.some((value) => /reduced motion|wenig.*beweg|keine.*unnöt.*beweg/i.test(value)), interactionRequirements: formValues.map((value) => briefEntry("interaction", value)) };
  fields.seoMetadata = { primaryKeywords: seoValues, exactTitle: seoValues.find((value) => /^(?:exact )?title\s*[:=]/i.test(value))?.replace(/^(?:exact )?title\s*[:=]\s*/i, ""), exactMetaDescription: seoValues.find((value) => /meta description\s*[:=]/i.test(value))?.replace(/^.*meta description\s*[:=]\s*/i, ""), locationTargeting: seoValues.filter((value) => /local|ort|city|region|gieß|giessen/i.test(value)).map((value) => briefEntry("seo-location", value)), pageMetadata: [] };
  const explicitInventionDecision = [...values("legal"), ...constraintValues, ...values("exclusions")].some((value) => /(?:invent|fabricat|erfinden|erfund|business facts?|fakten|unternehmensdaten)/iu.test(value));
  fields.legalComplianceConstraints = { constraints: [...entries("legal"), ...constraintValues.filter((value) => /legal|placeholder|invent|recht/i.test(value)).map((value) => briefEntry("legal", value))], placeholderPolicy: constraintValues.some((value) => /no\s+(?:placeholders?|platzhalter)|keine?\s+platzhalter|ohne\s+platzhalter/i.test(value)) ? "NO_PLACEHOLDERS" : "USE_EXPLICIT_PLACEHOLDERS", inventedFactsForbidden: explicitInventionDecision ? [...values("legal"), ...constraintValues, ...values("exclusions")].some((value) => /do not invent|never invent|nicht erfinden|keine? erfunden|ohne erfund/i.test(value)) : true };
  fields.prohibitedRequirements = [...entries("exclusions"), ...constraintValues.filter((value) => /do not|no |keine|nicht /i.test(value)).map((value) => briefEntry("prohibited", value))];
  fields.deferredIntegrations = [{ integration: "email", status: noTransmission ? "DEFERRED" as const : "DEFERRED" as const, rationale: "No real email transmission is approved by the deterministic intake contract.", sourceRefs: ["system-default:deferred-integrations"] }, { integration: "database", status: "DEFERRED" as const, rationale: "Persistence remains deferred unless explicitly approved.", sourceRefs: ["system-default:deferred-integrations"] }, { integration: "analytics", status: "PROHIBITED" as const, rationale: "Analytics is not enabled by default.", sourceRefs: ["system-default:deferred-integrations"] }];
  fields.decisions = [{ key: "form-data-transmission", value: fields.formBehaviorRequirements.dataTransmission, status: "CONFIRMED", sourceRefs: ["derived:form-behavior"] }, { key: "form-persistence", value: fields.formBehaviorRequirements.persistence, status: "CONFIRMED", sourceRefs: ["derived:form-behavior"] }];
  return fields;
};
export function assembleRequirements(input: { analysis: LeadAgentAnalysis; session: ClarificationSession }): BriefDraft {
  input = { ...input, session: { ...input.session, questions: input.session.questions.filter((question) => !isWorkflowRequirement(question)) } };
  const answerFacts = input.session.answers.filter((answer) => answer.status === "answered").map((answer) => {
    const question = input.session.questions.find((candidate) => candidate.id === answer.questionId);
    return question ? extracted(question.requirementKey ?? question.id, clarificationToRequirement[question.category], answer.answer ?? "", "confirmed", evidence(answer.answer ?? "", "prior-answer", answer.questionId)) : undefined;
  }).filter((value): value is ExtractedRequirement => Boolean(value));
  const facts = [...input.analysis.directlyStatedFacts, ...input.analysis.userPreferences, ...answerFacts];
  const values = (category: ExtractedRequirement["category"]) => facts.filter((fact) => fact.category === category).map((fact) => fact.value);
  const pages = values("pages").flatMap((value) => value.split(/[,;]\s*/).map((slug) => ({ slug: slug.toLowerCase().replace(/\s+/g, "-"), purpose: slug })));
  const image = values("image-sourcing")[0];
  const auth = values("authentication")[0];
  const storage = values("storage")[0];
  const email = values("email")[0];
  const admin = values("administration")[0];
  const languageValues = values("languages").flatMap((value) => value.split(/[,;]\s*/).map((entry) => normalizeSiteLanguage(entry))).filter((value): value is Exclude<typeof value, "UNRESOLVED"> => value !== "UNRESOLVED");
  const siteLanguage = input.analysis.siteLanguage !== "UNRESOLVED" ? input.analysis.siteLanguage : languageValues[0] ?? "UNRESOLVED";
  const locales = siteLanguage === "UNRESOLVED" ? ["en"] : [siteLanguage];
  const unresolved = input.session.questions.filter((question) => question.answerStatus === "unresolved").map((question) => ({ key: question.requirementKey ?? question.id, description: question.question, blocking: question.blocking }));
  const missingAcceptance = !values("constraints").some((value) => /accept|done|success/i.test(value));
  const blockingReasons = [...unresolved.filter((item) => item.blocking).map((item) => `CLARIFICATION_REQUIRED:${item.key}`), ...(siteLanguage === "UNRESOLVED" ? ["SITE_LANGUAGE_CONFIRMATION_REQUIRED"] : []), ...input.analysis.contradictions.map((item) => item.code), ...(input.analysis.unsupportedAssumptions.length ? ["REQUIRED_BUSINESS_DATA_MISSING"] : []), ...(missingAcceptance ? ["ACCEPTANCE_CRITERIA_MISSING"] : [])];
  const v2Fields = v2FromFacts(facts, values);
  const noForm = v2Fields.formBehaviorRequirements.formPresent === false;
  const protectedFunctionality = Boolean(auth || facts.some((fact) => fact.key === "protected-functionality"));
  const base = { schemaVersion: 1 as const, documentType: "requirements" as const, projectId: input.analysis.projectId, projectVersion: input.analysis.projectVersion, createdAt: now(), updatedAt: now(), operatorLanguage: input.analysis.operatorLanguage, projectSummary: values("business-purpose")[0] ?? "User-confirmed project purpose is pending.", protectedFunctionalityRequired: protectedFunctionality, imagesRequired: Boolean(facts.some((fact) => fact.key === "images") || image), businessGoals: values("business-purpose"), targetAudiences: values("audience"), pages, userRoles: values("user-roles"), features: values("functionality"), forms: values("forms"), contentRequirements: values("content"), backendRequirements: values("database"), supabaseRequirements: values("database"), authenticationDecision: auth ? (/no|guest/i.test(auth) ? "no-authentication-guest-first" : "authentication-required") : !protectedFunctionality ? "no-authentication-guest-first" : "pending", storageDecision: storage ? (/no|not/i.test(storage) ? "not-needed" : "needed") : noForm ? "not-needed" : "pending", emailDecision: email ? (/no|not/i.test(email) ? "not-needed" : "needed") : noForm ? "not-needed" : "pending", administrationDecision: admin ? (/no|not/i.test(admin) ? "not-needed" : "needed") : "pending", seoRequirements: values("seo"), localization: { locales, defaultLocale: siteLanguage === "UNRESOLVED" ? "en" : siteLanguage }, imageSourceDecision: image ? image.toLowerCase().replaceAll(" ", "-") as "ai-generated" | "user-supplied" | "ai-plus-user-supplied" | "placeholders" | "custom" : "pending", suppliedBrandInformation: values("brand").length ? { status: "provided" as const, value: values("brand")[0]! } : { status: "missing" as const }, suppliedLogoLocation: values("logo").length ? { status: "provided" as const, value: values("logo")[0]! } : { status: "missing" as const }, technicalConstraints: values("constraints"), explicitExclusions: values("exclusions"), userAcceptanceCriteria: values("constraints").filter((value) => /accept|done|success/i.test(value)), unresolvedItems: unresolved.map((item) => ({ id: stableId(item.key), description: item.description, blocking: item.blocking })), approval: { approved: false }, projectTitle: values("project-identity")[0], contactFacts: values("contact"), legalFacts: values("legal"), brandFacts: values("brand"), logoMetadata: values("logo"), imageSourcingNotes: values("image-sourcing"), evidence: facts.flatMap((fact) => fact.evidence.map((entry) => ({ field: fact.key, source: entry.sourceType, excerpt: entry.excerpt }))), recommendations: input.analysis.inferredRecommendations.map((fact) => fact.value), briefStatus: "draft" as const, briefVersion: 1 };
  const requirements = RequirementSpecificationSchema.parse({ ...base, ...v2Fields });
  const contradictionBlockers = validateBriefContradictions(requirements).map((item) => `BRIEF_CONTRADICTION_DETECTED:${item.code}`);
  const allBlockingReasons = [...new Set([...blockingReasons, ...contradictionBlockers])];
  const briefChecksum = checksumPersistedDocument(requirements);
  return { projectId: input.analysis.projectId, projectVersion: input.analysis.projectVersion, requirements, facts, recommendations: input.analysis.inferredRecommendations, unresolvedItems: unresolved, evidence: requirements.evidence, readyForApproval: allBlockingReasons.length === 0, blockingReasons: allBlockingReasons, nonBlockingWarnings: input.analysis.inferredRecommendations.map((fact) => fact.value), briefChecksum };
}
