import path from "node:path";
import { randomUUID } from "node:crypto";
import { DocumentRepository, DecisionRepository, ProjectRepository } from "../persistence/repositories";
import { checksumPersistedDocument } from "../persistence/serialization";
import { DEFAULT_ORCHESTRATION_POLICY } from "../orchestrator/contracts";
import { DEFAULT_FULL_EXECUTION_POLICY, type FullExecutionPolicy } from "../full-execution/contracts";
import { safeSmokeProjectReference } from "../real-factory-e2e/preflight";
import { RealFactoryE2EReportSchema, type RealFactoryE2EReport } from "../real-factory-e2e/contracts";
import { VELOFIX_WERKSTATT_PROMPT } from "../real-factory-e2e/spec";
import { resolveVeloFixClarification } from "../real-factory-e2e/clarification-resolver";
import type { ProductionFactoryRuntime } from "./production-factory-runtime";

export type ProductionE2EStageSink = (event: { stage: string; status: "started" | "passed" | "failed"; safeCode?: string }) => void | Promise<void>;
export type ValidatedSmokeSpecification = { prompt: string; slugPrefix: string; answers: Record<string, string> };
export const VELOFIX_SMOKE_SPECIFICATION: ValidatedSmokeSpecification = { prompt: VELOFIX_WERKSTATT_PROMPT, slugPrefix: "real-e2e-velofix", answers: { "project-identity": "VeloFix Werkstatt", "business-purpose": "Bicycle repairs", audience: "Local bicycle owners", "project-type": "A synthetic German bicycle repair workshop website", pages: "home, services, appointment", functionality: "Request an appointment with an appointment form", forms: "Request an appointment with client and server validation", languages: "German", localization: "German", "image-sourcing": "Use placeholders for imagery", logo: "No supplied logo", brand: "No supplied brand facts", authentication: "No authentication", database: "No real database", storage: "No Storage", email: "No real email", administration: "No admin", contact: "No contact details supplied", seo: "No additional SEO facts are supplied", exclusions: "No additional scope beyond the supplied VeloFix facts" } };

type Evidence = { leadRequest: boolean; plannerRequest: boolean; designRequest: boolean; implementationRequest: boolean; npmExecution: boolean; browserExecution: boolean };
type Stage = RealFactoryE2EReport["stages"][number];
const now = () => new Date().toISOString();
const safeCode = (error: unknown) => typeof error === "object" && error && "code" in error && typeof error.code === "string" ? error.code : error instanceof Error && /^[A-Z0-9_]+$/.test(error.message) ? error.message : "REAL_E2E_STAGE_FAILED";
const message = (error: unknown) => { if (typeof error === "object" && error && "details" in error && error.details && typeof error.details === "object") { const details = error.details as Record<string, unknown>; if (details.questionId && details.fixtureResolution === "missing") return `Clarification unresolved: questionId=${String(details.questionId)} category=${String(details.category)} blocking=${String(details.blocking)} fixtureResolution=missing safeReason=${String(details.safeReason)}`; if (Array.isArray(details.blockingReasons) || Array.isArray(details.unresolvedItems)) return `Brief readiness failed: blockingReasons=${JSON.stringify(details.blockingReasons ?? [])} unresolvedItems=${JSON.stringify(details.unresolvedItems ?? [])}`; } if (typeof error === "object" && error && "code" in error && error.code === "PLANNER_PROVIDER_FAILED") { let cause: unknown = "cause" in error ? error.cause : undefined; const codes: string[] = []; for (let depth = 0; depth < 3 && cause && typeof cause === "object"; depth++) { if (!("code" in cause) || typeof cause.code !== "string") break; codes.push(cause.code); cause = "cause" in cause ? cause.cause : undefined; } if (codes.length) return `Planner provider failed safely: providerCodes=${codes.join(">")}`; } if (typeof error === "object" && error && "code" in error && (error.code === "PLANNING_PACKAGE_INVALID" || error.code === "DESIGN_DIRECTION_COUNT_INVALID") && "cause" in error && error.cause && typeof error.cause === "object" && "issues" in error.cause && Array.isArray(error.cause.issues)) { const path = error.cause.issues[0]?.path; if (Array.isArray(path)) return `${error.code === "DESIGN_DIRECTION_COUNT_INVALID" ? "Design" : "Planner"} output failed canonical validation safely: schemaPath=${path.slice(0, 8).join(".")}`; } return error instanceof Error ? error.message.slice(0, 300) : "Stage failed safely."; };

export async function runProductionE2EStages(input: { specification: ValidatedSmokeSpecification; runtime: ProductionFactoryRuntime; smokeId: string; signal?: AbortSignal; sink?: ProductionE2EStageSink; policy?: FullExecutionPolicy }): Promise<RealFactoryE2EReport> {
  const startedAt = now(); const evidence: Evidence = { leadRequest: false, plannerRequest: false, designRequest: false, implementationRequest: false, npmExecution: false, browserExecution: false }; const stages: Stage[] = []; let projectId: string | undefined; let projectVersion: number | undefined; let projectPathReference: string | undefined;
  const base = { schemaVersion: 1 as const, reportType: "real-factory-e2e" as const, smokeId: input.smokeId, startedAt, optIn: true, preflightPassed: true, adapterIdentity: { leadProviderMode: "production", plannerProviderMode: "production", designProviderMode: "production", implementationProviderMode: "production", processRunnerMode: "real", browserRunnerMode: "real", executionStateMode: "production", taskExecutorMode: "production", repairerMode: "production", fullExecutorMode: "production" }, realStageEvidence: evidence, stages, provider: { status: "configured" as const, requestCount: 0, inputTokens: 0, outputTokens: 0 }, context7: { status: input.runtime.identity.context7 === "configured" ? "configured" as const : input.runtime.identity.context7 === "blocked" ? "blocked" as const : "not-needed" as const, requestCount: 0 }, shadcn: { status: input.runtime.identity.shadcn === "configured" ? "configured" as const : input.runtime.identity.shadcn === "blocked" ? "blocked" as const : "not-needed" as const, requestCount: 0 }, npm: { status: "not-configured" as const, commands: ["npm run lint", "npm run typecheck", "npm test -- --run", "npm run build"], passedCount: 0, failedCount: 0 }, playwright: { status: "not-configured" as const, scenarios: 0, passedCount: 0, failedCount: 0, unexpectedExternalRequests: 0 }, taskGraph: { taskCount: 0, passedCount: 0, failedCount: 0, repairCount: 0 }, generatedFiles: { createdCount: 0, changedCount: 0, checksumVerified: false }, blockers: [] as string[], warnings: [] as string[], releaseEligible: false, prohibitedActions: { deployment: false, gitMutation: false, customerDatabaseMigration: false, customerDataAccess: false, arbitraryBrowsing: false, screenshots: false } };
  const stage = async <T>(name: string, operation: () => Promise<T>): Promise<T> => { const started = now(); await input.sink?.({ stage: name, status: "started" }); if (input.signal?.aborted) throw Object.assign(new Error("REAL_E2E_CANCELLED"), { code: "REAL_E2E_CANCELLED" }); try { const value = await operation(); stages.push({ name, status: "passed", startedAt: started, completedAt: now(), summary: `${name} completed.` }); await input.sink?.({ stage: name, status: "passed" }); return value; } catch (error) { const code = safeCode(error); stages.push({ name, status: "failed", startedAt: started, completedAt: now(), safeFailureCode: code, summary: message(error) }); await input.sink?.({ stage: name, status: "failed", safeCode: code }); throw error; } };
  try {
    if (input.specification.prompt !== VELOFIX_WERKSTATT_PROMPT || input.specification.slugPrefix !== VELOFIX_SMOKE_SPECIFICATION.slugPrefix || JSON.stringify(input.specification.answers) !== JSON.stringify(VELOFIX_SMOKE_SPECIFICATION.answers)) throw Object.assign(new Error("REAL_E2E_SMOKE_SPEC_INVALID"), { code: "REAL_E2E_SMOKE_SPEC_INVALID" });
    const generatedRoot = path.resolve(input.runtime.generatedProjectsRoot ?? process.env.GENERATED_PROJECTS_ROOT ?? ".factory-generated"); const smokeRoot = safeSmokeProjectReference(generatedRoot, input.smokeId); const slug = `${input.specification.slugPrefix}-${input.smokeId.slice(0, 8)}`; const workspaceRoot = path.dirname(smokeRoot); const scope = input.runtime.createProjectScope({ workspaceRoot, slug });
    await stage("PROJECT", async () => { const result = await scope.lead.startProjectIntake({ projectId: randomUUID(), projectVersion: 1, originalPrompt: input.specification.prompt, suppliedFiles: [], knownUserAnswers: {}, currentWorkflowState: "DRAFT", projectSlug: slug, projectTitle: "VeloFix Werkstatt", idempotencyKey: `real-e2e-intake-${input.smokeId}` }); projectId = result.id; const materialized = await scope.workspace.materializeReservedInitialVersion(result, { operationId: `real-e2e-${input.smokeId}` }); projectVersion = materialized.version.versionNumber; projectPathReference = materialized.path; return result; });
    const leadInput = { projectId: projectId!, projectVersion: projectVersion!, originalPrompt: input.specification.prompt, suppliedFiles: [], knownUserAnswers: {}, currentWorkflowState: "DRAFT" as const, idempotencyKey: `real-e2e-lead-${input.smokeId}`, projectSlug: slug, projectTitle: "VeloFix Werkstatt" };
    await stage("LEAD", async () => { const analysis = await scope.lead.analyzeProjectPrompt(leadInput); evidence.leadRequest = input.runtime.evidence.roles.lead > 0 || input.runtime.evidence.roles["lead-agent"] > 0; const plan = await scope.lead.planClarifications(leadInput); return { analysis, plan }; });
    await stage("CLARIFICATION", async () => { const maxRounds = 2; for (let round = 0; round < maxRounds; round++) { const status = await scope.lead.getClarificationStatus(projectId!, projectVersion!); let answered = 0; for (const question of status.unresolved) { const resolution = resolveVeloFixClarification(question); if (!resolution.answer) { if (question.blocking) throw Object.assign(new Error("REAL_E2E_UNRESOLVED_CLARIFICATION"), { code: "REAL_E2E_UNRESOLVED_CLARIFICATION", details: { questionId: question.id, category: question.category, blocking: question.blocking, fixtureResolution: "missing", safeReason: "safeReason" in resolution ? resolution.safeReason : "FIXTURE_FACT_MISSING" } }); continue; } await scope.lead.recordClarificationAnswer({ projectId: projectId!, projectVersion: projectVersion!, questionId: question.id, status: "answered", answer: resolution.answer, answeredBy: "real-e2e-smoke", idempotencyKey: `real-e2e-answer-${input.smokeId}-${question.id}` }); answered++; } const next = await scope.lead.getClarificationStatus(projectId!, projectVersion!); if (!next.blockingUnresolved.length) return next; if (!answered) break; await scope.lead.planClarifications(leadInput); } throw Object.assign(new Error("REAL_E2E_CLARIFICATION_LIMIT_EXCEEDED"), { code: "REAL_E2E_CLARIFICATION_LIMIT_EXCEEDED" }); });
    const draft = await stage("BRIEF_FINALIZATION", async () => scope.lead.buildBriefDraft(projectId!, projectVersion!));
    await stage("BRIEF_VALIDATION", async () => { if (!draft.readyForApproval) throw Object.assign(new Error("LEAD_BRIEF_NOT_READY"), { code: "LEAD_BRIEF_NOT_READY", details: { blockingReasons: draft.blockingReasons.slice(0, 10), unresolvedItems: draft.unresolvedItems.filter((item) => item.blocking).map((item) => item.key).slice(0, 10) } }); return draft; });
    const approved = await stage("BRIEF_APPROVAL", async () => { const current = await new ProjectRepository(scope.database).getWithVersion(projectId!); return scope.lead.approveBrief({ projectId: projectId!, projectVersion: projectVersion!, briefChecksum: draft.briefChecksum, approvedAt: now(), approvedBy: "real-e2e-smoke", expectedRowVersion: current!.rowVersion, idempotencyKey: `real-e2e-brief-${input.smokeId}` }); });
    const planning = await stage("PLANNER", async () => { const current = await new ProjectRepository(scope.database).getWithVersion(projectId!); const result = await scope.planner.planApprovedProject({ projectId: projectId!, projectVersion: projectVersion!, approvedBrief: approved.brief.requirements, approvedBriefChecksum: approved.brief.briefChecksum, originalPromptReference: "original-prompt.md", clarificationEvidenceReferences: ["clarification-log.json"], currentWorkflowState: "AWAITING_DESIGN_SELECTION", existingDecisions: [], suppliedFiles: [], allowedSkills: [], idempotencyKey: `real-e2e-planner-${input.smokeId}`, expectedRowVersion: current!.rowVersion }); evidence.plannerRequest = input.runtime.evidence.roles.planner > 0 || input.runtime.evidence.roles["planner-architect"] > 0; return result; });
    const accepted = await stage("PLANNING_ACCEPTANCE", async () => scope.planner.acceptPlanningPackage({ projectId: projectId!, projectVersion: projectVersion!, planningChecksum: checksumPersistedDocument(planning), acceptedAt: now(), acceptedBy: "real-e2e-smoke", expectedRowVersion: (await new ProjectRepository(scope.database).getWithVersion(projectId!))!.rowVersion, idempotencyKey: `real-e2e-planning-accept-${input.smokeId}` }));
    const design = await stage("DESIGN", async () => { const current = await new ProjectRepository(scope.database).getWithVersion(projectId!); const result = await scope.design.generateDesignDirections({ projectId: projectId!, projectVersion: projectVersion!, approvedBrief: approved.brief.requirements, approvedBriefChecksum: approved.brief.briefChecksum, acceptedPlanningPackage: accepted.package, acceptedPlanningChecksum: accepted.planningChecksum, contentPlan: accepted.package.content, assetManifest: accepted.package.assets, suppliedBrandMetadata: {}, suppliedLogoMetadata: approved.brief.requirements.suppliedLogoLocation, imageSourceDecision: approved.brief.requirements.imageSourceDecision, designPreferences: [], explicitDesignExclusions: [], currentWorkflowState: "AWAITING_DESIGN_SELECTION", existingDecisions: [], allowedSkills: [], idempotencyKey: `real-e2e-design-${input.smokeId}`, expectedRowVersion: current!.rowVersion }); if (!result.readiness.readyForSelection || result.directionSet.directions.length !== 3) throw Object.assign(new Error("REAL_E2E_DESIGN_DIRECTION_COUNT_INVALID"), { code: "REAL_E2E_DESIGN_DIRECTION_COUNT_INVALID" }); evidence.designRequest = input.runtime.evidence.roles.design > 0; return result; });
    const selected = await stage("DESIGN_SELECTION", async () => scope.design.selectDesignDirection({ projectId: projectId!, projectVersion: projectVersion!, designDirectionSetId: design.directionSet.setId, selectedDirectionId: design.directionSet.directions[0].id, directionSetChecksum: design.readiness.directionSetChecksum, selectedDirectionChecksum: checksumPersistedDocument(design.directionSet.directions[0]), expectedRowVersion: (await new ProjectRepository(scope.database).getWithVersion(projectId!))!.rowVersion, selectedBy: "real-e2e-smoke", selectedAt: now(), selectionNotes: "Synthetic smoke selection of direction one.", idempotencyKey: `real-e2e-selection-${input.smokeId}` }));
    const documents = new DocumentRepository(scope.database); const decisions = await new DecisionRepository(scope.database).list(projectId!, projectVersion!); const brief = approved.brief.requirements; const acceptedPlanning = accepted.package; const allowedRoles: ("lead" | "planner-architect" | "design" | "implementation" | "qa-release")[] = ["lead", "planner-architect", "design", "implementation", "qa-release"]; const orchestratorInput = { projectId: projectId!, projectVersion: projectVersion!, approvedBrief: brief, approvedBriefChecksum: approved.brief.briefChecksum, acceptedPlanningPackage: acceptedPlanning, acceptedPlanningChecksum: accepted.planningChecksum, selectedDesign: selected.selectedDesign, selectedDesignChecksum: checksumPersistedDocument(selected.selectedDesign), technicalArchitecture: acceptedPlanning.architecture, contentPlan: acceptedPlanning.content, assetManifest: acceptedPlanning.assets, currentWorkflowState: "READY_FOR_IMPLEMENTATION" as const, existingDecisions: decisions, allowedRoles, approvedSkillRegistrySnapshot: { schemaVersion: 1 as const, checksum: "0".repeat(64), skills: [] }, toolPolicyVersion: "tools-v1", orchestrationPolicyVersion: DEFAULT_ORCHESTRATION_POLICY.version, idempotencyKey: `real-e2e-orchestrator-${input.smokeId}`, expectedRowVersion: (await new ProjectRepository(scope.database).getWithVersion(projectId!))!.rowVersion, workspaceReserved: true, projectImmutable: false };
    const graph = await stage("ORCHESTRATOR", async () => { const result = await scope.orchestrator.createImplementationTaskGraph(orchestratorInput); if (!result.valid || !result.readyForExecution) throw Object.assign(new Error("REAL_E2E_TASK_GRAPH_INVALID"), { code: "REAL_E2E_TASK_GRAPH_INVALID" }); return result; });
    const started = await stage("START_IMPLEMENTATION", async () => scope.orchestrator.startImplementation({ ...orchestratorInput, expectedRowVersion: (await new ProjectRepository(scope.database).getWithVersion(projectId!))!.rowVersion }));
    const staging = await scope.workspace.createMutableExecutionStaging(started.project, projectVersion!, `real-e2e-run-${input.smokeId}`); const context = { projectId: projectId!, projectVersion: projectVersion!, workspacePath: staging, generatedProjectsRoot: workspaceRoot, workspaceReservationId: `real-e2e-run-${input.smokeId}`, sourceDocumentChecksums: graph.taskGraph.sourceDocumentChecksums ?? {}, toolPolicyVersion: graph.taskGraph.toolPolicyVersion ?? "tools-v1", orchestrationPolicyVersion: graph.taskGraph.orchestrationPolicyVersion ?? DEFAULT_ORCHESTRATION_POLICY.version, approvedSkillSnapshotChecksum: graph.taskGraph.approvedSkillSnapshotChecksum, evidence: { implementationRequest: () => { evidence.implementationRequest = true; }, npmExecution: () => { evidence.npmExecution = true; }, browserExecution: () => { evidence.browserExecution = true; } } };
    const run = await stage("FULL_EXECUTION", async () => scope.createFullExecutor({ ...context, policy: input.policy ?? DEFAULT_FULL_EXECUTION_POLICY }).execute({ projectId: projectId!, projectVersion: projectVersion!, idempotencyKey: `real-e2e-execution-${input.smokeId}`, graph: started.taskGraph, expectedGraphChecksum: started.taskGraph.graphChecksum!, workflowState: "IMPLEMENTING", projectImmutable: false, workspaceValid: true, sourceDocumentChecksums: context.sourceDocumentChecksums, currentDocumentChecksums: context.sourceDocumentChecksums, toolPolicyVersion: context.toolPolicyVersion, activeRunIds: [], signal: input.signal }));
    if (evidence.npmExecution) stages.push({ name: "RUNTIME", status: "passed", completedAt: now(), summary: "Real ProcessRunner evidence was recorded by the production adapter." }); else stages.push({ name: "RUNTIME", status: "failed", completedAt: now(), safeFailureCode: "REAL_E2E_RUNTIME_EVIDENCE_MISSING", summary: "Real ProcessRunner evidence is missing." });
    if (evidence.browserExecution) stages.push({ name: "QA", status: "passed", completedAt: now(), summary: "Real Playwright evidence was recorded by the production adapter." }); else stages.push({ name: "QA", status: "failed", completedAt: now(), safeFailureCode: "REAL_E2E_BROWSER_EVIDENCE_MISSING", summary: "Real Playwright evidence is missing." });
    const summary = await stage("RELEASE_ELIGIBILITY", async () => documents.get(projectId!, projectVersion!, "full-execution")); if (!summary || summary.documentType !== "full-execution" || run.status !== "completed" || !summary.releaseEligible || !Object.values(evidence).every(Boolean)) throw Object.assign(new Error("REAL_E2E_REAL_STAGE_EVIDENCE_INCOMPLETE"), { code: "REAL_E2E_REAL_STAGE_EVIDENCE_INCOMPLETE" });
    const runtimeEvidence = input.runtime.evidence; if (base.context7.status === "blocked" || base.shadcn.status === "blocked") throw Object.assign(new Error("REAL_E2E_OPTIONAL_INTEGRATION_BLOCKED"), { code: "REAL_E2E_OPTIONAL_INTEGRATION_BLOCKED" }); const report = RealFactoryE2EReportSchema.parse({ ...base, projectId, projectVersion, projectPathReference, completedAt: now(), overallStatus: "passed", realStageEvidence: evidence, stages, provider: { status: "configured", modelLabel: input.runtime.ai.config.model, requestCount: runtimeEvidence.providerRequests, inputTokens: runtimeEvidence.inputTokens, outputTokens: runtimeEvidence.outputTokens }, npm: { ...base.npm, status: "configured", passedCount: 4 }, playwright: { ...base.playwright, status: "configured", scenarios: 1, passedCount: 1 }, taskGraph: { taskCount: summary.totalTasks, passedCount: summary.passed, failedCount: summary.failed, repairCount: summary.repairsAttempted }, generatedFiles: { ...base.generatedFiles, checksumVerified: true }, releaseEligible: summary.releaseEligible }); return report;
  } catch (error) { const runtimeEvidence = input.runtime.evidence; return RealFactoryE2EReportSchema.parse({ ...base, projectId, projectVersion, projectPathReference, completedAt: now(), overallStatus: "failed", realStageEvidence: evidence, provider: { status: "configured", modelLabel: input.runtime.ai.config.model, requestCount: runtimeEvidence.providerRequests, inputTokens: runtimeEvidence.inputTokens, outputTokens: runtimeEvidence.outputTokens }, blockers: [safeCode(error), message(error)] }); }
}
