import path from "node:path";
import { access } from "node:fs/promises";
import { randomUUID } from "node:crypto";
import { DocumentRepository, DecisionRepository, ProjectRepository, ProjectVersionRepository } from "@/persistence/database/repositories";
import { checksumPersistedDocument } from "@/persistence/database/serialization";
import { DEFAULT_ORCHESTRATION_POLICY } from "@/orchestration/orchestrator/contracts";
import { DEFAULT_FULL_EXECUTION_POLICY, type FullExecutionPolicy } from "@/orchestration/execution/contracts";
import { safeSmokeProjectReference } from "@/runtime/e2e/preflight";
import { RealFactoryE2EReportSchema, type RealFactoryE2EReport } from "@/runtime/e2e/contracts";
import { VELOFIX_WERKSTATT_PROMPT } from "@/runtime/e2e/spec";
import { resolveVeloFixClarification } from "@/runtime/e2e/clarification-resolver";
import { FactoryProjectSchema } from "@/domain/project/schema";
import { evaluatePlanningAcceptanceReadiness } from "@/agents/planner/deterministic";
import type { ProductionFactoryRuntime } from "./production-factory-runtime";
import { ownershipForTask } from "@/domain/tasks/ownership";
import { RUNTIME_DIAGNOSTIC_POLICY_VERSION } from "@/runtime/validation/contracts";
import { TaskGraphSchema } from "@/domain/tasks/schema";
import { deriveQaPolicyRefreshIdentity } from "@/orchestration/execution/qa-policy";
import { RequirementSpecificationSchema, type RequirementSpecification } from "@/domain/requirements/schema";
import { BriefV3DocumentSchema, type BriefV3Document } from "@/persistence/database/brief-revision-v3-contracts";
import type { BriefApprovalResult } from "@/runtime/trial-entry/brief-approval";
import { FACTORY_ARCHITECTURE_STACK } from "@/agents/reviewers/architecture/contracts";
import { taskExecutionCapability } from "@/orchestration/execution/capabilities";
import { canonicalBriefToPlannerBrief } from "@/agents/planner/brief-context";

export type ProductionE2EStageSink = (event: { stage: string; status: "started" | "passed" | "failed"; safeCode?: string }) => void | Promise<void>;
export type ValidatedSmokeSpecification = { prompt: string; slugPrefix: string; answers: Record<string, string> };
export type RealFactoryE2EResumeInput = { smokeId: string; report: RealFactoryE2EReport };
export const VELOFIX_SMOKE_SPECIFICATION: ValidatedSmokeSpecification = { prompt: VELOFIX_WERKSTATT_PROMPT, slugPrefix: "real-e2e-velofix", answers: { "project-identity": "VeloFix Werkstatt", "business-purpose": "Bicycle repairs", audience: "Local bicycle owners", "project-type": "A synthetic German bicycle repair workshop website", pages: "home, services, appointment", functionality: "Request an appointment with an appointment form", forms: "Request an appointment with client and server validation", languages: "German", localization: "German", "image-sourcing": "Use placeholders for imagery", logo: "No supplied logo", brand: "No supplied brand facts", authentication: "No authentication", database: "No real database", storage: "No Storage", email: "No real email", administration: "No admin", contact: "No contact details supplied", seo: "No additional SEO facts are supplied", exclusions: "No additional scope beyond the supplied VeloFix facts" } };

type Evidence = { leadRequest: boolean; plannerRequest: boolean; designRequest: boolean; implementationRequest: boolean; npmExecution: boolean; browserExecution: boolean };
type Stage = RealFactoryE2EReport["stages"][number];
const now = () => new Date().toISOString();
/**
 * The Planner still consumes the legacy-shaped brief contract. This adapter is
 * intentionally in-memory: host approval is persisted only on brief-v3, and
 * the legacy requirements document remains a read-only compatibility source.
 */
const approvedLegacyBriefForDownstream = (brief: RequirementSpecification, metadata: { briefChecksum: string; approvedAt: string; approvedBy: string; approvalNote?: string }) => RequirementSpecificationSchema.parse({
  ...brief,
  updatedAt: metadata.approvedAt,
  briefStatus: "approved",
  approval: {
    approved: true,
    approvedAt: metadata.approvedAt,
    approvedBy: metadata.approvedBy,
    approvedRequirementsChecksum: metadata.briefChecksum,
  },
  ...(metadata.approvalNote ? { briefApprovalNote: metadata.approvalNote } : {}),
});
const downstreamBriefFromHostApproval = (brief: RequirementSpecification, approval: BriefApprovalResult, approvedBy: string, approvedAt: string) => approvedLegacyBriefForDownstream(brief, { briefChecksum: approval.briefChecksum, approvedBy, approvedAt });
const approvedLegacyBriefFromV3 = (brief: RequirementSpecification, document: BriefV3Document) => document.approval?.approved ? canonicalBriefToPlannerBrief(document.brief, brief, document.approval) : brief;
const safeCode = (error: unknown) => typeof error === "object" && error && "code" in error && typeof error.code === "string" ? error.code : error instanceof Error && /^[A-Z0-9_]+$/.test(error.message) ? error.message : "REAL_E2E_STAGE_FAILED";
const message = (error: unknown) => { if (typeof error === "object" && error && "details" in error && error.details && typeof error.details === "object") { const details = error.details as Record<string, unknown>; if (details.questionId && details.fixtureResolution === "missing") return `Clarification unresolved: questionId=${String(details.questionId)} category=${String(details.category)} blocking=${String(details.blocking)} fixtureResolution=missing safeReason=${String(details.safeReason)}`; if (Array.isArray(details.blockingReasons) || Array.isArray(details.unresolvedItems)) return `Brief readiness failed: blockingReasons=${JSON.stringify(details.blockingReasons ?? [])} unresolvedItems=${JSON.stringify(details.unresolvedItems ?? [])}`; } if (typeof error === "object" && error && "code" in error && error.code === "PLANNER_PROVIDER_FAILED") { let cause: unknown = "cause" in error ? error.cause : undefined; const codes: string[] = []; for (let depth = 0; depth < 3 && cause && typeof cause === "object"; depth++) { if (!("code" in cause) || typeof cause.code !== "string") break; codes.push(cause.code); cause = "cause" in cause ? cause.cause : undefined; } if (codes.length) return `Planner provider failed safely: providerCodes=${codes.join(">")}`; } if (typeof error === "object" && error && "code" in error && (error.code === "PLANNING_PACKAGE_INVALID" || error.code === "DESIGN_DIRECTION_COUNT_INVALID" || error.code === "DESIGN_DIRECTION_SCHEMA_INVALID") && "cause" in error && error.cause && typeof error.cause === "object" && "issues" in error.cause && Array.isArray(error.cause.issues)) { const path = error.cause.issues[0]?.path; if (Array.isArray(path)) return `${error.code.startsWith("DESIGN") ? "Design" : "Planner"} output failed canonical validation safely: schemaPath=${path.slice(0, 8).join(".")}`; } return error instanceof Error ? error.message.slice(0, 300) : "Stage failed safely."; };
const checkpointStages = ["PROJECT", "LEAD", "CLARIFICATION", "BRIEF_FINALIZATION", "BRIEF_VALIDATION", "BRIEF_APPROVAL", "PLANNER", "PLANNING_ACCEPTANCE", "ARCHITECTURE_REVIEW", "DESIGN", "DESIGN_SELECTION", "ORCHESTRATOR", "START_IMPLEMENTATION"] as const;
export function validateResumeIdentity(report: RealFactoryE2EReport, smokeId: string) { if (report.smokeId !== smokeId || !report.projectId || !report.projectVersion || !report.projectPathReference) throw Object.assign(new Error("REAL_E2E_RESUME_IDENTITY_MISMATCH"), { code: "REAL_E2E_RESUME_IDENTITY_MISMATCH" }); return true; }
export function validateResumeCheckpoint(report: RealFactoryE2EReport) { for (const name of checkpointStages) { const stage = report.stages.find((candidate) => candidate.name === name); if (!stage || stage.status !== "passed") throw Object.assign(new Error(`REAL_E2E_RESUME_CHECKPOINT_INVALID:${name}`), { code: "REAL_E2E_RESUME_CHECKPOINT_INVALID" }); } return true; }

export async function runProductionE2EStages(input: { specification: ValidatedSmokeSpecification; runtime: ProductionFactoryRuntime; smokeId: string; signal?: AbortSignal; sink?: ProductionE2EStageSink; policy?: FullExecutionPolicy; resume?: RealFactoryE2EResumeInput }): Promise<RealFactoryE2EReport> {
  const startedAt = now(); const evidence: Evidence = { leadRequest: false, plannerRequest: false, designRequest: false, implementationRequest: false, npmExecution: false, browserExecution: false }; const stages: Stage[] = []; let projectId: string | undefined; let projectVersion: number | undefined; let projectPathReference: string | undefined;
  const base = { schemaVersion: 1 as const, reportType: "real-factory-e2e" as const, smokeId: input.smokeId, startedAt, optIn: true, preflightPassed: true, adapterIdentity: { leadProviderMode: "production", plannerProviderMode: "production", designProviderMode: "production", implementationProviderMode: "production", processRunnerMode: "real", browserRunnerMode: "real", executionStateMode: "production", taskExecutorMode: "production", repairerMode: "production", fullExecutorMode: "production" }, realStageEvidence: evidence, stages, provider: { status: "configured" as const, requestCount: 0, inputTokens: 0, outputTokens: 0 }, context7: { status: input.runtime.identity.context7 === "configured" ? "configured" as const : input.runtime.identity.context7 === "blocked" ? "blocked" as const : "not-needed" as const, requestCount: 0 }, shadcn: { status: input.runtime.identity.shadcn === "configured" ? "configured" as const : input.runtime.identity.shadcn === "blocked" ? "blocked" as const : "not-needed" as const, requestCount: 0 }, npm: { status: "not-configured" as const, commands: ["npm ci", "npm run lint", "npm run typecheck", "npm test", "npm run build"], passedCount: 0, failedCount: 0 }, playwright: { status: "not-configured" as const, scenarios: 0, passedCount: 0, failedCount: 0, unexpectedExternalRequests: 0 }, taskGraph: { taskCount: 0, passedCount: 0, failedCount: 0, repairCount: 0 }, generatedFiles: { createdCount: 0, changedCount: 0, checksumVerified: false }, blockers: [] as string[], warnings: [] as string[], releaseEligible: false, prohibitedActions: { deployment: false, gitMutation: false, customerDatabaseMigration: false, customerDataAccess: false, arbitraryBrowsing: false, screenshots: false } };
  if (input.resume) return resumeProductionE2E({ input, base });
  const stage = async <T>(name: string, operation: () => Promise<T>): Promise<T> => { const started = now(); await input.sink?.({ stage: name, status: "started" }); if (input.signal?.aborted) throw Object.assign(new Error("REAL_E2E_CANCELLED"), { code: "REAL_E2E_CANCELLED" }); try { const value = await operation(); stages.push({ name, status: "passed", executionMode: "EXECUTED", startedAt: started, completedAt: now(), summary: `${name} completed.` }); await input.sink?.({ stage: name, status: "passed" }); return value; } catch (error) { const code = safeCode(error); stages.push({ name, status: "failed", executionMode: "EXECUTED", startedAt: started, completedAt: now(), safeFailureCode: code, summary: message(error) }); await input.sink?.({ stage: name, status: "failed", safeCode: code }); throw error; } };
  try {
    if (input.specification.prompt !== VELOFIX_WERKSTATT_PROMPT || input.specification.slugPrefix !== VELOFIX_SMOKE_SPECIFICATION.slugPrefix || JSON.stringify(input.specification.answers) !== JSON.stringify(VELOFIX_SMOKE_SPECIFICATION.answers)) throw Object.assign(new Error("REAL_E2E_SMOKE_SPEC_INVALID"), { code: "REAL_E2E_SMOKE_SPEC_INVALID" });
    const generatedRoot = path.resolve(input.runtime.generatedProjectsRoot ?? process.env.GENERATED_PROJECTS_ROOT ?? ".factory-generated"); const smokeRoot = safeSmokeProjectReference(generatedRoot, input.smokeId); const slug = `${input.specification.slugPrefix}-${input.smokeId}`; const workspaceRoot = path.dirname(smokeRoot); const scope = input.runtime.createProjectScope({ workspaceRoot, slug });
    await stage("PROJECT", async () => { const intakeProjectId = randomUUID(); await scope.workspace.createProjectRoot(FactoryProjectSchema.parse({ schemaVersion: 1, documentType: "factory-project", projectId: intakeProjectId, projectVersion: 1, createdAt: now(), updatedAt: now(), id: intakeProjectId, slug, origin: "SMOKE", title: "VeloFix Werkstatt", originalPrompt: input.specification.prompt, currentVersion: 1, workflowState: "DRAFT" })); const result = await scope.lead.startProjectIntake({ projectId: intakeProjectId, projectVersion: 1, originalPrompt: input.specification.prompt, suppliedFiles: [], knownUserAnswers: {}, currentWorkflowState: "DRAFT", projectSlug: slug, projectTitle: "VeloFix Werkstatt", origin: "SMOKE", idempotencyKey: `real-e2e-intake-${input.smokeId}` }); projectId = result.id; const materialized = await scope.workspace.materializeReservedInitialVersion(result, { operationId: `real-e2e-${input.smokeId}` }); projectVersion = materialized.version.versionNumber; projectPathReference = materialized.path; return result; });
    const leadInput = { projectId: projectId!, projectVersion: projectVersion!, originalPrompt: input.specification.prompt, suppliedFiles: [], knownUserAnswers: {}, currentWorkflowState: "DRAFT" as const, idempotencyKey: `real-e2e-lead-${input.smokeId}`, projectSlug: slug, projectTitle: "VeloFix Werkstatt", operatorLanguage: "en" as const, origin: "SMOKE" as const };
    await stage("LEAD", async () => { const analysis = await scope.lead.analyzeProjectPrompt(leadInput); evidence.leadRequest = input.runtime.evidence.roles.lead > 0 || input.runtime.evidence.roles["lead-agent"] > 0; const plan = await scope.lead.planClarifications(leadInput); return { analysis, plan }; });
    await stage("CLARIFICATION", async () => { const maxRounds = 2; for (let round = 0; round < maxRounds; round++) { const status = await scope.lead.getClarificationStatus(projectId!, projectVersion!); let answered = 0; for (const question of status.unresolved) { const resolution = resolveVeloFixClarification(question); if (!resolution.answer) { if (question.blocking) throw Object.assign(new Error("REAL_E2E_UNRESOLVED_CLARIFICATION"), { code: "REAL_E2E_UNRESOLVED_CLARIFICATION", details: { questionId: question.id, category: question.category, blocking: question.blocking, fixtureResolution: "missing", safeReason: "safeReason" in resolution ? resolution.safeReason : "FIXTURE_FACT_MISSING" } }); continue; } await scope.lead.recordClarificationAnswer({ projectId: projectId!, projectVersion: projectVersion!, questionId: question.id, status: "answered", answer: resolution.answer, answeredBy: "real-e2e-smoke", idempotencyKey: `real-e2e-answer-${input.smokeId}-${question.id}` }); answered++; } const next = await scope.lead.getClarificationStatus(projectId!, projectVersion!); if (!next.blockingUnresolved.length) return next; if (!answered) break; await scope.lead.planClarifications(leadInput); } throw Object.assign(new Error("REAL_E2E_CLARIFICATION_LIMIT_EXCEEDED"), { code: "REAL_E2E_CLARIFICATION_LIMIT_EXCEEDED" }); });
    const draft = await stage("BRIEF_FINALIZATION", async () => scope.lead.buildBriefDraft(projectId!, projectVersion!));
    await stage("BRIEF_VALIDATION", async () => { if (!draft.readyForApproval) throw Object.assign(new Error("LEAD_BRIEF_NOT_READY"), { code: "LEAD_BRIEF_NOT_READY", details: { blockingReasons: draft.blockingReasons.slice(0, 10), unresolvedItems: draft.unresolvedItems.filter((item) => item.blocking).map((item) => item.key).slice(0, 10) } }); return draft; });
    const approved = await stage("BRIEF_APPROVAL", async () => { const current = await new ProjectRepository(scope.database).getWithVersion(projectId!); const approvedAt = now(); const result = await scope.briefApproval.approve({ projectId: projectId!, projectVersion: projectVersion!, briefChecksum: draft.briefChecksum, approvedBy: "real-e2e-smoke", expectedRowVersion: current!.rowVersion, idempotencyKey: `real-e2e-brief-${input.smokeId}` }); return { brief: { requirements: downstreamBriefFromHostApproval(draft.requirements, result, "real-e2e-smoke", approvedAt), briefChecksum: result.briefChecksum }, rowVersion: result.rowVersion }; });
    const planning = await stage("PLANNER", async () => { const current = await new ProjectRepository(scope.database).getWithVersion(projectId!); const result = await scope.planner.planApprovedProject({ projectId: projectId!, projectVersion: projectVersion!, approvedBrief: approved.brief.requirements, approvedBriefChecksum: approved.brief.briefChecksum, originalPromptReference: "original-prompt.md", clarificationEvidenceReferences: ["clarification-log.json"], currentWorkflowState: "AWAITING_DESIGN_SELECTION", existingDecisions: [], suppliedFiles: [], allowedSkills: [], idempotencyKey: `real-e2e-planner-${input.smokeId}`, expectedRowVersion: current!.rowVersion }); evidence.plannerRequest = input.runtime.evidence.roles.planner > 0 || input.runtime.evidence.roles["planner-architect"] > 0; return result; });
    const accepted = await stage("PLANNING_ACCEPTANCE", async () => scope.planner.acceptPlanningPackage({ projectId: projectId!, projectVersion: projectVersion!, planningChecksum: checksumPersistedDocument(planning), acceptedAt: now(), acceptedBy: "real-e2e-smoke", expectedRowVersion: (await new ProjectRepository(scope.database).getWithVersion(projectId!))!.rowVersion, idempotencyKey: `real-e2e-planning-accept-${input.smokeId}` }));
    await stage("ARCHITECTURE_REVIEW", async () => { const current = await new ProjectRepository(scope.database).getWithVersion(projectId!); return scope.architectureReviewer.reviewAndRoute({ projectId: projectId!, projectVersion: projectVersion!, approvedBrief: approved.brief.requirements, approvedBriefChecksum: approved.brief.briefChecksum, acceptedPlanningPackage: accepted.package, acceptedPlanningChecksum: accepted.planningChecksum, factoryArchitecturePolicy: { policyVersion: "factory-architecture-v1", stack: [...FACTORY_ARCHITECTURE_STACK], prohibitedTechnologies: ["redis", "nestjs"], serverActionPreference: "preferred", routeHandlerPreference: "second", packageManager: "npm" }, relevantProjectConstraints: approved.brief.requirements.technicalConstraints, idempotencyKey: `real-e2e-architecture-review-${input.smokeId}`, expectedRowVersion: current!.rowVersion }); });
    const design = await stage("DESIGN", async () => { const current = await new ProjectRepository(scope.database).getWithVersion(projectId!); const result = await scope.design.generateDesignDirections({ projectId: projectId!, projectVersion: projectVersion!, approvedBrief: approved.brief.requirements, approvedBriefChecksum: approved.brief.briefChecksum, acceptedPlanningPackage: accepted.package, acceptedPlanningChecksum: accepted.planningChecksum, contentPlan: accepted.package.content, assetManifest: accepted.package.assets, suppliedBrandMetadata: {}, suppliedLogoMetadata: approved.brief.requirements.suppliedLogoLocation, imageSourceDecision: approved.brief.requirements.imageSourceDecision, designPreferences: [], explicitDesignExclusions: [], currentWorkflowState: "AWAITING_DESIGN_SELECTION", existingDecisions: [], allowedSkills: [], idempotencyKey: `real-e2e-design-${input.smokeId}`, expectedRowVersion: current!.rowVersion }); evidence.designRequest = input.runtime.evidence.roles.design > 0; return result; });
    const selected = await stage("DESIGN_SELECTION", async () => scope.design.selectDesignDirection({ projectId: projectId!, projectVersion: projectVersion!, designDirectionSetId: design.directionSet.setId, selectedDirectionId: design.directionSet.directions[0].id, directionSetChecksum: design.readiness.directionSetChecksum, selectedDirectionChecksum: checksumPersistedDocument(design.directionSet.directions[0]), expectedRowVersion: (await new ProjectRepository(scope.database).getWithVersion(projectId!))!.rowVersion, selectedBy: "real-e2e-smoke", selectedAt: now(), selectionNotes: "Synthetic smoke selection of direction one.", idempotencyKey: `real-e2e-selection-${input.smokeId}` }));
    const documents = new DocumentRepository(scope.database); const decisions = await new DecisionRepository(scope.database).list(projectId!, projectVersion!); const phase7cDocument = await documents.get(projectId!, projectVersion!, "phase-7c-contract-package"); if (!phase7cDocument || phase7cDocument.documentType !== "phase-7c-contract-package") throw Object.assign(new Error("REAL_E2E_PHASE_7C_MISSING"), { code: "REAL_E2E_PHASE_7C_MISSING" }); const brief = approved.brief.requirements; const acceptedPlanning = accepted.package; const allowedRoles: ("lead" | "planner-architect" | "design" | "implementation" | "qa-release")[] = ["lead", "planner-architect", "design", "implementation", "qa-release"]; const orchestratorInput = { projectId: projectId!, projectVersion: projectVersion!, approvedBrief: brief, approvedBriefChecksum: approved.brief.briefChecksum, acceptedPlanningPackage: acceptedPlanning, acceptedPlanningChecksum: accepted.planningChecksum, selectedDesign: selected.selectedDesign, selectedDesignChecksum: checksumPersistedDocument(selected.selectedDesign), technicalArchitecture: acceptedPlanning.architecture, contentPlan: acceptedPlanning.content, assetManifest: acceptedPlanning.assets, currentWorkflowState: "READY_FOR_IMPLEMENTATION" as const, existingDecisions: decisions, allowedRoles, approvedSkillRegistrySnapshot: { schemaVersion: 1 as const, checksum: "0".repeat(64), skills: [] }, toolPolicyVersion: "tools-v1", orchestrationPolicyVersion: DEFAULT_ORCHESTRATION_POLICY.version, idempotencyKey: `real-e2e-orchestrator-${input.smokeId}`, expectedRowVersion: (await new ProjectRepository(scope.database).getWithVersion(projectId!))!.rowVersion, workspaceReserved: true, projectImmutable: false, phase7cContractPackage: phase7cDocument };
     const graph = await stage("ORCHESTRATOR", async () => { const result = await scope.orchestrator.createImplementationTaskGraph(orchestratorInput); if (!result.valid || !result.readyForExecution) throw Object.assign(new Error("REAL_E2E_TASK_GRAPH_INVALID"), { code: "REAL_E2E_TASK_GRAPH_INVALID" }); return result; });
     await stage("CONTRACT_AUDIT", async () => { const review = await documents.get(projectId!, projectVersion!, "architecture-review"); if (!review || review.documentType !== "architecture-review") throw Object.assign(new Error("REAL_E2E_ARCHITECTURE_REVIEW_MISSING"), { code: "REAL_E2E_ARCHITECTURE_REVIEW_MISSING" }); const entered = await scope.contractAuditor.enterAudit({ projectId: projectId!, projectVersion: projectVersion!, expectedRowVersion: (await new ProjectRepository(scope.database).getWithVersion(projectId!))!.rowVersion, idempotencyKey: `real-e2e-contract-audit-enter-${input.smokeId}` }); const result = await scope.contractAuditor.auditAndRoute({ projectId: projectId!, projectVersion: projectVersion!, approvedBrief: brief, briefChecksum: approved.brief.briefChecksum, acceptedPlanningPackage: acceptedPlanning, planningChecksum: accepted.planningChecksum, approvedArchitectureReview: review, architectureReviewChecksum: checksumPersistedDocument(review), selectedDesign: selected.selectedDesign, designChecksum: checksumPersistedDocument(selected.selectedDesign), taskGraph: graph.taskGraph, taskGraphChecksum: graph.taskGraph.graphChecksum!, executorCatalog: [{ executorId: "factory-runtime", kind: "runtime" as const, current: true, capabilities: [...new Set(graph.taskGraph.tasks.map((task) => taskExecutionCapability(task.taskType)).filter(Boolean) as string[])] }], idempotencyKey: `real-e2e-contract-audit-${input.smokeId}`, expectedRowVersion: entered.rowVersion }); if (result.result.verdict !== "APPROVED") throw Object.assign(new Error("REAL_E2E_CONTRACT_AUDIT_REJECTED"), { code: "REAL_E2E_CONTRACT_AUDIT_REJECTED" }); return result; });
     const approvedAudit = await documents.get(projectId!, projectVersion!, "contract-audit"); if (!approvedAudit || approvedAudit.documentType !== "contract-audit") throw Object.assign(new Error("REAL_E2E_CONTRACT_AUDIT_MISSING"), { code: "REAL_E2E_CONTRACT_AUDIT_MISSING" });
     const started = await stage("START_IMPLEMENTATION", async () => scope.orchestrator.startImplementation({ ...orchestratorInput, approvedContractAuditChecksum: checksumPersistedDocument(approvedAudit), expectedRowVersion: (await new ProjectRepository(scope.database).getWithVersion(projectId!))!.rowVersion }));
    const staging = await scope.workspace.createMutableExecutionStaging(started.project, projectVersion!, `real-e2e-run-${input.smokeId}`); const context = { projectId: projectId!, projectVersion: projectVersion!, workspacePath: staging, generatedProjectsRoot: workspaceRoot, workspaceReservationId: `real-e2e-run-${input.smokeId}`, sourceDocumentChecksums: graph.taskGraph.sourceDocumentChecksums ?? {}, toolPolicyVersion: graph.taskGraph.toolPolicyVersion ?? "tools-v1", orchestrationPolicyVersion: graph.taskGraph.orchestrationPolicyVersion ?? DEFAULT_ORCHESTRATION_POLICY.version, approvedSkillSnapshotChecksum: graph.taskGraph.approvedSkillSnapshotChecksum, evidence: { implementationRequest: () => { evidence.implementationRequest = true; }, npmExecution: () => { evidence.npmExecution = true; }, browserExecution: () => { evidence.browserExecution = true; } } };
    const run = await stage("FULL_EXECUTION", async () => { const result = await scope.createFullExecutor({ ...context, policy: { ...(input.policy ?? DEFAULT_FULL_EXECUTION_POLICY), maxConcurrency: 1 } }).execute({ projectId: projectId!, projectVersion: projectVersion!, idempotencyKey: `real-e2e-execution-${input.smokeId}`, graph: started.taskGraph, expectedGraphChecksum: started.taskGraph.graphChecksum!, workflowState: "IMPLEMENTING", projectImmutable: false, workspaceValid: true, sourceDocumentChecksums: context.sourceDocumentChecksums, currentDocumentChecksums: context.sourceDocumentChecksums, toolPolicyVersion: context.toolPolicyVersion, activeRunIds: [], signal: input.signal }); if (result.status !== "completed") throw Object.assign(new Error(`Full execution ended with status ${result.status}; safeFailureCode=${result.safeFailureCode ?? "REAL_E2E_FULL_EXECUTION_INCOMPLETE"}.`), { code: result.safeFailureCode ?? "REAL_E2E_FULL_EXECUTION_INCOMPLETE" }); return result; });
    if (evidence.npmExecution) stages.push({ name: "RUNTIME", status: "passed", executionMode: "EXECUTED", completedAt: now(), summary: "Real ProcessRunner evidence was recorded by the production adapter." }); else stages.push({ name: "RUNTIME", status: "failed", executionMode: "EXECUTED", completedAt: now(), safeFailureCode: "REAL_E2E_RUNTIME_EVIDENCE_MISSING", summary: "Real ProcessRunner evidence is missing." });
    if (evidence.browserExecution) stages.push({ name: "QA", status: "passed", executionMode: "EXECUTED", completedAt: now(), summary: "Real Playwright evidence was recorded by the production adapter." }); else stages.push({ name: "QA", status: "failed", executionMode: "EXECUTED", completedAt: now(), safeFailureCode: "REAL_E2E_BROWSER_EVIDENCE_MISSING", summary: "Real Playwright evidence is missing." });
    const summary = await stage("RELEASE_ELIGIBILITY", async () => documents.get(projectId!, projectVersion!, "full-execution")); if (!summary || summary.documentType !== "full-execution" || run.status !== "completed" || !summary.releaseEligible || !Object.values(evidence).every(Boolean)) throw Object.assign(new Error("REAL_E2E_REAL_STAGE_EVIDENCE_INCOMPLETE"), { code: "REAL_E2E_REAL_STAGE_EVIDENCE_INCOMPLETE" });
    const runtimeEvidence = input.runtime.evidence; if (base.context7.status === "blocked" || base.shadcn.status === "blocked") throw Object.assign(new Error("REAL_E2E_OPTIONAL_INTEGRATION_BLOCKED"), { code: "REAL_E2E_OPTIONAL_INTEGRATION_BLOCKED" }); const report = RealFactoryE2EReportSchema.parse({ ...base, projectId, projectVersion, projectPathReference, completedAt: now(), overallStatus: "passed", realStageEvidence: evidence, stages, provider: { status: "configured", modelLabel: input.runtime.ai.config.model, requestCount: runtimeEvidence.providerRequests, inputTokens: runtimeEvidence.inputTokens, outputTokens: runtimeEvidence.outputTokens }, npm: { ...base.npm, status: "configured", passedCount: 4 }, playwright: { ...base.playwright, status: "configured", scenarios: 1, passedCount: 1 }, taskGraph: { taskCount: summary.totalTasks, passedCount: summary.passed, failedCount: summary.failed, repairCount: summary.repairsAttempted }, generatedFiles: { ...base.generatedFiles, checksumVerified: true }, releaseEligible: summary.releaseEligible }); return report;
  } catch (error) { const runtimeEvidence = input.runtime.evidence; return RealFactoryE2EReportSchema.parse({ ...base, projectId, projectVersion, projectPathReference, completedAt: now(), overallStatus: "failed", realStageEvidence: evidence, provider: { status: "configured", modelLabel: input.runtime.ai.config.model, requestCount: runtimeEvidence.providerRequests, inputTokens: runtimeEvidence.inputTokens, outputTokens: runtimeEvidence.outputTokens }, blockers: [safeCode(error), message(error)] }); }
}

function resumeStageNames(report: RealFactoryE2EReport) { validateResumeCheckpoint(report); return checkpointStages.map((name) => { const prior = report.stages.find((stage) => stage.name === name)!; return { ...prior, executionMode: "REUSED_VALIDATED" as const, summary: `${name} reused from validated persisted checkpoint.` }; }); }

async function resumeFromClarification(options: { input: { specification: ValidatedSmokeSpecification; runtime: ProductionFactoryRuntime; smokeId: string; signal?: AbortSignal; policy?: FullExecutionPolicy; resume?: RealFactoryE2EResumeInput }; base: Record<string, unknown> }) {
  const previous = options.input.resume!.report; const projectId = previous.projectId!; const projectVersion = previous.projectVersion!; const projectPath = path.resolve(previous.projectPathReference!); const workspaceRoot = path.dirname(path.dirname(projectPath)); const slug = path.basename(path.dirname(projectPath)); const scope = options.input.runtime.createProjectScope({ workspaceRoot, slug }); const stages: Stage[] = previous.stages.filter((stage) => ["PROJECT", "LEAD", "CLARIFICATION"].includes(stage.name)).map((stage) => ({ ...stage, executionMode: "REUSED_VALIDATED" as const, summary: `${stage.name} reused from validated persisted checkpoint.` })); const evidence: Evidence = { leadRequest: false, plannerRequest: false, designRequest: false, implementationRequest: false, npmExecution: false, browserExecution: false }; const stage = async <T>(name: string, operation: () => Promise<T>) => { const started = now(); try { const value = await operation(); stages.push({ name, status: "passed", executionMode: "RESUMED", startedAt: started, completedAt: now(), summary: `${name} completed after clarification-policy reconciliation.` }); return value; } catch (error) { stages.push({ name, status: "failed", executionMode: "RESUMED", startedAt: started, completedAt: now(), safeFailureCode: safeCode(error), summary: message(error) }); throw error; } };
  try {
    const current = await new ProjectRepository(scope.database).getWithVersion(projectId); if (!current || !["CLARIFYING", "AWAITING_BRIEF_APPROVAL", "AWAITING_DESIGN_SELECTION"].includes(current.project.workflowState)) throw Object.assign(new Error("REAL_E2E_RESUME_CLARIFICATION_STATE_INVALID"), { code: "REAL_E2E_RESUME_CLARIFICATION_STATE_INVALID" });
    const approved: { brief: { requirements: RequirementSpecification; briefChecksum: string }; rowVersion: number } = current.project.workflowState === "AWAITING_DESIGN_SELECTION" ? await (async () => { const persisted = await new DocumentRepository(scope.database).get(projectId, projectVersion, "requirements"); if (!persisted || persisted.documentType !== "requirements") throw Object.assign(new Error("REAL_E2E_RESUME_BRIEF_MISSING"), { code: "REAL_E2E_RESUME_BRIEF_MISSING" }); const v3 = await new DocumentRepository(scope.database).get(projectId, projectVersion, "brief-v3"); const document = v3?.documentType === "brief-v3" ? BriefV3DocumentSchema.parse(v3) : null; if (!document?.approval?.approved || document.approval.approvedCanonicalChecksum !== document.briefChecksum) throw Object.assign(new Error("REAL_E2E_RESUME_BRIEF_V3_APPROVAL_MISSING"), { code: "REAL_E2E_RESUME_BRIEF_V3_APPROVAL_MISSING" }); return { brief: { requirements: approvedLegacyBriefFromV3(persisted, document), briefChecksum: document.briefChecksum }, rowVersion: current.rowVersion }; })() : await (async () => { await scope.lead.analyzeProjectPrompt({ projectId, projectVersion, originalPrompt: options.input.specification.prompt, suppliedFiles: [], knownUserAnswers: {}, currentWorkflowState: "DRAFT", idempotencyKey: `real-e2e-lead-${options.input.smokeId}`, projectSlug: slug, projectTitle: "VeloFix Werkstatt" }); const draft = await stage("BRIEF_FINALIZATION", () => scope.lead.buildBriefDraft(projectId, projectVersion)); await stage("BRIEF_VALIDATION", async () => { if (!draft.readyForApproval) throw Object.assign(new Error("LEAD_BRIEF_NOT_READY"), { code: "LEAD_BRIEF_NOT_READY", details: { blockingReasons: draft.blockingReasons.slice(0, 10), unresolvedItems: draft.unresolvedItems.filter((item) => item.blocking).map((item) => item.key).slice(0, 10) } }); return draft; }); const approvedAt = now(); const result = await scope.briefApproval.approve({ projectId, projectVersion, briefChecksum: draft.briefChecksum, approvedBy: "real-e2e-smoke", expectedRowVersion: (await new ProjectRepository(scope.database).getWithVersion(projectId))!.rowVersion, idempotencyKey: `real-e2e-brief-${options.input.smokeId}` }); return { brief: { requirements: downstreamBriefFromHostApproval(draft.requirements, result, "real-e2e-smoke", approvedAt), briefChecksum: result.briefChecksum }, rowVersion: result.rowVersion }; })();
    const planning = await stage("PLANNER", async () => { const row = await new ProjectRepository(scope.database).getWithVersion(projectId); const result = await scope.planner.planApprovedProject({ projectId, projectVersion, approvedBrief: approved.brief.requirements, approvedBriefChecksum: approved.brief.briefChecksum, originalPromptReference: "original-prompt.md", clarificationEvidenceReferences: ["clarification-log.json"], currentWorkflowState: "AWAITING_DESIGN_SELECTION", existingDecisions: [], suppliedFiles: [], allowedSkills: [], idempotencyKey: `real-e2e-planner-correction-${options.input.smokeId}`, expectedRowVersion: row!.rowVersion }); evidence.plannerRequest = options.input.runtime.evidence.roles.planner > 0 || options.input.runtime.evidence.roles["planner-architect"] > 0; return result; });
    const accepted = await stage("PLANNING_ACCEPTANCE", async () => scope.planner.acceptPlanningPackage({ projectId, projectVersion, planningChecksum: checksumPersistedDocument(planning), acceptedAt: now(), acceptedBy: "real-e2e-smoke", expectedRowVersion: (await new ProjectRepository(scope.database).getWithVersion(projectId))!.rowVersion, idempotencyKey: `real-e2e-planning-accept-${options.input.smokeId}` }));
    const design = await stage("DESIGN", async () => { const row = await new ProjectRepository(scope.database).getWithVersion(projectId); const result = await scope.design.generateDesignDirections({ projectId, projectVersion, approvedBrief: approved.brief.requirements, approvedBriefChecksum: approved.brief.briefChecksum, acceptedPlanningPackage: accepted.package, acceptedPlanningChecksum: accepted.planningChecksum, contentPlan: accepted.package.content, assetManifest: accepted.package.assets, suppliedBrandMetadata: {}, suppliedLogoMetadata: approved.brief.requirements.suppliedLogoLocation, imageSourceDecision: approved.brief.requirements.imageSourceDecision, designPreferences: [], explicitDesignExclusions: [], currentWorkflowState: "AWAITING_DESIGN_SELECTION", existingDecisions: [], allowedSkills: [], idempotencyKey: `real-e2e-design-${options.input.smokeId}`, expectedRowVersion: row!.rowVersion }); evidence.designRequest = options.input.runtime.evidence.roles.design > 0; return result; });
    const selected = await stage("DESIGN_SELECTION", async () => scope.design.selectDesignDirection({ projectId, projectVersion, designDirectionSetId: design.directionSet.setId, selectedDirectionId: design.directionSet.directions[0].id, directionSetChecksum: design.readiness.directionSetChecksum, selectedDirectionChecksum: checksumPersistedDocument(design.directionSet.directions[0]), expectedRowVersion: (await new ProjectRepository(scope.database).getWithVersion(projectId))!.rowVersion, selectedBy: "real-e2e-smoke", selectedAt: now(), selectionNotes: "Synthetic smoke selection of direction one.", idempotencyKey: `real-e2e-selection-${options.input.smokeId}` }));
    const documents = new DocumentRepository(scope.database); const decisions = await new DecisionRepository(scope.database).list(projectId, projectVersion); const phase7cDocument = await documents.get(projectId, projectVersion, "phase-7c-contract-package"); if (!phase7cDocument || phase7cDocument.documentType !== "phase-7c-contract-package") throw Object.assign(new Error("REAL_E2E_PHASE_7C_MISSING"), { code: "REAL_E2E_PHASE_7C_MISSING" }); const orchestratorInput = { projectId, projectVersion, approvedBrief: approved.brief.requirements, approvedBriefChecksum: approved.brief.briefChecksum, acceptedPlanningPackage: accepted.package, acceptedPlanningChecksum: accepted.planningChecksum, selectedDesign: selected.selectedDesign, selectedDesignChecksum: checksumPersistedDocument(selected.selectedDesign), technicalArchitecture: accepted.package.architecture, contentPlan: accepted.package.content, assetManifest: accepted.package.assets, currentWorkflowState: "READY_FOR_IMPLEMENTATION" as const, existingDecisions: decisions, allowedRoles: ["lead", "planner-architect", "design", "implementation", "qa-release"] as ("lead" | "planner-architect" | "design" | "implementation" | "qa-release")[], approvedSkillRegistrySnapshot: { schemaVersion: 1 as const, checksum: "0".repeat(64), skills: [] }, toolPolicyVersion: "tools-v1", orchestrationPolicyVersion: DEFAULT_ORCHESTRATION_POLICY.version, idempotencyKey: `real-e2e-orchestrator-${options.input.smokeId}`, expectedRowVersion: (await new ProjectRepository(scope.database).getWithVersion(projectId))!.rowVersion, workspaceReserved: true, projectImmutable: false, phase7cContractPackage: phase7cDocument };
     const graph = await stage("ORCHESTRATOR", async () => { const result = await scope.orchestrator.createImplementationTaskGraph(orchestratorInput); if (!result.valid || !result.readyForExecution) throw Object.assign(new Error("REAL_E2E_TASK_GRAPH_INVALID"), { code: "REAL_E2E_TASK_GRAPH_INVALID" }); return result; });
     await stage("CONTRACT_AUDIT", async () => { const review = await documents.get(projectId, projectVersion, "architecture-review"); if (!review || review.documentType !== "architecture-review") throw Object.assign(new Error("REAL_E2E_ARCHITECTURE_REVIEW_MISSING"), { code: "REAL_E2E_ARCHITECTURE_REVIEW_MISSING" }); const entered = await scope.contractAuditor.enterAudit({ projectId, projectVersion, expectedRowVersion: (await new ProjectRepository(scope.database).getWithVersion(projectId))!.rowVersion, idempotencyKey: `real-e2e-contract-audit-enter-${options.input.smokeId}` }); const result = await scope.contractAuditor.auditAndRoute({ projectId, projectVersion, approvedBrief: approved.brief.requirements, briefChecksum: approved.brief.briefChecksum, acceptedPlanningPackage: accepted.package, planningChecksum: accepted.planningChecksum, approvedArchitectureReview: review, architectureReviewChecksum: checksumPersistedDocument(review), selectedDesign: selected.selectedDesign, designChecksum: checksumPersistedDocument(selected.selectedDesign), taskGraph: graph.taskGraph, taskGraphChecksum: graph.taskGraph.graphChecksum!, executorCatalog: [{ executorId: "factory-runtime", kind: "runtime" as const, current: true, capabilities: [...new Set(graph.taskGraph.tasks.map((task) => taskExecutionCapability(task.taskType)).filter(Boolean) as string[])] }], idempotencyKey: `real-e2e-contract-audit-${options.input.smokeId}`, expectedRowVersion: entered.rowVersion }); if (result.result.verdict !== "APPROVED") throw Object.assign(new Error("REAL_E2E_CONTRACT_AUDIT_REJECTED"), { code: "REAL_E2E_CONTRACT_AUDIT_REJECTED" }); return result; });
     const approvedAudit = await documents.get(projectId, projectVersion, "contract-audit"); if (!approvedAudit || approvedAudit.documentType !== "contract-audit") throw Object.assign(new Error("REAL_E2E_CONTRACT_AUDIT_MISSING"), { code: "REAL_E2E_CONTRACT_AUDIT_MISSING" });
     const started = await stage("START_IMPLEMENTATION", async () => scope.orchestrator.startImplementation({ ...orchestratorInput, approvedContractAuditChecksum: checksumPersistedDocument(approvedAudit), expectedRowVersion: (await new ProjectRepository(scope.database).getWithVersion(projectId))!.rowVersion }));
    const staging = await scope.workspace.createMutableExecutionStaging(started.project, projectVersion, `real-e2e-run-${options.input.smokeId}`); const context = { projectId, projectVersion, workspacePath: staging, generatedProjectsRoot: workspaceRoot, workspaceReservationId: `real-e2e-run-${options.input.smokeId}`, sourceDocumentChecksums: graph.taskGraph.sourceDocumentChecksums ?? {}, toolPolicyVersion: graph.taskGraph.toolPolicyVersion ?? "tools-v1", orchestrationPolicyVersion: graph.taskGraph.orchestrationPolicyVersion ?? DEFAULT_ORCHESTRATION_POLICY.version, approvedSkillSnapshotChecksum: graph.taskGraph.approvedSkillSnapshotChecksum, evidence: { implementationRequest: () => { evidence.implementationRequest = true; }, npmExecution: () => { evidence.npmExecution = true; }, browserExecution: () => { evidence.browserExecution = true; } } };
    const run = await stage("FULL_EXECUTION", async () => { const result = await scope.createFullExecutor({ ...context, policy: { ...(options.input.policy ?? DEFAULT_FULL_EXECUTION_POLICY), maxConcurrency: 1 } }).execute({ projectId, projectVersion, idempotencyKey: `real-e2e-execution-${options.input.smokeId}`, graph: started.taskGraph, expectedGraphChecksum: started.taskGraph.graphChecksum!, workflowState: "IMPLEMENTING", projectImmutable: false, workspaceValid: true, sourceDocumentChecksums: context.sourceDocumentChecksums, currentDocumentChecksums: context.sourceDocumentChecksums, toolPolicyVersion: context.toolPolicyVersion, activeRunIds: [], signal: options.input.signal }); if (result.status !== "completed") throw Object.assign(new Error(`Full execution ended with status ${result.status}; safeFailureCode=${result.safeFailureCode ?? "REAL_E2E_FULL_EXECUTION_INCOMPLETE"}.`), { code: result.safeFailureCode ?? "REAL_E2E_FULL_EXECUTION_INCOMPLETE" }); return result; });
    if (evidence.npmExecution) stages.push({ name: "RUNTIME", status: "passed", executionMode: "RESUMED", completedAt: now(), summary: "Real ProcessRunner evidence was recorded by the production adapter." }); else stages.push({ name: "RUNTIME", status: "failed", executionMode: "RESUMED", completedAt: now(), safeFailureCode: "REAL_E2E_RUNTIME_EVIDENCE_MISSING", summary: "Real ProcessRunner evidence is missing." }); if (evidence.browserExecution) stages.push({ name: "QA", status: "passed", executionMode: "RESUMED", completedAt: now(), summary: "Real Playwright evidence was recorded by the production adapter." }); else stages.push({ name: "QA", status: "failed", executionMode: "RESUMED", safeFailureCode: "REAL_E2E_BROWSER_EVIDENCE_MISSING", summary: "Real Playwright evidence is missing." });
    const summary = await stage("RELEASE_ELIGIBILITY", () => documents.get(projectId, projectVersion, "full-execution")); if (!summary || summary.documentType !== "full-execution" || run.status !== "completed" || !summary.releaseEligible || !Object.values(evidence).every(Boolean)) throw Object.assign(new Error("REAL_E2E_REAL_STAGE_EVIDENCE_INCOMPLETE"), { code: "REAL_E2E_REAL_STAGE_EVIDENCE_INCOMPLETE" }); const runtimeEvidence = options.input.runtime.evidence; return RealFactoryE2EReportSchema.parse({ ...options.base, smokeId: options.input.smokeId, projectId, projectVersion, projectPathReference: previous.projectPathReference, completedAt: now(), overallStatus: "passed", stages, realStageEvidence: evidence, provider: { status: "configured", modelLabel: options.input.runtime.ai.config.model, requestCount: runtimeEvidence.providerRequests, inputTokens: runtimeEvidence.inputTokens, outputTokens: runtimeEvidence.outputTokens }, npm: { ...(options.base.npm as object), status: "configured", passedCount: 4 }, playwright: { ...(options.base.playwright as object), status: "configured", scenarios: 1, passedCount: 1 }, taskGraph: { taskCount: summary.totalTasks, passedCount: summary.passed, failedCount: summary.failed, repairCount: summary.repairsAttempted }, generatedFiles: { ...(options.base.generatedFiles as object), checksumVerified: true }, releaseEligible: true });
  } catch (error) { const runtimeEvidence = options.input.runtime.evidence; return RealFactoryE2EReportSchema.parse({ ...options.base, smokeId: options.input.smokeId, projectId, projectVersion, projectPathReference: previous.projectPathReference, completedAt: now(), overallStatus: "failed", stages, realStageEvidence: evidence, provider: { status: "configured", modelLabel: options.input.runtime.ai.config.model, requestCount: runtimeEvidence.providerRequests, inputTokens: runtimeEvidence.inputTokens, outputTokens: runtimeEvidence.outputTokens }, blockers: [safeCode(error), message(error)] }); }
}

async function resumeProductionE2E(input: { input: { specification: ValidatedSmokeSpecification; runtime: ProductionFactoryRuntime; smokeId: string; signal?: AbortSignal; sink?: ProductionE2EStageSink; policy?: FullExecutionPolicy; resume?: RealFactoryE2EResumeInput }; base: Record<string, unknown> }): Promise<RealFactoryE2EReport> {
  const { input: options, base } = input; const previous = options.resume!.report; const currentState = previous.projectId ? (await new ProjectRepository(options.runtime.database).getWithVersion(previous.projectId))?.project.workflowState : undefined; if (currentState !== "IMPLEMENTING" && previous.stages.some((stage) => stage.name === "CLARIFICATION" && stage.status === "passed") && (!previous.stages.some((stage) => stage.name === "BRIEF_APPROVAL" && stage.status === "passed") || (currentState === "AWAITING_DESIGN_SELECTION" && previous.stages.some((stage) => stage.name === "PLANNING_ACCEPTANCE" && stage.status === "failed")))) return resumeFromClarification({ input: options, base }); const stages = currentState === "IMPLEMENTING" ? checkpointStages.map((name) => { const prior = previous.stages.find((stage) => stage.name === name); return prior ? { ...prior, executionMode: "REUSED_VALIDATED" as const, summary: `${name} reused from validated persisted checkpoint.` } : { name, status: "passed" as const, executionMode: "REUSED_VALIDATED" as const, completedAt: now(), summary: `${name} reconstructed from canonical persisted checkpoint.` }; }) : resumeStageNames(previous); let implementationRequest = false; let npmExecution = false; let browserExecution = false; let executionStarted = false;
  try {
    validateResumeIdentity(previous, options.resume!.smokeId); if (options.resume!.smokeId !== options.smokeId) throw Object.assign(new Error("REAL_E2E_RESUME_IDENTITY_MISMATCH"), { code: "REAL_E2E_RESUME_IDENTITY_MISMATCH" });
    const projectId = previous.projectId!; const projectVersion = previous.projectVersion!; const database = options.runtime.database; const projects = new ProjectRepository(database); const versions = new ProjectVersionRepository(database); const documents = new DocumentRepository(database); const current = await projects.getWithVersion(projectId); const version = await versions.get(projectId, projectVersion); if (!current || current.project.currentVersion !== projectVersion || current.project.workflowState !== "IMPLEMENTING" || !version || version.immutable) throw Object.assign(new Error("REAL_E2E_RESUME_CANONICAL_STATE_INVALID"), { code: "REAL_E2E_RESUME_CANONICAL_STATE_INVALID" });
    const requirements = await documents.get(projectId, projectVersion, "requirements"); const briefV3 = await documents.get(projectId, projectVersion, "brief-v3"); const approvedBriefV3 = briefV3?.documentType === "brief-v3" ? BriefV3DocumentSchema.parse(briefV3) : null; const planning = await documents.get(projectId, projectVersion, "planning-package"); const selected = await documents.get(projectId, projectVersion, "selected-design"); const graphDocument = await documents.get(projectId, projectVersion, "task-graph"); if (!requirements || requirements.documentType !== "requirements" || !approvedBriefV3?.approval?.approved || approvedBriefV3.approval.approvedCanonicalChecksum !== approvedBriefV3.briefChecksum || !planning || planning.documentType !== "planning-package" || !planning.accepted || !planning.architecture.acceptance.accepted || !evaluatePlanningAcceptanceReadiness({ planningPackage: planning }).readyForAcceptance || !selected || selected.documentType !== "selected-design" || !graphDocument || graphDocument.documentType !== "task-graph" || !graphDocument.readyForExecution) throw Object.assign(new Error("REAL_E2E_RESUME_CANONICAL_CHECKPOINT_INVALID"), { code: "REAL_E2E_RESUME_CANONICAL_CHECKPOINT_INVALID" });
    let graph = graphDocument; const withoutChecksum = { ...graph }; delete withoutChecksum.graphChecksum; if (graph.graphChecksum !== checksumPersistedDocument(withoutChecksum)) { const repairedGraph = TaskGraphSchema.parse({ ...withoutChecksum, graphChecksum: checksumPersistedDocument(withoutChecksum) }); await documents.save(repairedGraph); graph = repairedGraph; } if (graph.projectId !== projectId || graph.projectVersion !== projectVersion) throw Object.assign(new Error("REAL_E2E_RESUME_GRAPH_IDENTITY_MISMATCH"), { code: "REAL_E2E_RESUME_GRAPH_IDENTITY_MISMATCH" });
    for (const task of graph.tasks) { const ownership = ownershipForTask(task.taskType); if (ownership && task.taskType !== "implement-page" && task.taskType !== "write-unit-tests" && JSON.stringify(task.fileScopes) !== JSON.stringify(ownership.scopes)) throw Object.assign(new Error(`REAL_E2E_TASK_POLICY_STALE:${task.taskType}`), { code: "REAL_E2E_TASK_POLICY_STALE" }); }
    const projectPath = path.resolve(previous.projectPathReference!); const workspaceRoot = path.dirname(path.dirname(projectPath)); const slug = path.basename(path.dirname(projectPath)); const scope = options.runtime.createProjectScope({ workspaceRoot, slug }); await scope.workspace.verifyVersion(slug, projectVersion); const stagingOperation = `real-e2e-run-${options.smokeId}`; const staging = await scope.workspace.openMutableExecutionStaging(current.project, projectVersion, stagingOperation); await scope.orchestrator.reconcileStaleFoundationTask({ projectId, projectVersion, expectedGraphChecksum: graph.graphChecksum!, actor: "real-e2e-resume", configPresent: (await Promise.all(["eslint.config.mjs", "next.config.mjs"].map((name) => access(path.join(staging, name)).then(() => true).catch(() => false)))).every(Boolean) }); await scope.orchestrator.reconcileStaleTestArtifactTask({ projectId, projectVersion, expectedGraphChecksum: (await new DocumentRepository(scope.database).get(projectId, projectVersion, "task-graph") as typeof graph).graphChecksum!, actor: "real-e2e-resume", artifactCount: (await scope.runtimeValidator.inspectRuntimeReadiness({ projectId, projectVersion, workspacePath: staging, generatedProjectsRoot: workspaceRoot, mutable: true })).testFileCount }); await scope.orchestrator.reconcileRuntimeGatePolicy({ projectId, projectVersion, expectedGraphChecksum: (await new DocumentRepository(scope.database).get(projectId, projectVersion, "task-graph") as typeof graph).graphChecksum!, actor: "real-e2e-resume", policyVersion: RUNTIME_DIAGNOSTIC_POLICY_VERSION }); const reconciliation = await scope.orchestrator.reconcileTaskGraph(projectId, projectVersion); if (reconciliation.some((issue) => !issue.automaticRepairAllowed || issue.code !== "ORCHESTRATION_CHECKSUM_MISMATCH")) { const codes = reconciliation.map((issue) => issue.code).slice(0, 8).join(","); throw Object.assign(new Error(`REAL_E2E_RESUME_RECONCILIATION_REQUIRED:${codes}`), { code: "REAL_E2E_RESUME_RECONCILIATION_REQUIRED" }); }
    let resumableGraph = (await new DocumentRepository(scope.database).get(projectId, projectVersion, "task-graph")) as typeof graph; const failedFormTask = resumableGraph.tasks.find((candidate) => candidate.taskType === "implement-form" && candidate.status === "failed" && candidate.safeFailureCode === "FORM_FIELD_UNAPPROVED"); if (failedFormTask) { const retried = await scope.orchestrator.retryFailedTask({ projectId, projectVersion, taskId: failedFormTask.id, expectedGraphChecksum: resumableGraph.graphChecksum!, actor: "real-e2e-resume", reason: `FORM_FIELD_UNAPPROVED_RETRY:${failedFormTask.id}:attempt-${failedFormTask.attempt}:planning-${(requirements as { projectVersion: number }).projectVersion}` }); resumableGraph = retried.taskGraph as typeof graph; } const qaTask = resumableGraph.tasks.find((candidate) => candidate.taskType === "validate-functional-flow" && ["failed", "pending"].includes(candidate.status)); if (qaTask && !resumableGraph.tasks.some((candidate) => candidate.repairOfTaskId === qaTask.id && ["pending", "ready", "running"].includes(candidate.status))) { const persistedDiagnostic = qaTask.validationDiagnostics?.[0]; const failureCode = qaTask.safeFailureCode ?? "QA_ROUTE_MISSING"; let route = persistedDiagnostic?.route; if (!route && failureCode === "QA_ROUTE_MISSING") for (const scenario of planning.sitemap.routes) { const candidatePath = path.join(staging, `src/app${scenario.path === "/" ? "" : scenario.path}/page.tsx`); if (!(await access(candidatePath).then(() => true).catch(() => false))) { route = scenario.path; break; } } const relativePath = persistedDiagnostic?.relativePath ?? (route ? `src/app${route === "/" ? "" : route}/page.tsx` : undefined); if (route && relativePath) { await scope.orchestrator.createTargetedRepairTask({ projectId, projectVersion, failedTaskId: qaTask.id, failureCode, failureSummary: persistedDiagnostic?.safeMessage ?? `Functional QA identified a missing planned route at ${route}.`, expectedCorrection: `Restore the approved canonical route artifact ${relativePath} within the owning page implementation scope.`, revalidationTaskIds: [qaTask.id], expectedGraphChecksum: resumableGraph.graphChecksum!, actor: "real-e2e-resume", fileScopes: [relativePath], lateValidationEvidence: qaTask.status === "pending", repairIdentity: `${qaTask.id}:${failureCode}:${relativePath}:functional-qa-diagnostics-v13` }); resumableGraph = (await new DocumentRepository(scope.database).get(projectId, projectVersion, "task-graph")) as typeof graph; } }
    const readiness = await scope.runtimeValidator.inspectRuntimeReadiness({ projectId, projectVersion, workspacePath: staging, generatedProjectsRoot: workspaceRoot, mutable: true }); const replayCandidate = resumableGraph.tasks.find((candidate) => candidate.status === "failed" && ["validate-lint", "validate-typecheck", "validate-unit-tests", "validate-build"].includes(candidate.taskType) && (candidate.validationDiagnosticCount === undefined || candidate.validationDiagnosticCount === 0) && ((candidate.validationReplayCount ?? 0) < 1 || candidate.validationDiagnosticPolicyVersion !== RUNTIME_DIAGNOSTIC_POLICY_VERSION)); if (replayCandidate) { const replayed = await scope.orchestrator.reconcileValidationReplay({ projectId, projectVersion, taskId: replayCandidate.id, expectedGraphChecksum: resumableGraph.graphChecksum!, actor: "real-e2e-resume", reason: "VALIDATION_EVIDENCE_REFRESH", sourceChecksum: readiness.sourceChecksum, diagnosticPolicyVersion: RUNTIME_DIAGNOSTIC_POLICY_VERSION }); resumableGraph = replayed.taskGraph; }
    const downstreamRequirements = approvedLegacyBriefFromV3(requirements, approvedBriefV3); const qaIdentity = deriveQaPolicyRefreshIdentity({ projectId, projectVersion, brief: downstreamRequirements, planning, selectedDesign: selected, sourceDocumentChecksums: resumableGraph.sourceDocumentChecksums }); resumableGraph = (await scope.orchestrator.reconcileQaPolicyRefresh({ projectId, projectVersion, expectedGraphChecksum: resumableGraph.graphChecksum!, actor: "real-e2e-resume", sourceChecksum: qaIdentity.sourceChecksum, policyVersion: qaIdentity.policyVersion, scenarioChecksum: qaIdentity.scenarioChecksum })).taskGraph; const context = { projectId, projectVersion, workspacePath: staging, generatedProjectsRoot: workspaceRoot, workspaceReservationId: stagingOperation, sourceDocumentChecksums: resumableGraph.sourceDocumentChecksums ?? {}, toolPolicyVersion: resumableGraph.toolPolicyVersion ?? "tools-v1", orchestrationPolicyVersion: resumableGraph.orchestrationPolicyVersion ?? DEFAULT_ORCHESTRATION_POLICY.version, approvedSkillSnapshotChecksum: resumableGraph.approvedSkillSnapshotChecksum, evidence: { implementationRequest: () => { implementationRequest = true; }, npmExecution: () => { npmExecution = true; }, browserExecution: () => { browserExecution = true; } } };
    executionStarted = true; const run = await scope.createFullExecutor({ ...context, policy: { ...(options.policy ?? DEFAULT_FULL_EXECUTION_POLICY), maxConcurrency: 1 } }).execute({ projectId, projectVersion, idempotencyKey: `real-e2e-resume-execution-${options.smokeId}`, graph: resumableGraph, expectedGraphChecksum: resumableGraph.graphChecksum!, workflowState: "IMPLEMENTING", projectImmutable: false, workspaceValid: true, sourceDocumentChecksums: context.sourceDocumentChecksums, currentDocumentChecksums: context.sourceDocumentChecksums, toolPolicyVersion: context.toolPolicyVersion, activeRunIds: [], signal: options.signal });
    const finalGraph = await documents.get(projectId, projectVersion, "task-graph"); const summary = await documents.get(projectId, projectVersion, "full-execution"); const finalQaTask = finalGraph?.documentType === "task-graph" ? finalGraph.tasks.find((task) => task.taskType === "validate-functional-flow") : undefined; const qaPassed = finalQaTask?.status === "passed"; const executionStage = { name: "FULL_EXECUTION", status: run.status === "completed" ? "passed" as const : "failed" as const, executionMode: "RESUMED" as const, completedAt: now(), safeFailureCode: run.safeFailureCode, summary: run.safeFailureSummary ?? `Full execution resumed from the persisted TaskGraph.` }; const report = RealFactoryE2EReportSchema.parse({ ...base, smokeId: options.smokeId, projectId, projectVersion, projectPathReference: previous.projectPathReference, completedAt: now(), overallStatus: run.status === "completed" && summary?.documentType === "full-execution" && summary.releaseEligible ? "passed" : "failed", stages: [...stages, executionStage], realStageEvidence: { leadRequest: false, plannerRequest: false, designRequest: false, implementationRequest, npmExecution, browserExecution }, provider: { status: "configured", modelLabel: options.runtime.ai.config.model, requestCount: options.runtime.evidence.providerRequests, inputTokens: options.runtime.evidence.inputTokens, outputTokens: options.runtime.evidence.outputTokens }, npm: { status: npmExecution ? "configured" : "not-configured", commands: ["npm ci", "npm run lint", "npm run typecheck", "npm test", "npm run build"], passedCount: npmExecution ? 5 : 0, failedCount: 0 }, playwright: { status: browserExecution ? "configured" : "not-configured", scenarios: browserExecution ? 1 : 0, passedCount: qaPassed ? 1 : 0, failedCount: browserExecution && !qaPassed ? 1 : 0, unexpectedExternalRequests: 0 }, taskGraph: { taskCount: finalGraph?.documentType === "task-graph" ? finalGraph.tasks.length : 0, passedCount: finalGraph?.documentType === "task-graph" ? finalGraph.tasks.filter((task) => task.status === "passed").length : 0, failedCount: finalGraph?.documentType === "task-graph" ? finalGraph.tasks.filter((task) => task.status === "failed").length : 0, repairCount: summary?.documentType === "full-execution" ? summary.repairsAttempted : 0 }, generatedFiles: { createdCount: 0, changedCount: 0, checksumVerified: run.status === "completed" }, releaseEligible: run.status === "completed" && summary?.documentType === "full-execution" ? summary.releaseEligible : false, blockers: run.status === "completed" ? [] : [run.safeFailureCode ?? "REAL_FACTORY_E2E_FULL_EXECUTION_INCOMPLETE", ...(run.safeFailureSummary ? [run.safeFailureSummary] : [])] }); return report;
  } catch (error) { const failureStages = executionStarted && !stages.some((stage) => stage.name === "FULL_EXECUTION") ? [...stages, { name: "FULL_EXECUTION", status: "failed" as const, executionMode: "RESUMED" as const, completedAt: now(), safeFailureCode: safeCode(error), summary: message(error) }] : stages; return RealFactoryE2EReportSchema.parse({ ...base, smokeId: options.smokeId, ...(previous.projectId ? { projectId: previous.projectId } : {}), ...(previous.projectVersion ? { projectVersion: previous.projectVersion } : {}), ...(previous.projectPathReference ? { projectPathReference: previous.projectPathReference } : {}), completedAt: now(), overallStatus: "failed", stages: failureStages, realStageEvidence: { leadRequest: false, plannerRequest: false, designRequest: false, implementationRequest, npmExecution, browserExecution }, blockers: [safeCode(error), message(error)] }); }
}
