import { z } from "zod";
import { AssetManifestSchema } from "@/domain/assets/schema";
import { TechnicalArchitectureSchema } from "@/domain/architecture/schema";
import { ContentPlanSchema } from "@/domain/content/schema";
import { RequirementSpecificationSchema } from "@/domain/requirements/schema";
import { CanonicalBriefV3Schema, type CanonicalBriefV3 } from "@/domain/requirements/v3/schema";
import { WorkflowStateSchema } from "@/domain/project/schema";
import { DocumentBaseSchema, IsoDateTimeSchema, NonEmptyStringSchema } from "@/domain/shared/schemas";
import { checksumPersistedDocument } from "@/persistence/database/serialization";
import { PlanningSemanticChecksumPolicyVersionSchema } from "./checksum-policy";

export const TraceabilitySchema = z.object({ decisionId: z.string().uuid(), category: NonEmptyStringSchema, requirementReferences: z.array(NonEmptyStringSchema).min(1), systemConstraintReferences: z.array(NonEmptyStringSchema), rationale: NonEmptyStringSchema, confidence: z.enum(["high", "medium", "low"]), unresolvedDependency: NonEmptyStringSchema.optional(), userConfirmationRequired: z.boolean() }).strict();
export type Traceability = z.infer<typeof TraceabilitySchema>;

const RefSchema = z.object({ id: NonEmptyStringSchema, requirementReferences: z.array(NonEmptyStringSchema).min(1) }).strict();
const RouteSchema = RefSchema.extend({ path: z.string().regex(/^\/(?:[a-z0-9-]+(?:\/[a-z0-9-]+)*)?$/), titlePurpose: NonEmptyStringSchema, pageType: z.enum(["landing", "content", "form", "dashboard", "auth", "legal", "application"]), visibility: z.enum(["public", "protected"]), intendedUser: NonEmptyStringSchema, primaryGoal: NonEmptyStringSchema, primaryCta: NonEmptyStringSchema.optional(), contentResponsibilities: z.array(NonEmptyStringSchema), dataDependencies: z.array(NonEmptyStringSchema), formDependencies: z.array(NonEmptyStringSchema), authRequired: z.boolean(), seoRelevant: z.boolean(), parentId: NonEmptyStringSchema.optional(), navigationVisible: z.boolean() }).strict();
export const SitemapPlanSchema = DocumentBaseSchema.extend({ documentType: z.literal("sitemap"), routes: z.array(RouteSchema), traceability: z.array(TraceabilitySchema) }).strict();
export type SitemapPlan = z.infer<typeof SitemapPlanSchema>;

const PageSchema = RefSchema.extend({ routeId: NonEmptyStringSchema, purpose: NonEmptyStringSchema, targetAudience: NonEmptyStringSchema, userIntent: NonEmptyStringSchema, contentBlocks: z.array(NonEmptyStringSchema), functionalComponents: z.array(NonEmptyStringSchema), forms: z.array(NonEmptyStringSchema), dataReads: z.array(NonEmptyStringSchema), dataWrites: z.array(NonEmptyStringSchema), loadingStates: z.array(NonEmptyStringSchema), emptyStates: z.array(NonEmptyStringSchema), errorStates: z.array(NonEmptyStringSchema), successStates: z.array(NonEmptyStringSchema), seoMetadata: z.array(NonEmptyStringSchema), assetRequirements: z.array(NonEmptyStringSchema), acceptanceCriteria: z.array(NonEmptyStringSchema) }).strict();
export const PageResponsibilityPlanSchema = DocumentBaseSchema.extend({ documentType: z.literal("page-responsibilities"), pages: z.array(PageSchema), traceability: z.array(TraceabilitySchema) }).strict();
export type PageResponsibilityPlan = z.infer<typeof PageResponsibilityPlanSchema>;

export const NavigationPlanSchema = DocumentBaseSchema.extend({ documentType: z.literal("navigation"), primary: z.array(NonEmptyStringSchema), secondary: z.array(NonEmptyStringSchema), footer: z.array(NonEmptyStringSchema), contextual: z.array(NonEmptyStringSchema), protected: z.array(NonEmptyStringSchema), mobileBehavior: NonEmptyStringSchema, ctaPlacementIntent: z.array(NonEmptyStringSchema), routeReferences: z.array(NonEmptyStringSchema), traceability: z.array(TraceabilitySchema) }).strict();
export type NavigationPlan = z.infer<typeof NavigationPlanSchema>;

const StepSchema = z.object({ order: z.number().int().positive(), description: NonEmptyStringSchema, routeId: NonEmptyStringSchema.optional(), decision: NonEmptyStringSchema.optional() }).strict();
export const UserFlowPlanSchema = DocumentBaseSchema.extend({ documentType: z.literal("user-flows"), flows: z.array(RefSchema.extend({ actor: NonEmptyStringSchema, trigger: NonEmptyStringSchema, startRoute: NonEmptyStringSchema, steps: z.array(StepSchema), dataCreated: z.array(NonEmptyStringSchema), dataRead: z.array(NonEmptyStringSchema), dataUpdated: z.array(NonEmptyStringSchema), successOutcome: NonEmptyStringSchema, failureOutcomes: z.array(NonEmptyStringSchema), authorizationRequirements: z.array(NonEmptyStringSchema), formRequirements: z.array(NonEmptyStringSchema), emailRequirements: z.array(NonEmptyStringSchema), storageRequirements: z.array(NonEmptyStringSchema), acceptanceCriteria: z.array(NonEmptyStringSchema) }).strict()), traceability: z.array(TraceabilitySchema) }).strict();
export type UserFlowPlan = z.infer<typeof UserFlowPlanSchema>;

export const FormFieldIdSchema = z.string().regex(/^[a-z][A-Za-z0-9]*$/, "Form field IDs must be stable English machine identifiers.");
export const FormFieldSchema = z.object({ fieldId: FormFieldIdSchema, label: NonEmptyStringSchema, type: NonEmptyStringSchema, required: z.boolean(), validation: z.array(NonEmptyStringSchema) }).strict();
export const LegacyFormFieldSchema = z.object({ name: NonEmptyStringSchema, type: NonEmptyStringSchema, required: z.boolean(), validation: z.array(NonEmptyStringSchema) }).strict();
export const FormFieldContractSchema = z.union([FormFieldSchema, LegacyFormFieldSchema]);
export const FormSubmissionMechanismSchema = z.enum(["client-only", "server-action", "route-handler", "pending-decision"]);
export type FormSubmissionMechanism = z.infer<typeof FormSubmissionMechanismSchema>;
const noDatabaseWrite = /(?:no\s+(?:database|persistent|storage)\s+write|no\s+persistent\s+(?:write|storage)|keine[nr]?\s+(?:datenbank|persistenz|speicherung)|local(?:\s+(?:client|frontend))?\s+state|lokal(?:er|e)?\s+(?:frontend|client))/i;
const noExternalSubmission = /(?:no\s+(?:email|e-?mail|api|external|provider|transmission)|keine[nr]?\s+(?:e-?mail|api|extern|übertragung)|ohne\s+(?:e-?mail|api|extern|übertragung))/i;
export const clientOnlyFormContractIssues = (value: { submissionMechanism: FormSubmissionMechanism; databaseWrite: string; emailBehavior: string }) => value.submissionMechanism !== "client-only" ? [] : [
  ...(!noDatabaseWrite.test(value.databaseWrite) ? ["CLIENT_ONLY_PERSISTENCE_FORBIDDEN"] : []),
  ...(!noExternalSubmission.test(value.emailBehavior) ? ["CLIENT_ONLY_TRANSMISSION_FORBIDDEN"] : []),
];
export const FormSchema = RefSchema.extend({ route: NonEmptyStringSchema, purpose: NonEmptyStringSchema, fields: z.array(FormFieldContractSchema), businessValidation: z.array(NonEmptyStringSchema), consentRequirements: z.array(NonEmptyStringSchema), submissionMechanism: FormSubmissionMechanismSchema, databaseWrite: NonEmptyStringSchema, emailBehavior: NonEmptyStringSchema, successState: NonEmptyStringSchema, errorState: NonEmptyStringSchema, rateLimitRequired: z.boolean(), spamProtectionRequired: z.boolean() }).strict().superRefine((value, context) => { for (const issue of clientOnlyFormContractIssues(value)) context.addIssue({ code: z.ZodIssueCode.custom, path: ["submissionMechanism"], message: issue }); });
export const FormPlanSchema = DocumentBaseSchema.extend({ documentType: z.literal("forms-plan"), forms: z.array(FormSchema), traceability: z.array(TraceabilitySchema) }).strict().superRefine((value, context) => { for (const [index, form] of value.forms.entries()) { const ids = form.fields.flatMap((field) => "fieldId" in field ? [field.fieldId] : []); if (new Set(ids).size !== ids.length) context.addIssue({ code: z.ZodIssueCode.custom, path: ["forms", index, "fields"], message: "Form fieldIds must be unique within a form." }); } });
export type FormPlan = z.infer<typeof FormPlanSchema>;
export type FormField = z.infer<typeof FormFieldSchema>;
export type LegacyFormField = z.infer<typeof LegacyFormFieldSchema>;
export const isLegacyFormField = (field: FormField | LegacyFormField): field is LegacyFormField => "name" in field;
export const formFieldId = (field: FormField | LegacyFormField) => isLegacyFormField(field) ? undefined : field.fieldId;

const EntitySchema = RefSchema.extend({ name: NonEmptyStringSchema, fields: z.array(z.object({ name: NonEmptyStringSchema, type: NonEmptyStringSchema, required: z.boolean(), public: z.boolean() }).strict()), relationships: z.array(NonEmptyStringSchema), ownership: NonEmptyStringSchema, lifecycle: NonEmptyStringSchema, retention: NonEmptyStringSchema, indexingRationale: z.array(NonEmptyStringSchema), uniquenessConstraints: z.array(NonEmptyStringSchema), rlsRequired: z.boolean(), auditFields: z.array(NonEmptyStringSchema) }).strict();
export const DataModelPlanSchema = DocumentBaseSchema.extend({ documentType: z.literal("data-model-plan"), entities: z.array(EntitySchema), traceability: z.array(TraceabilitySchema) }).strict();
export type DataModelPlan = z.infer<typeof DataModelPlanSchema>;

export const AuthenticationPlanSchema = DocumentBaseSchema.extend({ documentType: z.literal("authentication-plan"), decision: z.enum(["none", "supabase-auth", "pending-blocker"]), required: z.boolean(), userRoles: z.array(NonEmptyStringSchema), signInMethods: z.array(NonEmptyStringSchema), registrationBehavior: NonEmptyStringSchema, protectedRoutes: z.array(NonEmptyStringSchema), sessionNeeds: z.array(NonEmptyStringSchema), authorizationRules: z.array(NonEmptyStringSchema), rlsRelationship: NonEmptyStringSchema, accountLifecycle: NonEmptyStringSchema, passwordReset: NonEmptyStringSchema, emailVerification: NonEmptyStringSchema, traceability: z.array(TraceabilitySchema) }).strict();
export type AuthenticationPlan = z.infer<typeof AuthenticationPlanSchema>;

export const SupabasePlanSchema = DocumentBaseSchema.extend({ documentType: z.literal("supabase-plan"), postgres: z.boolean(), auth: z.boolean(), storage: z.boolean(), realtime: z.boolean(), edgeFunctions: z.boolean(), clientBoundaries: z.array(NonEmptyStringSchema), rlsExpectations: z.array(NonEmptyStringSchema), migrationNeeds: z.array(NonEmptyStringSchema), environmentVariables: z.array(NonEmptyStringSchema), storageBuckets: z.array(NonEmptyStringSchema), policies: z.array(NonEmptyStringSchema), serviceRoleUse: NonEmptyStringSchema, anonKeyUse: NonEmptyStringSchema, traceability: z.array(TraceabilitySchema) }).strict();
export type SupabasePlan = z.infer<typeof SupabasePlanSchema>;

export const EmailPlanSchema = DocumentBaseSchema.extend({ documentType: z.literal("email-plan"), decision: z.enum(["not-required", "required-provider-pending", "required-configured-provider", "pending-blocker"]), emailTypes: z.array(NonEmptyStringSchema), triggers: z.array(NonEmptyStringSchema), recipients: z.array(NonEmptyStringSchema), senderIdentityNeeds: z.array(NonEmptyStringSchema), templatesRequired: z.array(NonEmptyStringSchema), retryExpectations: NonEmptyStringSchema, failureBehavior: NonEmptyStringSchema, privacy: z.array(NonEmptyStringSchema), environmentVariables: z.array(NonEmptyStringSchema), testingStrategy: z.array(NonEmptyStringSchema), traceability: z.array(TraceabilitySchema) }).strict();
export type EmailPlan = z.infer<typeof EmailPlanSchema>;

export const StorageOperationSchema = z.enum(["SELECT", "INSERT", "UPDATE", "DELETE"]);
export type StorageOperation = z.infer<typeof StorageOperationSchema>;
const StorageIdentifierSchema = z.string().regex(/^[a-z][a-z0-9_-]{0,62}$/, "Storage identifiers must be stable English machine identifiers.");
const StorageSignedUrlSchema = z.object({ enabled: z.boolean(), operations: z.array(StorageOperationSchema), expirySeconds: z.number().int().positive().max(3600) }).strict();
export const StoragePlanSchema = DocumentBaseSchema.extend({ documentType: z.literal("storage-plan"), decision: z.enum(["not-required", "supabase-storage", "pending-blocker"]), assetCategories: z.array(NonEmptyStringSchema), uploadActors: z.array(NonEmptyStringSchema), acceptedFormats: z.array(NonEmptyStringSchema), sizeLimits: z.array(NonEmptyStringSchema), validation: z.array(NonEmptyStringSchema), access: z.enum(["public", "private", "mixed", "not-applicable"]), buckets: z.array(NonEmptyStringSchema), bucketId: StorageIdentifierSchema, policyIdentity: StorageIdentifierSchema, ownerSource: z.literal("authenticated-user-id"), objectPathStrategy: z.enum(["user-id-prefix", "not-applicable"]), objectPathTemplate: z.string().regex(/^\{userId\}\/\{objectName\}$|^not-applicable$/, "Storage paths must use the canonical owner-prefixed template."), allowedOperations: z.array(StorageOperationSchema), directClientAccess: z.boolean(), signedUrl: StorageSignedUrlSchema, ownershipTransfer: z.literal("forbidden"), serverPrivilegedAccess: z.literal(false), retention: NonEmptyStringSchema, deletionBehavior: NonEmptyStringSchema, policies: z.array(NonEmptyStringSchema), traceability: z.array(TraceabilitySchema) }).strict().superRefine((value, context) => {
  if (value.decision === "supabase-storage") {
    if (value.access !== "private") context.addIssue({ code: z.ZodIssueCode.custom, path: ["access"], message: "Runtime Storage must be private and owner scoped." });
    if (value.buckets.length !== 1 || value.buckets[0] !== value.bucketId) context.addIssue({ code: z.ZodIssueCode.custom, path: ["buckets"], message: "StoragePlan must contain exactly its canonical bucket ID." });
    if (value.objectPathStrategy !== "user-id-prefix" || value.objectPathTemplate !== "{userId}/{objectName}") context.addIssue({ code: z.ZodIssueCode.custom, path: ["objectPathTemplate"], message: "StoragePlan must use the canonical authenticated-user path template." });
    if (new Set(value.allowedOperations).size !== 4 || !(["SELECT", "INSERT", "UPDATE", "DELETE"] as const).every((operation) => value.allowedOperations.includes(operation))) context.addIssue({ code: z.ZodIssueCode.custom, path: ["allowedOperations"], message: "Owner-scoped StoragePlan must explicitly allow all four Storage operations." });
    if (!value.signedUrl.enabled || !value.signedUrl.operations.includes("SELECT") || !value.signedUrl.operations.includes("INSERT")) context.addIssue({ code: z.ZodIssueCode.custom, path: ["signedUrl"], message: "Private runtime Storage requires signed read and upload URL semantics." });
    if (value.directClientAccess || value.serverPrivilegedAccess) context.addIssue({ code: z.ZodIssueCode.custom, path: ["directClientAccess"], message: "Direct client and privileged service-role Storage access are disabled." });
  }
});
export type StoragePlan = z.infer<typeof StoragePlanSchema>;
export const storagePlanSecurityContract = (plan: StoragePlan) => ({ bucketId: plan.bucketId, policyIdentity: plan.policyIdentity, ownerSource: plan.ownerSource, objectPathStrategy: plan.objectPathStrategy, objectPathTemplate: plan.objectPathTemplate, allowedOperations: plan.allowedOperations, directClientAccess: plan.directClientAccess, signedUrl: plan.signedUrl, ownershipTransfer: plan.ownershipTransfer, serverPrivilegedAccess: plan.serverPrivilegedAccess });
export const storagePlanContractChecksum = (plan: StoragePlan) => checksumPersistedDocument(storagePlanSecurityContract(plan));

export const AdministrationPlanSchema = DocumentBaseSchema.extend({ documentType: z.literal("administration-plan"), decision: z.enum(["no-admin", "limited-management", "full-administration", "pending-blocker"]), actors: z.array(NonEmptyStringSchema), managedEntities: z.array(NonEmptyStringSchema), permittedActions: z.array(NonEmptyStringSchema), protectedRoutes: z.array(NonEmptyStringSchema), auditNeeds: z.array(NonEmptyStringSchema), authorizationRules: z.array(NonEmptyStringSchema), traceability: z.array(TraceabilitySchema) }).strict();
export type AdministrationPlan = z.infer<typeof AdministrationPlanSchema>;

export const EnvironmentVariablePlanSchema = DocumentBaseSchema.extend({ documentType: z.literal("environment-variable-plan"), variables: z.array(z.object({ name: z.string().regex(/^[A-Z][A-Z0-9_]*$/), purpose: NonEmptyStringSchema, required: z.boolean(), serverOnly: z.boolean(), secret: z.boolean(), source: NonEmptyStringSchema, environments: z.array(NonEmptyStringSchema), validationRule: NonEmptyStringSchema, requirementReferences: z.array(NonEmptyStringSchema).min(1) }).strict()) }).strict();
export const DependencyPlanSchema = DocumentBaseSchema.extend({ documentType: z.literal("dependency-plan"), dependencies: z.array(z.object({ name: NonEmptyStringSchema, purpose: NonEmptyStringSchema, runtime: z.enum(["runtime", "dev"]), required: z.boolean(), requirementReferences: z.array(NonEmptyStringSchema).min(1), builtInInsufficientReason: NonEmptyStringSchema, securityConsiderations: z.array(NonEmptyStringSchema) }).strict()) }).strict();
export const TestStrategyPlanSchema = DocumentBaseSchema.extend({ documentType: z.literal("test-strategy"), categories: z.array(NonEmptyStringSchema), acceptanceMapping: z.array(z.object({ acceptanceCriterion: NonEmptyStringSchema, testCategories: z.array(NonEmptyStringSchema).min(1) }).strict()), excludedGates: z.array(NonEmptyStringSchema) }).strict();
export const SecurityPlanSchema = DocumentBaseSchema.extend({ documentType: z.literal("security-plan"), controls: z.array(z.object({ control: NonEmptyStringSchema, scope: NonEmptyStringSchema, requirementReferences: z.array(NonEmptyStringSchema).min(1) }).strict()), dataRetention: z.array(NonEmptyStringSchema), loggingRedaction: z.array(NonEmptyStringSchema), errorHandling: z.array(NonEmptyStringSchema) }).strict();

export const ProductScopePlanSchema = DocumentBaseSchema.extend({ documentType: z.literal("product-scope"), purpose: NonEmptyStringSchema, primaryOutcomes: z.array(NonEmptyStringSchema), secondaryOutcomes: z.array(NonEmptyStringSchema), inScopeCapabilities: z.array(NonEmptyStringSchema), outOfScopeCapabilities: z.array(NonEmptyStringSchema), userRoles: z.array(NonEmptyStringSchema), majorEntities: z.array(NonEmptyStringSchema), majorWorkflows: z.array(NonEmptyStringSchema), externalIntegrations: z.array(NonEmptyStringSchema), assumptions: z.array(NonEmptyStringSchema), constraints: z.array(NonEmptyStringSchema), acceptanceMapping: z.array(z.object({ criterion: NonEmptyStringSchema, requirementReferences: z.array(NonEmptyStringSchema).min(1) }).strict()), traceability: z.array(TraceabilitySchema) }).strict();
export type ProductScopePlan = z.infer<typeof ProductScopePlanSchema>;

export const ProfileSelectionSchema = z.object({ selectedProfile: z.enum(["marketing-site", "business-site", "web-application"]), rationale: NonEmptyStringSchema, requirementReferences: z.array(NonEmptyStringSchema).min(1), rejectedProfiles: z.array(z.object({ profile: z.enum(["marketing-site", "business-site", "web-application"]), rationale: NonEmptyStringSchema }).strict()) }).strict();
export type ProfileSelection = z.infer<typeof ProfileSelectionSchema>;

export const PlannerAgentInputSchema = z.object({ projectId: z.string().uuid(), projectVersion: z.number().int().positive(), approvedBrief: RequirementSpecificationSchema, canonicalBrief: CanonicalBriefV3Schema.optional(), approvedBriefChecksum: z.string().regex(/^[a-f0-9]{64}$/), originalPromptReference: NonEmptyStringSchema, clarificationEvidenceReferences: z.array(NonEmptyStringSchema), currentWorkflowState: WorkflowStateSchema, existingDecisions: z.array(z.unknown()), suppliedFiles: z.array(z.object({ path: NonEmptyStringSchema, kind: NonEmptyStringSchema, sha256: z.string().regex(/^[a-f0-9]{64}$/).optional() }).strict()), allowedSkills: z.array(NonEmptyStringSchema), allowedTools: z.array(NonEmptyStringSchema).optional(), idempotencyKey: NonEmptyStringSchema, expectedRowVersion: z.number().int().positive() }).strict();
export type PlannerAgentInput = z.input<typeof PlannerAgentInputSchema>;
export type { CanonicalBriefV3 };

export const DatabaseRecommendationSchema = z.object({ recommendation: z.enum(["REQUIRED", "NOT_REQUIRED", "UNCERTAIN"]), rationale: NonEmptyStringSchema, requirementReferences: z.array(NonEmptyStringSchema).min(1), userDecisionRequired: z.literal(true), selectedMode: z.enum(["NONE", "SUPABASE_NEW", "SUPABASE_EXISTING"]).optional() }).strict();
export const PlanningPackageSchema = DocumentBaseSchema.extend({ documentType: z.literal("planning-package"), semanticChecksumPolicyVersion: PlanningSemanticChecksumPolicyVersionSchema.optional(), approvedBriefChecksum: z.string().regex(/^[a-f0-9]{64}$/), profile: ProfileSelectionSchema, productScope: ProductScopePlanSchema, sitemap: SitemapPlanSchema, navigation: NavigationPlanSchema, pages: PageResponsibilityPlanSchema, userFlows: UserFlowPlanSchema, forms: FormPlanSchema, dataModel: DataModelPlanSchema, authentication: AuthenticationPlanSchema, supabase: SupabasePlanSchema, email: EmailPlanSchema, storage: StoragePlanSchema, administration: AdministrationPlanSchema, content: ContentPlanSchema, assets: AssetManifestSchema, architecture: TechnicalArchitectureSchema, environment: EnvironmentVariablePlanSchema, dependencies: DependencyPlanSchema, testStrategy: TestStrategyPlanSchema, security: SecurityPlanSchema, traceability: z.array(TraceabilitySchema), blockers: z.array(NonEmptyStringSchema), accepted: z.boolean(), acceptance: z.object({ acceptedAt: IsoDateTimeSchema.optional(), acceptedBy: NonEmptyStringSchema.optional(), checksum: z.string().regex(/^[a-f0-9]{64}$/).optional() }).strict(), databaseRecommendation: DatabaseRecommendationSchema.optional() }).strict();
export type PlanningPackage = z.infer<typeof PlanningPackageSchema>;
export const PlannerAnalysisResultSchema = z.object({ profile: ProfileSelectionSchema, planningPackage: PlanningPackageSchema }).strict();
