import { z } from "zod";
import { QualityCheckSchema } from "../domain/quality/schema";
export const RuntimeCommandTypeSchema = z.enum(["npm-lockfile", "npm-ci", "lint", "typecheck", "tests", "build"]);
export type RuntimeCommandType = z.infer<typeof RuntimeCommandTypeSchema>;
export const RuntimeCommandSpecSchema = z.object({ commandType: RuntimeCommandTypeSchema, executable: z.literal("npm"), args: z.array(z.string()), timeoutMs: z.number().int().positive(), exclusive: z.boolean() }).strict();
export type RuntimeCommandSpec = z.infer<typeof RuntimeCommandSpecSchema>;
export const RuntimeDiagnosticReferenceSchema = z.object({ relativePath: z.string().min(1).max(300), line: z.number().int().positive().optional(), column: z.number().int().positive().optional(), code: z.string().regex(/^[A-Z0-9_-]+$/).max(80).optional(), relatedFiles: z.array(z.string().min(1).max(300)).max(8).optional(), route: z.string().regex(/^\/(?:[a-z0-9-]+(?:\/[a-z0-9-]+)*)?$/).optional() }).strict();
export type RuntimeDiagnosticReference = z.infer<typeof RuntimeDiagnosticReferenceSchema>;
export const RUNTIME_COMMAND_SPECS: Readonly<Record<RuntimeCommandType, RuntimeCommandSpec>> = Object.freeze({ "npm-lockfile": Object.freeze({ commandType: "npm-lockfile", executable: "npm", args: ["install", "--package-lock-only", "--ignore-scripts", "--no-audit", "--no-fund"], timeoutMs: 300000, exclusive: true }), "npm-ci": Object.freeze({ commandType: "npm-ci", executable: "npm", args: ["ci"], timeoutMs: 300000, exclusive: true }), lint: Object.freeze({ commandType: "lint", executable: "npm", args: ["run", "lint"], timeoutMs: 120000, exclusive: false }), typecheck: Object.freeze({ commandType: "typecheck", executable: "npm", args: ["run", "typecheck"], timeoutMs: 120000, exclusive: false }), tests: Object.freeze({ commandType: "tests", executable: "npm", args: ["test", "--", "--run"], timeoutMs: 180000, exclusive: false }), build: Object.freeze({ commandType: "build", executable: "npm", args: ["run", "build"], timeoutMs: 300000, exclusive: true }) });
export const RuntimeCommandResultSchema = z.object({ commandId: z.string().uuid(), validationRunId: z.string().uuid(), projectId: z.string().uuid(), projectVersion: z.number().int().positive(), commandType: RuntimeCommandTypeSchema, executableIdentity: z.string().min(1), safeArgsSummary: z.string().min(1), cwdReference: z.string().min(1), startedAt: z.string().datetime(), completedAt: z.string().datetime(), durationMs: z.number().int().nonnegative(), exitCode: z.number().int().nullable(), terminationReason: z.enum(["completed", "timeout", "cancelled", "spawn-failed"]), stdoutSummary: z.string(), stderrSummary: z.string(), stdoutBytes: z.number().int().nonnegative(), stderrBytes: z.number().int().nonnegative(), outputTruncated: z.boolean(), timeout: z.boolean(), cancelled: z.boolean(), passed: z.boolean(), diagnostics: z.array(RuntimeDiagnosticReferenceSchema).max(50).default([]), safeFailureCode: z.string().regex(/^[A-Z0-9_]+$/).optional() }).strict();
export type RuntimeCommandResult = z.infer<typeof RuntimeCommandResultSchema>;
export const RuntimeValidationReportSchema = z.object({ validationRunId: z.string().uuid(), projectId: z.string().uuid(), projectVersion: z.number().int().positive(), workspaceReference: z.string().min(1), packageChecksum: z.string().regex(/^[a-f0-9]{64}$/), lockfileChecksum: z.string().regex(/^[a-f0-9]{64}$/), startedAt: z.string().datetime(), completedAt: z.string().datetime(), overallStatus: z.enum(["pending", "running", "passed", "failed", "skipped", "cancelled"]), commandResults: z.array(RuntimeCommandResultSchema), qualityChecks: z.array(QualityCheckSchema), failureCategory: z.string().regex(/^[A-Z0-9_]+$/).optional(), repairEligible: z.boolean(), failedTaskReference: z.string().optional(), warnings: z.array(z.string()), policyVersion: z.string().min(1) }).strict();
export type RuntimeValidationReport = z.infer<typeof RuntimeValidationReportSchema>;
export type RuntimeReadiness = { projectId: string; projectVersion: number; workspacePath: string; packageChecksum: string; lockfileChecksum: string; scripts: string[] };
export type RuntimeRunnerRequest = { executable: string; args: readonly string[]; cwd: string; env: NodeJS.ProcessEnv; timeoutMs: number; signal?: AbortSignal; commandType: RuntimeCommandType; validationRunId: string };
export type RuntimeRunnerResponse = { exitCode: number | null; stdout: string; stderr: string; terminationReason: "completed" | "timeout" | "cancelled" | "spawn-failed" };
export interface RuntimeProcessRunner { run(request: RuntimeRunnerRequest): Promise<RuntimeRunnerResponse>; }
export type RuntimeValidatorInput = { projectId: string; projectVersion: number; workspacePath: string; generatedProjectsRoot: string; mutable?: boolean; validationRunId?: string; environmentPlan?: Array<{ name: string; serverOnly: boolean; secret: boolean }>; signal?: AbortSignal; outputLimitBytes?: number; lineLimitBytes?: number; policyVersion?: string };
export interface GeneratedProjectRuntimeValidator { inspectRuntimeReadiness(input: RuntimeValidatorInput): Promise<RuntimeReadiness>; runNpmCi(input: RuntimeValidatorInput): Promise<RuntimeCommandResult>; runLint(input: RuntimeValidatorInput): Promise<RuntimeCommandResult>; runTypecheck(input: RuntimeValidatorInput): Promise<RuntimeCommandResult>; runTests(input: RuntimeValidatorInput): Promise<RuntimeCommandResult>; runBuild(input: RuntimeValidatorInput): Promise<RuntimeCommandResult>; runValidationSequence(input: RuntimeValidatorInput): Promise<RuntimeValidationReport>; reconcileValidationState(input: { report: RuntimeValidationReport; workspacePath: string; expectedPackageChecksum: string; expectedLockfileChecksum: string; activeProcess?: boolean }): Promise<Array<{ code: string; description: string; automaticRepairAllowed: boolean }>>; }
