import { createHash } from "node:crypto";
import { lstat, readFile, stat } from "node:fs/promises";
import path from "node:path";
import { RuntimeValidationError } from "./errors";
import { RUNTIME_COMMAND_SPECS, type RuntimeCommandSpec, type RuntimeValidatorInput } from "./contracts";
const forbiddenLock = ["pnpm-lock.yaml", "yarn.lock", "bun.lockb", "bun.lock"];
const unsafeScript = /(^|[;&|])\s*(curl|wget|powershell|cmd(?:\.exe)?|bash|sh|git\s+push|npm\s+(install|exec)|npx\b|pnpm\b|yarn\b|bun\b|supabase\b|drop\s+database|deploy|vercel|docker)\b|https?:\/\/|>\s*[/A-Za-z]|&&|\|\|/i;
const lifecycle = new Set(["preinstall", "install", "postinstall", "prepare"]);
const sha = (bytes: Buffer) => createHash("sha256").update(bytes).digest("hex");
export async function readRuntimeFiles(input: RuntimeValidatorInput) { const root = path.resolve(input.workspacePath); const configured = path.resolve(input.generatedProjectsRoot); if (!root.startsWith(`${configured}${path.sep}`) || root === configured) throw new RuntimeValidationError("RUNTIME_WORKSPACE_INVALID", "Workspace is outside the configured generated-project staging root."); if (input.mutable === false) throw new RuntimeValidationError("RUNTIME_WORKSPACE_IMMUTABLE", "Runtime validation requires a mutable staging workspace."); const info = await lstat(root).catch(() => undefined); if (!info?.isDirectory() || info.isSymbolicLink()) throw new RuntimeValidationError("RUNTIME_WORKSPACE_INVALID", "Runtime workspace is not a regular directory."); const packagePath = path.join(root, "package.json"); const lockPath = path.join(root, "package-lock.json"); const packageBytes = await readFile(packagePath).catch(() => { throw new RuntimeValidationError("RUNTIME_WORKSPACE_INVALID", "package.json is missing."); }); const lockBytes = await readFile(lockPath).catch(() => { throw new RuntimeValidationError("RUNTIME_WORKSPACE_INVALID", "package-lock.json is missing."); }); for (const lock of forbiddenLock) if (await stat(path.join(root, lock)).then(() => true).catch(() => false)) throw new RuntimeValidationError("RUNTIME_PACKAGE_MANAGER_VIOLATION", "Only npm lockfiles are permitted."); let packageJson: { scripts?: Record<string, unknown>; dependencies?: Record<string, unknown>; devDependencies?: Record<string, unknown>; packageManager?: unknown }; try { packageJson = JSON.parse(packageBytes.toString("utf8")) as typeof packageJson; } catch (error) { throw new RuntimeValidationError("RUNTIME_PACKAGE_JSON_INVALID", "package.json is invalid JSON.", error); } if (packageJson.packageManager && (typeof packageJson.packageManager !== "string" || !/^npm(?:@|$)/i.test(packageJson.packageManager))) throw new RuntimeValidationError("RUNTIME_PACKAGE_MANAGER_VIOLATION", "Only npm is permitted."); const scripts = packageJson.scripts ?? {}; for (const required of ["lint", "typecheck", "test", "build"]) { if (typeof scripts[required] !== "string") throw new RuntimeValidationError("RUNTIME_SCRIPT_MISSING", `Required script ${required} is missing.`); if (unsafeScript.test(scripts[required])) throw new RuntimeValidationError("RUNTIME_SCRIPT_UNSAFE", `Script ${required} contains a forbidden command.`); } for (const [name, value] of Object.entries(scripts)) { if (lifecycle.has(name) && typeof value === "string") throw new RuntimeValidationError("RUNTIME_LIFECYCLE_SCRIPT_FORBIDDEN", `Lifecycle script ${name} is forbidden.`); } if (JSON.stringify(packageJson).match(/(npmrc|registry\s*=|NPM_TOKEN|_authToken)/i)) throw new RuntimeValidationError("RUNTIME_PRIVATE_REGISTRY_NOT_ALLOWED", "Private npm registry configuration is not allowed."); return { root, packageBytes, lockBytes, packageChecksum: sha(packageBytes), lockfileChecksum: sha(lockBytes), packageJson }; }
export async function readRuntimePackage(input: RuntimeValidatorInput) { const root = path.resolve(input.workspacePath); const configured = path.resolve(input.generatedProjectsRoot); if (!root.startsWith(`${configured}${path.sep}`) || root === configured) throw new RuntimeValidationError("RUNTIME_WORKSPACE_INVALID", "Workspace is outside the configured generated-project staging root."); if (input.mutable === false) throw new RuntimeValidationError("RUNTIME_WORKSPACE_IMMUTABLE", "Runtime validation requires a mutable staging workspace."); const info = await lstat(root).catch(() => undefined); if (!info?.isDirectory() || info.isSymbolicLink()) throw new RuntimeValidationError("RUNTIME_WORKSPACE_INVALID", "Runtime workspace is not a regular directory."); const packageBytes = await readFile(path.join(root, "package.json")).catch(() => { throw new RuntimeValidationError("RUNTIME_WORKSPACE_INVALID", "package.json is missing."); }); let packageJson: { scripts?: Record<string, unknown>; packageManager?: unknown }; try { packageJson = JSON.parse(packageBytes.toString("utf8")) as typeof packageJson; } catch (error) { throw new RuntimeValidationError("RUNTIME_PACKAGE_JSON_INVALID", "package.json is invalid JSON.", error); } if (packageJson.packageManager && (typeof packageJson.packageManager !== "string" || !/^npm(?:@|$)/i.test(packageJson.packageManager))) throw new RuntimeValidationError("RUNTIME_PACKAGE_MANAGER_VIOLATION", "Only npm is permitted."); return { root, packageBytes, packageChecksum: sha(packageBytes), packageJson }; }
export function getCommandSpec(commandType: string): RuntimeCommandSpec { if (!(commandType in RUNTIME_COMMAND_SPECS)) throw new RuntimeValidationError("RUNTIME_COMMAND_NOT_ALLOWED", "The requested runtime command is not allowlisted."); return RUNTIME_COMMAND_SPECS[commandType as keyof typeof RUNTIME_COMMAND_SPECS]; }
export function buildRuntimeEnvironment(input: RuntimeValidatorInput, base: NodeJS.ProcessEnv = process.env) { const allowed = new Set(["PATH", "Path", "SystemRoot", "TEMP", "TMP", "HOME", "USERPROFILE", "NODE_PATH", "NODE_OPTIONS"]); for (const variable of input.environmentPlan ?? []) if (!variable.secret && variable.serverOnly) allowed.add(variable.name); const env = {} as NodeJS.ProcessEnv; for (const name of allowed) if (base[name] !== undefined) env[name] = base[name]; for (const name of ["OPENAI_API_KEY", "DATABASE_URL", "SUPABASE_SERVICE_ROLE_KEY", "CONTEXT7_API_KEY", "SHADCN_REGISTRY_TOKEN", "NPM_TOKEN", "NODE_AUTH_TOKEN"]) delete env[name]; return env; }
