import { spawn } from "node:child_process";
import { access } from "node:fs/promises";
import path from "node:path";
import { RuntimeValidationError } from "./errors";
import type { RuntimeProcessRunner, RuntimeRunnerRequest, RuntimeRunnerResponse } from "./contracts";
export type NpmInvocation = { executable: string; argsPrefix: string[]; kind: "npm" | "npm.cmd" };
export function resolveNpmExecutable(platform = process.platform) { return platform === "win32" ? "npm.cmd" : "npm"; }
function pathEntries(env: NodeJS.ProcessEnv, platform: NodeJS.Platform) { return (platform === "win32" ? (env.Path ?? env.PATH ?? "") : (env.PATH ?? "")).split(platform === "win32" ? ";" : path.delimiter).map((entry) => entry.trim().replace(/^"|"$/g, "")).filter(Boolean); }
function normalizeWindowsPath(entry: string) { const match = entry.match(/^\/([a-zA-Z])\/(.*)$/); return match ? `${match[1].toUpperCase()}:\\${match[2].replaceAll("/", "\\")}` : entry; }
export async function resolveNpmInvocation(env: NodeJS.ProcessEnv | Record<string, string | undefined> = process.env, platform: NodeJS.Platform = process.platform): Promise<NpmInvocation | undefined> { if (platform !== "win32") return { executable: resolveNpmExecutable(platform), argsPrefix: [], kind: "npm" }; for (const rawEntry of pathEntries(env as NodeJS.ProcessEnv, platform)) { const entry = normalizeWindowsPath(rawEntry); const npmCmd = path.resolve(entry, "npm.cmd"); if (!(await access(npmCmd).then(() => true).catch(() => false))) continue; const npmDirectory = path.dirname(npmCmd); const cli = path.join(npmDirectory, "node_modules", "npm", "bin", "npm-cli.js"); if (!(await access(cli).then(() => true).catch(() => false))) continue; const localNode = path.join(npmDirectory, "node.exe"); const node = (await access(localNode).then(() => true).catch(() => false)) ? localNode : process.execPath; return { executable: node, argsPrefix: [cli], kind: "npm.cmd" }; } return undefined; }
export async function probeNpmAvailability(env: NodeJS.ProcessEnv | Record<string, string | undefined> = process.env) { const invocation = await resolveNpmInvocation(env); if (!invocation) return { available: false as const, safeErrorCode: "RUNTIME_NPM_EXECUTABLE_NOT_FOUND" as const }; return new Promise<{ available: boolean; executableKind?: NpmInvocation["kind"]; safeErrorCode?: string }>((resolve) => { const child = spawn(invocation.executable, [...invocation.argsPrefix, "--version"], { env: env as NodeJS.ProcessEnv, shell: false, stdio: "ignore" }); child.once("error", () => resolve({ available: false, safeErrorCode: "RUNTIME_NPM_SPAWN_FAILED" })); child.once("exit", (code) => resolve(code === 0 ? { available: true, executableKind: invocation.kind } : { available: false, executableKind: invocation.kind, safeErrorCode: "RUNTIME_NPM_VERSION_FAILED" })); }); }
export class NodeRuntimeProcessRunner implements RuntimeProcessRunner { async run(request: RuntimeRunnerRequest): Promise<RuntimeRunnerResponse> { if (request.executable !== "npm") throw new RuntimeValidationError("RUNTIME_COMMAND_NOT_ALLOWED", "Only the Factory npm executable may be launched."); if (request.signal?.aborted) return { exitCode: null, stdout: "", stderr: "", terminationReason: "cancelled" }; const invocation = await resolveNpmInvocation(request.env); if (!invocation) return { exitCode: null, stdout: "", stderr: "npm executable unavailable", terminationReason: "spawn-failed" }; return new Promise((resolve) => { const child = spawn(invocation.executable, [...invocation.argsPrefix, ...request.args], { cwd: request.cwd, env: request.env, shell: false, stdio: ["ignore", "pipe", "pipe"] }); let stdout = ""; let stderr = ""; let settled = false; const finish = (value: RuntimeRunnerResponse) => { if (!settled) { settled = true; clearTimeout(timer); request.signal?.removeEventListener("abort", cancel); resolve(value); } }; const timer = setTimeout(() => { child.kill(); finish({ exitCode: null, stdout, stderr, terminationReason: "timeout" }); }, request.timeoutMs); const cancel = () => { child.kill(); finish({ exitCode: null, stdout, stderr, terminationReason: "cancelled" }); }; request.signal?.addEventListener("abort", cancel, { once: true }); child.stdout.on("data", (chunk: Buffer) => { stdout += chunk.toString("utf8"); }); child.stderr.on("data", (chunk: Buffer) => { stderr += chunk.toString("utf8"); }); child.on("error", (error) => finish({ exitCode: null, stdout, stderr: `${stderr}\n${error.message}`, terminationReason: "spawn-failed" })); child.on("close", (code) => finish({ exitCode: code, stdout, stderr, terminationReason: "completed" })); }); } }
