import { createHash, randomUUID } from "node:crypto";
import { readFile } from "node:fs/promises";
import path from "node:path";
import { QualityCheckSchema } from "../domain/quality/schema";
import { RuntimeCommandResultSchema, RuntimeValidationReportSchema, type GeneratedProjectRuntimeValidator, type RuntimeCommandResult, type RuntimeCommandType, type RuntimeProcessRunner, type RuntimeReadiness, type RuntimeValidationReport, type RuntimeValidatorInput } from "./contracts";
import { buildRuntimeEnvironment, getCommandSpec, readRuntimeFiles } from "./policy";
import { NodeRuntimeProcessRunner } from "./runner";
const sha = (bytes: Buffer) => createHash("sha256").update(bytes).digest("hex");
const qualityName: Record<RuntimeCommandType, "npm-ci" | "lint" | "typecheck" | "unit-tests" | "build"> = { "npm-ci": "npm-ci", lint: "lint", typecheck: "typecheck", tests: "unit-tests", build: "build" };
const failureCode: Record<RuntimeCommandType, string> = { "npm-ci": "QUALITY_NPM_CI_FAILED", lint: "QUALITY_LINT_FAILED", typecheck: "QUALITY_TYPECHECK_FAILED", tests: "QUALITY_TESTS_FAILED", build: "QUALITY_BUILD_FAILED" };
const repairCategory: Record<RuntimeCommandType, string> = { "npm-ci": "FOUNDATION_DEPENDENCY_REPAIR", lint: "TARGETED_SOURCE_STYLE_REPAIR", typecheck: "TARGETED_TYPESCRIPT_API_REPAIR", tests: "IMPLEMENTATION_TEST_REPAIR", build: "INTEGRATION_RUNTIME_BUILD_REPAIR" };
function boundOutput(value: string, limit: number, lineLimit: number) { const redacted = value.replace(/(sk-[A-Za-z0-9]{12,}|AKIA[A-Z0-9]{12,}|DATABASE_URL\s*[:=]\s*\S+|Bearer\s+\S+)/gi, "[REDACTED]").replace(/[A-Za-z]:\\[^\s]+|\/Users\/[^\s]+|\/home\/[^\s]+/g, "[PATH]"); const joined = redacted.split(/\r?\n/).map((line) => line.length > lineLimit ? `${line.slice(0, lineLimit)}…` : line).join("\n"); return { value: joined.length > limit ? `${joined.slice(0, Math.floor(limit / 2))}\n…[TRUNCATED]…\n${joined.slice(-Math.floor(limit / 2))}` : joined, truncated: joined.length > limit }; }
export class GeneratedRuntimeValidator implements GeneratedProjectRuntimeValidator {
  constructor(private readonly runner: RuntimeProcessRunner = new NodeRuntimeProcessRunner(), private readonly defaults: { outputLimitBytes?: number; lineLimitBytes?: number; policyVersion?: string } = {}) {}
  async inspectRuntimeReadiness(input: RuntimeValidatorInput): Promise<RuntimeReadiness> { const files = await readRuntimeFiles(input); return { projectId: input.projectId, projectVersion: input.projectVersion, workspacePath: files.root, packageChecksum: files.packageChecksum, lockfileChecksum: files.lockfileChecksum, scripts: Object.keys(files.packageJson.scripts ?? {}).sort() }; }
  async runNpmCi(input: RuntimeValidatorInput) { return this.runOne("npm-ci", input); }
  async runLint(input: RuntimeValidatorInput) { return this.runOne("lint", input); }
  async runTypecheck(input: RuntimeValidatorInput) { return this.runOne("typecheck", input); }
  async runTests(input: RuntimeValidatorInput) { return this.runOne("tests", input); }
  async runBuild(input: RuntimeValidatorInput) { return this.runOne("build", input); }
  async runValidationSequence(input: RuntimeValidatorInput): Promise<RuntimeValidationReport> {
    const validationRunId = input.validationRunId ?? randomUUID(); const startedAt = new Date().toISOString(); const readiness = await this.inspectRuntimeReadiness(input); const results: RuntimeCommandResult[] = [];
    for (const command of ["npm-ci", "lint", "typecheck", "tests", "build"] as const) { if (input.signal?.aborted) break; const result = await this.runOne(command, { ...input, validationRunId }); results.push(result); if (!result.passed) break; }
    const cancelled = Boolean(input.signal?.aborted || results.some((result) => result.cancelled)); const failed = results.some((result) => !result.passed);
    const qualityChecks = results.map((result) => QualityCheckSchema.parse({ name: qualityName[result.commandType], status: result.cancelled ? "skipped" : result.passed ? "passed" : "failed", startedAt: result.startedAt, completedAt: result.completedAt, resultSummary: result.stdoutSummary || result.stderrSummary || "Runtime command completed.", ...(result.cancelled ? { skippedReason: "Validation was cancelled." } : {}), ...(result.safeFailureCode ? { safeFailureCode: result.safeFailureCode } : {}), attempt: 0, required: true, command: `${result.executableIdentity} ${result.safeArgsSummary}`, ...(result.exitCode === null ? {} : { exitCode: result.exitCode }) }));
    return RuntimeValidationReportSchema.parse({ validationRunId, projectId: input.projectId, projectVersion: input.projectVersion, workspaceReference: path.relative(input.generatedProjectsRoot, input.workspacePath).replaceAll("\\", "/"), packageChecksum: readiness.packageChecksum, lockfileChecksum: readiness.lockfileChecksum, startedAt, completedAt: new Date().toISOString(), overallStatus: cancelled ? "cancelled" : failed ? "failed" : results.length === 5 ? "passed" : "skipped", commandResults: results, qualityChecks, ...(failed ? { failureCategory: repairCategory[results.find((result) => !result.passed)!.commandType] } : {}), repairEligible: failed, warnings: [], policyVersion: input.policyVersion ?? this.defaults.policyVersion ?? "runtime-v1" });
  }
  private async runOne(commandType: RuntimeCommandType, input: RuntimeValidatorInput & { validationRunId?: string }): Promise<RuntimeCommandResult> { const readiness = await this.inspectRuntimeReadiness(input); const spec = getCommandSpec(commandType); const validationRunId = input.validationRunId ?? randomUUID(); const startedAt = new Date().toISOString(); const started = Date.now(); const response = await this.runner.run({ executable: spec.executable, args: spec.args, cwd: readiness.workspacePath, env: buildRuntimeEnvironment(input), timeoutMs: spec.timeoutMs, signal: input.signal, commandType, validationRunId }); const stdout = boundOutput(response.stdout, input.outputLimitBytes ?? this.defaults.outputLimitBytes ?? 16000, input.lineLimitBytes ?? this.defaults.lineLimitBytes ?? 2000); const stderr = boundOutput(response.stderr, input.outputLimitBytes ?? this.defaults.outputLimitBytes ?? 16000, input.lineLimitBytes ?? this.defaults.lineLimitBytes ?? 2000); const passed = response.terminationReason === "completed" && response.exitCode === 0; return RuntimeCommandResultSchema.parse({ commandId: randomUUID(), validationRunId, projectId: input.projectId, projectVersion: input.projectVersion, commandType, executableIdentity: spec.executable, safeArgsSummary: spec.args.join(" "), cwdReference: path.relative(input.generatedProjectsRoot, readiness.workspacePath).replaceAll("\\", "/"), startedAt, completedAt: new Date().toISOString(), durationMs: Date.now() - started, exitCode: response.exitCode, terminationReason: response.terminationReason, stdoutSummary: stdout.value, stderrSummary: stderr.value, stdoutBytes: Buffer.byteLength(response.stdout), stderrBytes: Buffer.byteLength(response.stderr), outputTruncated: stdout.truncated || stderr.truncated, timeout: response.terminationReason === "timeout", cancelled: response.terminationReason === "cancelled", passed, ...(passed ? {} : { safeFailureCode: response.terminationReason === "timeout" ? "RUNTIME_COMMAND_TIMEOUT" : response.terminationReason === "cancelled" ? "RUNTIME_VALIDATION_CANCELLED" : failureCode[commandType] }) }); }
  async reconcileValidationState(input: { report: RuntimeValidationReport; workspacePath: string; expectedPackageChecksum: string; expectedLockfileChecksum: string; activeProcess?: boolean }) { const issues: Array<{ code: string; description: string; automaticRepairAllowed: boolean }> = []; if (input.activeProcess === false && input.report.overallStatus === "running") issues.push({ code: "RUNTIME_PROCESS_ORPHANED", description: "Validation report is RUNNING without an active process.", automaticRepairAllowed: false }); const packageBytes = await readFile(path.join(input.workspacePath, "package.json")).catch(() => undefined); const lockBytes = await readFile(path.join(input.workspacePath, "package-lock.json")).catch(() => undefined); if (!packageBytes || sha(packageBytes) !== input.expectedPackageChecksum) issues.push({ code: "RUNTIME_PACKAGE_CHANGED", description: "package.json changed after validation.", automaticRepairAllowed: false }); if (!lockBytes || sha(lockBytes) !== input.expectedLockfileChecksum) issues.push({ code: "RUNTIME_LOCKFILE_CHANGED", description: "package-lock.json changed after validation.", automaticRepairAllowed: false }); if (input.report.overallStatus === "passed" && input.report.commandResults.length < 5) issues.push({ code: "RUNTIME_COMMAND_RESULT_MISSING", description: "A passed validation report is missing command results.", automaticRepairAllowed: false }); return issues; }
}
