import { describe, expect, it } from "vitest";
import { normalizeTestDiagnostics } from "./test-diagnostics";

const input = (stdout = "", stderr = "") => ({ workspacePath: "C:/generated/project", stdout, stderr });

describe("test diagnostic normalizer", () => {
  it("extracts a failed Vitest assertion and test identity", () => { const [d] = normalizeTestDiagnostics(input("× contact form submits (src/components/contact-form.test.tsx:18:5)\nAssertionError: expected false to be true")); expect(d).toMatchObject({ category: "ASSERTION_FAILURE", testFile: "src/components/contact-form.test.tsx", testName: "contact form submits", relativePath: "src/components/contact-form.test.tsx" }); });
  it("prefers an implementation frame over the test frame", () => { const [d] = normalizeTestDiagnostics(input("AssertionError: expected value\n at submit (src/components/contact-form.tsx:22:9)\n at test (src/components/contact-form.test.tsx:18:5)")); expect(d).toMatchObject({ sourceFile: "src/components/contact-form.tsx", relativePath: "src/components/contact-form.tsx", classification: "IMPLEMENTATION_DEFECT" }); });
  it("normalizes Windows frames and rejects external or node_modules frames", () => { expect(normalizeTestDiagnostics(input("Error\n at run (C:\\generated\\project\\src\\lib\\api.ts:4:2)"))[0]).toMatchObject({ relativePath: "src/lib/api.ts" }); expect(normalizeTestDiagnostics(input("Error\n at run (C:\\other\\src\\api.ts:4:2)"))).toEqual([]); expect(normalizeTestDiagnostics(input("Error\n at run (C:\\generated\\project\\node_modules\\x\\index.js:4:2)"))).toEqual([]); expect(normalizeTestDiagnostics(input("Error\n at run (.next/server/page.js:4:2)"))).toEqual([]); });
  it("normalizes module-not-found and timeout failures", () => { expect(normalizeTestDiagnostics(input("Cannot find module '@/components/contact-form' from src/components/contact-form.test.tsx:3:1"))[0]).toMatchObject({ category: "MODULE_NOT_FOUND", testFile: "src/components/contact-form.test.tsx", module: "@/components/contact-form" }); expect(normalizeTestDiagnostics(input("× appointment flow\nTest timed out in tests/appointment.test.ts:9:1"))[0]).toMatchObject({ category: "TEST_TIMEOUT", testFile: "tests/appointment.test.ts" }); });
  it("supports config/setup, boundary, stdout and stderr evidence", () => { expect(normalizeTestDiagnostics(input("", "Vitest setup failure at vitest.config.ts:6:1"))[0]).toMatchObject({ category: "TEST_CONFIGURATION", relativePath: "vitest.config.ts" }); expect(normalizeTestDiagnostics(input("server-only module in src/components/form.tsx:2:1 client component"))[0]).toMatchObject({ category: "SERVER_CLIENT_BOUNDARY" }); });
  it("classifies the observed Vitest no-tests output precisely", () => { expect(normalizeTestDiagnostics(input("> test\n> vitest run --run\n"))[0]).toMatchObject({ category: "TEST_SUITE_MISSING", relativePath: "tests", classification: "NON_TARGETABLE" }); });
  it("deduplicates, bounds, redacts, and preserves the bounded tail", () => { const line = "AssertionError at src/app/page.tsx:2:1 SECRET=hidden"; expect(normalizeTestDiagnostics(input(Array.from({ length: 100 }, () => line).join("\n")))).toHaveLength(1); const many = normalizeTestDiagnostics(input(Array.from({ length: 100 }, (_, i) => `AssertionError at src/app/p${i}.tsx:2:1`).join("\n"))); expect(many.length).toBeLessThanOrEqual(50); expect(many[0]?.safeMessage).not.toContain("hidden"); expect(normalizeTestDiagnostics(input("unknown worker infrastructure failure"))).toEqual([]); });
});
