import { z } from "zod";
import { QualityCheckSchema } from "../domain/quality/schema";
import { type PlanningPackage } from "../planner/contracts";
import { type RequirementSpecification } from "../domain/requirements/schema";
import { DocumentBaseSchema } from "../domain/shared/schemas";
import { RuntimeDiagnosticReferenceSchema } from "../runtime-validation/contracts";

const Uuid = z.string().uuid();
const Iso = z.string().datetime();
const Ref = z.string().min(1).max(200);
const Route = z.string().regex(/^\/(?:[a-z0-9-]+(?:\/[a-z0-9-]+)*)?$/);
export const FUNCTIONAL_QA_DIAGNOSTIC_POLICY_VERSION = "functional-qa-diagnostics-v4";

export const FunctionalQaActionSchema = z.enum(["navigate", "fill", "click", "submit", "select", "check", "waitFor", "assertText", "assertVisible", "assertUrl", "assertStatus"]);
export type FunctionalQaAction = z.infer<typeof FunctionalQaActionSchema>;
export const FunctionalQaScenarioTypeSchema = z.enum(["route", "navigation", "form", "protected-route", "authorization", "status", "runtime-error"]);
export type FunctionalQaScenarioType = z.infer<typeof FunctionalQaScenarioTypeSchema>;
export const FunctionalQaRunDiagnosticSchema = z.object({ category: z.string().regex(/^QA_[A-Z0-9_]+$/), lifecyclePhase: z.enum(["server-start", "server-readiness", "browser-launch", "browser-context", "page-create", "scenario-dispatch", "navigation", "cleanup"]), assignedPort: z.number().int().positive().optional(), serverCommand: z.string().max(120), processSpawned: z.boolean(), serverPidExists: z.boolean(), serverReady: z.boolean(), browserLaunched: z.boolean(), contextCreated: z.boolean(), pageCreated: z.boolean(), scenarioDispatchStarted: z.boolean(), firstNavigationAttempted: z.boolean(), cancellationRequested: z.boolean(), timeoutCategory: z.string().max(80).optional(), safeErrorCode: z.string().regex(/^QA_[A-Z0-9_]+$/), safeMessage: z.string().max(500) }).strict();
export type FunctionalQaRunDiagnostic = z.infer<typeof FunctionalQaRunDiagnosticSchema>;
export const FunctionalQaStepSchema = z.object({ stepId: Ref.optional(), order: z.number().int().positive(), action: FunctionalQaActionSchema, assertion: Ref.optional(), targetRole: Ref.optional(), route: Route.optional(), selector: Ref.optional(), value: z.string().max(500).optional(), expectedText: z.string().max(500).optional(), expectedUrl: Route.optional(), expectedStatus: z.number().int().min(100).max(599).optional(), artifactReferences: z.array(Ref).max(8).default([]), timeoutMs: z.number().int().positive().max(30000).default(5000) }).strict().superRefine((step, context) => {
  if (["fill", "click", "submit", "select", "check", "assertVisible", "assertText"].includes(step.action) && !step.selector) context.addIssue({ code: "custom", path: ["selector"], message: "This action requires an approved selector." });
  if (["navigate", "assertUrl"].includes(step.action) && !(step.route || step.expectedUrl)) context.addIssue({ code: "custom", path: ["route"], message: "Navigation actions require a localhost route." });
  if (step.action === "assertText" && !step.expectedText) context.addIssue({ code: "custom", path: ["expectedText"], message: "Text assertions require approved expected text." });
  if (step.action === "assertStatus" && !step.expectedStatus) context.addIssue({ code: "custom", path: ["expectedStatus"], message: "Status assertions require an expected status." });
});
export type FunctionalQaStep = z.infer<typeof FunctionalQaStepSchema>;

export const FunctionalQaAssertionSchema = z.object({ category: z.enum(["route", "navigation", "form", "auth", "authorization", "runtime", "status"]), expected: Ref, mandatory: z.boolean() }).strict();
export const FunctionalQaScenarioSchema = z.object({ scenarioId: Ref, scenarioType: FunctionalQaScenarioTypeSchema.default("route"), title: Ref, actor: Ref, purpose: Ref, acceptanceCriteriaReferences: z.array(Ref).min(1), requirementReferences: z.array(Ref).min(1), planningReferences: z.array(Ref).default([]), userFlowReferences: z.array(Ref), artifactReferences: z.array(Ref).default([]), ownershipCandidates: z.array(z.enum(["implement-navigation", "implement-page", "implement-form", "implement-server-action", "implement-route-handler", "implement-authentication", "implement-shared-layout"])).default([]), startRoute: Route, preconditions: z.array(Ref), steps: z.array(FunctionalQaStepSchema).min(1), assertions: z.array(FunctionalQaAssertionSchema).min(1), expectedOutcome: Ref, failureCategory: z.string().regex(/^QA_[A-Z0-9_]+$/), requiresAuth: z.boolean(), requiresForm: z.boolean(), requiresDatabaseFixture: z.boolean(), timeoutMs: z.number().int().positive().max(120000) }).strict();
export type FunctionalQaScenario = z.infer<typeof FunctionalQaScenarioSchema>;

export const FunctionalQaPlanSchema = z.object({ planId: Uuid, projectId: Uuid, projectVersion: z.number().int().positive(), scenarios: z.array(FunctionalQaScenarioSchema), selectedBriefChecksum: z.string().regex(/^[a-f0-9]{64}$/), selectedPlanningChecksum: z.string().regex(/^[a-f0-9]{64}$/), selectedDesignChecksum: z.string().regex(/^[a-f0-9]{64}$/), policyVersion: Ref }).strict();
export type FunctionalQaPlan = z.infer<typeof FunctionalQaPlanSchema>;
export type ScenarioDerivationInput = { projectId: string; projectVersion: number; brief: RequirementSpecification; planning: PlanningPackage; briefChecksum: string; planningChecksum: string; designChecksum: string; policyVersion?: string };

export const FunctionalQaEvidenceSchema = z.object({ scenarioId: Ref, stepId: Ref.optional(), stepIndex: z.number().int().nonnegative(), action: FunctionalQaActionSchema, result: z.enum(["passed", "failed", "skipped"]), assertionCategory: z.string().max(80).optional(), route: Route.optional(), expectedState: z.string().max(300).optional(), actualSafeSummary: z.string().max(1000), durationMs: z.number().int().nonnegative(), safeErrorCode: z.string().regex(/^QA_[A-Z0-9_]+$/).optional() }).strict();
export type FunctionalQaEvidence = z.infer<typeof FunctionalQaEvidenceSchema>;
export const FunctionalQaDiagnosticSchema = z.object({ category: z.string().regex(/^QA_[A-Z0-9_]+$/), scenarioId: Ref, scenarioType: FunctionalQaScenarioTypeSchema.optional(), route: Route.optional(), stepId: Ref.optional(), stepIndex: z.number().int().nonnegative().optional(), action: FunctionalQaActionSchema.optional(), assertion: z.string().max(200).optional(), selectorRole: z.string().max(120).optional(), safeMessage: z.string().min(1).max(500), requirementReferences: z.array(Ref).max(20), planningReferences: z.array(Ref).max(20), artifactReferences: z.array(Ref).max(20).default([]), candidateOwnership: z.array(z.enum(["implement-project-foundation", "implement-navigation", "implement-page", "implement-form", "implement-server-action", "implement-route-handler", "implement-authentication", "implement-shared-layout"])).max(4), sourceHints: z.array(z.string().regex(/^[A-Z0-9_]+$/).max(80)).max(8), runtimeReference: RuntimeDiagnosticReferenceSchema.optional() }).strict();
export type FunctionalQaDiagnostic = z.infer<typeof FunctionalQaDiagnosticSchema>;
export const FunctionalQaScenarioResultSchema = z.object({ scenarioId: Ref, scenarioType: FunctionalQaScenarioTypeSchema.optional(), route: Route.optional(), status: z.enum(["passed", "failed", "skipped", "cancelled"]), startedAt: Iso, completedAt: Iso, durationMs: z.number().int().nonnegative(), evidence: z.array(FunctionalQaEvidenceSchema).max(100), safeFailureCode: z.string().regex(/^QA_[A-Z0-9_]+$/).optional(), summary: z.string().max(1000) }).strict();
export type FunctionalQaScenarioResult = z.infer<typeof FunctionalQaScenarioResultSchema>;

export const FunctionalQaBrowserErrorSchema = z.object({ kind: z.enum(["console-error", "page-error", "failed-navigation", "failed-resource", "failed-api", "server-5xx", "external-request"]), route: Route.optional(), safeSummary: z.string().max(500), safeErrorCode: z.string().regex(/^QA_[A-Z0-9_]+$/).optional(), approvedNoise: z.boolean() }).strict();
export const FunctionalQaReportSchema = z.object({ runId: Uuid, projectId: Uuid, projectVersion: z.number().int().positive(), taskId: Uuid, runtimeValidationRunId: Uuid, startedAt: Iso, completedAt: Iso, status: z.enum(["passed", "failed", "skipped", "cancelled"]), scenarios: z.array(FunctionalQaScenarioResultSchema), passedCount: z.number().int().nonnegative(), failedCount: z.number().int().nonnegative(), skippedCount: z.number().int().nonnegative(), browserErrors: z.array(FunctionalQaBrowserErrorSchema).max(100), diagnostics: z.array(FunctionalQaDiagnosticSchema).max(50), unexpectedExternalRequests: z.array(z.string().max(300)).max(100), failureCategory: z.string().regex(/^QA_[A-Z0-9_]+$/).optional(), runLevelFailure: z.object({ safeErrorCode: z.string().regex(/^QA_[A-Z0-9_]+$/), safeSummary: z.string().max(1000) }).strict().optional(), runLevelDiagnostic: FunctionalQaRunDiagnosticSchema.optional(), repairEligible: z.boolean(), qualityCheck: QualityCheckSchema, policyVersion: Ref, runtimeValidationPackageChecksum: z.string().regex(/^[a-f0-9]{64}$/), runtimeValidationLockfileChecksum: z.string().regex(/^[a-f0-9]{64}$/), selectedBriefChecksum: z.string().regex(/^[a-f0-9]{64}$/), selectedPlanningChecksum: z.string().regex(/^[a-f0-9]{64}$/), selectedDesignChecksum: z.string().regex(/^[a-f0-9]{64}$/), warnings: z.array(z.string().max(300)).max(20) }).strict();
export type FunctionalQaReport = z.infer<typeof FunctionalQaReportSchema>;
export const FunctionalQaMemorySummarySchema = DocumentBaseSchema.extend({ documentType: z.literal("functional-qa"), runId: Uuid, status: z.enum(["passed", "failed", "skipped", "cancelled"]), passedCount: z.number().int().nonnegative(), failedCount: z.number().int().nonnegative(), skippedCount: z.number().int().nonnegative(), scenarioStatuses: z.array(z.object({ scenarioId: Ref, status: z.enum(["passed", "failed", "skipped", "cancelled"]), safeFailureCode: z.string().regex(/^QA_[A-Z0-9_]+$/).optional() }).strict()).max(100), qualityCheckReference: Ref, runtimeValidationPackageChecksum: z.string().regex(/^[a-f0-9]{64}$/), policyVersion: Ref }).strict();

export type RuntimePrerequisite = { overallStatus: "passed"; validationRunId: string; packageChecksum: string; lockfileChecksum: string };
export type QaReadinessInput = { projectId: string; projectVersion: number; workspacePath: string; generatedProjectsRoot: string; mutable: boolean; runtimeValidation: RuntimePrerequisite | undefined; task: { id: string; taskType: string; status: string; allowedTools: string[]; requirementReferences?: string[]; planningReferences?: string[]; selectedDesignReferences?: string[] }; expectedBriefChecksum: string; expectedPlanningChecksum: string; expectedDesignChecksum: string; actualBriefChecksum: string; actualPlanningChecksum: string; actualDesignChecksum: string; blockingImplementationTask: boolean; fixturesAvailable: boolean };
export type LocalServerHandle = { pid: number; port: number; baseUrl: string };
export type LocalServerLauncher = { start(input: { workspacePath: string; port: number; signal?: AbortSignal }): Promise<LocalServerHandle>; stop(handle: LocalServerHandle): Promise<void>; isRunning(handle: LocalServerHandle): Promise<boolean>; waitForReady?(handle: LocalServerHandle, timeoutMs: number, signal?: AbortSignal): Promise<number> };
export type PlaywrightFunctionalRunner = { launch(input: { baseUrl: string; port: number; signal?: AbortSignal }): Promise<void>; navigate(route: string, timeoutMs: number): Promise<number>; fill(selector: string, value: string, timeoutMs: number): Promise<void>; click(selector: string, timeoutMs: number): Promise<void>; submit(selector: string, timeoutMs: number): Promise<void>; select(selector: string, value: string, timeoutMs: number): Promise<void>; check(selector: string, timeoutMs: number): Promise<void>; waitFor(input: { selector?: string; timeoutMs: number }): Promise<void>; assertText(selector: string, expected: string, timeoutMs: number): Promise<void>; assertVisible(selector: string, timeoutMs: number): Promise<void>; assertUrl(route: string): Promise<void>; assertStatus(expected: number): Promise<void>; readConsoleErrors(): Promise<Array<{ kind: "console-error" | "page-error" | "failed-navigation" | "failed-resource" | "failed-api" | "server-5xx" | "external-request"; route?: string; safeSummary: string; safeErrorCode?: string; approvedNoise: boolean }>>; close(): Promise<void> };
export type FunctionalQaServiceInput = { projectId: string; projectVersion: number; taskId: string; workspacePath: string; generatedProjectsRoot: string; runtimeValidation: RuntimePrerequisite | undefined; plan: FunctionalQaPlan; readiness: Omit<QaReadinessInput, "projectId" | "projectVersion" | "workspacePath" | "generatedProjectsRoot" | "runtimeValidation">; signal?: AbortSignal; totalTimeoutMs?: number };
