import { describe, expect, it } from "vitest";
import { deriveFunctionalQaDiagnostics } from "./diagnostics";
import { FunctionalQaScenarioSchema, FunctionalQaScenarioResultSchema } from "./contracts";

const scenario = (overrides: Record<string, unknown> = {}) => FunctionalQaScenarioSchema.parse({ scenarioId: "route:contact", title: "Contact route", actor: "visitor", purpose: "Reach contact", acceptanceCriteriaReferences: ["ac:contact"], requirementReferences: ["req:contact"], userFlowReferences: ["flow:contact"], startRoute: "/contact", preconditions: [], steps: [{ order: 1, action: "navigate", route: "/contact" }, { order: 2, action: "assertStatus", expectedStatus: 200 }], assertions: [{ category: "route", expected: "reachable", mandatory: true }], expectedOutcome: "reachable", failureCategory: "QA_ROUTE_MISSING", requiresAuth: false, requiresForm: false, requiresDatabaseFixture: false, timeoutMs: 30000, ...overrides });
const failed = (overrides: Record<string, unknown> = {}) => FunctionalQaScenarioResultSchema.parse({ scenarioId: "route:contact", status: "failed", startedAt: "2026-01-01T00:00:00.000Z", completedAt: "2026-01-01T00:00:01.000Z", durationMs: 1000, evidence: [{ scenarioId: "route:contact", stepIndex: 0, action: "navigate", result: "failed", route: "/contact", actualSafeSummary: "safe", safeErrorCode: "QA_ROUTE_MISSING", durationMs: 1000 }], safeFailureCode: "QA_ROUTE_MISSING", summary: "safe", ...overrides });

describe("functional QA diagnostic derivation", () => {
  it("preserves route, scenario, and requirement traceability", () => { const [diagnostic] = deriveFunctionalQaDiagnostics({ plan: { scenarios: [scenario()] }, results: [failed()], browserErrors: [] }); expect(diagnostic).toMatchObject({ category: "QA_ROUTE_MISSING", scenarioId: "route:contact", route: "/contact", requirementReferences: ["req:contact", "ac:contact"], planningReferences: ["flow:contact", "route:contact"], candidateOwnership: ["implement-page"] }); expect(diagnostic?.runtimeReference).toMatchObject({ relativePath: "src/app/contact/page.tsx", route: "/contact" }); });
  it("maps form submit failures to form and server-action candidates", () => { const [diagnostic] = deriveFunctionalQaDiagnostics({ plan: { scenarios: [scenario({ scenarioId: "form:booking", requiresForm: true, failureCategory: "QA_FORM_VALIDATION_FAILURE", steps: [{ order: 1, action: "submit", selector: "[data-qa-form=booking]" }] })] }, results: [failed({ scenarioId: "form:booking", evidence: [{ scenarioId: "form:booking", stepIndex: 0, action: "submit", result: "failed", route: "/contact", actualSafeSummary: "safe", safeErrorCode: "QA_FORM_VALIDATION_FAILURE", durationMs: 1 }] })], browserErrors: [] }); expect(diagnostic?.candidateOwnership).toEqual(["implement-form", "implement-server-action"]); });
  it("keeps an ambiguous run-level browser failure without a fabricated route target", () => { const result = deriveFunctionalQaDiagnostics({ plan: { scenarios: [scenario()] }, results: [], browserErrors: [{ kind: "console-error", safeSummary: "safe browser error", approvedNoise: false }] }); expect(result[0]?.route).toBe("/contact"); expect(result[0]?.sourceHints).toContain("BROWSER_SAFE_ERROR"); });
  it("never includes raw browser output or generated bundle paths", () => { const [diagnostic] = deriveFunctionalQaDiagnostics({ plan: { scenarios: [scenario()] }, results: [failed()], browserErrors: [{ kind: "console-error", route: "/contact", safeSummary: "safe" , approvedNoise: false }] }); expect(JSON.stringify(diagnostic)).not.toContain(".next"); expect(JSON.stringify(diagnostic)).not.toContain("console.error"); });
});
