import { describe, expect, it } from "vitest";
import { assertLocalhostRoute, assertLocalhostUrl, assertSafeTestServerScript, deriveFunctionalQaPlan, validateQaReadiness } from "./policy";
import { FunctionalQaError } from "./errors";
import { DeterministicFakeBrowserRunner } from "./fake";
import { FunctionalQaService } from "./service";
import { completeFunctionalQaTask, startFunctionalQaTask } from "./task";
import { reconcileFunctionalQa } from "./reconcile";
import { FunctionalQaMemorySummarySchema, FunctionalQaPlanSchema, type FunctionalQaPlan, type LocalServerHandle, type LocalServerLauncher, type FunctionalQaReport } from "./contracts";
import type { PlanningPackage } from "../planner/contracts";
import type { RequirementSpecification } from "../domain/requirements/schema";
import type { AgentTask } from "../domain/tasks/schema";

const projectId = "11111111-1111-4111-8111-111111111111"; const taskId = "22222222-2222-4222-8222-222222222222"; const checksum = "a".repeat(64); const runtime = { overallStatus: "passed" as const, validationRunId: "33333333-3333-4333-8333-333333333333", packageChecksum: checksum, lockfileChecksum: "b".repeat(64) };

class FakeServer implements LocalServerLauncher { handle?: LocalServerHandle; async start(input: { port: number }) { this.handle = { pid: 123, port: input.port, baseUrl: `http://127.0.0.1:${input.port}` }; return this.handle; } async waitForReady() { return 200; } async stop() { this.handle = undefined; } async isRunning() { return Boolean(this.handle); } }
function task(status: AgentTask["status"] = "ready"): AgentTask { return { id: taskId, projectId, projectVersion: 1, role: "qa-release", taskType: "validate-functional-flow", title: "Functional QA", objective: "Run approved functional QA", inputs: ["runtime report"], expectedOutputs: ["QA report"], acceptanceCriteria: ["Approved scenarios pass"], allowedSkills: [], allowedTools: ["filesystem-read", "Playwright-functional"], deniedTools: ["git-write"], fileScopes: [], dependencies: ["44444444-4444-4444-8444-444444444444"], status, priority: "normal", executionMode: "validation-only", attempt: 0, maxAttempts: 1, createdAt: "2026-01-01T00:00:00.000Z", ...(status === "running" ? { startedAt: "2026-01-01T00:00:00.000Z" } : {}), ...(status === "passed" || status === "failed" || status === "cancelled" ? { completedAt: "2026-01-01T00:00:00.000Z" } : {}), blockingFailure: true, estimatedContextBytes: 1000, expectedArtifactTypes: ["validation-report"] }; }
function plan(): FunctionalQaPlan { return FunctionalQaPlanSchema.parse({ planId: "55555555-5555-4555-8555-555555555555", projectId, projectVersion: 1, scenarios: [{ scenarioId: "route:home", title: "Home route", actor: "Visitor", purpose: "Load home", acceptanceCriteriaReferences: ["acceptance:home"], requirementReferences: ["requirement:home"], userFlowReferences: [], startRoute: "/", preconditions: [], steps: [{ order: 1, action: "navigate", route: "/", timeoutMs: 1000 }, { order: 2, action: "assertStatus", expectedStatus: 200, timeoutMs: 1000 }, { order: 3, action: "assertUrl", expectedUrl: "/", timeoutMs: 1000 }], assertions: [{ category: "route", expected: "Home returns 200", mandatory: true }], expectedOutcome: "Home loads", failureCategory: "QA_ROUTE_MISSING", requiresAuth: false, requiresForm: false, requiresDatabaseFixture: false, timeoutMs: 10000 }], selectedBriefChecksum: checksum, selectedPlanningChecksum: checksum, selectedDesignChecksum: checksum, policyVersion: "playwright-functional-v1" }); }
function readiness(overrides: Partial<Parameters<typeof validateQaReadiness>[0]> = {}) { return { projectId, projectVersion: 1, workspacePath: "C:\\generated\\project\\v1", generatedProjectsRoot: "C:\\generated", mutable: true, runtimeValidation: runtime, task: task(), expectedBriefChecksum: checksum, expectedPlanningChecksum: checksum, expectedDesignChecksum: checksum, actualBriefChecksum: checksum, actualPlanningChecksum: checksum, actualDesignChecksum: checksum, blockingImplementationTask: false, fixturesAvailable: true, ...overrides }; }

describe("Playwright functional QA foundation", () => {
  it("accepts only the assigned loopback URL and rejects external schemes", () => { expect(assertLocalhostUrl("http://127.0.0.1:4173/", 4173).pathname).toBe("/"); expect(assertLocalhostRoute("/contact", 4173).pathname).toBe("/contact"); for (const value of ["https://example.com/", "file:///tmp/a", "javascript:alert(1)", "http://192.168.1.1:4173/"]) expect(() => assertLocalhostUrl(value, 4173)).toThrow(FunctionalQaError); });
  it("rejects incomplete runtime, wrong task, missing permission, stale inputs, and invalid workspace", () => { expect(() => validateQaReadiness(readiness({ runtimeValidation: undefined }))).toThrow("Runtime validation"); expect(() => validateQaReadiness(readiness({ task: { ...task(), taskType: "validate-build" } }))).toThrow("READY"); expect(() => validateQaReadiness(readiness({ task: { ...task(), allowedTools: ["filesystem-read"] } }))).toThrow("Playwright"); expect(() => validateQaReadiness(readiness({ actualBriefChecksum: "c".repeat(64) }))).toThrow("stale"); expect(() => validateQaReadiness(readiness({ workspacePath: "C:\\other" }))).toThrow("staging"); });
  it("derives only planned route and approved form scenarios", () => { const brief = { userAcceptanceCriteria: ["Home loads"] , targetAudiences: ["Visitor"] } as unknown as RequirementSpecification; const planning = { sitemap: { routes: [{ id: "home", path: "/", titlePurpose: "Home", intendedUser: "Visitor", primaryGoal: "Learn", requirementReferences: ["requirement:home"], visibility: "public", formDependencies: [] }] }, forms: { forms: [] }, userFlows: { flows: [] }, authentication: { required: false } } as unknown as PlanningPackage; const derived = deriveFunctionalQaPlan({ projectId, projectVersion: 1, brief, planning, briefChecksum: checksum, planningChecksum: checksum, designChecksum: checksum }); expect(derived.scenarios.map((scenario) => scenario.startRoute)).toEqual(["/"]); expect(derived.scenarios.some((scenario) => scenario.startRoute === "/unplanned")).toBe(false); });
  it("runs deterministic local navigation QA and persists a passed QualityCheck", async () => { const browser = new DeterministicFakeBrowserRunner(); const server = new FakeServer(); const report = await new FunctionalQaService(server, browser).run({ projectId, projectVersion: 1, taskId, workspacePath: "C:\\generated\\project\\v1", generatedProjectsRoot: "C:\\generated", runtimeValidation: runtime, plan: plan(), readiness: { ...readiness(), task: task() } }); expect(report.status).toBe("passed"); expect(report.qualityCheck.status).toBe("passed"); expect(report.scenarios[0]?.status).toBe("passed"); expect(browser.operations).toContain("close"); expect(server.handle).toBeUndefined(); });
  it("preserves canonical scenario, route, and step identity when browser dispatch fails", async () => { const canonical = plan(); const scenario = canonical.scenarios[0]!; const tracedPlan = FunctionalQaPlanSchema.parse({ ...canonical, scenarios: [{ ...scenario, scenarioType: "route", steps: scenario.steps.map((step) => ({ ...step, stepId: `route:home:step:${step.order}` })) }] }); const report = await new FunctionalQaService(new FakeServer(), new DeterministicFakeBrowserRunner({ failingAction: "navigate:/" })).run({ projectId, projectVersion: 1, taskId, workspacePath: "C:\\generated\\project\\v1", generatedProjectsRoot: "C:\\generated", runtimeValidation: runtime, plan: tracedPlan, readiness: readiness() }); expect(report.runId).not.toBe(report.scenarios[0]?.scenarioId); expect(report.scenarios[0]).toMatchObject({ scenarioId: "route:home", route: "/", status: "failed" }); expect(report.scenarios[0]?.evidence[0]).toMatchObject({ scenarioId: "route:home", stepId: "route:home:step:1", stepIndex: 0, route: "/", action: "navigate" }); expect(report.diagnostics[0]).toMatchObject({ scenarioId: "route:home", route: "/", stepId: "route:home:step:1" }); });
  it("maps browser/external failures and never records screenshot, HTML, cookies, or tokens", async () => { const browser = new DeterministicFakeBrowserRunner({ externalRequest: true }); const report = await new FunctionalQaService(new FakeServer(), browser).run({ projectId, projectVersion: 1, taskId, workspacePath: "C:\\generated\\project\\v1", generatedProjectsRoot: "C:\\generated", runtimeValidation: runtime, plan: plan(), readiness: readiness() }); expect(report.status).toBe("failed"); expect(report.unexpectedExternalRequests).toHaveLength(1); expect(JSON.stringify(report)).not.toMatch(/screenshot|html|cookie|token/i); });
  it("transitions only the functional QA task and does not execute dependent tasks", async () => { const running = startFunctionalQaTask(task(), "2026-01-01T00:00:00.000Z"); expect(running.status).toBe("running"); const fakeReport = { status: "passed", qualityCheck: { status: "passed" } } as unknown as FunctionalQaReport; expect(completeFunctionalQaTask(running, fakeReport, "2026-01-01T00:01:00.000Z").status).toBe("passed"); });
  it("stores only the bounded Project Memory summary shape", () => { const summary = FunctionalQaMemorySummarySchema.parse({ schemaVersion: 1, documentType: "functional-qa", projectId, projectVersion: 1, createdAt: "2026-01-01T00:00:00.000Z", updatedAt: "2026-01-01T00:00:00.000Z", runId: "66666666-6666-4666-8666-666666666666", status: "passed", passedCount: 1, failedCount: 0, skippedCount: 0, scenarioStatuses: [{ scenarioId: "route:home", status: "passed" }], qualityCheckReference: "quality-report:e2e", runtimeValidationPackageChecksum: checksum, policyVersion: "playwright-functional-v1" }); expect(summary).not.toHaveProperty("html"); expect(summary).not.toHaveProperty("screenshot"); });
  it("restricts the local server script and reconciles stale reports", async () => { expect(() => assertSafeTestServerScript("node server.js")).not.toThrow(); expect(() => assertSafeTestServerScript("npm run build && deploy")).toThrow(); const report = await new FunctionalQaService(new FakeServer(), new DeterministicFakeBrowserRunner()).run({ projectId, projectVersion: 1, taskId, workspacePath: "C:\\generated\\project\\v1", generatedProjectsRoot: "C:\\generated", runtimeValidation: runtime, plan: plan(), readiness: readiness() }); const issues = reconcileFunctionalQa({ report, activeBrowser: false, activeServer: false, qualityCheckPresent: false, currentProjectId: projectId, currentProjectVersion: 1, currentRuntimeValidationPackageChecksum: "c".repeat(64), currentRuntimeValidationLockfileChecksum: runtime.lockfileChecksum, currentBriefChecksum: checksum, currentPlanningChecksum: checksum, currentDesignChecksum: checksum, expectedRuntimeValidationRunId: runtime.validationRunId }); expect(issues.map((issue) => issue.code)).toContain("QA_RECONCILIATION_FAILED"); expect(issues.map((issue) => issue.code)).toContain("QA_PROJECT_STATE_STALE"); });
});
