import { randomUUID } from "node:crypto";
import { FunctionalQaError } from "./errors";
import { FunctionalQaReportSchema, FunctionalQaScenarioResultSchema, FunctionalQaEvidenceSchema, type FunctionalQaScenario, type FunctionalQaServiceInput, type FunctionalQaReport, type FunctionalQaStep, type LocalServerHandle, type LocalServerLauncher, type PlaywrightFunctionalRunner } from "./contracts";
import { validateQaReadiness } from "./policy";
import { NodeLocalTestServer, chooseLoopbackPort, waitForLocalReadiness } from "./server";
import { PlaywrightBrowserRunner } from "./browser";
import { QualityCheckSchema } from "../domain/quality/schema";
import { deriveFunctionalQaDiagnostics } from "./diagnostics";

const repairCategory: Record<string, string> = { QA_ROUTE_MISSING: "ROUTE_REPAIR", QA_ROUTE_RUNTIME_ERROR: "PAGE_COMPONENT_BACKEND_REPAIR", QA_ROUTE_ACCESS_MISMATCH: "AUTHORIZATION_ROUTE_REPAIR", QA_NAVIGATION_BROKEN: "NAVIGATION_REPAIR", QA_FORM_VALIDATION_FAILURE: "FORM_SERVER_ACTION_REPAIR", QA_AUTHORIZATION_FAILURE: "AUTHORIZATION_REPAIR", QA_BROWSER_RUNTIME_ERROR: "PAGE_COMPONENT_BACKEND_REPAIR", QA_EXTERNAL_REQUEST_BLOCKED: "INTEGRATION_SECURITY_REPAIR" };

export class FunctionalQaService {
  constructor(private readonly server: LocalServerLauncher = new NodeLocalTestServer(), private readonly browser: PlaywrightFunctionalRunner = new PlaywrightBrowserRunner()) {}
  async run(input: FunctionalQaServiceInput): Promise<FunctionalQaReport> {
    validateQaReadiness({ projectId: input.projectId, projectVersion: input.projectVersion, workspacePath: input.workspacePath, generatedProjectsRoot: input.generatedProjectsRoot, runtimeValidation: input.runtimeValidation, ...input.readiness });
    const runId = randomUUID(); const startedAt = new Date().toISOString(); const timeout = input.totalTimeoutMs ?? 180000; const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), timeout); const relay = () => controller.abort(); input.signal?.addEventListener("abort", relay, { once: true }); let handle: LocalServerHandle | undefined; let status: FunctionalQaReport["status"] = "passed"; const results: FunctionalQaReport["scenarios"] = []; let browserErrors: FunctionalQaReport["browserErrors"] = [];
    try {
      if (input.signal?.aborted) throw new FunctionalQaError("QA_CANCELLED", "QA was cancelled before server start.");
      const port = await chooseLoopbackPort(); handle = await this.server.start({ workspacePath: input.workspacePath, port, signal: controller.signal }); if (this.server.waitForReady) await this.server.waitForReady(handle, Math.min(timeout, 30000), controller.signal); else await waitForLocalReadiness(handle.baseUrl, handle.port, "/", Math.min(timeout, 30000), controller.signal); await this.browser.launch({ baseUrl: handle.baseUrl, port: handle.port, signal: controller.signal });
      for (const scenario of input.plan.scenarios) { if (controller.signal.aborted) throw new FunctionalQaError(input.signal?.aborted ? "QA_CANCELLED" : "QA_TIMEOUT", "Functional QA was interrupted."); const result = await this.runScenario(scenario, controller.signal); results.push(result); if (result.status === "failed") { status = "failed"; break; } }
      browserErrors = await this.browser.readConsoleErrors(); if (browserErrors.some((error) => !error.approvedNoise)) { status = "failed"; }
      if (input.signal?.aborted) status = "cancelled"; else if (controller.signal.aborted) status = "failed";
    } catch (error) { status = input.signal?.aborted ? "cancelled" : error instanceof FunctionalQaError && error.code === "QA_TIMEOUT" ? "failed" : "failed"; if (error instanceof FunctionalQaError) results.push(this.failedRunResult("__run__", error.code, error.message)); else results.push(this.failedRunResult("__run__", "QA_ASSERTION_FAILED", "Functional QA failed safely.")); }
    finally { clearTimeout(timer); input.signal?.removeEventListener("abort", relay); await this.browser.close().catch(() => undefined); if (handle) { try { await this.server.stop(handle); } catch { status = "failed"; } } }
    const passedCount = results.filter((result) => result.status === "passed").length; const failedCount = results.filter((result) => result.status === "failed").length; const skippedCount = results.filter((result) => result.status === "skipped" || result.status === "cancelled").length; const diagnostics = deriveFunctionalQaDiagnostics({ plan: input.plan, results, browserErrors }); const failure = results.find((result) => result.safeFailureCode)?.safeFailureCode ?? diagnostics[0]?.category ?? browserErrors.find((error) => error.safeErrorCode)?.safeErrorCode; const qualityCheck = QualityCheckSchema.parse({ name: "e2e", status: status === "passed" && failedCount === 0 && results.length === input.plan.scenarios.length ? "passed" : status === "cancelled" ? "skipped" : "failed", startedAt, completedAt: new Date().toISOString(), resultSummary: `${passedCount} passed, ${failedCount} failed, ${skippedCount} skipped functional QA scenarios.`, ...(failure ? { safeFailureCode: failure } : {}), ...(status === "cancelled" ? { skippedReason: "Functional QA was cancelled." } : {}), attempt: 0, required: true, command: "Playwright functional QA" });
    return FunctionalQaReportSchema.parse({ runId, projectId: input.projectId, projectVersion: input.projectVersion, taskId: input.taskId, runtimeValidationRunId: input.runtimeValidation?.validationRunId ?? randomUUID(), startedAt, completedAt: new Date().toISOString(), status: status === "passed" && failedCount === 0 && results.length === input.plan.scenarios.length ? "passed" : status === "cancelled" ? "cancelled" : "failed", scenarios: results, passedCount, failedCount, skippedCount, browserErrors, diagnostics, unexpectedExternalRequests: browserErrors.filter((error) => error.kind === "external-request").map((error) => error.safeSummary), ...(failure ? { failureCategory: `QA_${repairCategory[failure] ? repairCategory[failure].replace(/[^A-Z0-9]+/g, "_") : "FUNCTIONAL_FAILURE"}` } : {}), repairEligible: status !== "passed", qualityCheck, policyVersion: input.plan.policyVersion, runtimeValidationPackageChecksum: input.runtimeValidation?.packageChecksum ?? "0".repeat(64), runtimeValidationLockfileChecksum: input.runtimeValidation?.lockfileChecksum ?? "0".repeat(64), selectedBriefChecksum: input.plan.selectedBriefChecksum, selectedPlanningChecksum: input.plan.selectedPlanningChecksum, selectedDesignChecksum: input.plan.selectedDesignChecksum, warnings: [] });
  }
  private async runScenario(scenario: FunctionalQaScenario, signal: AbortSignal) { const startedAt = new Date().toISOString(); const started = Date.now(); const evidence: FunctionalQaReport["scenarios"][number]["evidence"] = []; try { for (let index = 0; index < scenario.steps.length; index++) { if (signal.aborted) throw new FunctionalQaError("QA_CANCELLED", "Scenario cancelled."); const step = scenario.steps[index]!; const stepStarted = Date.now(); await this.runStep(step, signal); evidence.push(FunctionalQaEvidenceSchema.parse({ scenarioId: scenario.scenarioId, stepIndex: index, action: step.action, result: "passed", route: step.route ?? step.expectedUrl, expectedState: step.expectedText, actualSafeSummary: "Approved functional step passed.", durationMs: Date.now() - stepStarted })); } return FunctionalQaScenarioResultSchema.parse({ scenarioId: scenario.scenarioId, status: "passed", startedAt, completedAt: new Date().toISOString(), durationMs: Date.now() - started, evidence, summary: "Approved functional scenario passed." }); } catch (error) { const code = error instanceof FunctionalQaError ? error.code : scenario.failureCategory; evidence.push(FunctionalQaEvidenceSchema.parse({ scenarioId: scenario.scenarioId, stepIndex: evidence.length, action: scenario.steps[evidence.length]?.action ?? "waitFor", result: "failed", route: scenario.startRoute, actualSafeSummary: "Approved functional scenario failed safely.", durationMs: Date.now() - started, safeErrorCode: code.startsWith("QA_") ? code : scenario.failureCategory })); return FunctionalQaScenarioResultSchema.parse({ scenarioId: scenario.scenarioId, status: "failed", startedAt, completedAt: new Date().toISOString(), durationMs: Date.now() - started, evidence, safeFailureCode: code.startsWith("QA_") ? code : scenario.failureCategory, summary: error instanceof Error ? error.message.slice(0, 1000) : "Functional scenario failed safely." }); } }
  private async runStep(step: FunctionalQaStep, signal: AbortSignal) { if (signal.aborted) throw new FunctionalQaError("QA_CANCELLED", "Functional QA was cancelled."); const b = this.browser; switch (step.action) { case "navigate": await b.navigate(step.route!, step.timeoutMs); break; case "fill": await b.fill(step.selector!, step.value ?? "", step.timeoutMs); break; case "click": await b.click(step.selector!, step.timeoutMs); break; case "submit": await b.submit(step.selector!, step.timeoutMs); break; case "select": await b.select(step.selector!, step.value ?? "", step.timeoutMs); break; case "check": await b.check(step.selector!, step.timeoutMs); break; case "waitFor": await b.waitFor({ selector: step.selector, timeoutMs: step.timeoutMs }); break; case "assertText": await b.assertText(step.selector!, step.expectedText!, step.timeoutMs); break; case "assertVisible": await b.assertVisible(step.selector!, step.timeoutMs); break; case "assertUrl": await b.assertUrl(step.expectedUrl ?? step.route!); break; case "assertStatus": await b.assertStatus(step.expectedStatus!); break; } }
  private failedRunResult(scenarioId: string, code: string, summary: string) { const now = new Date().toISOString(); return FunctionalQaScenarioResultSchema.parse({ scenarioId, status: "failed", startedAt: now, completedAt: now, durationMs: 0, evidence: [], safeFailureCode: code.startsWith("QA_") ? code : "QA_ASSERTION_FAILED", summary }); }
}

export const createFunctionalQaService = () => new FunctionalQaService();
