import { z } from "zod";
import { RuntimeDiagnosticReferenceSchema } from "@/runtime/validation/contracts";
import { DocumentBaseSchema, IsoDateTimeSchema, NonEmptyStringSchema, ProjectVersionSchema, UuidSchema } from "../shared/schemas";
import { CapabilityIdSchema } from "@/domain/tooling/schema";
import { ImplementationDomainSchema, ImplementationSpecialistIdSchema } from "@/domain/implementation/profiles";
import { ArchitectureCriticResultSchema, ThreatModelResultSchema } from "@/domain/assurance/contracts";

export const TaskRoleSchema = z.enum(["lead", "planner-architect", "design", "implementation", "qa-release"]);
export const TaskStatusSchema = z.enum(["pending", "blocked", "ready", "running", "passed", "failed", "cancelled"]);
export const TaskExecutionModeSchema = z.enum(["sequential", "parallel-safe", "exclusive-write", "validation-only"]);
export const ImplementationTaskTypeSchema = z.enum(["prepare-workspace", "implement-project-foundation", "implement-design-system", "implement-shared-layout", "implement-navigation", "implement-page", "implement-shared-component", "implement-form", "implement-server-action", "implement-route-handler", "implement-database-schema", "implement-rls-policy", "write-database-tests", "implement-authentication", "implement-storage", "implement-email", "integrate-assets", "integrate-content", "implement-seo", "implement-motion", "write-unit-tests", "write-integration-tests", "write-e2e-tests", "validate-lint", "validate-typecheck", "validate-unit-tests", "validate-build", "validate-database", "validate-security", "validate-functional-flow", "repair-targeted-failure", "prepare-release", "review-architecture", "review-contracts", "review-code-integration", "review-browser-qa", "review-security", "review-accessibility", "review-performance", "review-visual-regression", "review-code", "review-test-quality", "review-release-readiness", "review-seo", "review-content-quality", "review-dependencies", "review-documentation", "review-security-threat-model", "review-security-test", "review-german-web-compliance", "review-exploratory-qa", "review-ux-critic", "review-product-critic", "review-architecture-critic", "review-design", "review-animation", "audit-animation", "find-animation-opportunities"]);
export const TaskContractBindingSchema = z.object({ taskContractId: UuidSchema, taskContractChecksum: z.string().regex(/^[a-f0-9]{64}$/), dataContractIds: z.array(UuidSchema), databaseDecisionId: UuidSchema.optional(), databaseDecisionChecksum: z.string().regex(/^[a-f0-9]{64}$/).optional(), dependencyProposalId: UuidSchema.optional() }).strict();
export const AgentTaskSchema = z.object({ id: UuidSchema, projectId: UuidSchema, projectVersion: ProjectVersionSchema, role: TaskRoleSchema, taskType: NonEmptyStringSchema, title: NonEmptyStringSchema, objective: NonEmptyStringSchema, implementationDomain: ImplementationDomainSchema.optional(), specialistProfileId: ImplementationSpecialistIdSchema.optional(), requirementReferences: z.array(NonEmptyStringSchema).optional(), planningReferences: z.array(NonEmptyStringSchema).optional(), selectedDesignReferences: z.array(NonEmptyStringSchema).optional(), inputs: z.array(NonEmptyStringSchema), expectedOutputs: z.array(NonEmptyStringSchema), acceptanceCriteria: z.array(NonEmptyStringSchema).optional(), allowedSkills: z.array(NonEmptyStringSchema), allowedTools: z.array(NonEmptyStringSchema), deniedTools: z.array(NonEmptyStringSchema).optional(), requiredCapabilities: z.array(CapabilityIdSchema).optional(), fileScopes: z.array(NonEmptyStringSchema), requiredArtifacts: z.array(NonEmptyStringSchema).optional(), requiredArtifactCount: z.number().int().positive().optional(), taskAcceptancePolicyVersion: z.string().min(1).optional(), dependencies: z.array(UuidSchema), status: TaskStatusSchema, priority: z.enum(["low", "normal", "high", "critical"]).optional(), executionMode: TaskExecutionModeSchema.optional(), parallelGroup: NonEmptyStringSchema.optional(), attempt: z.number().int().nonnegative(), maxAttempts: z.number().int().positive(), repairOfTaskId: UuidSchema.optional(), repairIdentity: z.string().min(1).optional(), createdAt: IsoDateTimeSchema, startedAt: IsoDateTimeSchema.optional(), completedAt: IsoDateTimeSchema.optional(), safeFailureCode: z.string().regex(/^[A-Z0-9_]+$/).optional(), validationDiagnosticCount: z.number().int().nonnegative().optional(), validationDiagnostics: z.array(RuntimeDiagnosticReferenceSchema).max(50).optional(), validationDiagnosticPolicyVersion: z.string().min(1).optional(), validationSourceChecksum: z.string().regex(/^[a-f0-9]{64}$/).optional(), validationPlanChecksum: z.string().regex(/^[a-f0-9]{64}$/).optional(), validationReplayCount: z.number().int().nonnegative().max(1).optional(), validationReplayIdentity: z.string().min(1).optional(), validationReplayPolicyVersion: z.string().min(1).optional(), validationReplayBaseAttempt: z.number().int().nonnegative().optional(), validationReplayKind: z.enum(["evidence-refresh", "policy-refresh"]).optional(), blockingFailure: z.boolean().optional(), estimatedContextBytes: z.number().int().positive().optional(), expectedArtifactTypes: z.array(NonEmptyStringSchema).optional(), phase7c: TaskContractBindingSchema.optional() }).strict().superRefine((task, context) => {
  if (task.status === "running" && !task.startedAt) context.addIssue({ code: "custom", path: ["startedAt"], message: "Running tasks require startedAt" });
  if (["passed", "failed", "cancelled"].includes(task.status) && !task.completedAt) context.addIssue({ code: "custom", path: ["completedAt"], message: "Completed tasks require completedAt" });
  if (task.attempt > task.maxAttempts && !((task.validationReplayKind && task.validationReplayCount === 1 && task.validationReplayBaseAttempt !== undefined && task.attempt <= task.validationReplayBaseAttempt + 1) || (!task.validationReplayKind && task.validationReplayCount === 1 && task.attempt <= task.maxAttempts + 2))) context.addIssue({ code: "custom", path: ["attempt"], message: "Attempt exceeds maxAttempts" });
});
export const TaskGraphSchema = DocumentBaseSchema.extend({ documentType: z.literal("task-graph"), tasks: z.array(AgentTaskSchema), graphChecksum: z.string().regex(/^[a-f0-9]{64}$/).optional(), orchestrationPolicyVersion: z.string().min(1).optional(), toolPolicyVersion: z.string().min(1).optional(), approvedSkillSnapshotChecksum: z.string().regex(/^[a-f0-9]{64}$/).optional(), sourceDocumentChecksums: z.record(z.string(), z.string().regex(/^[a-f0-9]{64}$/)).optional(), securityThreatModel: ThreatModelResultSchema.optional(), architectureCritic: ArchitectureCriticResultSchema.optional(), phase7cContractPackageChecksum: z.string().regex(/^[a-f0-9]{64}$/).optional(), databaseDecisionChecksum: z.string().regex(/^[a-f0-9]{64}$/).optional(), validation: z.object({ valid: z.boolean(), errors: z.array(NonEmptyStringSchema), warnings: z.array(NonEmptyStringSchema) }).strict().optional(), checkpoint: z.enum(["inputs-validated", "graph-created", "graph-validated", "workspace-reserved", "execution-ready", "implementation-started", "implementation-complete", "validation-started", "repair-required", "release-ready"]).optional(), readyForExecution: z.boolean().optional(), blockingReasons: z.array(NonEmptyStringSchema).optional(), warnings: z.array(NonEmptyStringSchema).optional() }).strict().superRefine((graph, context) => {
  if (graph.securityThreatModel && graph.sourceDocumentChecksums?.architecture && graph.securityThreatModel.architectureChecksum !== graph.sourceDocumentChecksums.architecture) context.addIssue({ code: "custom", path: ["securityThreatModel", "architectureChecksum"], message: "Security threat evidence must bind to the TaskGraph architecture checksum." });
  if (graph.architectureCritic && graph.sourceDocumentChecksums?.architecture && graph.architectureCritic.architectureChecksum !== graph.sourceDocumentChecksums.architecture) context.addIssue({ code: "custom", path: ["architectureCritic", "architectureChecksum"], message: "Architecture critic evidence must bind to the TaskGraph architecture checksum." });
  const ids = new Set<string>();
  const taskIds = new Set(graph.tasks.map((task) => task.id));
  for (const task of graph.tasks) {
    if (ids.has(task.id)) context.addIssue({ code: "custom", path: ["tasks"], message: "Task IDs must be unique" });
    ids.add(task.id);
    if (task.dependencies.includes(task.id)) context.addIssue({ code: "custom", path: ["tasks"], message: "Task cannot depend on itself" });
    for (const dependency of task.dependencies) if (!taskIds.has(dependency)) context.addIssue({ code: "custom", path: ["tasks"], message: "Task dependency does not exist" });
  }
  const visiting = new Set<string>(); const visited = new Set<string>();
  const visit = (id: string) => { if (visiting.has(id)) return true; if (visited.has(id)) return false; visiting.add(id); const task = graph.tasks.find((candidate) => candidate.id === id); const cycle = task?.dependencies.some(visit) ?? false; visiting.delete(id); visited.add(id); return cycle; };
  if (graph.tasks.some((task) => visit(task.id))) context.addIssue({ code: "custom", path: ["tasks"], message: "Task graph contains a dependency cycle" });
});
export type AgentTask = z.infer<typeof AgentTaskSchema>;
export type TaskGraph = z.infer<typeof TaskGraphSchema>;
