import OpenAI from "openai";
import { z, type ZodType } from "zod";
import { zodResponseFormat } from "openai/helpers/zod";
import { AiProviderError } from "./errors";
import { FifoConcurrencyLimiter } from "./limiter";
import type { AiProviderConfig } from "./config";
import type { ProviderEventSink, ProviderUsage, ProviderUsageSink } from "./usage";

export type StructuredRequest<T> = { role: string; promptVersion: string; system: string; user: string; schemaName: string; schema: ZodType<T>; signal?: AbortSignal; idempotencyKey?: string };
export type StructuredResponse<T> = { value: T; usage: ProviderUsage; requestId: string };
export type StructuredExecutor = <T>(request: StructuredRequest<T>, client: OpenAI, config: AiProviderConfig, correction: boolean) => Promise<{ value: T; requestId: string; inputTokens?: number; cachedInputTokens?: number; outputTokens?: number }>;

export class OpenAiStructuredClient {
  private readonly client: OpenAI; private readonly limiter: FifoConcurrencyLimiter; private readonly inFlight = new Map<string, Promise<StructuredResponse<unknown>>>();
  constructor(private readonly config: AiProviderConfig, options: { client?: OpenAI; executor?: StructuredExecutor; usageSink?: ProviderUsageSink; eventSink?: ProviderEventSink } = {}) { this.client = options.client ?? new OpenAI({ apiKey: config.apiKey, timeout: config.timeoutMs, maxRetries: 0 }); this.executor = options.executor ?? defaultExecutor; this.limiter = new FifoConcurrencyLimiter(config.maxConcurrentRequests); this.usageSink = options.usageSink; this.eventSink = options.eventSink; }
  private readonly executor: StructuredExecutor; private readonly usageSink?: ProviderUsageSink; private readonly eventSink?: ProviderEventSink;
  request<T>(request: StructuredRequest<T>): Promise<StructuredResponse<T>> {
    if (request.idempotencyKey) { const existing = this.inFlight.get(request.idempotencyKey); if (existing) return existing.then((value) => value as StructuredResponse<T>); }
    const promise = this.limiter.run(() => this.execute(request), request.signal) as Promise<StructuredResponse<unknown>>;
    if (request.idempotencyKey) { this.inFlight.set(request.idempotencyKey, promise); void promise.then(() => this.inFlight.delete(request.idempotencyKey!), () => this.inFlight.delete(request.idempotencyKey!)); }
    return promise as Promise<StructuredResponse<T>>;
  }
  private async execute<T>(request: StructuredRequest<T>): Promise<StructuredResponse<T>> {
    let retries = 0; let correction = false; this.eventSink?.({ type: "request.started", provider: "openai", model: this.config.model, role: request.role, promptVersion: request.promptVersion });
    try { while (true) { if (request.signal?.aborted) throw new AiProviderError("AI_REQUEST_CANCELLED", "AI request was cancelled."); try { const result = await withTimeout(this.executor(request, this.client, this.config, correction), this.config.timeoutMs, request.signal); const usage: ProviderUsage = { inputTokens: result.inputTokens ?? 0, cachedInputTokens: result.cachedInputTokens ?? 0, outputTokens: result.outputTokens ?? 0, totalTokens: (result.inputTokens ?? 0) + (result.outputTokens ?? 0), requestCount: 1, retryCount: retries, correctionCount: correction ? 1 : 0, provider: "openai", model: this.config.model, role: request.role, promptVersion: request.promptVersion }; await this.usageSink?.(usage); this.eventSink?.({ type: "request.completed", provider: "openai", model: this.config.model, role: request.role, promptVersion: request.promptVersion, requestId: result.requestId, retryCount: retries }); return { value: result.value, usage, requestId: result.requestId }; } catch (error) { const mapped = mapError(error); if (mapped.code === "AI_OUTPUT_SCHEMA_MISMATCH" && !correction) { correction = true; continue; } if (isRetryable(mapped) && retries < this.config.maxRetries) { retries++; continue; } this.eventSink?.({ type: "request.failed", provider: "openai", model: this.config.model, role: request.role, promptVersion: request.promptVersion, code: mapped.code, retryCount: retries }); throw retries ? new AiProviderError("AI_RETRY_EXHAUSTED", "AI provider retries were exhausted.", mapped) : mapped; } } } catch (error) { throw mapError(error); }
  }
}
async function defaultExecutor<T>(request: StructuredRequest<T>, client: OpenAI, config: AiProviderConfig, correction: boolean) { const responseSchema = request.schema as unknown as Parameters<typeof zodResponseFormat>[0]; const completion = await client.chat.completions.parse({ model: config.model, temperature: 0, messages: [{ role: "system", content: `${request.system}${correction ? "\nCorrect the previous structured-output formatting." : ""}` }, { role: "user", content: request.user }], response_format: zodResponseFormat(responseSchema, request.schemaName), ...(request.signal ? { signal: request.signal } : {}) }); const message = completion.choices[0]?.message; if (message?.refusal) throw new AiProviderError("AI_OUTPUT_REFUSED", "The provider refused the structured request."); if (completion.choices[0]?.finish_reason === "length") throw new AiProviderError("AI_OUTPUT_TRUNCATED", "The provider output was truncated."); if (!message?.parsed) throw new AiProviderError("AI_OUTPUT_SCHEMA_MISMATCH", "The provider did not return the requested schema."); const value = request.schema.parse(message.parsed); return { value, requestId: completion.id, inputTokens: completion.usage?.prompt_tokens, cachedInputTokens: completion.usage?.prompt_tokens_details?.cached_tokens ?? 0, outputTokens: completion.usage?.completion_tokens } as const; }
function isRetryable(error: AiProviderError) { return ["AI_PROVIDER_UNAVAILABLE", "AI_RATE_LIMITED", "AI_REQUEST_TIMEOUT"].includes(error.code); }
function mapError(error: unknown): AiProviderError { if (error instanceof AiProviderError) return error; if (error instanceof z.ZodError) return new AiProviderError("AI_OUTPUT_SCHEMA_MISMATCH", "Provider output failed schema validation.", error); const status = typeof error === "object" && error && "status" in error ? Number(error.status) : 0; if (status === 401 || status === 403) return new AiProviderError("AI_AUTHENTICATION_FAILED", "AI provider authentication failed."); if (status === 429) return new AiProviderError("AI_RATE_LIMITED", "AI provider rate limit reached."); if (status >= 500) return new AiProviderError("AI_PROVIDER_UNAVAILABLE", "AI provider is unavailable."); return new AiProviderError("AI_OUTPUT_INVALID", "AI provider request failed safely.", error); }
async function withTimeout<T>(promise: Promise<T>, timeoutMs: number, signal?: AbortSignal): Promise<T> { let timer: ReturnType<typeof setTimeout> | undefined; const timeout = new Promise<never>((_, reject) => { timer = setTimeout(() => reject(new AiProviderError("AI_REQUEST_TIMEOUT", "AI provider request timed out.")), timeoutMs); }); try { if (signal) { if (signal.aborted) throw new AiProviderError("AI_REQUEST_CANCELLED", "AI request was cancelled."); return await Promise.race([promise, timeout, new Promise<never>((_, reject) => signal.addEventListener("abort", () => reject(new AiProviderError("AI_REQUEST_CANCELLED", "AI request was cancelled.")), { once: true }))]); } return await Promise.race([promise, timeout]); } finally { if (timer) clearTimeout(timer); } }

