import { DocumentRepository, ProjectRepository, WorkflowPersistenceService } from "@/persistence/database/repositories";
import type { PersistenceDatabase } from "@/persistence/database/types";
import type { TestQualityReviewInput } from "@/agents/reviewers/test-quality/contracts";
import { TestQualityReviewService } from "@/agents/reviewers/test-quality/service";

export class TestQualityReviewOrchestrationService {
  private readonly workflow: WorkflowPersistenceService; private readonly projects: ProjectRepository; private readonly documents: DocumentRepository;
  constructor(private readonly database: PersistenceDatabase, private readonly reviewer = new TestQualityReviewService(database)) { this.workflow = new WorkflowPersistenceService(database); this.projects = new ProjectRepository(database); this.documents = new DocumentRepository(database); }
  get reviewerService() { return this.reviewer; }
  async enterReview(input: { projectId: string; projectVersion: number; expectedRowVersion: number; idempotencyKey: string }) { const current = await this.projects.getWithVersion(input.projectId); if (!current || current.project.workflowState === "TEST_QUALITY_REVIEW") return { rowVersion: current?.rowVersion ?? input.expectedRowVersion, projectState: "TEST_QUALITY_REVIEW" as const }; const transition = await this.workflow.transition({ projectId: input.projectId, projectVersion: input.projectVersion, expectedState: current.project.workflowState === "SECURITY_REVIEW" ? "SECURITY_REVIEW" : "VALIDATING", expectedRowVersion: input.expectedRowVersion, targetState: "TEST_QUALITY_REVIEW", actor: "orchestrator", reason: "Deterministic quality evidence is current; Test / Quality Review is required before release qualification.", idempotencyKey: input.idempotencyKey }); return { rowVersion: transition.rowVersion, projectState: "TEST_QUALITY_REVIEW" as const }; }
  async reviewAndRoute(input: TestQualityReviewInput, signal?: AbortSignal) { const result = await this.reviewer.review(input, signal); const current = await this.projects.getWithVersion(input.projectId); if (result.verdict !== "APPROVED" || !current || current.project.workflowState !== "TEST_QUALITY_REVIEW") return { result, projectState: current?.project.workflowState ?? "TEST_QUALITY_REVIEW", rowVersion: current?.rowVersion ?? input.expectedRowVersion }; const transition = await this.workflow.transition({ projectId: input.projectId, projectVersion: input.projectVersion, expectedState: "TEST_QUALITY_REVIEW", expectedRowVersion: current.rowVersion, targetState: "VALIDATING", actor: "test-quality-reviewer", reason: "Current Test / Quality Review approved meaningful verification evidence.", idempotencyKey: `${input.idempotencyKey}:approved` }); return { result, projectState: "VALIDATING" as const, rowVersion: transition.rowVersion }; }
  async getCurrentReview(projectId: string, projectVersion: number, sourceChecksum: string, testSourceChecksum: string, qualityEvidenceChecksum?: string) { return this.reviewer.getCurrentReview(projectId, projectVersion, sourceChecksum, testSourceChecksum, qualityEvidenceChecksum); }
  async getExecutionSummary(projectId: string, projectVersion: number) { return this.documents.get(projectId, projectVersion, "full-execution"); }
}
