import { randomUUID } from "node:crypto";
import { describe, expect, it } from "vitest";
import { DesignDirectionSetSchema } from "../domain/design/schema";
import { FactoryProjectSchema } from "../domain/project/schema";
import { RequirementSpecificationSchema, type RequirementSpecification } from "../domain/requirements/schema";
import { resolveLogoPolicy } from "../domain/requirements/logo-policy";
import { DocumentRepository, ProjectRepository, ProjectVersionRepository } from "../persistence/repositories";
import { InMemoryPersistenceDatabase } from "../persistence/fake";
import { checksumPersistedDocument } from "../persistence/serialization";
import { buildPlanningPackage } from "../planner/deterministic";
import type { PlannerAgentInput } from "../planner/contracts";
import { DesignAgentInputSchema, type DesignAgentInput } from "./contracts";
import { DesignError } from "./errors";
import { buildDesignDirectionSet, directionChecksum, directionSetChecksum, validateDesignDirectionSet } from "./deterministic";
import { DesignAgentService } from "./service";
import { FakeDesignMemoryPort } from "./memory";

const id = () => randomUUID();
const brief = (overrides: Partial<RequirementSpecification> = {}): RequirementSpecification => RequirementSpecificationSchema.parse({ schemaVersion: 1, documentType: "requirements", projectId: id(), projectVersion: 1, createdAt: "2026-01-01T00:00:00.000Z", updatedAt: "2026-01-01T00:00:00.000Z", projectSummary: "Serve local customers", protectedFunctionalityRequired: false, imagesRequired: true, businessGoals: ["Serve local customers"], targetAudiences: ["Visitors"], pages: [{ slug: "home", purpose: "Introduce the business" }, { slug: "contact", purpose: "Receive inquiries" }], userRoles: [], features: ["Contact form"], forms: ["Contact form"], contentRequirements: [], backendRequirements: [], supabaseRequirements: [], authenticationDecision: "no-authentication-guest-first", storageDecision: "not-needed", emailDecision: "not-needed", administrationDecision: "not-needed", seoRequirements: [], localization: { locales: ["en"], defaultLocale: "en" }, imageSourceDecision: "ai-generated", suppliedBrandInformation: { status: "missing" }, suppliedLogoLocation: { status: "missing" }, technicalConstraints: [], explicitExclusions: [], userAcceptanceCriteria: ["Visitors can submit an inquiry"], unresolvedItems: [], approval: { approved: true, approvedAt: "2026-01-01T00:00:00.000Z", approvedBy: "user", approvedRequirementsChecksum: "a".repeat(64) }, contactFacts: [], legalFacts: [], brandFacts: [], logoMetadata: [], imageSourcingNotes: [], evidence: [], recommendations: [], briefStatus: "approved", briefVersion: 1, ...overrides });
const plannerInput = (value: RequirementSpecification): PlannerAgentInput => ({ projectId: value.projectId, projectVersion: 1, approvedBrief: value, approvedBriefChecksum: checksumPersistedDocument(value), originalPromptReference: "original-prompt.md", clarificationEvidenceReferences: ["clarification-log.json"], currentWorkflowState: "AWAITING_DESIGN_SELECTION", existingDecisions: [], suppliedFiles: [], allowedSkills: [], idempotencyKey: "planner-fixture", expectedRowVersion: 1 });
const designInput = (value: RequirementSpecification, key = "design-fixture"): DesignAgentInput => { const planning = buildPlanningPackage(plannerInput(value)); const accepted = { ...planning, accepted: true, acceptance: { acceptedAt: "2026-01-01T00:00:00.000Z", acceptedBy: "user", checksum: checksumPersistedDocument(planning) }, architecture: { ...planning.architecture, acceptance: { accepted: true, acceptedAt: "2026-01-01T00:00:00.000Z", acceptedBy: "user" } } }; return DesignAgentInputSchema.parse({ projectId: value.projectId, projectVersion: 1, approvedBrief: value, approvedBriefChecksum: checksumPersistedDocument(value), acceptedPlanningPackage: accepted, acceptedPlanningChecksum: checksumPersistedDocument(accepted), contentPlan: accepted.content, assetManifest: accepted.assets, suppliedBrandMetadata: {}, suppliedLogoMetadata: value.suppliedLogoLocation, imageSourceDecision: value.imageSourceDecision, designPreferences: [], explicitDesignExclusions: [], currentWorkflowState: "AWAITING_DESIGN_SELECTION", existingDecisions: [], allowedSkills: [], idempotencyKey: key, expectedRowVersion: 1 }); };

describe("Design Agent workflow", () => {
  it("creates exactly three meaningfully different directions", () => { const input = designInput(brief()); const set = buildDesignDirectionSet(input); expect(set.directions).toHaveLength(3); expect(new Set(set.directions.map((direction) => direction.label)).size).toBe(3); expect(validateDesignDirectionSet(input, set).readyForSelection).toBe(true); expect(new Set(set.directions.map((direction) => direction.layoutStrategy)).size).toBe(3); });
  it("preserves image source, logo boundary, motion, and responsive planning", () => { const input = designInput(brief({ imagesRequired: true, imageSourceDecision: "user-supplied", suppliedLogoLocation: { status: "provided", value: "assets/logo.svg" }, brandFacts: ["Blue brand identity"] })); const set = buildDesignDirectionSet(input); expect(set.directions.every((direction) => /supplied/i.test(direction.imageArtDirectionDetails?.subjectCharacter ?? ""))).toBe(true); expect(set.directions.every((direction) => /supplied user logo/i.test(direction.logoUsageRules ?? ""))).toBe(true); expect(set.directions.every((direction) => direction.motionDetails && direction.responsiveDetails)).toBe(true); });
  it("blocks missing required logo and pending image source", () => { const logoInput = designInput(brief({ brandFacts: ["Known brand"], suppliedLogoLocation: { status: "missing" } })); expect(validateDesignDirectionSet(logoInput, buildDesignDirectionSet(logoInput)).blockingReasons).toContain("LOGO_FILE_MISSING"); const imageInput = designInput(brief({ imageSourceDecision: "pending" })); expect(validateDesignDirectionSet(imageInput, buildDesignDirectionSet(imageInput)).blockingReasons).toContain("IMAGE_SOURCE_PENDING"); });
  it("does not treat explicit no-logo fixture facts as supplied branding", () => { const input = designInput(brief({ brandFacts: ["No logo was supplied"], suppliedLogoLocation: { status: "missing" } })); expect(validateDesignDirectionSet(input, buildDesignDirectionSet(input)).blockingReasons).not.toContain("LOGO_FILE_MISSING"); });
  it("accepts a text wordmark without a logo file and preserves its policy", () => { const value = brief({ projectTitle: "VeloFix Werkstatt", logoMetadata: ["Use a text wordmark"], suppliedLogoLocation: { status: "missing" } }); expect(resolveLogoPolicy(value)).toEqual({ mode: "TEXT_WORDMARK", wordmarkText: "VeloFix Werkstatt" }); const input = designInput(value); const set = buildDesignDirectionSet(input); expect(validateDesignDirectionSet(input, set).blockingReasons).not.toContain("LOGO_FILE_MISSING"); });
  it("keeps missing-file blocking for an explicitly supplied logo strategy", async () => { const value = brief({ brandFacts: ["Known brand identity"], suppliedLogoLocation: { status: "missing" } }); expect(resolveLogoPolicy(value).mode).toBe("USER_SUPPLIED_LOGO"); const input = designInput(value); await expect(new DesignAgentService({ database: new InMemoryPersistenceDatabase(), memory: new FakeDesignMemoryPort() }).generateDesignDirections(input)).rejects.toMatchObject({ code: "LOGO_FILE_MISSING" }); });
  it("rejects color-only superficial differentiation", () => { const input = designInput(brief()); const set = buildDesignDirectionSet(input); const similar = DesignDirectionSetSchema.parse({ ...set, directions: set.directions.map((_, index) => ({ ...set.directions[0], id: id(), colorStrategy: `variant ${index}`, label: `Variant ${index}` })) }); expect(validateDesignDirectionSet(input, similar).blockingReasons).toContain("DESIGN_DIRECTIONS_TOO_SIMILAR"); });
  it("rejects direction counts other than three", () => { const input = designInput(brief()); const set = buildDesignDirectionSet(input); expect(() => DesignDirectionSetSchema.parse({ ...set, directions: set.directions.slice(0, 2) })).toThrow(); expect(() => DesignDirectionSetSchema.parse({ ...set, directions: [...set.directions, { ...set.directions[0], id: id(), label: "Fourth" }] })).toThrow(); });
  it("rejects provider sets with insufficient differentiation before persistence", async () => { const value = brief({ imagesRequired: false }); const input = designInput(value); const database = new InMemoryPersistenceDatabase(); const memory = new FakeDesignMemoryPort(); const project = FactoryProjectSchema.parse({ schemaVersion: 1, documentType: "factory-project", projectId: value.projectId, projectVersion: 1, createdAt: "2026-01-01T00:00:00.000Z", updatedAt: "2026-01-01T00:00:00.000Z", id: value.projectId, slug: "invalid-design-fixture", originalPrompt: "Design fixture", currentVersion: 1, workflowState: "AWAITING_DESIGN_SELECTION" }); await new ProjectRepository(database).create(project); await new ProjectVersionRepository(database).create({ id: id(), projectId: value.projectId, versionNumber: 1, state: "AWAITING_DESIGN_SELECTION", memoryRootPath: null, requirementsChecksum: null, selectedDesignChecksum: null, architectureChecksum: null, releasedAt: null, immutable: false, createdAt: project.createdAt, updatedAt: project.updatedAt, rowVersion: 1 }); await new DocumentRepository(database).save(value); await new DocumentRepository(database).save(input.acceptedPlanningPackage); const valid = buildDesignDirectionSet(input); const duplicateContent = DesignDirectionSetSchema.parse({ ...valid, directions: valid.directions.map((direction, index) => ({ ...valid.directions[0], id: index === 0 ? valid.directions[0].id : id(), label: `Distinct label ${index}` })) }); const service = new DesignAgentService({ database, memory, provider: { proposeDesignDirections: async () => duplicateContent } }); await expect(service.generateDesignDirections(input)).rejects.toMatchObject({ code: "DESIGN_DIRECTIONS_TOO_SIMILAR" }); expect(await new DocumentRepository(database).get(value.projectId, 1, "design-directions")).toBeNull(); expect(memory.documents.get(`${value.projectId}:1`)?.["design-directions.json"]).toBeUndefined(); });
  it("uses deterministic checksums and direction membership", () => { const input = designInput(brief()); const first = buildDesignDirectionSet(input); const second = buildDesignDirectionSet(input); expect(directionSetChecksum(first)).toBe(directionSetChecksum(second)); expect(directionChecksum(first.directions[0])).toMatch(/^[a-f0-9]{64}$/); });
  it("does not select automatically and persists explicit user selection", async () => { const database = new InMemoryPersistenceDatabase(); const memory = new FakeDesignMemoryPort(); const value = brief({ imagesRequired: false }); const project = FactoryProjectSchema.parse({ schemaVersion: 1, documentType: "factory-project", projectId: value.projectId, projectVersion: 1, createdAt: "2026-01-01T00:00:00.000Z", updatedAt: "2026-01-01T00:00:00.000Z", id: value.projectId, slug: "design-fixture", originalPrompt: "Design fixture", currentVersion: 1, workflowState: "AWAITING_DESIGN_SELECTION" }); await new ProjectRepository(database).create(project); await new ProjectVersionRepository(database).create({ id: id(), projectId: value.projectId, versionNumber: 1, state: "AWAITING_DESIGN_SELECTION", memoryRootPath: null, requirementsChecksum: null, selectedDesignChecksum: null, architectureChecksum: null, releasedAt: null, immutable: false, createdAt: project.createdAt, updatedAt: project.updatedAt, rowVersion: 1 }); const input = designInput(value); const planning = input.acceptedPlanningPackage; await new DocumentRepository(database).save(value); await new DocumentRepository(database).save(planning); const service = new DesignAgentService({ database, memory }); const generated = await service.generateDesignDirections(input); expect(memory.documents.get(`${value.projectId}:1`)?.["selected-design.json"]).toBeUndefined(); const selected = await service.selectDesignDirection({ projectId: value.projectId, projectVersion: 1, designDirectionSetId: generated.directionSet.setId, selectedDirectionId: generated.directionSet.directions[1].id, directionSetChecksum: generated.readiness.directionSetChecksum, selectedDirectionChecksum: directionChecksum(generated.directionSet.directions[1]!), expectedRowVersion: 1, selectedBy: "user", selectedAt: "2026-01-01T00:00:00.000Z", selectionNotes: "Preferred direction", idempotencyKey: "selection-1" }); expect(selected.projectState).toBe("READY_FOR_IMPLEMENTATION"); expect(memory.documents.get(`${value.projectId}:1`)?.["selected-design.json"]).toBeTruthy(); });
  it("regenerates directions, supersedes the prior set, and invalidates selection", async () => { const database = new InMemoryPersistenceDatabase(); const memory = new FakeDesignMemoryPort(); const value = brief({ imagesRequired: false }); const project = FactoryProjectSchema.parse({ schemaVersion: 1, documentType: "factory-project", projectId: value.projectId, projectVersion: 1, createdAt: "2026-01-01T00:00:00.000Z", updatedAt: "2026-01-01T00:00:00.000Z", id: value.projectId, slug: "revision-fixture", originalPrompt: "Design revision fixture", currentVersion: 1, workflowState: "AWAITING_DESIGN_SELECTION" }); await new ProjectRepository(database).create(project); await new ProjectVersionRepository(database).create({ id: id(), projectId: value.projectId, versionNumber: 1, state: "AWAITING_DESIGN_SELECTION", memoryRootPath: null, requirementsChecksum: null, selectedDesignChecksum: null, architectureChecksum: null, releasedAt: null, immutable: false, createdAt: project.createdAt, updatedAt: project.updatedAt, rowVersion: 1 }); const input = designInput(value, "first-generation"); await new DocumentRepository(database).save(value); await new DocumentRepository(database).save(input.acceptedPlanningPackage); const service = new DesignAgentService({ database, memory }); const first = await service.generateDesignDirections(input); const revised = await service.regenerateDesignDirections({ projectId: value.projectId, projectVersion: 1, reason: "User rejected all directions", requestedBy: "user", idempotencyKey: "second-generation" }); expect(revised.directionSet.setId).not.toBe(first.directionSet.setId); expect(revised.directionSet.supersedesSetId).toBe(first.directionSet.setId); expect(memory.documents.get(`${value.projectId}:1`)?.["selected-design.json"]).toBeUndefined(); });
  it("safe errors do not expose full brief contents", () => { const error = new DesignError("DESIGN_BLOCKED", "Design is blocked."); expect(JSON.stringify({ code: error.code, message: error.message })).not.toContain("Serve local customers"); });
});
