import { randomUUID } from "node:crypto";
import { constants } from "node:fs";
import { chmod, copyFile, lstat, mkdir, open, readFile, readdir, rename, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { FactoryProjectSchema, type FactoryProject } from "../domain/project/schema";
import { DecisionRecordSchema } from "../domain/workflow/decision";
import { ProjectMemoryStore } from "../project-memory/store";
import { CANONICAL_DOCUMENT_NAMES, type StructuredDocumentName } from "../project-memory/filenames";
import type { ProjectVersionRow } from "../persistence/types";
import { WorkspaceError } from "./errors";
import { OperationIdSchema, WorkspaceProjectMetadataSchema, WorkspaceRootSchema, WorkspaceSlugSchema, normalizeWorkspaceRoot, versionDirectoryName, type WorkspaceProjectMetadata } from "./schemas";
import type { WorkspaceDecisionPort, WorkspaceVersionPort } from "./ports";

type WorkspaceOptions = { root: string; versions: WorkspaceVersionPort; decisions?: WorkspaceDecisionPort; testMode?: boolean; configuredProductionRoot?: string };
type VersionCreationOptions = { documents?: Record<string, unknown>; operationId?: string; idempotencyKey?: string };
export type ReconciliationIssue = { code: string; description: string; recommendedAction: string; automaticRepairAllowed: boolean };
export type ReconciliationReport = { projectId: string; slug: string; issues: ReconciliationIssue[] };
export type WorkspaceLock = { operationId: string; createdAt: string; expiresAt: string };

const now = () => new Date().toISOString();
const operationId = (value?: string) => OperationIdSchema.parse(value ?? `operation-${randomUUID()}`);
const versionPathPattern = /^v([1-9]\d*)$/;
const transientNames = new Set(["node_modules", ".next", "dist", "coverage", ".env", ".env.local"]);

export class WorkspaceManager {
  readonly root: string;
  private readonly versions: WorkspaceVersionPort;
  private readonly decisions?: WorkspaceDecisionPort;
  constructor(options: WorkspaceOptions) {
    this.root = normalizeWorkspaceRoot(WorkspaceRootSchema.parse(options.root));
    this.versions = options.versions;
    this.decisions = options.decisions;
    if (options.testMode && options.configuredProductionRoot && this.root.toLowerCase() === normalizeWorkspaceRoot(options.configuredProductionRoot).toLowerCase()) throw new WorkspaceError("WORKSPACE_TEST_ROOT_REJECTED", "Test operations cannot use the configured production workspace root.");
  }

  async inspectWorkspaceRoot() { await this.ensureRoot(); return { rootConfigured: true, exists: true }; }
  async createProjectRoot(project: FactoryProject) {
    const parsed = FactoryProjectSchema.parse(project); const projectRoot = this.projectRoot(parsed.slug); await this.ensureRoot();
    try {
      const existing = await lstat(projectRoot);
      if (!existing.isDirectory()) throw new WorkspaceError("WORKSPACE_PROJECT_EXISTS", "A workspace project path is already occupied.");
      const metadata = await this.readWorkspaceMetadata(parsed.slug);
      if (metadata.projectId !== parsed.id) throw new WorkspaceError("WORKSPACE_PROJECT_EXISTS", "A different workspace project already uses this slug.");
      return projectRoot;
    } catch (error) {
      if (error instanceof WorkspaceError) throw error;
      if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw new WorkspaceError("WORKSPACE_PROJECT_EXISTS", "The workspace project could not be inspected.", undefined, error);
    }
    await mkdir(projectRoot, { recursive: false }); await mkdir(path.join(projectRoot, ".staging"), { recursive: true });
    const timestamp = now(); const metadata: WorkspaceProjectMetadata = { schemaVersion: 1, documentType: "workspace-project", projectId: parsed.id, slug: parsed.slug, ...(parsed.title ? { title: parsed.title } : {}), latestVersion: 0, createdAt: timestamp, updatedAt: timestamp, versions: [] };
    await this.writeMetadata(parsed.slug, metadata); return projectRoot;
  }
  async getProjectRoot(slug: string) { const root = this.projectRoot(slug); try { if (!(await lstat(root)).isDirectory()) throw new WorkspaceError("WORKSPACE_PROJECT_NOT_FOUND", "Workspace project was not found."); return root; } catch (error) { if (error instanceof WorkspaceError) throw error; throw new WorkspaceError("WORKSPACE_PROJECT_NOT_FOUND", "Workspace project was not found.", undefined, error); } }
  async listProjectVersions(slug: string) { const root = await this.getProjectRoot(slug); const entries = await readdir(root, { withFileTypes: true }); return entries.filter((entry) => entry.isDirectory() && versionPathPattern.test(entry.name)).map((entry) => Number(entry.name.slice(1))).sort((a, b) => a - b); }
  async readWorkspaceMetadata(slug: string): Promise<WorkspaceProjectMetadata> { try { return WorkspaceProjectMetadataSchema.parse(JSON.parse(await readFile(path.join(await this.getProjectRoot(slug), "project.json"), "utf8"))); } catch (error) { if (error instanceof WorkspaceError) throw error; throw new WorkspaceError("WORKSPACE_INTEGRITY_FAILED", "Workspace metadata is invalid.", undefined, error); } }

  async reserveNextVersion(projectId: string, idempotencyKey?: string) { return this.versions.reserveNextVersion(projectId, idempotencyKey); }

  async createInitialVersion(project: FactoryProject, options: VersionCreationOptions = {}) {
    const parsed = FactoryProjectSchema.parse(project); const projectRoot = await this.createProjectRoot(parsed); const op = operationId(options.operationId); const lock = await this.acquireLock(parsed.slug, op); let staging: string | undefined;
    try {
      const version = await this.versions.reserveNextVersion(parsed.id, options.idempotencyKey ?? `workspace-v-${parsed.id}`); if (version.versionNumber !== 1) throw new WorkspaceError("WORKSPACE_VERSION_RESERVED", "The initial workspace version is already reserved."); const finalPath = path.join(projectRoot, versionDirectoryName(version.versionNumber)); if (await this.exists(finalPath)) { await this.verifyVersion(parsed.slug, version.versionNumber); return { version, path: finalPath }; }
      staging = await this.createStaging(parsed.slug, version.versionNumber, op); const versionProject = this.versionProject(parsed, version.versionNumber); await this.initializeVersionMemoryAt(staging, versionProject, options.documents); await this.verifyStaging(staging); await this.promoteStagingInternal(parsed.slug, version, staging); return { version, path: path.join(projectRoot, versionDirectoryName(version.versionNumber)) };
    } catch (error) { if (staging) await this.safeRemoveStaging(parsed.slug, staging, op).catch(() => undefined); if (error instanceof WorkspaceError) throw error; throw new WorkspaceError("WORKSPACE_STAGING_FAILED", "Workspace version creation failed.", undefined, error); }
    finally { await this.releaseLock(parsed.slug, lock.operationId).catch(() => undefined); }
  }

  async initializeVersionMemory(slug: string, version: number, operation: string, project: FactoryProject, documents?: Record<string, unknown>) { const staging = this.stagingPath(slug, version, operation); await this.initializeVersionMemoryAt(staging, this.versionProject(project, version), documents); return staging; }
  async promoteStagingVersion(slug: string, version: number, operation: string) { const op = OperationIdSchema.parse(operation); const lock = await this.acquireLock(slug, op); try { const versionRow = await this.versions.getVersion((await this.readWorkspaceMetadata(slug)).projectId, version); if (!versionRow) throw new WorkspaceError("WORKSPACE_VERSION_NOT_FOUND", "Workspace version was not found in persistence."); await this.promoteStagingInternal(slug, versionRow, this.stagingPath(slug, version, op)); } finally { await this.releaseLock(slug, lock.operationId).catch(() => undefined); } }

  async createRevisionFromVersion(project: FactoryProject, sourceVersion: number, options: VersionCreationOptions = {}) {
    const parsed = FactoryProjectSchema.parse(project); await this.getProjectRoot(parsed.slug); const source = await this.versions.getVersion(parsed.id, sourceVersion); if (!source) throw new WorkspaceError("WORKSPACE_VERSION_NOT_FOUND", "Revision source version was not found."); if (!source.immutable) throw new WorkspaceError("WORKSPACE_VERSION_RESERVED", "Revision source must be immutable.");
    const op = operationId(options.operationId); const lock = await this.acquireLock(parsed.slug, op); let staging: string | undefined;
    try {
      const target = await this.versions.reserveNextVersion(parsed.id, options.idempotencyKey ?? `workspace-revision-${parsed.id}-${sourceVersion}`); staging = await this.createStaging(parsed.slug, target.versionNumber, op); const sourceDir = path.join(this.projectRoot(parsed.slug), versionDirectoryName(sourceVersion)); await this.copyVersionFiles(sourceDir, staging); await this.initializeRevisionMemory(sourceDir, staging, parsed, target.versionNumber); await this.verifyStaging(staging); await this.promoteStagingInternal(parsed.slug, target, staging);
      const decision = DecisionRecordSchema.parse({ id: randomUUID(), timestamp: now(), actorType: "system", actorIdentifier: "workspace-manager", category: "revision", decision: `Created version ${target.versionNumber} from immutable version ${sourceVersion}`, rationale: "Revisions preserve released versions and start from a staged copy.", affectedDocuments: ["project.json", "manifest.json"], requirementChange: false, userApprovalRequired: false, userApprovalStatus: "not-required" });
      if (this.decisions) await this.decisions.append(parsed.id, target.versionNumber, decision); return { version: target, path: path.join(this.projectRoot(parsed.slug), versionDirectoryName(target.versionNumber)) };
    } catch (error) { if (staging) await this.safeRemoveStaging(parsed.slug, staging, op).catch(() => undefined); if (error instanceof WorkspaceError) throw error; throw new WorkspaceError("WORKSPACE_STAGING_FAILED", "Workspace revision failed.", undefined, error); }
    finally { await this.releaseLock(parsed.slug, lock.operationId).catch(() => undefined); }
  }

  async verifyVersion(slug: string, version: number) { const directory = path.join(await this.getProjectRoot(slug), versionDirectoryName(version)); await this.assertContained(directory); try { if (!(await lstat(directory)).isDirectory()) throw new Error("not-directory"); await new ProjectMemoryStore(path.join(directory, ".factory")).verifyIntegrity(); return true; } catch (error) { throw new WorkspaceError("WORKSPACE_INTEGRITY_FAILED", "Workspace version integrity verification failed.", undefined, error); } }
  async markVersionImmutable(projectId: string, slug: string, version: number, releasedAt = now()) { const versionRow = await this.versions.getVersion(projectId, version); if (!versionRow) throw new WorkspaceError("WORKSPACE_VERSION_NOT_FOUND", "Workspace version was not found."); if (versionRow.immutable) throw new WorkspaceError("WORKSPACE_IMMUTABLE", "Workspace version is already immutable."); const directory = path.join(await this.getProjectRoot(slug), versionDirectoryName(version)); const store = new ProjectMemoryStore(path.join(directory, ".factory")); const current = await store.readDocument("project.json"); const immutableProject = this.versionProject({ ...current, workflowState: "PROJECT_READY", completedAt: releasedAt, implementationStartedAt: current.implementationStartedAt ?? releasedAt }, version, false); await store.writeDocument("project.json", immutableProject); await this.versions.markImmutable(projectId, version, releasedAt); await this.updateMetadataVersion(slug, { ...versionRow, immutable: true, state: "PROJECT_READY", releasedAt }); }

  async cleanupFailedStaging(slug: string, version: number, operation: string) { const op = OperationIdSchema.parse(operation); const target = this.stagingPath(slug, version, op); try { const info = await lstat(target); if (!info.isDirectory() || info.isSymbolicLink()) throw new WorkspaceError("WORKSPACE_CLEANUP_FAILED", "Staging target is not a safe directory."); await rm(target, { recursive: true, force: false }); return { removed: true }; } catch (error) { if (error instanceof WorkspaceError) throw error; if ((error as NodeJS.ErrnoException).code === "ENOENT") return { removed: false }; throw new WorkspaceError("WORKSPACE_CLEANUP_FAILED", "Staging cleanup failed.", undefined, error); } }

  async acquireLock(slug: string, operation: string, ttlMs = 120_000): Promise<WorkspaceLock> { const op = OperationIdSchema.parse(operation); const root = await this.getProjectRoot(slug); const lockPath = path.join(root, ".workspace.lock"); const lock: WorkspaceLock = { operationId: op, createdAt: now(), expiresAt: new Date(Date.now() + ttlMs).toISOString() }; await this.assertContained(lockPath); try { await writeFile(lockPath, JSON.stringify(lock), { flag: "wx", mode: 0o600 }); return lock; } catch (error) { if ((error as NodeJS.ErrnoException).code !== "EEXIST") throw new WorkspaceError("WORKSPACE_LOCKED", "Workspace lock could not be created.", undefined, error); let existingRaw: string; try { existingRaw = await readFile(lockPath, "utf8"); } catch { throw new WorkspaceError("WORKSPACE_LOCKED", "Workspace lock is active."); } const existing = JSON.parse(existingRaw) as WorkspaceLock; if (Date.parse(existing.expiresAt) > Date.now() && existing.operationId !== op) throw new WorkspaceError("WORKSPACE_LOCKED", "Workspace is locked by another active operation."); if (existing.operationId !== op && Date.parse(existing.expiresAt) <= Date.now()) await rm(lockPath, { force: false }); await writeFile(lockPath, JSON.stringify(lock), { flag: "wx", mode: 0o600 }); return lock; } }
  async releaseLock(slug: string, operation: string) { const root = await this.getProjectRoot(slug); const lockPath = path.join(root, ".workspace.lock"); try { const existing = JSON.parse(await readFile(lockPath, "utf8")) as WorkspaceLock; if (existing.operationId !== operation && Date.parse(existing.expiresAt) > Date.now()) throw new WorkspaceError("WORKSPACE_LOCKED", "Active lock belongs to another operation."); await rm(lockPath, { force: false }); } catch (error) { if (error instanceof WorkspaceError) throw error; if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw new WorkspaceError("WORKSPACE_LOCKED", "Workspace lock could not be released.", undefined, error); } }

  async reconcile(projectId: string, slug: string): Promise<ReconciliationReport> { const issues: ReconciliationIssue[] = []; let metadata: WorkspaceProjectMetadata | undefined; try { metadata = await this.readWorkspaceMetadata(slug); } catch { issues.push({ code: "WORKSPACE_PROJECT_NOT_FOUND", description: "Workspace metadata is missing or invalid.", recommendedAction: "Inspect the project root before controlled repair.", automaticRepairAllowed: false }); }
    const databaseVersions = await this.versions.listVersions(projectId); const filesystemVersions = await this.listProjectVersions(slug).catch(() => []); const dbSet = new Set(databaseVersions.map((version) => version.versionNumber)); const fsSet = new Set(filesystemVersions); for (const version of databaseVersions) if (!fsSet.has(version.versionNumber)) issues.push({ code: "DATABASE_VERSION_DIRECTORY_MISSING", description: `Persisted version ${version.versionNumber} has no final directory.`, recommendedAction: "Inspect staging and decide whether to recreate or reconcile the version.", automaticRepairAllowed: false }); for (const version of filesystemVersions) if (!dbSet.has(version)) issues.push({ code: "DIRECTORY_DATABASE_VERSION_MISSING", description: `Final directory v${version} has no persisted version record.`, recommendedAction: "Do not delete automatically; inspect and reconcile persistence.", automaticRepairAllowed: false });
    const staging = await readdir(path.join(await this.getProjectRoot(slug), ".staging"), { withFileTypes: true }).catch(() => []); for (const entry of staging) if (entry.isDirectory()) issues.push({ code: "WORKSPACE_STAGING_INTERRUPTED", description: "A staging operation was left after interruption.", recommendedAction: "Review operation ownership and clean only the matching staging directory.", automaticRepairAllowed: false }); if (metadata && metadata.latestVersion !== (databaseVersions.length ? Math.max(...databaseVersions.map((version) => version.versionNumber)) : 0)) issues.push({ code: "PROJECT_METADATA_STALE", description: "Filesystem project metadata does not match persisted latest version.", recommendedAction: "Reconcile metadata after confirming the authoritative version record.", automaticRepairAllowed: false }); return { projectId, slug, issues };
  }

  private async initializeVersionMemoryAt(directory: string, project: FactoryProject, documents?: Record<string, unknown>) { await mkdir(path.join(directory, ".factory"), { recursive: true }); const store = new ProjectMemoryStore(path.join(directory, ".factory")); await store.initialize(); await store.writeDocument("project.json", project); await store.writeOriginalPrompt(project.originalPrompt); for (const [name, value] of Object.entries(documents ?? {})) { if (name === "project.json" || name === "original-prompt.md" || name === "manifest.json" || name === "decisions.jsonl") continue; if (!CANONICAL_DOCUMENT_NAMES.includes(name as typeof CANONICAL_DOCUMENT_NAMES[number])) throw new WorkspaceError("MEMORY_SYNC_SCHEMA_MISMATCH", "Unsupported Project Memory document."); await store.writeDocument(name as StructuredDocumentName, value); } await store.rebuildManifest(); }
  private versionProject(project: FactoryProject, version: number, downgradeReleased = true) { const next = { ...project }; if (downgradeReleased) { delete next.implementationStartedAt; delete next.completedAt; } const workflowState = downgradeReleased && project.workflowState === "PROJECT_READY" ? "READY_FOR_IMPLEMENTATION" : project.workflowState; return FactoryProjectSchema.parse({ ...next, projectVersion: version, currentVersion: version, updatedAt: now(), workflowState }); }
  private async initializeRevisionMemory(sourceDir: string, destinationDir: string, project: FactoryProject, version: number) { const sourceStore = new ProjectMemoryStore(path.join(sourceDir, ".factory")); const destinationStore = new ProjectMemoryStore(path.join(destinationDir, ".factory")); await destinationStore.initialize(); const sourceProject = await sourceStore.readDocument("project.json"); await destinationStore.writeDocument("project.json", this.versionProject({ ...sourceProject, slug: project.slug }, version)); await destinationStore.writeOriginalPrompt(await sourceStore.readDocument("project.json").then(() => sourceProject.originalPrompt)); for (const name of await sourceStore.listAvailableDocuments()) { if (["project.json", "manifest.json", "original-prompt.md", "decisions.jsonl", "quality-report.json", "release-report.json"].includes(name)) continue; const document = await sourceStore.readDocument(name as StructuredDocumentName); const next = { ...document, projectVersion: version, updatedAt: now(), ...(document.documentType === "task-graph" ? { tasks: document.tasks.map((task) => ({ ...task, projectVersion: version })) } : {}) }; await destinationStore.writeDocument(name as StructuredDocumentName, next); } try { const decisions = await readFile(path.join(sourceDir, ".factory", "decisions.jsonl")); await writeFile(path.join(destinationDir, ".factory", "decisions.jsonl"), decisions, { mode: 0o600 }); } catch (error) { if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error; } const revisionDecision = DecisionRecordSchema.parse({ id: randomUUID(), timestamp: now(), actorType: "system", actorIdentifier: "workspace-manager", category: "revision", decision: `Copied version ${version - 1} into version ${version}`, rationale: "Revision starts from an immutable source while removing release-only documents.", affectedDocuments: ["project.json", "manifest.json"], requirementChange: false, userApprovalRequired: false, userApprovalStatus: "not-required" }); await destinationStore.appendDecision(revisionDecision); }
  private async copyVersionFiles(source: string, destination: string) { await this.copyTree(source, destination, new Set([".factory", ...transientNames])); }
  private async copyTree(source: string, destination: string, excluded: Set<string>) { await mkdir(destination, { recursive: true }); for (const entry of await readdir(source, { withFileTypes: true })) { if (excluded.has(entry.name)) continue; const sourcePath = path.join(source, entry.name); const destinationPath = path.join(destination, entry.name); await this.assertContained(sourcePath); await this.assertContained(destinationPath); const info = await lstat(sourcePath); if (info.isSymbolicLink()) throw new WorkspaceError("WORKSPACE_INTEGRITY_FAILED", "Symbolic links are not permitted in copied project files."); if (info.isDirectory()) await this.copyTree(sourcePath, destinationPath, excluded); else if (info.isFile()) { await copyFile(sourcePath, destinationPath); await chmod(destinationPath, info.mode).catch(() => undefined); } } }
  private async createStaging(slug: string, version: number, operation: string) { const directory = this.stagingPath(slug, version, operation); try { await mkdir(directory, { recursive: false }); await writeFile(path.join(directory, ".workspace-operation"), JSON.stringify({ operationId: operation, version }), { flag: "wx", mode: 0o600 }); return directory; } catch (error) { throw new WorkspaceError("WORKSPACE_STAGING_FAILED", "Staging directory could not be created.", undefined, error); } }
  private async verifyStaging(directory: string) { try { await new ProjectMemoryStore(path.join(directory, ".factory")).verifyIntegrity(); } catch (error) { throw new WorkspaceError("WORKSPACE_INTEGRITY_FAILED", "Staging Project Memory failed integrity verification.", undefined, error); } }
  private async promoteStagingInternal(slug: string, version: ProjectVersionRow, staging: string) { const projectRoot = await this.getProjectRoot(slug); const finalPath = path.join(projectRoot, versionDirectoryName(version.versionNumber)); await this.assertContained(staging); await this.assertContained(finalPath); try { if (await this.exists(finalPath)) throw new WorkspaceError("WORKSPACE_VERSION_EXISTS", "Final workspace version already exists."); await rm(path.join(staging, ".workspace-operation"), { force: false }); await rename(staging, finalPath); const previous = await readFile(path.join(projectRoot, "project.json")).catch(() => undefined); try { const metadata = await this.readWorkspaceMetadata(slug); const next: WorkspaceProjectMetadata = { ...metadata, latestVersion: Math.max(metadata.latestVersion, version.versionNumber), updatedAt: now(), versions: [...metadata.versions.filter((entry) => entry.version !== version.versionNumber), { version: version.versionNumber, directory: versionDirectoryName(version.versionNumber), immutable: version.immutable, state: version.state, createdAt: version.createdAt }].sort((a, b) => a.version - b.version) }; await this.atomicWrite(path.join(projectRoot, "project.json"), JSON.stringify(next, null, 2) + "\n"); } catch (error) { await rm(finalPath, { recursive: true, force: true }).catch(() => undefined); if (previous) await this.atomicWrite(path.join(projectRoot, "project.json"), previous.toString("utf8")); throw error; } } catch (error) { if (error instanceof WorkspaceError) throw error; if ((error as NodeJS.ErrnoException).code === "EXDEV") throw new WorkspaceError("WORKSPACE_CROSS_DEVICE_MOVE", "Staging and final workspace paths are on different filesystems.", undefined, error); throw new WorkspaceError("WORKSPACE_PROMOTION_FAILED", "Staging promotion failed.", undefined, error); } }
  private async updateMetadataVersion(slug: string, version: ProjectVersionRow) { const metadata = await this.readWorkspaceMetadata(slug); const next = { ...metadata, updatedAt: now(), versions: metadata.versions.map((entry) => entry.version === version.versionNumber ? { ...entry, immutable: version.immutable, state: version.state } : entry) }; await this.writeMetadata(slug, next); }
  private async writeMetadata(slug: string, metadata: WorkspaceProjectMetadata) { await this.atomicWrite(path.join(await this.getProjectRoot(slug), "project.json"), JSON.stringify(WorkspaceProjectMetadataSchema.parse(metadata), null, 2) + "\n"); }
  private projectRoot(slug: string) { const safeSlug = WorkspaceSlugSchema.parse(slug); const candidate = path.resolve(this.root, safeSlug); if (candidate !== this.root && !candidate.toLowerCase().startsWith(`${this.root.toLowerCase()}${path.sep}`)) throw new WorkspaceError("WORKSPACE_ROOT_INVALID", "Workspace path escapes the configured root."); return candidate; }
  private stagingPath(slug: string, version: number, operation: string) { const root = this.projectRoot(slug); const safeOperation = OperationIdSchema.parse(operation); const candidate = path.resolve(root, ".staging", `${versionDirectoryName(version)}-${safeOperation}`); if (!candidate.toLowerCase().startsWith(`${path.join(root, ".staging").toLowerCase()}${path.sep}`)) throw new WorkspaceError("WORKSPACE_STAGING_FAILED", "Staging path is unsafe."); return candidate; }
  private async ensureRoot() { try { await mkdir(this.root, { recursive: true }); const info = await lstat(this.root); if (!info.isDirectory() || info.isSymbolicLink()) throw new WorkspaceError("WORKSPACE_ROOT_INVALID", "Workspace root is not a safe directory."); } catch (error) { if (error instanceof WorkspaceError) throw error; throw new WorkspaceError("WORKSPACE_ROOT_INVALID", "Workspace root is unavailable.", undefined, error); } }
  private async assertContained(target: string) { const resolved = path.resolve(target); if (resolved.toLowerCase() !== this.root.toLowerCase() && !resolved.toLowerCase().startsWith(`${this.root.toLowerCase()}${path.sep}`)) throw new WorkspaceError("WORKSPACE_ROOT_INVALID", "Workspace path escapes the configured root."); }
  private async exists(target: string) { try { await lstat(target); return true; } catch (error) { if ((error as NodeJS.ErrnoException).code === "ENOENT") return false; throw error; } }
  private async safeRemoveStaging(slug: string, staging: string, operation: string) { const match = path.basename(staging).match(/^v([1-9]\d*)-/); const expected = this.stagingPath(slug, Number(match?.[1] ?? 0), operation); if (path.resolve(expected).toLowerCase() !== path.resolve(staging).toLowerCase()) throw new WorkspaceError("WORKSPACE_CLEANUP_FAILED", "Cleanup target does not match the operation."); if (!(await this.exists(staging))) return; try { const marker = JSON.parse(await readFile(path.join(staging, ".workspace-operation"), "utf8")) as { operationId?: string }; if (marker.operationId !== operation) throw new WorkspaceError("WORKSPACE_CLEANUP_FAILED", "Staging ownership does not match the operation."); } catch (error) { if (error instanceof WorkspaceError) throw error; throw new WorkspaceError("WORKSPACE_CLEANUP_FAILED", "Staging ownership could not be verified.", undefined, error); } await rm(staging, { recursive: true, force: true }); }
  private async atomicWrite(target: string, content: string | Buffer) { await this.assertContained(target); const temp = `${target}.${randomUUID()}.tmp`; try { await writeFile(temp, content, { flag: "wx", mode: 0o600 }); const handle = await open(temp, constants.O_RDWR); await handle.sync(); await handle.close(); await rename(temp, target); } catch (error) { await rm(temp, { force: true }).catch(() => undefined); throw new WorkspaceError("WORKSPACE_PROMOTION_FAILED", "Workspace metadata write failed.", undefined, error); } }
}

export function createWorkspaceManager(root: string, versions: WorkspaceVersionPort, decisions?: WorkspaceDecisionPort) { return new WorkspaceManager({ root, versions, decisions }); }
