import { randomUUID } from "node:crypto";
import { RealFactoryE2EReportSchema, type RealFactoryE2EReport } from "./contracts";
import type { RealFactoryE2EPreflight } from "./preflight";

export const VELOFIX_WERKSTATT_PROMPT = `Create a synthetic German bicycle repair workshop website for VeloFix Werkstatt. Use only the supplied facts: name VeloFix Werkstatt; language German; service bicycle repairs; audience local bicycle owners; primary action request an appointment; pages home, services, appointment; no supplied logo; use placeholders for imagery; acceptance requires local navigation, an appointment form with client and server validation, and a successful production build. Do not invent address, opening hours, prices, staff, testimonials, contact details, or customer data.`;

export type RealFactoryStageRunner = { run(input: { smokeId: string; projectId: string; prompt: string }): Promise<{ projectId: string; projectVersion: number; projectPathReference: string; taskCount: number; passedTasks: number; failedTasks: number; createdFiles: number; changedFiles: number; checksumVerified: boolean; npmPassed: boolean; qaPassed: boolean; qaScenarios: number; qaExternalRequests: number; providerRequests: number; inputTokens: number; outputTokens: number; modelLabel: string; context7Requests?: number; shadcnRequests?: number }>; };
const productionIdentity = { leadProviderMode: "production", plannerProviderMode: "production", designProviderMode: "production", implementationProviderMode: "production", processRunnerMode: "real", browserRunnerMode: "real", executionStateMode: "production", taskExecutorMode: "production", repairerMode: "production", fullExecutorMode: "production" } as const;

export function assertRealDependencies(dependencies: RealFactoryStageRunner | undefined, preflight: RealFactoryE2EPreflight) { if (!dependencies) throw new Error("REAL_E2E_STAGE_RUNNER_REQUIRED"); if (preflight.status !== "passed") throw new Error("REAL_E2E_PREFLIGHT_REQUIRED"); }

export async function runRealFactoryE2E(input: { preflight: RealFactoryE2EPreflight; generatedProjectsRoot: string; runner?: RealFactoryStageRunner }): Promise<RealFactoryE2EReport> {
  const smokeId = randomUUID(); const startedAt = new Date().toISOString();
  const base = { schemaVersion: 1 as const, reportType: "real-factory-e2e" as const, smokeId, startedAt, optIn: input.preflight.optIn, preflightPassed: input.preflight.status === "passed", adapterIdentity: productionIdentity, realStageEvidence: { leadRequest: false, plannerRequest: false, designRequest: false, implementationRequest: false, npmExecution: false, browserExecution: false }, stages: [], provider: { status: input.preflight.integrations.provider, requestCount: 0, inputTokens: 0, outputTokens: 0 }, context7: { status: input.preflight.integrations.context7, requestCount: 0 }, shadcn: { status: input.preflight.integrations.shadcn, requestCount: 0 }, npm: { status: "not-configured" as const, commands: ["npm ci", "npm run lint", "npm run typecheck", "npm test -- --run", "npm run build"], passedCount: 0, failedCount: 0 }, playwright: { status: "not-configured" as const, scenarios: 0, passedCount: 0, failedCount: 0, unexpectedExternalRequests: 0 }, taskGraph: { taskCount: 0, passedCount: 0, failedCount: 0, repairCount: 0 }, generatedFiles: { createdCount: 0, changedCount: 0, checksumVerified: false }, blockers: [...input.preflight.blockers], warnings: [...input.preflight.warnings], releaseEligible: false, prohibitedActions: { deployment: false, gitMutation: false, customerDatabaseMigration: false, customerDataAccess: false, arbitraryBrowsing: false, screenshots: false } };
  if (input.preflight.status !== "passed") return RealFactoryE2EReportSchema.parse({ ...base, overallStatus: input.preflight.status === "pending" ? "pending" : "failed", completedAt: new Date().toISOString() });
  assertRealDependencies(input.runner, input.preflight);
  const result = await input.runner!.run({ smokeId, projectId: randomUUID(), prompt: VELOFIX_WERKSTATT_PROMPT });
  const realStageEvidence = { leadRequest: true, plannerRequest: true, designRequest: true, implementationRequest: result.providerRequests > 3, npmExecution: result.npmPassed, browserExecution: result.qaPassed };
  const passed = Object.values(realStageEvidence).every(Boolean) && result.checksumVerified && result.failedTasks === 0;
  return RealFactoryE2EReportSchema.parse({ ...base, overallStatus: passed ? "passed" : "failed", completedAt: new Date().toISOString(), projectId: result.projectId, projectVersion: result.projectVersion, projectPathReference: result.projectPathReference, realStageEvidence, provider: { status: "configured", modelLabel: result.modelLabel, requestCount: result.providerRequests, inputTokens: result.inputTokens, outputTokens: result.outputTokens }, context7: { status: result.context7Requests ? "configured" : "not-needed", requestCount: result.context7Requests ?? 0 }, shadcn: { status: result.shadcnRequests ? "configured" : "not-needed", requestCount: result.shadcnRequests ?? 0 }, npm: { ...base.npm, status: result.npmPassed ? "configured" : "blocked", passedCount: result.npmPassed ? 5 : 0, failedCount: result.npmPassed ? 0 : 1 }, playwright: { status: result.qaPassed ? "configured" : "blocked", scenarios: result.qaScenarios, passedCount: result.qaPassed ? result.qaScenarios : 0, failedCount: result.qaPassed ? 0 : 1, unexpectedExternalRequests: result.qaExternalRequests }, taskGraph: { taskCount: result.taskCount, passedCount: result.passedTasks, failedCount: result.failedTasks, repairCount: 0 }, generatedFiles: { createdCount: result.createdFiles, changedCount: result.changedFiles, checksumVerified: result.checksumVerified }, releaseEligible: passed });
}
