import { describe, expect, it } from "vitest";
import { runRealFactoryE2EPreflight } from "./preflight";
describe("real E2E prerequisite diagnostics", () => {
  it("detects missing credentials without exposing values", async () => { const result = await runRealFactoryE2EPreflight({ ALLOW_REAL_FACTORY_E2E: "true", OPENAI_MODEL: "approved-model" }, { npmDiagnostic: { available: true }, chromiumAvailable: true }); expect(result.blockers).toContain("REAL_E2E_OPENAI_NOT_CONFIGURED"); expect(result.diagnostics?.openai).toMatchObject({ keyPresent: false, modelConfigured: true, clientConstructable: false, safeErrorCode: "REAL_E2E_OPENAI_KEY_MISSING" }); expect(JSON.stringify(result)).not.toContain("secret"); });
  it("distinguishes missing model from missing key", async () => { const result = await runRealFactoryE2EPreflight({ ALLOW_REAL_FACTORY_E2E: "true", OPENAI_API_KEY: "test-key" }, { npmDiagnostic: { available: true }, chromiumAvailable: true }); expect(result.blockers).toContain("REAL_E2E_OPENAI_MODEL_MISSING"); expect(result.diagnostics?.openai).toMatchObject({ keyPresent: true, modelConfigured: false, safeErrorCode: "REAL_E2E_OPENAI_MODEL_MISSING" }); });
  it("accepts valid local production AI configuration without making a request", async () => { const result = await runRealFactoryE2EPreflight({ ALLOW_REAL_FACTORY_E2E: "true", OPENAI_API_KEY: "test-key", OPENAI_MODEL: "approved-model", EXTRA_ENV: "ignored" }, { npmDiagnostic: { available: true }, chromiumAvailable: true, gitClean: true }); expect(result.diagnostics?.openai).toMatchObject({ configured: true, keyPresent: true, modelConfigured: true, clientConstructable: true }); expect(result.blockers).not.toContain("REAL_E2E_OPENAI_NOT_CONFIGURED"); });
  it("distinguishes invalid provider configuration safely", async () => { const result = await runRealFactoryE2EPreflight({ ALLOW_REAL_FACTORY_E2E: "true", OPENAI_API_KEY: "test-key", OPENAI_MODEL: "approved-model", OPENAI_REQUEST_TIMEOUT_MS: "not-a-number" }, { npmDiagnostic: { available: true }, chromiumAvailable: true }); expect(result.diagnostics?.openai.safeErrorCode).toBe("REAL_E2E_OPENAI_CONFIGURATION_INVALID"); expect(JSON.stringify(result)).not.toContain("test-key"); });
  it("remains pending without explicit opt-in", async () => { const result = await runRealFactoryE2EPreflight({ OPENAI_API_KEY: "test-key", OPENAI_MODEL: "approved-model" }); expect(result.status).toBe("pending"); expect(result.diagnostics?.npm.safeErrorCode).toBe("REAL_E2E_OPT_IN_REQUIRED"); });
});
