import { createHash } from "node:crypto";
import { ShadcnRegistryError } from "./errors";
import { RegistryFileSchema, ShadcnComponentReferenceSchema, type ShadcnComponentQueryPlan, type ShadcnComponentReference } from "./contracts";
import { assertSourceSafe } from "./security";
import { FORBIDDEN_DEPENDENCIES } from "./policy";
const sha = (value: string) => createHash("sha256").update(value, "utf8").digest("hex");
const badPath = /^(?:[A-Za-z]:[\\/]|[\\/]{2}|\/)|(^|[\\/])\.\.?([\\/]|$)|(^|[\\/])(?:\.git|\.env|node_modules|\.next|dist|coverage)(?:[\\/]|$)/i;
type Raw = { name?: unknown; title?: unknown; description?: unknown; files?: unknown; dependencies?: unknown; devDependencies?: unknown; cssVars?: unknown; registryDependencies?: unknown };
export function normalizeComponent(raw: unknown, plan: ShadcnComponentQueryPlan, designMetadata?: { colorStrategy?: string; typographyStrategy?: string; radiusPolicy?: string; spacingCharacter?: string; density?: string; motionPolicy?: string }, retrievedAt = new Date().toISOString()): ShadcnComponentReference {
  if (!raw || typeof raw !== "object") throw new ShadcnRegistryError("SHADCN_REGISTRY_SOURCE_INVALID", "Registry response is not an object."); const value = raw as Raw; if (!Array.isArray(value.files)) throw new ShadcnRegistryError("SHADCN_REGISTRY_SOURCE_INVALID", "Registry response has no file list."); const files: Array<ReturnType<typeof RegistryFileSchema.parse>> = []; const seen = new Set<string>(); let bytes = 0;
  for (const rawFile of value.files) { if (!rawFile || typeof rawFile !== "object") throw new ShadcnRegistryError("SHADCN_REGISTRY_SOURCE_INVALID", "Registry file metadata is malformed."); const candidate = rawFile as { path?: unknown; content?: unknown; type?: unknown }; if (typeof candidate.path !== "string" || badPath.test(candidate.path)) throw new ShadcnRegistryError("SHADCN_FILE_PATH_INVALID", "Registry suggested path is unsafe."); if (typeof candidate.content !== "string") throw new ShadcnRegistryError("SHADCN_BINARY_UNSUPPORTED", "Only UTF-8 text component files are supported."); const content = candidate.content.replace(/\r\n?/g, "\n"); const checksum = sha(content); if (seen.has(checksum)) continue; const byteSize = Buffer.byteLength(content, "utf8"); if (byteSize > plan.maxBytes) throw new ShadcnRegistryError("SHADCN_CONTENT_LIMIT_EXCEEDED", "A Registry file exceeds the byte limit."); if (files.length >= plan.maxFiles) throw new ShadcnRegistryError("SHADCN_FILE_LIMIT_EXCEEDED", "The Registry file limit was exceeded."); bytes += byteSize; if (bytes > plan.maxBytes) throw new ShadcnRegistryError("SHADCN_CONTENT_LIMIT_EXCEEDED", "The Registry component exceeds the byte limit."); files.push(RegistryFileSchema.parse({ suggestedPath: candidate.path, type: candidate.type === "style" || candidate.type === "config" ? candidate.type : "component", content, checksum, byteSize, frameworkRelevance: "Reference only; adapt to the selected design." })); seen.add(checksum); }
  const dependencies = Array.isArray(value.dependencies) ? value.dependencies.filter((item): item is string => typeof item === "string") : []; const devDependencies = Array.isArray(value.devDependencies) ? value.devDependencies.filter((item): item is string => typeof item === "string") : []; const registryDependencies = Array.isArray(value.registryDependencies) ? value.registryDependencies.filter((item): item is string => typeof item === "string") : []; if (registryDependencies.includes(plan.componentName)) throw new ShadcnRegistryError("SHADCN_REGISTRY_DEPENDENCY_CYCLE", "The Registry dependency tree contains a cycle."); if (registryDependencies.length > 3) throw new ShadcnRegistryError("SHADCN_REGISTRY_DEPENDENCY_DEPTH_EXCEEDED", "The Registry dependency tree exceeds the bounded depth."); const allDependencies = [...dependencies, ...devDependencies]; if (allDependencies.some((dependency) => FORBIDDEN_DEPENDENCIES.test(dependency) || !plan.allowedDependencyNames.includes(dependency))) throw new ShadcnRegistryError("SHADCN_UNAPPROVED_DEPENDENCY", "Registry source requested an unapproved dependency."); assertSourceSafe(files);
  const compatibility = designMetadata?.colorStrategy || designMetadata?.typographyStrategy ? "adaptation-required" as const : "compatible" as const; const adaptationNotes = ["Default shadcn classes are non-authoritative.", ...(designMetadata ? [`Adapt to selected typography: ${designMetadata.typographyStrategy ?? "approved strategy"}.`, `Adapt to selected color strategy: ${designMetadata.colorStrategy ?? "approved strategy"}.`] : [])]; const base = { registryId: "official-shadcn" as const, componentName: plan.componentName, registryReference: `official-shadcn:${plan.componentName}`, title: typeof value.title === "string" ? value.title : plan.componentName, description: typeof value.description === "string" ? value.description : "Approved component reference.", files: files.sort((a, b) => a.suggestedPath.localeCompare(b.suggestedPath)), dependencies, devDependencies, cssVariables: Array.isArray(value.cssVars) ? value.cssVars.filter((item): item is string => typeof item === "string") : [], registryDependencies: Array.isArray(value.registryDependencies) ? value.registryDependencies.filter((item): item is string => typeof item === "string") : [], sourceMetadata: { source: "official-shadcn" as const, trustStatus: "trusted" as const, reviewStatus: "approved" as const }, retrievedAt, checksum: sha(JSON.stringify({ plan, files, dependencies, devDependencies })), compatibility, compatibilityNotes: ["Selected DesignDirection remains authoritative."], adaptationNotes, truncationState: "complete" as const }; return ShadcnComponentReferenceSchema.parse(base);
}
