import { createHash } from "node:crypto";
import { ShadcnRegistryCache } from "./cache";
import { readShadcnRegistryConfig, type ShadcnRegistryConfig } from "./config";
import { ShadcnComponentQueryPlanSchema, ShadcnRegistryDefinitionSchema, type ShadcnComponentQueryPlan, type ShadcnRegistryInput, type ShadcnRegistryPort, type ShadcnRegistryTransport, type ShadcnReferenceResult } from "./contracts";
import { ShadcnRegistryError } from "./errors";
import { normalizeComponent } from "./normalize";
import { APPROVED_REGISTRY, assertNarrowComponent, assertRegistry, assertRelevant } from "./policy";

const sleep = (ms: number, signal?: AbortSignal) => new Promise<void>((resolve, reject) => { const timer = setTimeout(resolve, ms); signal?.addEventListener("abort", () => { clearTimeout(timer); reject(new ShadcnRegistryError("SHADCN_CANCELLED", "Registry request was cancelled.")); }, { once: true }); });
export class ShadcnRegistryService implements ShadcnRegistryPort {
  private readonly inFlight = new Map<string, Promise<ShadcnReferenceResult>>(); private readonly idempotency = new Map<string, string>(); private active = 0; private readonly queued: Array<{ run: () => void; signal?: AbortSignal }> = [];
  constructor(private readonly transport: ShadcnRegistryTransport, private readonly config: ShadcnRegistryConfig = readShadcnRegistryConfig(), private readonly cache = new ShadcnRegistryCache(".shadcn-registry-cache", config.cacheTtlSeconds)) {}
  async resolveRegistry(registryId: string) { assertRegistry(registryId); return ShadcnRegistryDefinitionSchema.parse(APPROVED_REGISTRY); }
  async resolveComponent(input: ShadcnRegistryInput): Promise<ShadcnComponentQueryPlan> { await this.resolveRegistry(input.registryId); assertNarrowComponent(input.componentName); assertRelevant(input.componentName, input.expectedComponentRole); return ShadcnComponentQueryPlanSchema.parse({ queryId: crypto.randomUUID(), registryId: "official-shadcn", componentName: input.componentName, taskId: input.taskId, taskType: input.taskType, reason: input.reason, requirementReferences: input.requirementReferences, planningReferences: input.planningReferences, selectedDesignReferences: input.selectedDesignReferences, expectedComponentRole: input.expectedComponentRole, maxFiles: Math.min(input.maxFiles, APPROVED_REGISTRY.maxFiles), maxBytes: Math.min(input.maxBytes, APPROVED_REGISTRY.maxBytes), allowedDependencyNames: input.allowedDependencyNames, targetAdaptationNotes: input.targetAdaptationNotes, dependencyPlanNames: input.dependencyPlanNames, selectedDesignChecksum: input.selectedDesignChecksum, dependencyPlanChecksum: input.dependencyPlanChecksum, createdAt: new Date().toISOString() }); }
  async fetchComponentReference(input: { plan: ShadcnComponentQueryPlan; cancellation?: AbortSignal; idempotencyKey: string; designMetadata?: ShadcnRegistryInput["designMetadata"] }): Promise<ShadcnReferenceResult> { const plan = ShadcnComponentQueryPlanSchema.parse(input.plan); await this.resolveRegistry(plan.registryId); if (!this.config.enabled) throw new ShadcnRegistryError("SHADCN_REGISTRY_NOT_CONFIGURED", "The shadcn Registry is disabled."); if (input.cancellation?.aborted) throw new ShadcnRegistryError("SHADCN_CANCELLED", "Registry request was cancelled."); const canonical = createHash("sha256").update(JSON.stringify({ plan, designMetadata: input.designMetadata }), "utf8").digest("hex"); const priorHash = this.idempotency.get(input.idempotencyKey); if (priorHash && priorHash !== canonical) throw new ShadcnRegistryError("IDEMPOTENCY_CONFLICT", "Registry idempotency key was reused with a different query."); this.idempotency.set(input.idempotencyKey, canonical); const prior = this.inFlight.get(input.idempotencyKey); if (prior) return prior; const promise = this.run(plan, input.cancellation, input.designMetadata); this.inFlight.set(input.idempotencyKey, promise); try { return await promise; } finally { this.inFlight.delete(input.idempotencyKey); } }
  private async run(plan: ShadcnComponentQueryPlan, signal?: AbortSignal, designMetadata?: ShadcnRegistryInput["designMetadata"]): Promise<ShadcnReferenceResult> { const cached = await this.cache.get(plan); if (cached) return cached; const result = await this.enqueue(() => this.request(plan, signal, designMetadata), signal); if (!signal?.aborted) await this.cache.set(plan, result); return result; }
  private enqueue<T>(work: () => Promise<T>, signal?: AbortSignal): Promise<T> { if (signal?.aborted) return Promise.reject(new ShadcnRegistryError("SHADCN_CANCELLED", "Registry request was cancelled.")); if (this.active < this.config.maxConcurrentRequests) { this.active++; return work().finally(() => this.release()); } return new Promise<T>((resolve, reject) => { const run = () => { if (signal?.aborted) { reject(new ShadcnRegistryError("SHADCN_CANCELLED", "Registry request was cancelled.")); return; } this.active++; void work().then(resolve, reject).finally(() => this.release()); }; this.queued.push({ run, signal }); }); }
  private release() { this.active--; while (this.queued.length) { const next = this.queued.shift(); if (next?.signal?.aborted) continue; next?.run(); break; } }
  private async request(plan: ShadcnComponentQueryPlan, signal?: AbortSignal, designMetadata?: ShadcnRegistryInput["designMetadata"]): Promise<ShadcnReferenceResult> { const controller = new AbortController(); const onAbort = () => controller.abort(); signal?.addEventListener("abort", onAbort, { once: true }); let attempt = 0; try { while (true) { try { if (signal?.aborted) throw new ShadcnRegistryError("SHADCN_CANCELLED", "Registry request was cancelled."); const raw = await Promise.race([this.transport({ registryId: "official-shadcn", componentName: plan.componentName, signal: controller.signal }), new Promise<never>((_, reject) => setTimeout(() => reject(new ShadcnRegistryError("SHADCN_TIMEOUT", "Registry request timed out.")), this.config.timeoutMs))]); const reference = normalizeComponent(raw, plan, designMetadata); if (reference.compatibility === "incompatible") throw new ShadcnRegistryError("SHADCN_DESIGN_INCOMPATIBLE", "Component cannot be adapted to the selected design."); return { reference, cache: "miss" }; } catch (error) { const mapped = error instanceof ShadcnRegistryError ? error : new ShadcnRegistryError("SHADCN_UNAVAILABLE", "Registry request failed safely.", error); if (["SHADCN_CANCELLED", "SHADCN_UNSAFE_SOURCE", "SHADCN_UNAPPROVED_DEPENDENCY", "SHADCN_FILE_PATH_INVALID", "SHADCN_BINARY_UNSUPPORTED"].includes(mapped.code) || (mapped.code === "SHADCN_TIMEOUT" && signal?.aborted)) throw mapped; if (!( ["SHADCN_TIMEOUT", "SHADCN_UNAVAILABLE", "SHADCN_RATE_LIMITED"].includes(mapped.code)) || attempt >= this.config.maxRetries) throw attempt ? new ShadcnRegistryError("SHADCN_RETRY_EXHAUSTED", "Registry retries were exhausted.", mapped) : mapped; attempt++; await sleep(20 * attempt, signal); } } } finally { signal?.removeEventListener("abort", onAbort); controller.abort(); } }
}
export function syntheticShadcnTransport(): ShadcnRegistryTransport { return async ({ componentName }) => ({ name: componentName, title: componentName, description: "Synthetic approved component reference.", files: [{ path: `components/ui/${componentName}.tsx`, content: `export function ${componentName.replace(/-([a-z])/g, (_, letter: string) => letter.toUpperCase())}() { return null; }`, type: "component" }], dependencies: [], devDependencies: [], cssVars: [], registryDependencies: [] }); }
