import { z } from "zod";
import { AssetManifestSchema } from "../domain/assets/schema";
import { TechnicalArchitectureSchema } from "../domain/architecture/schema";
import { ContentPlanSchema } from "../domain/content/schema";
import { RequirementSpecificationSchema } from "../domain/requirements/schema";
import { WorkflowStateSchema } from "../domain/project/schema";
import { DocumentBaseSchema, IsoDateTimeSchema, NonEmptyStringSchema } from "../domain/shared/schemas";

export const TraceabilitySchema = z.object({ decisionId: z.string().uuid(), category: NonEmptyStringSchema, requirementReferences: z.array(NonEmptyStringSchema).min(1), systemConstraintReferences: z.array(NonEmptyStringSchema), rationale: NonEmptyStringSchema, confidence: z.enum(["high", "medium", "low"]), unresolvedDependency: NonEmptyStringSchema.optional(), userConfirmationRequired: z.boolean() }).strict();
export type Traceability = z.infer<typeof TraceabilitySchema>;

const RefSchema = z.object({ id: NonEmptyStringSchema, requirementReferences: z.array(NonEmptyStringSchema).min(1) }).strict();
const RouteSchema = RefSchema.extend({ path: z.string().regex(/^\/(?:[a-z0-9-]+(?:\/[a-z0-9-]+)*)?$/), titlePurpose: NonEmptyStringSchema, pageType: z.enum(["landing", "content", "form", "dashboard", "auth", "legal", "application"]), visibility: z.enum(["public", "protected"]), intendedUser: NonEmptyStringSchema, primaryGoal: NonEmptyStringSchema, primaryCta: NonEmptyStringSchema.optional(), contentResponsibilities: z.array(NonEmptyStringSchema), dataDependencies: z.array(NonEmptyStringSchema), formDependencies: z.array(NonEmptyStringSchema), authRequired: z.boolean(), seoRelevant: z.boolean(), parentId: NonEmptyStringSchema.optional(), navigationVisible: z.boolean() }).strict();
export const SitemapPlanSchema = DocumentBaseSchema.extend({ documentType: z.literal("sitemap"), routes: z.array(RouteSchema), traceability: z.array(TraceabilitySchema) }).strict();
export type SitemapPlan = z.infer<typeof SitemapPlanSchema>;

const PageSchema = RefSchema.extend({ routeId: NonEmptyStringSchema, purpose: NonEmptyStringSchema, targetAudience: NonEmptyStringSchema, userIntent: NonEmptyStringSchema, contentBlocks: z.array(NonEmptyStringSchema), functionalComponents: z.array(NonEmptyStringSchema), forms: z.array(NonEmptyStringSchema), dataReads: z.array(NonEmptyStringSchema), dataWrites: z.array(NonEmptyStringSchema), loadingStates: z.array(NonEmptyStringSchema), emptyStates: z.array(NonEmptyStringSchema), errorStates: z.array(NonEmptyStringSchema), successStates: z.array(NonEmptyStringSchema), seoMetadata: z.array(NonEmptyStringSchema), assetRequirements: z.array(NonEmptyStringSchema), acceptanceCriteria: z.array(NonEmptyStringSchema) }).strict();
export const PageResponsibilityPlanSchema = DocumentBaseSchema.extend({ documentType: z.literal("page-responsibilities"), pages: z.array(PageSchema), traceability: z.array(TraceabilitySchema) }).strict();
export type PageResponsibilityPlan = z.infer<typeof PageResponsibilityPlanSchema>;

export const NavigationPlanSchema = DocumentBaseSchema.extend({ documentType: z.literal("navigation"), primary: z.array(NonEmptyStringSchema), secondary: z.array(NonEmptyStringSchema), footer: z.array(NonEmptyStringSchema), contextual: z.array(NonEmptyStringSchema), protected: z.array(NonEmptyStringSchema), mobileBehavior: NonEmptyStringSchema, ctaPlacementIntent: z.array(NonEmptyStringSchema), routeReferences: z.array(NonEmptyStringSchema), traceability: z.array(TraceabilitySchema) }).strict();
export type NavigationPlan = z.infer<typeof NavigationPlanSchema>;

const StepSchema = z.object({ order: z.number().int().positive(), description: NonEmptyStringSchema, routeId: NonEmptyStringSchema.optional(), decision: NonEmptyStringSchema.optional() }).strict();
export const UserFlowPlanSchema = DocumentBaseSchema.extend({ documentType: z.literal("user-flows"), flows: z.array(RefSchema.extend({ actor: NonEmptyStringSchema, trigger: NonEmptyStringSchema, startRoute: NonEmptyStringSchema, steps: z.array(StepSchema), dataCreated: z.array(NonEmptyStringSchema), dataRead: z.array(NonEmptyStringSchema), dataUpdated: z.array(NonEmptyStringSchema), successOutcome: NonEmptyStringSchema, failureOutcomes: z.array(NonEmptyStringSchema), authorizationRequirements: z.array(NonEmptyStringSchema), formRequirements: z.array(NonEmptyStringSchema), emailRequirements: z.array(NonEmptyStringSchema), storageRequirements: z.array(NonEmptyStringSchema), acceptanceCriteria: z.array(NonEmptyStringSchema) }).strict()), traceability: z.array(TraceabilitySchema) }).strict();
export type UserFlowPlan = z.infer<typeof UserFlowPlanSchema>;

const FormSchema = RefSchema.extend({ route: NonEmptyStringSchema, purpose: NonEmptyStringSchema, fields: z.array(z.object({ name: NonEmptyStringSchema, type: NonEmptyStringSchema, required: z.boolean(), validation: z.array(NonEmptyStringSchema) }).strict()), businessValidation: z.array(NonEmptyStringSchema), consentRequirements: z.array(NonEmptyStringSchema), submissionMechanism: z.enum(["server-action", "route-handler", "pending-decision"]), databaseWrite: NonEmptyStringSchema, emailBehavior: NonEmptyStringSchema, successState: NonEmptyStringSchema, errorState: NonEmptyStringSchema, rateLimitRequired: z.boolean(), spamProtectionRequired: z.boolean() }).strict();
export const FormPlanSchema = DocumentBaseSchema.extend({ documentType: z.literal("forms-plan"), forms: z.array(FormSchema), traceability: z.array(TraceabilitySchema) }).strict();
export type FormPlan = z.infer<typeof FormPlanSchema>;

const EntitySchema = RefSchema.extend({ name: NonEmptyStringSchema, fields: z.array(z.object({ name: NonEmptyStringSchema, type: NonEmptyStringSchema, required: z.boolean(), public: z.boolean() }).strict()), relationships: z.array(NonEmptyStringSchema), ownership: NonEmptyStringSchema, lifecycle: NonEmptyStringSchema, retention: NonEmptyStringSchema, indexingRationale: z.array(NonEmptyStringSchema), uniquenessConstraints: z.array(NonEmptyStringSchema), rlsRequired: z.boolean(), auditFields: z.array(NonEmptyStringSchema) }).strict();
export const DataModelPlanSchema = DocumentBaseSchema.extend({ documentType: z.literal("data-model-plan"), entities: z.array(EntitySchema), traceability: z.array(TraceabilitySchema) }).strict();
export type DataModelPlan = z.infer<typeof DataModelPlanSchema>;

export const AuthenticationPlanSchema = DocumentBaseSchema.extend({ documentType: z.literal("authentication-plan"), decision: z.enum(["none", "supabase-auth", "pending-blocker"]), required: z.boolean(), userRoles: z.array(NonEmptyStringSchema), signInMethods: z.array(NonEmptyStringSchema), registrationBehavior: NonEmptyStringSchema, protectedRoutes: z.array(NonEmptyStringSchema), sessionNeeds: z.array(NonEmptyStringSchema), authorizationRules: z.array(NonEmptyStringSchema), rlsRelationship: NonEmptyStringSchema, accountLifecycle: NonEmptyStringSchema, passwordReset: NonEmptyStringSchema, emailVerification: NonEmptyStringSchema, traceability: z.array(TraceabilitySchema) }).strict();
export type AuthenticationPlan = z.infer<typeof AuthenticationPlanSchema>;

export const SupabasePlanSchema = DocumentBaseSchema.extend({ documentType: z.literal("supabase-plan"), postgres: z.boolean(), auth: z.boolean(), storage: z.boolean(), realtime: z.boolean(), edgeFunctions: z.boolean(), clientBoundaries: z.array(NonEmptyStringSchema), rlsExpectations: z.array(NonEmptyStringSchema), migrationNeeds: z.array(NonEmptyStringSchema), environmentVariables: z.array(NonEmptyStringSchema), storageBuckets: z.array(NonEmptyStringSchema), policies: z.array(NonEmptyStringSchema), serviceRoleUse: NonEmptyStringSchema, anonKeyUse: NonEmptyStringSchema, traceability: z.array(TraceabilitySchema) }).strict();
export type SupabasePlan = z.infer<typeof SupabasePlanSchema>;

export const EmailPlanSchema = DocumentBaseSchema.extend({ documentType: z.literal("email-plan"), decision: z.enum(["not-required", "required-provider-pending", "required-configured-provider", "pending-blocker"]), emailTypes: z.array(NonEmptyStringSchema), triggers: z.array(NonEmptyStringSchema), recipients: z.array(NonEmptyStringSchema), senderIdentityNeeds: z.array(NonEmptyStringSchema), templatesRequired: z.array(NonEmptyStringSchema), retryExpectations: NonEmptyStringSchema, failureBehavior: NonEmptyStringSchema, privacy: z.array(NonEmptyStringSchema), environmentVariables: z.array(NonEmptyStringSchema), testingStrategy: z.array(NonEmptyStringSchema), traceability: z.array(TraceabilitySchema) }).strict();
export type EmailPlan = z.infer<typeof EmailPlanSchema>;

export const StoragePlanSchema = DocumentBaseSchema.extend({ documentType: z.literal("storage-plan"), decision: z.enum(["not-required", "supabase-storage", "pending-blocker"]), assetCategories: z.array(NonEmptyStringSchema), uploadActors: z.array(NonEmptyStringSchema), acceptedFormats: z.array(NonEmptyStringSchema), sizeLimits: z.array(NonEmptyStringSchema), validation: z.array(NonEmptyStringSchema), access: z.enum(["public", "private", "mixed", "not-applicable"]), buckets: z.array(NonEmptyStringSchema), objectPathStrategy: NonEmptyStringSchema, retention: NonEmptyStringSchema, deletionBehavior: NonEmptyStringSchema, policies: z.array(NonEmptyStringSchema), traceability: z.array(TraceabilitySchema) }).strict();
export type StoragePlan = z.infer<typeof StoragePlanSchema>;

export const AdministrationPlanSchema = DocumentBaseSchema.extend({ documentType: z.literal("administration-plan"), decision: z.enum(["no-admin", "limited-management", "full-administration", "pending-blocker"]), actors: z.array(NonEmptyStringSchema), managedEntities: z.array(NonEmptyStringSchema), permittedActions: z.array(NonEmptyStringSchema), protectedRoutes: z.array(NonEmptyStringSchema), auditNeeds: z.array(NonEmptyStringSchema), authorizationRules: z.array(NonEmptyStringSchema), traceability: z.array(TraceabilitySchema) }).strict();
export type AdministrationPlan = z.infer<typeof AdministrationPlanSchema>;

export const EnvironmentVariablePlanSchema = DocumentBaseSchema.extend({ documentType: z.literal("environment-variable-plan"), variables: z.array(z.object({ name: z.string().regex(/^[A-Z][A-Z0-9_]*$/), purpose: NonEmptyStringSchema, required: z.boolean(), serverOnly: z.boolean(), secret: z.boolean(), source: NonEmptyStringSchema, environments: z.array(NonEmptyStringSchema), validationRule: NonEmptyStringSchema, requirementReferences: z.array(NonEmptyStringSchema).min(1) }).strict()) }).strict();
export const DependencyPlanSchema = DocumentBaseSchema.extend({ documentType: z.literal("dependency-plan"), dependencies: z.array(z.object({ name: NonEmptyStringSchema, purpose: NonEmptyStringSchema, runtime: z.enum(["runtime", "dev"]), required: z.boolean(), requirementReferences: z.array(NonEmptyStringSchema).min(1), builtInInsufficientReason: NonEmptyStringSchema, securityConsiderations: z.array(NonEmptyStringSchema) }).strict()) }).strict();
export const TestStrategyPlanSchema = DocumentBaseSchema.extend({ documentType: z.literal("test-strategy"), categories: z.array(NonEmptyStringSchema), acceptanceMapping: z.array(z.object({ acceptanceCriterion: NonEmptyStringSchema, testCategories: z.array(NonEmptyStringSchema).min(1) }).strict()), excludedGates: z.array(NonEmptyStringSchema) }).strict();
export const SecurityPlanSchema = DocumentBaseSchema.extend({ documentType: z.literal("security-plan"), controls: z.array(z.object({ control: NonEmptyStringSchema, scope: NonEmptyStringSchema, requirementReferences: z.array(NonEmptyStringSchema).min(1) }).strict()), dataRetention: z.array(NonEmptyStringSchema), loggingRedaction: z.array(NonEmptyStringSchema), errorHandling: z.array(NonEmptyStringSchema) }).strict();

export const ProductScopePlanSchema = DocumentBaseSchema.extend({ documentType: z.literal("product-scope"), purpose: NonEmptyStringSchema, primaryOutcomes: z.array(NonEmptyStringSchema), secondaryOutcomes: z.array(NonEmptyStringSchema), inScopeCapabilities: z.array(NonEmptyStringSchema), outOfScopeCapabilities: z.array(NonEmptyStringSchema), userRoles: z.array(NonEmptyStringSchema), majorEntities: z.array(NonEmptyStringSchema), majorWorkflows: z.array(NonEmptyStringSchema), externalIntegrations: z.array(NonEmptyStringSchema), assumptions: z.array(NonEmptyStringSchema), constraints: z.array(NonEmptyStringSchema), acceptanceMapping: z.array(z.object({ criterion: NonEmptyStringSchema, requirementReferences: z.array(NonEmptyStringSchema).min(1) }).strict()), traceability: z.array(TraceabilitySchema) }).strict();
export type ProductScopePlan = z.infer<typeof ProductScopePlanSchema>;

export const ProfileSelectionSchema = z.object({ selectedProfile: z.enum(["marketing-site", "business-site", "web-application"]), rationale: NonEmptyStringSchema, requirementReferences: z.array(NonEmptyStringSchema).min(1), rejectedProfiles: z.array(z.object({ profile: z.enum(["marketing-site", "business-site", "web-application"]), rationale: NonEmptyStringSchema }).strict()) }).strict();
export type ProfileSelection = z.infer<typeof ProfileSelectionSchema>;

export const PlannerAgentInputSchema = z.object({ projectId: z.string().uuid(), projectVersion: z.number().int().positive(), approvedBrief: RequirementSpecificationSchema, approvedBriefChecksum: z.string().regex(/^[a-f0-9]{64}$/), originalPromptReference: NonEmptyStringSchema, clarificationEvidenceReferences: z.array(NonEmptyStringSchema), currentWorkflowState: WorkflowStateSchema, existingDecisions: z.array(z.unknown()), suppliedFiles: z.array(z.object({ path: NonEmptyStringSchema, kind: NonEmptyStringSchema, sha256: z.string().regex(/^[a-f0-9]{64}$/).optional() }).strict()), allowedSkills: z.array(NonEmptyStringSchema), idempotencyKey: NonEmptyStringSchema, expectedRowVersion: z.number().int().positive() }).strict();
export type PlannerAgentInput = z.input<typeof PlannerAgentInputSchema>;

export const PlanningPackageSchema = DocumentBaseSchema.extend({ documentType: z.literal("planning-package"), approvedBriefChecksum: z.string().regex(/^[a-f0-9]{64}$/), profile: ProfileSelectionSchema, productScope: ProductScopePlanSchema, sitemap: SitemapPlanSchema, navigation: NavigationPlanSchema, pages: PageResponsibilityPlanSchema, userFlows: UserFlowPlanSchema, forms: FormPlanSchema, dataModel: DataModelPlanSchema, authentication: AuthenticationPlanSchema, supabase: SupabasePlanSchema, email: EmailPlanSchema, storage: StoragePlanSchema, administration: AdministrationPlanSchema, content: ContentPlanSchema, assets: AssetManifestSchema, architecture: TechnicalArchitectureSchema, environment: EnvironmentVariablePlanSchema, dependencies: DependencyPlanSchema, testStrategy: TestStrategyPlanSchema, security: SecurityPlanSchema, traceability: z.array(TraceabilitySchema), blockers: z.array(NonEmptyStringSchema), accepted: z.boolean(), acceptance: z.object({ acceptedAt: IsoDateTimeSchema.optional(), acceptedBy: NonEmptyStringSchema.optional(), checksum: z.string().regex(/^[a-f0-9]{64}$/).optional() }).strict() }).strict();
export type PlanningPackage = z.infer<typeof PlanningPackageSchema>;
export const PlannerAnalysisResultSchema = z.object({ profile: ProfileSelectionSchema, planningPackage: PlanningPackageSchema }).strict();
