import { checksumPersistedDocument } from "@/persistence/database/serialization";
import { TestQualityReviewProviderOutputSchema, type TestQualityReviewResult } from "@/domain/review/schema";
import { TestQualityReviewInputSchema, type TestQualityReviewInput } from "./contracts";
import type { TestQualityReviewProvider } from "./ports";

const finding = (id: string, category: TestQualityReviewResult["findings"][number]["category"], summary: string, refs: string[], target: TestQualityReviewResult["findings"][number]["correctionTarget"], ownerTaskId?: string) => ({ findingId: id, severity: "ERROR" as const, category, summary, evidenceRefs: refs, affectedArtifacts: refs, recommendedAction: ownerTaskId ? `Correct the bounded behavior or validation owned by task ${ownerTaskId}.` : "Add or correct the smallest meaningful validation evidence and rerun quality review.", correctionTarget: target, ...(ownerTaskId ? { ownerTaskId } : {}) });
const has = (input: TestQualityReviewInput, pattern: RegExp) => pattern.test(JSON.stringify(input.approvedBrief)) || pattern.test(JSON.stringify(input.acceptedPlanningPackage));

export function deterministicTestQualityReview(raw: TestQualityReviewInput) {
  const input = TestQualityReviewInputSchema.parse(raw); const findings: TestQualityReviewResult["findings"] = [];
  const stale = input.qualityEvidence.sourceChecksum !== input.sourceChecksum || input.qualityEvidence.testSourceChecksum !== input.testSourceChecksum || input.qualityEvidence.qualityGates.some((gate) => gate.sourceChecksum !== input.sourceChecksum) || input.qualityEvidence.unitTests.sourceChecksum !== input.sourceChecksum;
  if (stale) findings.push(finding("quality-evidence-stale", "QUALITY_EVIDENCE_STALE", "Quality evidence is not bound to the current application and test source checksums.", ["quality-evidence", "source"], "UPSTREAM_TEST_CONTRACT"));
  const canonical = [["brief", input.approvedBrief, input.briefChecksum], ["planning-package", input.acceptedPlanningPackage, input.planningChecksum], ["architecture-review", input.approvedArchitectureReview, input.architectureReviewChecksum], ["selected-design", input.selectedDesign, input.designChecksum], ["contract-audit", input.approvedContractAudit, input.contractAuditChecksum], ["code-integration-review", input.approvedCodeIntegrationReview, input.codeIntegrationReviewChecksum], ["security-review", input.approvedSecurityReview, input.securityReviewChecksum]] as const;
  for (const [name, document, expected] of canonical) if (checksumPersistedDocument(document) !== expected) findings.push(finding(`${name}-stale`, "QUALITY_EVIDENCE_STALE", `Bound ${name} evidence is stale for this review.`, [name], "UPSTREAM_TEST_CONTRACT"));
  if (input.taskGraph.graphChecksum !== input.taskGraphChecksum) findings.push(finding("task-graph-stale", "QUALITY_EVIDENCE_STALE", "Bound TaskGraph evidence is stale for this review.", ["task-graph"], "UPSTREAM_TEST_CONTRACT"));
  for (const gate of input.qualityEvidence.qualityGates) if (gate.status !== "PASSED") findings.push(finding(`quality-gate-${gate.name}`, "TEST_CONTRACT_MISMATCH", `Required deterministic quality gate ${gate.name} is not passing.`, gate.evidenceRefs, "UPSTREAM_TEST_CONTRACT"));
  if (input.approvedCodeIntegrationReview.result.verdict !== "APPROVED") findings.push(finding("code-review-not-approved", "TEST_CONTRACT_MISMATCH", "Test Quality Review requires a current approved Code / Integration Review.", ["code-integration-review"], "UPSTREAM_TEST_CONTRACT"));
  if (input.approvedSecurityReview.result.verdict !== "APPROVED") findings.push(finding("security-review-not-approved", "TEST_CONTRACT_MISMATCH", "Test Quality Review requires a current approved Security Review or policy-approved low-surface result.", ["security-review"], "UPSTREAM_TEST_CONTRACT"));
  for (const trace of input.qualityEvidence.requirements) {
    if (!trace.evidenceRefs.length && trace.validationResponsibility !== "NONE") findings.push(finding(`requirement-${trace.requirementId.replace(/[^a-z0-9]+/gi, "-").toLowerCase()}`, trace.validationResponsibility === "FUNCTIONAL_QA" ? "CRITICAL_FLOW_NOT_VERIFIED" : "REQUIREMENT_NOT_VERIFIED", `Approved requirement ${trace.requirementId} has no executed evidence for its validation responsibility.`, [trace.requirementId, "quality-evidence"], trace.validationResponsibility === "FUNCTIONAL_QA" ? "FUNCTIONAL_QA_TASK" : "TEST_TASK", trace.implementationTaskIds[0]));
  }
  const importantForm = input.acceptedPlanningPackage.forms.forms.length > 0 || has(input, /contact|submit|form/i);
  if (importantForm && !input.qualityEvidence.functionalScenarios.some((s) => s.flowKind === "form" && s.status === "PASSED" && s.assertions.some((a) => /success|confirm|submitted|result/i.test(a)))) findings.push(finding("form-submit-unverified", "FORM_FLOW_NOT_VERIFIED", "An approved form or submit behavior has no functional evidence asserting its resulting success state.", ["planning-package", "quality-evidence"], "FUNCTIONAL_QA_TASK"));
  const auth = input.acceptedPlanningPackage.authentication.required || has(input, /authentication|protected route|login|logout/i);
  if (auth && !input.qualityEvidence.functionalScenarios.some((s) => s.flowKind === "auth" && s.status === "PASSED" && s.assertions.some((a) => /protected|unauthenticated|authenticated|login/i.test(a)))) findings.push(finding("auth-flow-unverified", "AUTH_FLOW_NOT_VERIFIED", "Authentication or protected behavior is approved but no functional protected-flow evidence is present.", ["planning-package", "quality-evidence"], "FUNCTIONAL_QA_TASK"));
  const persistence = input.acceptedPlanningPackage.dataModel.entities.length > 0 || input.acceptedPlanningPackage.supabase.postgres;
  if (persistence && !input.qualityEvidence.functionalScenarios.some((s) => s.flowKind === "data" && s.status === "PASSED" && s.assertions.some((a) => /persist|created|updated|saved|stored/i.test(a))) && !input.qualityEvidence.requirements.some((t) => t.validationResponsibility === "INTEGRATION" && t.evidenceRefs.length)) findings.push(finding("data-flow-unverified", "DATA_FLOW_NOT_VERIFIED", "Approved persistence behavior has no meaningful evidence of its required consequence.", ["planning-package", "quality-evidence"], "TEST_TASK"));
  if (input.qualityEvidence.unitTests.status === "PASSED" && !input.qualityEvidence.unitTests.meaningfulAssertions) findings.push(finding("weak-unit-assertions", "WEAK_ASSERTION", "Unit-test evidence is marked passing but does not contain meaningful assertions for the bounded requirements.", input.qualityEvidence.unitTests.evidenceRefs, "TEST_TASK"));
  for (const scenario of input.qualityEvidence.functionalScenarios) if (scenario.status === "PASSED" && !scenario.assertions.length) findings.push(finding(`scenario-${scenario.scenarioId.replace(/[^a-z0-9]+/gi, "-").toLowerCase()}`, "FUNCTIONAL_SCENARIO_INCOMPLETE", `Functional scenario ${scenario.scenarioId} has no outcome assertion.`, scenario.evidenceRefs, "FUNCTIONAL_QA_TASK"));
  const result = { verdict: findings.length ? "CHANGES_REQUIRED" as const : "APPROVED" as const, findings, reviewedArtifactRefs: ["brief", "planning-package", "task-graph", "source", "quality-evidence"] };
  return TestQualityReviewProviderOutputSchema.parse(result);
}
export class DeterministicTestQualityReviewProvider implements TestQualityReviewProvider { readonly promptVersion = "test-quality-reviewer.v1"; async review(input: TestQualityReviewInput) { return deterministicTestQualityReview(input); } }
