export type FunctionalQaErrorCode =
  | "QA_NOT_READY" | "QA_RUNTIME_VALIDATION_INCOMPLETE" | "QA_TOOL_NOT_ALLOWED" | "QA_PROJECT_STATE_STALE" | "QA_WORKSPACE_INVALID"
  | "QA_URL_NOT_ALLOWED" | "QA_SERVER_START_FAILED" | "QA_SERVER_BUILD_NOT_FOUND" | "QA_SERVER_READY_TIMEOUT" | "QA_SERVER_RUNTIME_FAILED" | "QA_SERVER_STOP_FAILED" | "QA_ORPHAN_PROCESS"
  | "QA_CANCELLED" | "QA_TIMEOUT" | "QA_ROUTE_MISSING" | "QA_ROUTE_RUNTIME_ERROR" | "QA_ROUTE_ACCESS_MISMATCH"
  | "QA_NAVIGATION_BROKEN" | "QA_FORM_VALIDATION_FAILURE" | "QA_AUTHORIZATION_FAILURE" | "QA_BROWSER_RUNTIME_ERROR"
  | "QA_BROWSER_EXECUTABLE_NOT_FOUND" | "QA_BROWSER_LAUNCH_FAILED" | "QA_BROWSER_CRASHED" | "QA_BROWSER_CONTEXT_FAILED" | "QA_BROWSER_PAGE_FAILED" | "QA_BROWSER_NAVIGATION_FAILED" | "QA_BROWSER_DISCONNECTED" | "QA_BROWSER_TIMEOUT" | "QA_APPLICATION_RUNTIME_ERROR"
  | "QA_EXTERNAL_REQUEST_BLOCKED" | "QA_ASSERTION_FAILED" | "QA_RECONCILIATION_FAILED"
  | "QA_WORKSPACE_OWNERSHIP_UNVERIFIED" | "QA_WORKSPACE_PATH_UNSAFE" | "QA_WORKSPACE_ACTIVE"
  | "QA_PROCESS_TERMINATION_FAILED" | "QA_WORKSPACE_CLEANUP_RETRY_EXHAUSTED" | "QA_WORKSPACE_CLEANUP_FAILED"
  | "QA_WORKSPACE_MARKER_INVALID" | "QA_WORKSPACE_LEGACY_OWNERSHIP_UNVERIFIED";

export class FunctionalQaError extends Error {
  constructor(readonly code: FunctionalQaErrorCode, message: string, readonly cause?: unknown) { super(message); this.name = "FunctionalQaError"; }
}
