import { mkdtemp, rm } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { describe, expect, it } from "vitest";
import { assertLocalhostRoute, assertLocalhostUrl, assertSafeTestServerScript, deriveFunctionalQaPlan, validateQaReadiness } from "./policy";
import { FunctionalQaError } from "./errors";
import { DeterministicFakeBrowserRunner } from "./fake";
import { FunctionalQaService } from "./service";
import { buildLocalTestServerCommand } from "./server";
import { completeFunctionalQaTask, startFunctionalQaTask } from "./task";
import { reconcileFunctionalQa } from "./reconcile";
import { QaWorkspaceLifecycle } from "./workspace";
import { FunctionalQaMemorySummarySchema, FunctionalQaPlanSchema, type FunctionalQaPlan, type LocalServerHandle, type LocalServerLauncher, type FunctionalQaReport } from "./contracts";
import type { PlanningPackage } from "@/agents/planner/contracts";
import type { RequirementSpecification } from "@/domain/requirements/schema";
import type { AgentTask } from "@/domain/tasks/schema";

const projectId = "11111111-1111-4111-8111-111111111111"; const taskId = "22222222-2222-4222-8222-222222222222"; const checksum = "a".repeat(64); const runtime = { overallStatus: "passed" as const, validationRunId: "33333333-3333-4333-8333-333333333333", packageChecksum: checksum, lockfileChecksum: "b".repeat(64) };

class FakeServer implements LocalServerLauncher { handle?: LocalServerHandle; async start(input: { port: number }) { this.handle = { pid: 123, port: input.port, baseUrl: `http://127.0.0.1:${input.port}` }; return this.handle; } async waitForReady() { return 200; } async stop() { this.handle = undefined; } async isRunning() { return Boolean(this.handle); } }
class FailingServer implements LocalServerLauncher { async start(): Promise<LocalServerHandle> { throw new FunctionalQaError("QA_SERVER_START_FAILED", "The generated start:test script is missing."); } async stop() {} async isRunning() { return false; } }
class ReadinessTimeoutServer implements LocalServerLauncher { handle?: LocalServerHandle; async start(input: { port: number }) { this.handle = { pid: 456, port: input.port, baseUrl: `http://127.0.0.1:${input.port}` }; return this.handle; } async waitForReady(): Promise<number> { throw new FunctionalQaError("QA_SERVER_READY_TIMEOUT", "The local test server did not become ready in time."); } async stop() { this.handle = undefined; } async isRunning() { return Boolean(this.handle); } }
class TimeoutServer implements LocalServerLauncher { handle?: LocalServerHandle; async start(input: { port: number }) { this.handle = { pid: 457, port: input.port, baseUrl: `http://127.0.0.1:${input.port}` }; return this.handle; } async waitForReady(_handle: LocalServerHandle, _timeoutMs: number, signal?: AbortSignal): Promise<number> { await new Promise<void>((resolve, reject) => { signal?.addEventListener("abort", () => reject(new FunctionalQaError("QA_TIMEOUT", "The QA server readiness operation timed out.")), { once: true }); }); return 200; } async stop() { this.handle = undefined; } async isRunning() { return Boolean(this.handle); } }
class FailingStopServer implements LocalServerLauncher { handle?: LocalServerHandle; async start(input: { port: number }) { this.handle = { pid: 458, port: input.port, baseUrl: `http://127.0.0.1:${input.port}` }; return this.handle; } async waitForReady() { return 200; } async stop() { throw new FunctionalQaError("QA_PROCESS_TERMINATION_FAILED", "Synthetic owned process termination failure."); } async isRunning() { return Boolean(this.handle); } }
class UnexpectedBrowser extends DeterministicFakeBrowserRunner { override async launch(): Promise<void> { throw new Error("unexpected browser runtime exception"); } }
function task(status: AgentTask["status"] = "ready"): AgentTask { return { id: taskId, projectId, projectVersion: 1, role: "qa-release", taskType: "validate-functional-flow", title: "Functional QA", objective: "Run approved functional QA", inputs: ["runtime report"], expectedOutputs: ["QA report"], acceptanceCriteria: ["Approved scenarios pass"], allowedSkills: [], allowedTools: ["filesystem-read", "Playwright-functional"], deniedTools: ["git-write"], fileScopes: [], dependencies: ["44444444-4444-4444-8444-444444444444"], status, priority: "normal", executionMode: "validation-only", attempt: 0, maxAttempts: 1, createdAt: "2026-01-01T00:00:00.000Z", ...(status === "running" ? { startedAt: "2026-01-01T00:00:00.000Z" } : {}), ...(status === "passed" || status === "failed" || status === "cancelled" ? { completedAt: "2026-01-01T00:00:00.000Z" } : {}), blockingFailure: true, estimatedContextBytes: 1000, expectedArtifactTypes: ["validation-report"] }; }
function plan(): FunctionalQaPlan { return FunctionalQaPlanSchema.parse({ planId: "55555555-5555-4555-8555-555555555555", projectId, projectVersion: 1, scenarios: [{ scenarioId: "route:home", title: "Home route", actor: "Visitor", purpose: "Load home", acceptanceCriteriaReferences: ["acceptance:home"], requirementReferences: ["requirement:home"], userFlowReferences: [], startRoute: "/", preconditions: [], steps: [{ order: 1, action: "navigate", route: "/", timeoutMs: 1000 }, { order: 2, action: "assertStatus", expectedStatus: 200, timeoutMs: 1000 }, { order: 3, action: "assertUrl", expectedUrl: "/", timeoutMs: 1000 }], assertions: [{ category: "route", expected: "Home returns 200", mandatory: true }], expectedOutcome: "Home loads", failureCategory: "QA_ROUTE_MISSING", requiresAuth: false, requiresForm: false, requiresDatabaseFixture: false, timeoutMs: 10000 }], selectedBriefChecksum: checksum, selectedPlanningChecksum: checksum, selectedDesignChecksum: checksum, policyVersion: "playwright-functional-v1" }); }
function readiness(overrides: Partial<Parameters<typeof validateQaReadiness>[0]> = {}) { return { projectId, projectVersion: 1, workspacePath: "C:\\generated\\project\\v1", generatedProjectsRoot: "C:\\generated", mutable: true, runtimeValidation: runtime, task: task(), expectedBriefChecksum: checksum, expectedPlanningChecksum: checksum, expectedDesignChecksum: checksum, actualBriefChecksum: checksum, actualPlanningChecksum: checksum, actualDesignChecksum: checksum, blockingImplementationTask: false, fixturesAvailable: true, ...overrides }; }
async function ownedQaInput() { const root = await mkdtemp(path.join(os.tmpdir(), "factory-qa-service-")); const lifecycle = new QaWorkspaceLifecycle({ authorizedRoot: root, isProcessAlive: async () => false, sleep: async () => undefined }); const qa = await lifecycle.create({ projectId, projectVersion: 1 }); return { root, lifecycle, qa, input: { projectId, projectVersion: 1, taskId, workspacePath: qa.projectPath, generatedProjectsRoot: qa.workspacePath, qaWorkspace: qa, runtimeValidation: runtime, plan: plan(), readiness: readiness({ workspacePath: qa.projectPath, generatedProjectsRoot: qa.workspacePath }) } }; }

describe("Playwright functional QA foundation", () => {
  it("accepts only the assigned loopback URL and rejects external schemes", () => { expect(assertLocalhostUrl("http://127.0.0.1:4173/", 4173).pathname).toBe("/"); expect(assertLocalhostRoute("/contact", 4173).pathname).toBe("/contact"); for (const value of ["https://example.com/", "file:///tmp/a", "javascript:alert(1)", "http://192.168.1.1:4173/"]) expect(() => assertLocalhostUrl(value, 4173)).toThrow(FunctionalQaError); });
  it("rejects incomplete runtime, wrong task, missing permission, stale inputs, and invalid workspace", () => { expect(() => validateQaReadiness(readiness({ runtimeValidation: undefined }))).toThrow("Runtime validation"); expect(() => validateQaReadiness(readiness({ task: { ...task(), taskType: "validate-build" } }))).toThrow("READY"); expect(() => validateQaReadiness(readiness({ task: { ...task(), allowedTools: ["filesystem-read"] } }))).toThrow("Playwright"); expect(() => validateQaReadiness(readiness({ actualBriefChecksum: "c".repeat(64) }))).toThrow("stale"); expect(() => validateQaReadiness(readiness({ workspacePath: "C:\\other" }))).toThrow("staging"); });
  it("derives only planned route and approved form scenarios", () => { const brief = { userAcceptanceCriteria: ["Home loads"] , targetAudiences: ["Visitor"] } as unknown as RequirementSpecification; const planning = { sitemap: { routes: [{ id: "home", path: "/", titlePurpose: "Home", intendedUser: "Visitor", primaryGoal: "Learn", requirementReferences: ["requirement:home"], visibility: "public", formDependencies: [] }] }, forms: { forms: [] }, userFlows: { flows: [] }, authentication: { required: false } } as unknown as PlanningPackage; const derived = deriveFunctionalQaPlan({ projectId, projectVersion: 1, brief, planning, briefChecksum: checksum, planningChecksum: checksum, designChecksum: checksum }); expect(derived.scenarios.map((scenario) => scenario.startRoute)).toEqual(["/"]); expect(derived.scenarios.some((scenario) => scenario.startRoute === "/unplanned")).toBe(false); });
  it("runs deterministic local navigation QA and persists a passed QualityCheck", async () => { const browser = new DeterministicFakeBrowserRunner(); const server = new FakeServer(); const report = await new FunctionalQaService(server, browser).run({ projectId, projectVersion: 1, taskId, workspacePath: "C:\\generated\\project\\v1", generatedProjectsRoot: "C:\\generated", runtimeValidation: runtime, plan: plan(), readiness: { ...readiness(), task: task() } }); expect(report.status).toBe("passed"); expect(report.qualityCheck.status).toBe("passed"); expect(report.scenarios[0]?.status).toBe("passed"); expect(browser.operations).toContain("close"); expect(server.handle).toBeUndefined(); });
  it("preserves canonical scenario, route, and step identity when browser dispatch fails", async () => { const canonical = plan(); const scenario = canonical.scenarios[0]!; const tracedPlan = FunctionalQaPlanSchema.parse({ ...canonical, scenarios: [{ ...scenario, scenarioType: "route", steps: scenario.steps.map((step) => ({ ...step, stepId: `route:home:step:${step.order}` })) }] }); const report = await new FunctionalQaService(new FakeServer(), new DeterministicFakeBrowserRunner({ failingAction: "navigate:/" })).run({ projectId, projectVersion: 1, taskId, workspacePath: "C:\\generated\\project\\v1", generatedProjectsRoot: "C:\\generated", runtimeValidation: runtime, plan: tracedPlan, readiness: readiness() }); expect(report.runId).not.toBe(report.scenarios[0]?.scenarioId); expect(report.scenarios[0]).toMatchObject({ scenarioId: "route:home", route: "/", status: "failed" }); expect(report.scenarios[0]?.evidence[0]).toMatchObject({ scenarioId: "route:home", stepId: "route:home:step:1", stepIndex: 0, route: "/", action: "navigate" }); expect(report.diagnostics[0]).toMatchObject({ scenarioId: "route:home", route: "/", stepId: "route:home:step:1" }); });
  it("preserves a precise missing-route classification at navigation", async () => { const report = await new FunctionalQaService(new FakeServer(), new DeterministicFakeBrowserRunner({ navigationStatus: 404 })).run({ projectId, projectVersion: 1, taskId, workspacePath: "C:\\generated\\project\\v1", generatedProjectsRoot: "C:\\generated", runtimeValidation: runtime, plan: plan(), readiness: readiness() }); expect(report.scenarios[0]).toMatchObject({ status: "failed", safeFailureCode: "QA_ROUTE_MISSING" }); expect(report.diagnostics[0]).toMatchObject({ category: "QA_ROUTE_MISSING", scenarioId: "route:home", route: "/" }); });
  it("maps browser/external failures and never records screenshot, HTML, cookies, or tokens", async () => { const browser = new DeterministicFakeBrowserRunner({ externalRequest: true }); const report = await new FunctionalQaService(new FakeServer(), browser).run({ projectId, projectVersion: 1, taskId, workspacePath: "C:\\generated\\project\\v1", generatedProjectsRoot: "C:\\generated", runtimeValidation: runtime, plan: plan(), readiness: readiness() }); expect(report.status).toBe("failed"); expect(report.unexpectedExternalRequests).toHaveLength(1); expect(JSON.stringify(report)).not.toMatch(/screenshot|html|cookie|token/i); });
  it("classifies server-start infrastructure failure before spawn and scenario dispatch", async () => { const report = await new FunctionalQaService(new FailingServer(), new DeterministicFakeBrowserRunner()).run({ projectId, projectVersion: 1, taskId, workspacePath: "C:\\generated\\project\\v1", generatedProjectsRoot: "C:\\generated", runtimeValidation: runtime, plan: plan(), readiness: readiness() }); expect(report.runLevelDiagnostic).toMatchObject({ safeErrorCode: "QA_SERVER_START_FAILED", lifecyclePhase: "server-start", processSpawned: false, serverReady: false, browserLaunched: false, contextCreated: false, pageCreated: false, scenarioDispatchStarted: false, firstNavigationAttempted: false }); expect(report.scenarios).toHaveLength(0); expect(report.diagnostics).toHaveLength(0); });
  it("classifies readiness timeout as run-level infrastructure failure with preserved lifecycle context", async () => { const report = await new FunctionalQaService(new ReadinessTimeoutServer(), new DeterministicFakeBrowserRunner()).run({ projectId, projectVersion: 1, taskId, workspacePath: "C:\\generated\\project\\v1", generatedProjectsRoot: "C:\\generated", runtimeValidation: runtime, plan: plan(), readiness: readiness() }); expect(report.runLevelDiagnostic).toMatchObject({ safeErrorCode: "QA_SERVER_READY_TIMEOUT", lifecyclePhase: "server-readiness", processSpawned: true, serverReady: false, browserLaunched: false, contextCreated: false, pageCreated: false, scenarioDispatchStarted: false, firstNavigationAttempted: false, lifecycle: { readinessProbeStarted: true, readinessSucceeded: false, browserLaunchAttempted: false, primaryFailurePhase: "server-readiness", cleanupStarted: true, cleanupCompleted: true } }); expect(report.scenarios).toHaveLength(0); expect(report.diagnostics).toHaveLength(0); });
  it("transitions only the functional QA task and does not execute dependent tasks", async () => { const running = startFunctionalQaTask(task(), "2026-01-01T00:00:00.000Z"); expect(running.status).toBe("running"); const fakeReport = { status: "passed", qualityCheck: { status: "passed" } } as unknown as FunctionalQaReport; expect(completeFunctionalQaTask(running, fakeReport, "2026-01-01T00:01:00.000Z").status).toBe("passed"); });
  it("stores only the bounded Project Memory summary shape", () => { const summary = FunctionalQaMemorySummarySchema.parse({ schemaVersion: 1, documentType: "functional-qa", projectId, projectVersion: 1, createdAt: "2026-01-01T00:00:00.000Z", updatedAt: "2026-01-01T00:00:00.000Z", runId: "66666666-6666-4666-8666-666666666666", status: "passed", passedCount: 1, failedCount: 0, skippedCount: 0, scenarioStatuses: [{ scenarioId: "route:home", status: "passed" }], qualityCheckReference: "quality-report:e2e", runtimeValidationPackageChecksum: checksum, policyVersion: "playwright-functional-v1" }); expect(summary).not.toHaveProperty("html"); expect(summary).not.toHaveProperty("screenshot"); });
  it("uses the approved npm start:test contract and forwards the allocated loopback port", () => { expect(buildLocalTestServerCommand(43127)).toEqual({ script: "start:test", args: ["run", "start:test", "--", "--hostname", "127.0.0.1", "--port", "43127"], host: "127.0.0.1", port: "43127" }); expect(() => assertSafeTestServerScript("next start")).not.toThrow(); });
  it("restricts the local server script and reconciles stale reports", async () => { expect(() => assertSafeTestServerScript("node server.js")).not.toThrow(); expect(() => assertSafeTestServerScript("npm run build && deploy")).toThrow(); const report = await new FunctionalQaService(new FakeServer(), new DeterministicFakeBrowserRunner()).run({ projectId, projectVersion: 1, taskId, workspacePath: "C:\\generated\\project\\v1", generatedProjectsRoot: "C:\\generated", runtimeValidation: runtime, plan: plan(), readiness: readiness() }); const issues = reconcileFunctionalQa({ report, activeBrowser: false, activeServer: false, qualityCheckPresent: false, currentProjectId: projectId, currentProjectVersion: 1, currentRuntimeValidationPackageChecksum: "c".repeat(64), currentRuntimeValidationLockfileChecksum: runtime.lockfileChecksum, currentBriefChecksum: checksum, currentPlanningChecksum: checksum, currentDesignChecksum: checksum, expectedRuntimeValidationRunId: runtime.validationRunId }); expect(issues.map((issue) => issue.code)).toContain("QA_RECONCILIATION_FAILED"); expect(issues.map((issue) => issue.code)).toContain("QA_PROJECT_STATE_STALE"); });
  it("cleans an owned workspace after assertion and browser failure while preserving the QA report", async () => { const value = await ownedQaInput(); try { const report = await new FunctionalQaService(new FakeServer(), new DeterministicFakeBrowserRunner({ failingAction: "navigate:/" })).run(value.input); expect(report.status).toBe("failed"); expect(report.scenarios[0]?.safeFailureCode).toBe("QA_ASSERTION_FAILED"); expect(report.qaWorkspaceCleanup).toMatchObject({ removed: true, verifiedAbsent: true, reason: "failure" }); } finally { await rm(value.root, { recursive: true, force: true }); } });
  it("cleans an owned workspace after server-start failure and validation failure", async () => { const value = await ownedQaInput(); try { const report = await new FunctionalQaService(new FailingServer(), new DeterministicFakeBrowserRunner()).run(value.input); expect(report.runLevelDiagnostic?.safeErrorCode).toBe("QA_SERVER_START_FAILED"); expect(report.qaWorkspaceCleanup).toMatchObject({ removed: true, verifiedAbsent: true }); } finally { await rm(value.root, { recursive: true, force: true }); } const invalid = await ownedQaInput(); await expect(new FunctionalQaService(new FakeServer(), new DeterministicFakeBrowserRunner()).run({ ...invalid.input, readiness: readiness({ workspacePath: invalid.qa.projectPath, generatedProjectsRoot: invalid.qa.workspacePath, actualBriefChecksum: "c".repeat(64) }) })).rejects.toMatchObject({ code: "QA_PROJECT_STATE_STALE" }); expect(await invalid.lifecycle.inventory()).toEqual([]); await rm(invalid.root, { recursive: true, force: true }); });
  it("cleans an owned workspace after an unexpected browser exception", async () => { const value = await ownedQaInput(); try { const report = await new FunctionalQaService(new FakeServer(), new UnexpectedBrowser()).run(value.input); expect(report.status).toBe("failed"); expect(report.runLevelFailure?.safeErrorCode).toBe("QA_BROWSER_LAUNCH_FAILED"); expect(report.qaWorkspaceCleanup).toMatchObject({ removed: true, verifiedAbsent: true, reason: "failure" }); } finally { await rm(value.root, { recursive: true, force: true }); } });
  it("cleans on timeout and explicit cancellation", async () => { const timeout = await ownedQaInput(); try { const report = await new FunctionalQaService(new TimeoutServer(), new DeterministicFakeBrowserRunner()).run({ ...timeout.input, totalTimeoutMs: 5 }); expect(report.status).toBe("failed"); expect(report.qaWorkspaceCleanup).toMatchObject({ reason: "timeout", removed: true, verifiedAbsent: true }); } finally { await rm(timeout.root, { recursive: true, force: true }); } const cancelled = await ownedQaInput(); const controller = new AbortController(); controller.abort(); try { const report = await new FunctionalQaService(new FakeServer(), new DeterministicFakeBrowserRunner()).run({ ...cancelled.input, signal: controller.signal }); expect(report.status).toBe("cancelled"); expect(report.qaWorkspaceCleanup).toMatchObject({ reason: "cancellation", removed: true, verifiedAbsent: true }); } finally { await rm(cancelled.root, { recursive: true, force: true }); } });
  it("records process termination failure without deleting before owned resources exit", async () => { const value = await ownedQaInput(); try { const report = await new FunctionalQaService(new FailingStopServer(), new DeterministicFakeBrowserRunner()).run(value.input); expect(report.status).toBe("failed"); expect(report.qaWorkspaceCleanup).toMatchObject({ removed: false, verifiedAbsent: false, deferred: true, failureCode: "QA_PROCESS_TERMINATION_FAILED" }); await expect(value.qa.cleanup({ resourcesStopped: true, processesExited: true, reason: "failure" })).resolves.toMatchObject({ removed: true, verifiedAbsent: true }); } finally { await rm(value.root, { recursive: true, force: true }); } });
});
