import { createHash, randomUUID } from "node:crypto";
import { mkdtemp, mkdir, readFile, rm as remove, symlink, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { QA_WORKSPACE_MARKER_NAME, QA_WORKSPACE_PREFIX, QaWorkspaceLifecycle, QaWorkspaceMarkerSchema } from "./workspace";

const projectId = "11111111-1111-4111-8111-111111111111";
const roots: string[] = [];
const rootIdentity = (root: string) => createHash("sha256").update(path.resolve(root).toLowerCase(), "utf8").digest("hex");
const errorWithCode = (code: string) => Object.assign(new Error(code), { code });

afterEach(async () => { await Promise.all(roots.splice(0).map((root) => remove(root, { recursive: true, force: true }))); });

async function fixture(options: Partial<ConstructorParameters<typeof QaWorkspaceLifecycle>[0]> = {}) {
  const root = await mkdtemp(path.join(os.tmpdir(), "factory-qa-lifecycle-"));
  roots.push(root);
  return { root, lifecycle: new QaWorkspaceLifecycle({ authorizedRoot: root, isProcessAlive: async () => false, sleep: async () => undefined, ...options }) };
}

async function manualWorkspace(root: string, overrides: Record<string, unknown> = {}) {
  const target = await mkdtemp(path.join(root, QA_WORKSPACE_PREFIX));
  const marker = QaWorkspaceMarkerSchema.parse({ schemaVersion: 1, workspaceKind: "QA_FOUNDATION", workspaceId: randomUUID(), qaRunId: randomUUID(), factoryProjectIdentity: { projectId, projectVersion: 1 }, authorizedRootIdentity: rootIdentity(root), createdAt: new Date().toISOString(), ownerProcessId: 999999, ownerSessionId: randomUUID(), state: "ACTIVE", ...overrides });
  await writeFile(path.join(target, QA_WORKSPACE_MARKER_NAME), `${JSON.stringify(marker)}\n`, { encoding: "utf8", flag: "wx" });
  return { target, marker };
}

const cleanupOptions = { reason: "reconciliation" as const, resourcesStopped: true, processesExited: true, allowReconciliation: true };

describe("QA workspace ownership and lifecycle", () => {
  it("E1 creates a host-owned marker with unique workspace and run identity", async () => { const { lifecycle } = await fixture(); const handle = await lifecycle.create({ projectId, projectVersion: 1 }); const marker = JSON.parse(await readFile(path.join(handle.workspacePath, QA_WORKSPACE_MARKER_NAME), "utf8")); expect(QaWorkspaceMarkerSchema.parse(marker)).toMatchObject({ workspaceKind: "QA_FOUNDATION", workspaceId: handle.workspaceId, qaRunId: handle.qaRunId, ownerProcessId: process.pid, state: "CREATED" }); expect(handle.workspaceId).not.toBe(handle.qaRunId); await handle.cleanup(); });
  it("E2 rejects invalid markers and E3 preserves a prefix-only directory", async () => { const { root, lifecycle } = await fixture(); const invalid = await mkdtemp(path.join(root, QA_WORKSPACE_PREFIX)); await writeFile(path.join(invalid, QA_WORKSPACE_MARKER_NAME), "not-json", "utf8"); const random = await mkdtemp(path.join(root, QA_WORKSPACE_PREFIX)); const result = await lifecycle.reconcile(); expect(result.cleaned).toBe(0); expect(result.preserved).toBe(2); expect(result.entries.every((entry) => entry.classification === "UNVERIFIED_PREFIX_MATCH")).toBe(true); expect(await readFile(path.join(invalid, QA_WORKSPACE_MARKER_NAME), "utf8")).toBe("not-json"); expect(await readFile(path.join(random, "missing"), "utf8").catch(() => "missing")).toBe("missing"); });
  it("E4-E6 reject outside-root, repository-root, and traversal targets", async () => { const { root, lifecycle } = await fixture(); const options = { reason: "normal" as const, resourcesStopped: true, processesExited: true }; await expect(lifecycle.cleanupPath(path.dirname(root), options)).rejects.toMatchObject({ code: "QA_WORKSPACE_PATH_UNSAFE" }); await expect(lifecycle.cleanupPath(root, options)).rejects.toMatchObject({ code: "QA_WORKSPACE_PATH_UNSAFE" }); await expect(lifecycle.cleanupPath(path.join(root, "..", path.basename(root)), options)).rejects.toMatchObject({ code: "QA_WORKSPACE_PATH_UNSAFE" }); });
  it("E7 rejects a link that resolves outside the authorized root", async () => { const { root, lifecycle } = await fixture(); const { target } = await manualWorkspace(root); const outside = await mkdtemp(path.join(os.tmpdir(), "factory-qa-outside-")); roots.push(outside); await symlink(outside, path.join(target, "escape"), "junction"); await expect(lifecycle.cleanupPath(target, cleanupOptions)).rejects.toMatchObject({ code: "QA_WORKSPACE_PATH_UNSAFE" }); expect(await readFile(path.join(target, QA_WORKSPACE_MARKER_NAME), "utf8")).toContain("QA_FOUNDATION"); });
  it("E8 fails a marker/path collision without deleting the existing workspace", async () => { const { root } = await fixture(); const existing = await manualWorkspace(root); const lifecycle = new QaWorkspaceLifecycle({ authorizedRoot: root, fileSystem: { mkdtemp: async () => existing.target }, sleep: async () => undefined, isProcessAlive: async () => false }); await expect(lifecycle.create({ projectId, projectVersion: 1 })).rejects.toBeInstanceOf(Error); expect(await readFile(path.join(existing.target, QA_WORKSPACE_MARKER_NAME), "utf8")).toContain(existing.marker.workspaceId); });
  it("E9 removes a successful workspace and verifies terminal absence", async () => { const { lifecycle } = await fixture(); const handle = await lifecycle.create({ projectId, projectVersion: 1 }); const result = await handle.cleanup({ reason: "success" }); expect(result).toMatchObject({ attempted: true, removed: true, verifiedAbsent: true, deferred: false, state: "CLEANED" }); await expect(readFile(handle.workspacePath, "utf8")).rejects.toBeTruthy(); });
  it("E10-E16 keep cleanup separate from the primary failure and record failure/timeout/cancellation reasons", async () => { const { lifecycle } = await fixture(); for (const reason of ["failure", "timeout", "cancellation"] as const) { const handle = await lifecycle.create({ projectId, projectVersion: 1 }); const primaryExecutionFailure = "QA_ASSERTION_FAILED"; const result = await handle.cleanup({ reason }); expect(primaryExecutionFailure).toBe("QA_ASSERTION_FAILED"); expect(result.reason).toBe(reason); expect(result.verifiedAbsent).toBe(true); } });
  it("E17-E21 reports resources as stopped only when the host says they are stopped", async () => { const { lifecycle } = await fixture(); const handle = await lifecycle.create({ projectId, projectVersion: 1 }); const deferred = await handle.cleanup({ resourcesStopped: false, processesExited: false, reason: "failure" }); expect(deferred).toMatchObject({ removed: false, verifiedAbsent: false, deferred: true, failureCode: "QA_PROCESS_TERMINATION_FAILED" }); const result = await handle.cleanup({ resourcesStopped: true, processesExited: true, reason: "failure" }); expect(result).toMatchObject({ removed: true, verifiedAbsent: true }); });
  it("E22 retries EPERM, E23 retries EBUSY, and E24 retries ENOTEMPTY", async () => { for (const code of ["EPERM", "EBUSY", "ENOTEMPTY"]) { const { lifecycle } = await fixture({ fileSystem: { rm: (() => { let first = true; return async (target: string) => { if (first) { first = false; throw errorWithCode(code); } await remove(target, { recursive: true, force: true }); }; })() } }); const handle = await lifecycle.create({ projectId, projectVersion: 1 }); await expect(handle.cleanup()).resolves.toMatchObject({ removed: true, verifiedAbsent: true, retryCount: 1 }); } });
  it("E25 reaches bounded retry exhaustion and E26 does not retry non-transient errors", async () => { const persistent = await fixture({ fileSystem: { rm: async () => { throw errorWithCode("EPERM"); } } }); const persistentHandle = await persistent.lifecycle.create({ projectId, projectVersion: 1 }); const exhausted = await persistentHandle.cleanup(); expect(exhausted).toMatchObject({ removed: false, verifiedAbsent: false, deferred: true, retryCount: 4, failureCode: "QA_WORKSPACE_CLEANUP_RETRY_EXHAUSTED" }); const nonRetry = await fixture({ fileSystem: { rm: async () => { throw errorWithCode("EACCES"); } } }); const nonRetryHandle = await nonRetry.lifecycle.create({ projectId, projectVersion: 1 }); await expect(nonRetryHandle.cleanup()).resolves.toMatchObject({ retryCount: 0, failureCode: "QA_WORKSPACE_CLEANUP_FAILED", removed: false }); });
  it("E27 refuses to claim absence when removal returns without removing the directory", async () => { const { lifecycle } = await fixture({ fileSystem: { rm: async () => undefined } }); const handle = await lifecycle.create({ projectId, projectVersion: 1 }); const result = await handle.cleanup(); expect(result).toMatchObject({ removed: false, verifiedAbsent: false, failureCode: "QA_WORKSPACE_CLEANUP_RETRY_EXHAUSTED" }); });
  it("E28 removes a valid stale marker and E29 protects an active current workspace", async () => { const { root, lifecycle } = await fixture(); const stale = await manualWorkspace(root, { state: "ACTIVE" }); const active = await lifecycle.create({ projectId, projectVersion: 1 }); const result = await lifecycle.reconcile(); expect(result.cleaned).toBe(1); expect(result.entries.find((entry) => entry.name === path.basename(stale.target))?.classification).toBe("STALE_QA_WORKSPACE"); expect(result.entries.find((entry) => entry.name === path.basename(active.workspacePath))?.classification).toBe("ACTIVE_QA_WORKSPACE"); expect(await readFile(path.join(active.workspacePath, QA_WORKSPACE_MARKER_NAME), "utf8")).toContain("QA_FOUNDATION"); await active.cleanup(); });
  it("E30 preserves an unverified prefix, E31 is idempotent, and E32 cleans multiple stale workspaces", async () => { const { root, lifecycle } = await fixture(); const unverified = await mkdtemp(path.join(root, QA_WORKSPACE_PREFIX)); const stale = await Promise.all([manualWorkspace(root), manualWorkspace(root), manualWorkspace(root)]); const first = await lifecycle.reconcile(); const second = await lifecycle.reconcile(); expect(first.cleaned).toBe(3); expect(second.cleaned).toBe(0); expect((await lifecycle.inventory()).find((entry) => entry.name === path.basename(unverified))?.classification).toBe("UNVERIFIED_PREFIX_MATCH"); expect(stale).toHaveLength(3); });
  it("E33 processes other stale workspaces when one cleanup fails", async () => { const { root } = await fixture(); const first = await manualWorkspace(root); const second = await manualWorkspace(root); const failingName = path.basename(first.target); const lifecycle = new QaWorkspaceLifecycle({ authorizedRoot: root, isProcessAlive: async () => false, sleep: async () => undefined, fileSystem: { rm: async (target: string) => { if (path.basename(target) === failingName) throw errorWithCode("EPERM"); await remove(target, { recursive: true, force: true }); } } }); const result = await lifecycle.reconcile(); expect(result.cleaned).toBe(1); expect(result.failures).toEqual([{ workspacePathSafeRef: failingName, failureCode: "QA_WORKSPACE_CLEANUP_RETRY_EXHAUSTED" }]); await expect(readFile(path.join(second.target, QA_WORKSPACE_MARKER_NAME), "utf8")).rejects.toBeTruthy(); });
  it("E34 reconciles a crash-like owned marker with a dead owner", async () => { const { root, lifecycle } = await fixture(); const { target } = await manualWorkspace(root, { state: "ACTIVE", ownerProcessId: 999998 }); const result = await lifecycle.reconcile(); expect(result.cleaned).toBe(1); await expect(readFile(target, "utf8")).rejects.toBeTruthy(); });
  it("E35 leaves no owned workspace after repeated runs", async () => { const { lifecycle } = await fixture(); for (let index = 0; index < 8; index += 1) { const handle = await lifecycle.create({ projectId, projectVersion: 1 }); await expect(handle.cleanup()).resolves.toMatchObject({ removed: true, verifiedAbsent: true }); expect((await lifecycle.inventory()).filter((entry) => entry.ownershipConfidence === "HIGH")).toHaveLength(0); } });
  it("E36 gives bounded concurrent workspaces distinct identities and protects each active owner", async () => { const { lifecycle } = await fixture(); const handles = await Promise.all([1, 2, 3].map(() => lifecycle.create({ projectId, projectVersion: 1 }))); expect(new Set(handles.map((handle) => handle.workspaceId)).size).toBe(3); expect((await lifecycle.inventory()).filter((entry) => entry.active)).toHaveLength(3); await Promise.all(handles.map((handle) => handle.cleanup())); expect((await lifecycle.inventory()).filter((entry) => entry.ownershipConfidence === "HIGH")).toHaveLength(0); });
  it("E37 makes cleanup idempotent, E38 leaves no empty shell, and E39 changes no source files", async () => { const { lifecycle } = await fixture(); const handle = await lifecycle.create({ projectId, projectVersion: 1 }); const first = await handle.cleanup(); const second = await handle.cleanup(); expect(second).toEqual(first); expect(await lifecycle.inventory()).toEqual([]); });
  it("E40 keeps the current QA foundation contract usable with the lifecycle owner", async () => { const { lifecycle } = await fixture(); const handle = await lifecycle.create({ projectId, projectVersion: 1 }); await mkdir(handle.projectPath, { recursive: true }); handle.assertProjectPath(handle.projectPath); const cleanup = await handle.cleanup(); expect(cleanup.verifiedAbsent).toBe(true); });
});
