import { DocumentRepository, ProjectRepository, WorkflowPersistenceService } from "@/persistence/database/repositories";
import type { PersistenceDatabase } from "@/persistence/database/types";
import type { CodeIntegrationReviewInput } from "@/agents/reviewers/code-integration/contracts";
import { CodeIntegrationReviewService } from "@/agents/reviewers/code-integration/service";

export class CodeIntegrationReviewOrchestrationService {
  private readonly workflow: WorkflowPersistenceService; private readonly projects: ProjectRepository; private readonly documents: DocumentRepository;
  constructor(private readonly database: PersistenceDatabase, private readonly reviewer = new CodeIntegrationReviewService(database)) { this.workflow = new WorkflowPersistenceService(database); this.projects = new ProjectRepository(database); this.documents = new DocumentRepository(database); }
  get reviewerService() { return this.reviewer; }
  async enterReview(input: { projectId: string; projectVersion: number; expectedRowVersion: number; idempotencyKey: string }) { const current = await this.projects.getWithVersion(input.projectId); if (!current || current.project.workflowState === "CODE_INTEGRATION_REVIEW") return { rowVersion: current?.rowVersion ?? input.expectedRowVersion, projectState: "CODE_INTEGRATION_REVIEW" as const }; const transition = await this.workflow.transition({ projectId: input.projectId, projectVersion: input.projectVersion, expectedState: current.project.workflowState === "VALIDATING" ? "VALIDATING" : "IMPLEMENTING", expectedRowVersion: input.expectedRowVersion, targetState: "CODE_INTEGRATION_REVIEW", actor: "orchestrator", reason: "Static source validation completed; semantic code integration review is required.", idempotencyKey: input.idempotencyKey }); return { rowVersion: transition.rowVersion, projectState: "CODE_INTEGRATION_REVIEW" as const }; }
  async reviewAndRoute(input: CodeIntegrationReviewInput, signal?: AbortSignal) { const result = await this.reviewer.review(input, signal); const current = await this.projects.getWithVersion(input.projectId); if (result.verdict !== "APPROVED" || !current || current.project.workflowState !== "CODE_INTEGRATION_REVIEW") return { result, projectState: current?.project.workflowState ?? "CODE_INTEGRATION_REVIEW", rowVersion: current?.rowVersion ?? input.expectedRowVersion }; const transition = await this.workflow.transition({ projectId: input.projectId, projectVersion: input.projectVersion, expectedState: "CODE_INTEGRATION_REVIEW", expectedRowVersion: current.rowVersion, targetState: "VALIDATING", actor: "code-integration-reviewer", reason: "Current Code / Integration Review approved the implementation integration.", idempotencyKey: `${input.idempotencyKey}:approved` }); return { result, projectState: "VALIDATING" as const, rowVersion: transition.rowVersion }; }
  async getCurrentReview(projectId: string, projectVersion: number, sourceChecksum: string, contractAuditChecksum: string) { return this.reviewer.getCurrentReview(projectId, projectVersion, sourceChecksum, contractAuditChecksum); }
  async getExecutionSummary(projectId: string, projectVersion: number) { return this.documents.get(projectId, projectVersion, "full-execution"); }
}
