import { createHash } from "node:crypto";
import { checksumPersistedDocument } from "@/persistence/database/serialization";
import { AgentTaskSchema, TaskGraphSchema, type AgentTask, type TaskGraph } from "@/domain/tasks/schema";
import { OrchestratorError } from "./errors";
import { resolveTools } from "./tools";
import type { OrchestratorInput, OrchestrationPolicy } from "./contracts";
import { ownershipForTask, UNIT_TEST_ARTIFACT_POLICY_VERSION } from "@/domain/tasks/ownership";
import { taskCapabilitiesFor } from "@/orchestration/tooling/authority";
import { bindTaskContractsToPackage, validateTaskContractBinding } from "@/domain/contracts/phase7c";
import { implementationDomainForTaskType, specialistProfileIdForDomain } from "@/domain/implementation/profiles";

export const uuidFor = (seed: string) => { const hex = createHash("sha256").update(seed).digest("hex").slice(0, 30); return `${hex.slice(0, 8)}-${hex.slice(8, 12)}-4${hex.slice(12, 15)}-8${hex.slice(15, 18)}-${hex.slice(18, 30)}`; };
const unique = (values: string[]) => [...new Set(values.filter(Boolean))];
const safeTaskSlug = (value: string, fallback: string) => value.toLowerCase().replace(/https?:\/\/[^\s]+/g, "").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "").slice(0, 48) || fallback;
const routeHandlerScope = (responsibility: string, index: number) => {
  const route = responsibility.match(/\/(?:api\/)?[A-Za-z0-9_\-\[\]\/]+/)?.[0];
  if (!route || route.includes("..")) throw new OrchestratorError("ORCHESTRATOR_GRAPH_INVALID", `Route Handler responsibility ${index + 1} does not contain a bounded application route.`);
  const normalized = route.startsWith("/api/") ? route : `/api${route}`;
  return `src/app${normalized}/route.ts`;
};
const briefRequirementRefs = (brief: unknown) => {
  const refs: string[] = [];
  const visit = (value: unknown): void => {
    if (Array.isArray(value)) {
      value.forEach(visit);
      return;
    }
    if (!value || typeof value !== "object") return;
    const record = value as Record<string, unknown>;
    if (typeof record.id === "string" && /^REQUIREMENT:v3-[a-f0-9]{64}$/i.test(record.id)) refs.push(record.id);
    if (Array.isArray(record.sourceRefs)) refs.push(...record.sourceRefs.filter((ref): ref is string => typeof ref === "string"));
    Object.values(record).forEach(visit);
  };
  visit(brief);
  return refs;
};
const allRequirementRefs = (input: OrchestratorInput) => unique(input.acceptedPlanningPackage.traceability.flatMap((trace) => trace.requirementReferences).concat(input.approvedBrief.pages.map((page) => `requirement:page:${page.slug}`), input.approvedBrief.features.map((feature) => `requirement:feature:${feature}`), briefRequirementRefs(input.approvedBrief)));
const allPlanningRefs = (input: OrchestratorInput) => unique(input.acceptedPlanningPackage.traceability.map((trace) => `decision:${trace.decisionId}`).concat(input.acceptedPlanningPackage.pages.pages.map((page) => page.id), input.acceptedPlanningPackage.sitemap.routes.map((route) => route.id)));

type Draft = Omit<AgentTask, "id" | "dependencies" | "status" | "createdAt" | "projectId" | "projectVersion"> & { key: string; dependencies?: string[] };
type DraftInput = Omit<Draft, "role" | "allowedSkills" | "allowedTools" | "deniedTools" | "requiredCapabilities" | "fileScopes" | "attempt" | "maxAttempts" | "priority" | "executionMode" | "acceptanceCriteria" | "inputs" | "expectedOutputs" | "requirementReferences" | "planningReferences" | "selectedDesignReferences" | "blockingFailure" | "estimatedContextBytes" | "expectedArtifactTypes"> & Partial<Pick<Draft, "role" | "allowedSkills" | "allowedTools" | "deniedTools" | "fileScopes" | "attempt" | "maxAttempts" | "priority" | "executionMode" | "acceptanceCriteria" | "inputs" | "expectedOutputs" | "requirementReferences" | "planningReferences" | "selectedDesignReferences" | "blockingFailure" | "estimatedContextBytes" | "expectedArtifactTypes">>;
function draft(input: OrchestratorInput, policy: OrchestrationPolicy, value: DraftInput) {
  const tools = resolveTools(value.taskType, input.assetManifest.entries.map((entry) => entry.sourceDecision));
  const allowedTools = value.allowedTools ?? tools.allowed;
  const implementation = value.role !== "qa-release";
  const implementationDomain = value.implementationDomain ?? (implementation ? implementationDomainForTaskType(value.taskType) : undefined);
  const specialistProfileId = value.specialistProfileId ?? (implementationDomain ? specialistProfileIdForDomain(implementationDomain) : undefined);
  return { key: value.key, role: value.role ?? (implementation ? "implementation" : "qa-release"), taskType: value.taskType, title: value.title, objective: value.objective, ...(implementationDomain ? { implementationDomain } : {}), ...(specialistProfileId ? { specialistProfileId } : {}), inputs: value.inputs ?? ["approved project specification"], expectedOutputs: value.expectedOutputs ?? ["validated task artifact"], acceptanceCriteria: value.acceptanceCriteria ?? ["Output matches the approved specification and assigned scope."], requirementReferences: value.requirementReferences ?? allRequirementRefs(input), planningReferences: value.planningReferences ?? allPlanningRefs(input), selectedDesignReferences: value.selectedDesignReferences ?? (value.taskType.includes("design") || value.taskType.includes("layout") || value.taskType.includes("page") || value.taskType.includes("motion") || value.taskType.includes("component") ? [input.selectedDesign.selectedDirectionId] : []), allowedSkills: value.allowedSkills ?? [], allowedTools, deniedTools: value.deniedTools ?? tools.denied, requiredCapabilities: taskCapabilitiesFor({ taskType: value.taskType, allowedTools }), fileScopes: value.fileScopes ?? ["src/**"], requiredArtifacts: value.requiredArtifacts, requiredArtifactCount: value.requiredArtifactCount, taskAcceptancePolicyVersion: value.taskAcceptancePolicyVersion, dependencies: value.dependencies ?? [], priority: value.priority ?? "normal", executionMode: value.executionMode ?? (implementation ? "exclusive-write" : "validation-only"), parallelGroup: value.parallelGroup, attempt: value.attempt ?? 0, maxAttempts: value.maxAttempts ?? (value.taskType.startsWith("validate-") ? policy.validationMaxAttempts : value.taskType === "prepare-release" ? policy.releaseMaxAttempts : policy.implementationMaxAttempts), blockingFailure: value.blockingFailure ?? true, estimatedContextBytes: value.estimatedContextBytes ?? 24000, expectedArtifactTypes: value.expectedArtifactTypes ?? ["task-output"] };
}

export function buildImplementationTaskGraph(input: OrchestratorInput, policy: OrchestrationPolicy): TaskGraph {
  const parsed = input;
  const createdAt = parsed.acceptedPlanningPackage.createdAt;
  const drafts: Draft[] = [];
  const add = (value: Parameters<typeof draft>[2]) => drafts.push(draft(parsed, policy, value));
  add({ key: "workspace", taskType: "prepare-workspace", title: "Prepare project workspace", objective: "Reserve and verify the selected project version workspace for future execution, then create the approved workspace-prepared source marker.", fileScopes: ["src/app/factory-prepared.ts"], executionMode: "sequential", expectedArtifactTypes: ["workspace-reservation"] });
  add({ key: "foundation", taskType: "implement-project-foundation", title: "Implement project foundation", objective: "Prepare the fixed Next.js, React, TypeScript and validation foundation required by the approved project.", dependencies: ["workspace"], fileScopes: ownershipForTask("implement-project-foundation")!.scopes.slice(), allowedTools: ["filesystem-read", "filesystem-write", "generated-runtime-validation"], deniedTools: ["Context7-read", "codebase-memory-read", "npm", "git-write"], requiredArtifacts: ["package.json", "package-lock.json", "eslint.config.mjs", "next.config.mjs", "tsconfig.json"], expectedArtifactTypes: ["project-foundation"] });
  add({ key: "design-system", taskType: "implement-design-system", title: "Implement selected design system", objective: "Encode the explicitly selected design direction's visual tokens and component character.", dependencies: ["foundation"], fileScopes: ownershipForTask("implement-design-system")!.scopes.slice(), expectedArtifactTypes: ["design-system"] });
  add({ key: "layout", taskType: "implement-shared-layout", title: "Implement shared layout", objective: "Implement the selected design's responsive shell, typography, header, footer and page composition rules.", dependencies: ["design-system"], fileScopes: ownershipForTask("implement-shared-layout")!.scopes.slice(), expectedArtifactTypes: ["shared-layout"] });
  add({ key: "navigation", taskType: "implement-navigation", title: "Implement navigation", objective: "Implement approved primary, secondary and mobile navigation behavior.", dependencies: ["layout"], fileScopes: ownershipForTask("implement-navigation")!.scopes.slice(), requirementReferences: unique(input.acceptedPlanningPackage.navigation.routeReferences.concat(allRequirementRefs(parsed))), planningReferences: input.acceptedPlanningPackage.navigation.routeReferences, expectedArtifactTypes: ["navigation"] });
  const architecture = parsed.technicalArchitecture;
  const phase7cInput = parsed.phase7cContractPackage;
  const persistenceNone = parsed.approvedBrief.formBehaviorRequirements?.persistence === "NONE";
  const needsDatabase = !persistenceNone && Boolean(phase7cInput && phase7cInput.databaseDecision.mode !== "NONE" && (parsed.acceptedPlanningPackage.dataModel.entities.length > 0 || architecture.supabaseDatabaseRequirements.length > 0 || parsed.acceptedPlanningPackage.supabase.postgres));
  const needsAuth = parsed.acceptedPlanningPackage.authentication.decision === "supabase-auth" || parsed.approvedBrief.authenticationDecision === "authentication-required";
  const needsStorage = parsed.acceptedPlanningPackage.storage.decision === "supabase-storage" || parsed.approvedBrief.storageDecision === "needed";
  const transmissionNone = parsed.approvedBrief.formBehaviorRequirements?.dataTransmission === "NONE";
  const needsEmail = !transmissionNone && (parsed.acceptedPlanningPackage.email.decision === "required-configured-provider" || parsed.acceptedPlanningPackage.email.decision === "required-provider-pending" || parsed.approvedBrief.emailDecision === "needed");
  const backend: string[] = [];
  if (needsDatabase) { add({ key: "database", taskType: "implement-database-schema", title: "Implement database schema", objective: "Implement only the approved data model and ordered migrations.", dependencies: ["foundation"], fileScopes: ["supabase/config.toml", "supabase/migrations/**"], selectedDesignReferences: [], expectedArtifactTypes: ["database-schema"] }); backend.push("database"); add({ key: "rls", taskType: "implement-rls-policy", title: "Implement database access policies", objective: "Implement approved access-control and row-level security policies.", dependencies: ["database"], fileScopes: ["supabase/migrations/**"], selectedDesignReferences: [], expectedArtifactTypes: ["rls-policy"] }); backend.push("rls"); add({ key: "database-tests", taskType: "write-database-tests", title: "Write database behavior tests", objective: "Prove approved schema integrity and allowed and forbidden RLS behavior with local database tests.", dependencies: ["rls"], fileScopes: ["supabase/tests/**", "supabase/seed.sql"], selectedDesignReferences: [], expectedArtifactTypes: ["database-tests"] }); backend.push("database-tests"); }
  if (needsAuth) { add({ key: "auth", taskType: "implement-authentication", title: "Implement authentication server boundary", objective: "Implement the approved server-side authentication, session, and protected-route behavior.", dependencies: ["foundation", ...(needsDatabase ? ["rls"] : [])], fileScopes: ["src/lib/auth/**", "src/lib/supabase/**", "src/middleware.*"], selectedDesignReferences: [], expectedArtifactTypes: ["authentication"] }); backend.push("auth"); }
  if (needsStorage) { add({ key: "storage", taskType: "implement-storage", title: "Implement approved storage", objective: "Implement runtime upload storage only where the approved storage plan requires it; database policies remain Database-owned.", dependencies: ["foundation", ...(needsDatabase ? ["rls"] : [])], fileScopes: ["src/lib/storage/**", "src/app/api/uploads/**"], selectedDesignReferences: [], expectedArtifactTypes: ["storage"] }); backend.push("storage"); }
  if (needsEmail) { add({ key: "email", taskType: "implement-email", title: "Implement approved email behavior", objective: "Implement the approved email workflow and safe failure behavior.", dependencies: ["foundation", ...(needsDatabase ? ["database"] : [])], fileScopes: ["src/lib/email/**", "src/app/api/email/**", "src/app/actions/**"], expectedArtifactTypes: ["email"] }); backend.push("email"); }
  for (const [index, responsibility] of architecture.serverActions.entries()) { const key = `server-action-${safeTaskSlug(responsibility, String(index + 1))}`; add({ key, taskType: "implement-server-action", title: `Implement server action ${index + 1}`, objective: `Implement the approved Server Action responsibility: ${responsibility}.`, dependencies: ["foundation", ...backend], fileScopes: [`src/actions/${safeTaskSlug(responsibility, `action-${index + 1}`)}.ts`], selectedDesignReferences: [], expectedArtifactTypes: ["server-contract", "server-action"] }); backend.push(key); }
  for (const [index, responsibility] of architecture.routeHandlers.entries()) { const key = `route-handler-${safeTaskSlug(responsibility, String(index + 1))}`; add({ key, taskType: "implement-route-handler", title: `Implement route handler ${index + 1}`, objective: `Implement the approved Route Handler responsibility: ${responsibility}.`, dependencies: ["foundation", ...backend], fileScopes: [routeHandlerScope(responsibility, index)], selectedDesignReferences: [], expectedArtifactTypes: ["server-contract", "route-handler"] }); backend.push(key); }
  const shared = [...backend, "navigation"];
  for (const component of parsed.acceptedPlanningPackage.architecture.componentBoundaries.slice(0, 8)) { const key = `component-${component.toLowerCase().replace(/[^a-z0-9]+/g, "-").slice(0, 30)}`; add({ key, taskType: "implement-shared-component", title: `Implement ${component}`, objective: `Implement the approved shared component boundary: ${component}.`, dependencies: ["design-system", "layout"], fileScopes: [`src/components/shared/${key.slice("component-".length)}/**`], expectedArtifactTypes: ["shared-component"] }); shared.push(key); }
  for (const page of parsed.acceptedPlanningPackage.pages.pages) { const key = `page-${page.routeId}`; const route = parsed.acceptedPlanningPackage.sitemap.routes.find((candidate) => candidate.id === page.routeId); const pagePath = route?.path ?? "/"; const appPath = pagePath === "/" ? "" : pagePath; const pageDeps = [...shared]; if (route?.authRequired && needsAuth) pageDeps.push("auth"); add({ key, taskType: "implement-page", title: `Implement ${pagePath || "/"}`, objective: `Implement the approved page responsibility for ${pagePath || "/"}.`, dependencies: pageDeps, fileScopes: [`src/app${appPath}/**`], requirementReferences: page.requirementReferences, planningReferences: [page.id, page.routeId], ...(appPath ? { executionMode: "parallel-safe" as const, parallelGroup: "independent-pages" } : {}), expectedArtifactTypes: ["page"] }); if (page.forms.length) add({ key: `form-${page.id}`, taskType: "implement-form", title: `Implement form for ${pagePath || "/"}`, objective: "Implement the approved form validation, states and submission mechanism with Zod runtime validation for every planned field.", dependencies: [key, ...backend], fileScopes: [`src/app${appPath}/**`, "src/components/forms/**"], requirementReferences: page.requirementReferences, planningReferences: [page.id, page.routeId, ...page.forms], expectedArtifactTypes: ["form"] }); }
  if (parsed.contentPlan.approvedGeneratedCopy.length || parsed.contentPlan.userProvidedFacts.length) add({ key: "content", taskType: "integrate-content", title: "Integrate approved content", objective: "Integrate only supplied facts, approved copy, approved placeholders and host-approved current assets; preserve the approved asset-source and no-invention policy.", dependencies: parsed.acceptedPlanningPackage.pages.pages.map((page) => `page-${page.routeId}`), fileScopes: ["src/content/**", "src/app/**/page.*"], expectedArtifactTypes: ["content-integration"] });
  if (parsed.assetManifest.entries.length) add({ key: "assets", taskType: "integrate-assets", title: "Integrate approved assets", objective: "Integrate the approved asset manifest without inventing or sourcing unapproved assets.", dependencies: parsed.acceptedPlanningPackage.pages.pages.map((page) => `page-${page.routeId}`), fileScopes: ["public/**", "src/assets/**", "src/app/**/page.*"], expectedArtifactTypes: ["asset-integration"] });
  if (parsed.approvedBrief.seoRequirements.length || parsed.approvedBrief.seoMetadata?.primaryKeywords.length || parsed.approvedBrief.seoMetadata?.pageMetadata.length || parsed.acceptedPlanningPackage.sitemap.routes.some((route) => route.seoRelevant)) add({ key: "seo", taskType: "implement-seo", title: "Implement approved SEO metadata", objective: "Implement approved route metadata and SEO requirements.", dependencies: parsed.acceptedPlanningPackage.pages.pages.map((page) => `page-${page.routeId}`), fileScopes: ["src/app/**/metadata.*", "src/app/sitemap.*", "src/app/robots.*"], expectedArtifactTypes: ["seo"] });
  // SelectedDesign intentionally stores the selected direction checksum, not the full direction. The direction set is supplied by callers through planning/design references in production. Motion is therefore opt-in from the selected design notes.
  if (/motion|transition|microinteraction|animation/i.test(JSON.stringify(parsed.selectedDesign))) add({ key: "motion", taskType: "implement-motion", title: "Implement selected motion policy", objective: "Implement only purposeful motion required by the selected design, with reduced-motion fallback.", dependencies: ["layout", ...parsed.acceptedPlanningPackage.pages.pages.map((page) => `page-${page.routeId}`)], fileScopes: ["src/components/motion/**", "src/styles/**"], expectedArtifactTypes: ["motion"] });
  const implementationKeys = drafts.map((item) => item.key);
  const testDeps = implementationKeys.filter((key) => key !== "workspace");
  add({ key: "unit-tests", taskType: "write-unit-tests", title: "Write unit tests", objective: "Cover only approved application behavior such as form validation, submission behavior, navigation/shared component behavior where unit-test appropriate, and deterministic utility logic.", dependencies: testDeps, fileScopes: ownershipForTask("write-unit-tests")!.scopes.slice(), acceptanceCriteria: ["Create at least one non-placeholder Vitest unit-test file under the canonical src/**/*.test.ts or src/**/*.test.tsx scope.", "Cover approved behavior only; do not invent business requirements.", "Read relevant production source but do not modify production files."], inputs: ["approved project specification", "relevant passed implementation source", "approved acceptance references"], expectedOutputs: ["one or more discovered Vitest unit-test files"], executionMode: "parallel-safe", requiredArtifactCount: 1, taskAcceptancePolicyVersion: UNIT_TEST_ARTIFACT_POLICY_VERSION, expectedArtifactTypes: ["unit-tests"] });
  add({ key: "integration-tests", taskType: "write-integration-tests", title: "Write integration tests", objective: "Cover approved integration boundaries; for frontend-only forms, verify local validation, simulated success/reset, privacy consent, and that submission performs no network transmission.", dependencies: testDeps, fileScopes: ["src/**/*.integration.test.*", "tests/integration/**"], executionMode: "parallel-safe", expectedArtifactTypes: ["integration-tests"] });
  add({ key: "e2e-tests", taskType: "write-e2e-tests", title: "Write functional flow tests", objective: "Define functional tests for approved user flows.", dependencies: testDeps, fileScopes: ["tests/e2e/**"], executionMode: "parallel-safe", expectedArtifactTypes: ["e2e-tests"] });
  for (const [key, taskType, title] of [["lint", "validate-lint", "Validate lint"], ["typecheck", "validate-typecheck", "Validate typecheck"], ["unit-validation", "validate-unit-tests", "Validate unit tests"], ["build", "validate-build", "Validate build"], ["functional", "validate-functional-flow", "Validate functional flows"]] as const) add({ key, taskType, role: "qa-release", title, objective: `Validate the completed implementation with ${title.toLowerCase()}.`, dependencies: ["unit-tests", "integration-tests", "e2e-tests", ...(taskType !== "validate-lint" && taskType !== "validate-functional-flow" ? ["lint"] : []), ...(taskType === "validate-functional-flow" ? ["lint", "typecheck", "unit-validation", "build"] : [])], fileScopes: [], expectedArtifactTypes: ["validation-report"], executionMode: "validation-only" });
  if (needsDatabase) add({ key: "database-validation", taskType: "validate-database", role: "qa-release", title: "Validate database", objective: "Validate approved migrations, schema and RLS behavior against the generated-project local Supabase runtime.", dependencies: ["database", "rls", "database-tests", "integration-tests"], fileScopes: [], expectedArtifactTypes: ["database-validation"], executionMode: "validation-only" });
  add({ key: "security", taskType: "validate-security", role: "qa-release", title: "Validate security", objective: "Validate secret boundaries, tool restrictions and approved security controls.", dependencies: ["unit-tests", "integration-tests"], fileScopes: [], expectedArtifactTypes: ["security-report"], executionMode: "validation-only" });
  const validations = drafts.filter((item) => item.taskType.startsWith("validate-")).map((item) => item.key);
  add({ key: "release", taskType: "prepare-release", role: "qa-release", title: "Prepare release validation", objective: "Prepare release only after all required implementation and quality paths pass.", dependencies: validations, fileScopes: [".factory/task-graph.json"], expectedArtifactTypes: ["release-readiness"] });
  const ids = new Map(drafts.map((item) => [item.key, uuidFor(`${parsed.projectId}:${parsed.projectVersion}:${item.key}`)]));
  const tasks = drafts.map((item) => AgentTaskSchema.parse({ id: ids.get(item.key), projectId: parsed.projectId, projectVersion: parsed.projectVersion, role: item.role, taskType: item.taskType, title: item.title, objective: item.objective, ...(item.implementationDomain ? { implementationDomain: item.implementationDomain } : {}), ...(item.specialistProfileId ? { specialistProfileId: item.specialistProfileId } : {}), requirementReferences: item.requirementReferences, planningReferences: item.planningReferences, selectedDesignReferences: item.selectedDesignReferences, inputs: item.inputs, expectedOutputs: item.expectedOutputs, acceptanceCriteria: item.acceptanceCriteria, allowedSkills: item.allowedSkills, allowedTools: item.allowedTools, deniedTools: item.deniedTools, requiredCapabilities: item.requiredCapabilities, fileScopes: item.fileScopes, requiredArtifacts: item.requiredArtifacts, requiredArtifactCount: item.requiredArtifactCount, taskAcceptancePolicyVersion: item.taskAcceptancePolicyVersion, dependencies: (item.dependencies ?? []).map((key) => ids.get(key) ?? (() => { throw new OrchestratorError("ORCHESTRATOR_GRAPH_INVALID", "A generated task dependency could not be resolved."); })()), status: "pending", priority: item.priority, executionMode: item.executionMode, ...(item.parallelGroup ? { parallelGroup: item.parallelGroup } : {}), attempt: item.attempt, maxAttempts: item.maxAttempts, ...(item.repairOfTaskId ? { repairOfTaskId: item.repairOfTaskId } : {}), createdAt, blockingFailure: item.blockingFailure, estimatedContextBytes: item.estimatedContextBytes, expectedArtifactTypes: item.expectedArtifactTypes }));
  const phase7c = phase7cInput ? (phase7cInput.taskContracts.length ? phase7cInput : bindTaskContractsToPackage(phase7cInput, tasks)) : undefined;
  const boundTasks = phase7c ? tasks.map((task) => {
    const existing = phase7c.taskContracts.find((contract) => contract.taskId === task.id);
    if (!existing) throw new OrchestratorError("ORCHESTRATOR_GRAPH_INVALID", `Phase 7C TaskContract is missing for ${task.taskType}.`);
    try { validateTaskContractBinding(task, existing); } catch (error) { throw new OrchestratorError("ORCHESTRATOR_GRAPH_INVALID", "Task exceeds its Phase 7C TaskContract.", error); }
    return AgentTaskSchema.parse({ ...task, phase7c: { taskContractId: existing.taskContractId, taskContractChecksum: existing.checksum, dataContractIds: [...new Set([...existing.inputDataContractIds, ...existing.outputDataContractIds])], ...(existing.databaseDecisionRef ? { databaseDecisionId: existing.databaseDecisionRef.id, databaseDecisionChecksum: existing.databaseDecisionRef.checksum } : {}), ...(existing.dependencyProposalRef ? { dependencyProposalId: existing.dependencyProposalRef.id } : {}) } });
  }) : tasks;
  const sourceChecksums = { brief: parsed.approvedBriefChecksum, planning: parsed.acceptedPlanningChecksum, design: parsed.selectedDesignChecksum, architecture: checksumPersistedDocument(parsed.technicalArchitecture), content: checksumPersistedDocument(parsed.contentPlan), assets: checksumPersistedDocument(parsed.assetManifest) };
  const base = { schemaVersion: 1 as const, documentType: "task-graph" as const, projectId: parsed.projectId, projectVersion: parsed.projectVersion, createdAt, updatedAt: createdAt, tasks: boundTasks, orchestrationPolicyVersion: policy.version, toolPolicyVersion: parsed.toolPolicyVersion, approvedSkillSnapshotChecksum: parsed.approvedSkillRegistrySnapshot.checksum, sourceDocumentChecksums: sourceChecksums, ...(phase7c ? { phase7cContractPackageChecksum: checksumPersistedDocument(phase7c), databaseDecisionChecksum: phase7c.databaseDecision.checksum } : {}), checkpoint: "graph-validated" as const, readyForExecution: true, blockingReasons: [], warnings: [], validation: { valid: true, errors: [], warnings: [] } };
  const graphChecksum = checksumPersistedDocument(base);
  return TaskGraphSchema.parse({ ...base, graphChecksum });
}
