import { randomUUID } from "node:crypto";
import { describe, expect, it } from "vitest";
import { RequirementSpecificationSchema, type RequirementSpecification } from "@/domain/requirements/schema";
import { FactoryProjectSchema } from "@/domain/project/schema";
import { ProjectRepository, ProjectVersionRepository, DocumentRepository } from "@/persistence/database/repositories";
import { InMemoryPersistenceDatabase } from "@/persistence/database/fake";
import { checksumPersistedDocument } from "@/persistence/database/serialization";
import { buildPlanningPackage } from "../../agents/planner/deterministic";
import type { PlannerAgentInput } from "../../agents/planner/contracts";
import { OrchestratorService } from "./service";
import { buildImplementationTaskGraph } from "./graph";
import { validateFileScopes, validateImplementationTaskGraph } from "./validation";
import { TaskGraphSchema } from "@/domain/tasks/schema";

const id = () => randomUUID();
const brief = (overrides: Partial<RequirementSpecification> = {}) => RequirementSpecificationSchema.parse({ schemaVersion: 1, documentType: "requirements", projectId: id(), projectVersion: 1, createdAt: "2026-01-01T00:00:00.000Z", updatedAt: "2026-01-01T00:00:00.000Z", projectSummary: "Present a local business", protectedFunctionalityRequired: false, imagesRequired: false, businessGoals: ["Reach local customers"], targetAudiences: ["Local visitors"], pages: [{ slug: "home", purpose: "Explain the business" }], userRoles: [], features: [], forms: [], contentRequirements: [], backendRequirements: [], supabaseRequirements: [], authenticationDecision: "no-authentication-guest-first", storageDecision: "not-needed", emailDecision: "not-needed", administrationDecision: "not-needed", seoRequirements: [], localization: { locales: ["en"], defaultLocale: "en" }, imageSourceDecision: "user-supplied", suppliedBrandInformation: { status: "missing" }, suppliedLogoLocation: { status: "missing" }, technicalConstraints: [], explicitExclusions: [], userAcceptanceCriteria: ["Visitor can understand the offer"], unresolvedItems: [], approval: { approved: true, approvedAt: "2026-01-01T00:00:00.000Z", approvedBy: "user", approvedRequirementsChecksum: "a".repeat(64) }, contactFacts: [], legalFacts: [], brandFacts: [], logoMetadata: [], imageSourcingNotes: [], evidence: [], recommendations: [], briefStatus: "approved", briefVersion: 1, ...overrides });
// The fixture intentionally keeps the selected document literal narrowness out of the setup helper.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
function input(value = brief(), changes: Record<string, unknown> = {}): any {
  const plannerInput: PlannerAgentInput = { projectId: value.projectId, projectVersion: 1, approvedBrief: value, approvedBriefChecksum: checksumPersistedDocument(value), originalPromptReference: "original-prompt.md", clarificationEvidenceReferences: [], currentWorkflowState: "AWAITING_DESIGN_SELECTION", existingDecisions: [], suppliedFiles: [], allowedSkills: [], idempotencyKey: "planner-fixture", expectedRowVersion: 1 };
  const generated = buildPlanningPackage(plannerInput);
  const planning = { ...generated, accepted: true, acceptance: { acceptedAt: "2026-01-01T00:00:00.000Z", acceptedBy: "user", checksum: checksumPersistedDocument(generated) }, architecture: { ...generated.architecture, acceptance: { accepted: true, acceptedAt: "2026-01-01T00:00:00.000Z", acceptedBy: "user" } } };
  const selected = { schemaVersion: 1, documentType: "selected-design" as const, projectId: value.projectId, projectVersion: 1, createdAt: "2026-01-01T00:00:00.000Z", updatedAt: "2026-01-01T00:00:00.000Z", directionSetId: id(), selectedDirectionId: id(), selectedAt: "2026-01-01T00:00:00.000Z", selectedBy: "user", selectionNotes: "Selected direction", selectedDirectionChecksum: "b".repeat(64) };
  return { projectId: value.projectId, projectVersion: 1, approvedBrief: value, approvedBriefChecksum: checksumPersistedDocument(value), acceptedPlanningPackage: planning, acceptedPlanningChecksum: checksumPersistedDocument(planning), selectedDesign: selected, selectedDesignChecksum: checksumPersistedDocument(selected), technicalArchitecture: planning.architecture, contentPlan: planning.content, assetManifest: planning.assets, currentWorkflowState: "READY_FOR_IMPLEMENTATION" as const, existingDecisions: [], allowedRoles: ["lead", "planner-architect", "design", "implementation", "qa-release"] as const, approvedSkillRegistrySnapshot: { schemaVersion: 1 as const, checksum: "c".repeat(64), skills: [] }, toolPolicyVersion: "tool-policy-v1", orchestrationPolicyVersion: "orchestrator-v1", idempotencyKey: id(), expectedRowVersion: 1, workspaceReserved: true, ...changes };
}
const policy = { version: "orchestrator-v1", maxConcurrency: 3, implementationMaxAttempts: 3, validationMaxAttempts: 2, releaseMaxAttempts: 1, maxContextBytes: 120000 } as const;

describe("Orchestrator task graph workflow", () => {
  it("declares canonical foundation artifacts and excludes optional codebase tools", () => { const graph = buildImplementationTaskGraph(input(), policy); const foundation = graph.tasks.find((task) => task.taskType === "implement-project-foundation"); expect(foundation?.requiredArtifacts).toEqual(["package.json", "package-lock.json", "eslint.config.mjs", "next.config.mjs"]); expect(foundation?.fileScopes).toContain("package.json"); expect(foundation?.fileScopes).toContain("package-lock.json"); expect(foundation?.allowedTools).not.toContain("codebase-memory-read"); expect(foundation?.allowedTools).not.toContain("Context7-read"); expect(foundation?.deniedTools).toContain("npm"); });
  it("requires every runtime gate, including the production build, before functional QA can run", () => { const graph = buildImplementationTaskGraph(input(), policy); const runtime = graph.tasks.filter((task) => ["validate-lint", "validate-typecheck", "validate-unit-tests", "validate-build"].includes(task.taskType)); const functional = graph.tasks.find((task) => task.taskType === "validate-functional-flow")!; expect(runtime.every((task) => functional.dependencies.includes(task.id))).toBe(true); });
  it("keeps implementation task ownership boundaries canonical", () => { const graph = buildImplementationTaskGraph(input(), policy); const scopes = (taskType: string) => graph.tasks.find((task) => task.taskType === taskType)?.fileScopes; expect(scopes("implement-design-system")).toEqual(["src/components/ui/**", "src/styles/**", "src/app/globals.css"]); expect(scopes("implement-shared-layout")).toEqual(["src/app/layout.*", "src/components/layout/**"]); expect(scopes("implement-navigation")).toEqual(["src/components/navigation/**", "src/app/**/layout.*"]); expect(scopes("implement-page")).toEqual(["src/app/**"]); });
  it("rejects unapproved Briefs and wrong workflow state", async () => { const service = new OrchestratorService(new InMemoryPersistenceDatabase()); await expect(service.createImplementationTaskGraph(input(brief({ approval: { approved: false }, briefStatus: "draft" })))).rejects.toMatchObject({ code: "ORCHESTRATOR_BRIEF_STALE" }); await expect(service.createImplementationTaskGraph(input(brief(), { currentWorkflowState: "AWAITING_DESIGN_SELECTION" }))).rejects.toMatchObject({ code: "ORCHESTRATOR_WORKFLOW_STATE_INVALID" }); });
  it("creates a smaller marketing graph and conditional auth/database tasks", () => { const simple = buildImplementationTaskGraph(input(), policy); const stateful = buildImplementationTaskGraph(input(brief({ pages: [{ slug: "home", purpose: "Explain" }, { slug: "dashboard", purpose: "Manage bookings" }], features: ["Private dashboard", "Booking"], forms: ["Booking"], protectedFunctionalityRequired: true, authenticationDecision: "authentication-required", backendRequirements: ["Store bookings"], userRoles: ["member"] }), {}), policy); expect(simple.tasks.length).toBeLessThan(stateful.tasks.length); expect(stateful.tasks.some((task) => task.taskType === "implement-authentication")).toBe(true); expect(stateful.tasks.some((task) => task.taskType === "implement-rls-policy")).toBe(true); expect(simple.tasks.some((task) => task.taskType === "implement-authentication")).toBe(false); });
  it("keeps static images out of Storage and assigns image generation only to asset work", () => { const graph = buildImplementationTaskGraph(input(brief({ imagesRequired: true, imageSourceDecision: "ai-generated" })), policy); expect(graph.tasks.some((task) => task.taskType === "implement-storage")).toBe(false); expect(graph.tasks.filter((task) => task.role === "implementation").every((task) => task.requirementReferences?.length && task.planningReferences?.length)).toBe(true); expect(graph.tasks.find((task) => task.taskType === "integrate-assets")?.allowedTools).toContain("image-generation"); });
  it("detects traceability and file-scope conflicts", () => { const graph = buildImplementationTaskGraph(input(), policy); const page = graph.tasks.find((task) => task.taskType === "implement-page")!; const invalid = TaskGraphSchema.parse({ ...graph, tasks: graph.tasks.map((task) => task.id === page.id ? { ...task, requirementReferences: [], planningReferences: [] } : task) }); expect(validateImplementationTaskGraph(invalid)).toMatchObject({ valid: false, errors: expect.arrayContaining(["TASK_TRACEABILITY_MISSING"]) }); expect(() => validateFileScopes([{ ...page, parallelGroup: "pages", executionMode: "parallel-safe" }, { ...page, id: id(), parallelGroup: "pages", executionMode: "parallel-safe" }])).toThrowError(/overlapping write scopes/); });
  it("blocks implementation until Contract Audit approval", async () => { const database = new InMemoryPersistenceDatabase(); const value = input(); const project = FactoryProjectSchema.parse({ schemaVersion: 1, documentType: "factory-project", projectId: value.projectId, projectVersion: 1, createdAt: "2026-01-01T00:00:00.000Z", updatedAt: "2026-01-01T00:00:00.000Z", id: value.projectId, slug: "orchestrator-fixture", originalPrompt: "fixture", currentVersion: 1, workflowState: "READY_FOR_IMPLEMENTATION" }); await new ProjectRepository(database).create(project); await new ProjectVersionRepository(database).create({ id: id(), projectId: value.projectId, versionNumber: 1, state: "READY_FOR_IMPLEMENTATION", memoryRootPath: null, requirementsChecksum: null, selectedDesignChecksum: null, architectureChecksum: null, releasedAt: null, immutable: false, createdAt: project.createdAt, updatedAt: project.updatedAt, rowVersion: 1 }); const service = new OrchestratorService(database); await service.createImplementationTaskGraph(value); await expect(service.startImplementation({ ...value, idempotencyKey: id() })).rejects.toMatchObject({ code: "IMPLEMENTATION_START_BLOCKED" }); });
  it("guards transitions and increments attempts on retry", async () => { const database = new InMemoryPersistenceDatabase(); const value = input(); const service = new OrchestratorService(database); const result = await service.createImplementationTaskGraph(value); const task = result.taskGraph.tasks[0]!; const ready = await service.transitionTaskState({ projectId: value.projectId, projectVersion: 1, taskId: task.id, targetStatus: "ready", expectedGraphChecksum: result.taskGraph.graphChecksum!, actor: "test", reason: "ready" }); const running = await service.transitionTaskState({ projectId: value.projectId, projectVersion: 1, taskId: task.id, targetStatus: "running", expectedGraphChecksum: ready.taskGraph.graphChecksum!, actor: "test", reason: "run" }); const failed = await service.transitionTaskState({ projectId: value.projectId, projectVersion: 1, taskId: task.id, targetStatus: "failed", expectedGraphChecksum: running.taskGraph.graphChecksum!, actor: "test", reason: "failure" }); const retried = await service.retryFailedTask({ projectId: value.projectId, projectVersion: 1, taskId: task.id, expectedGraphChecksum: failed.taskGraph.graphChecksum!, actor: "test", reason: "retry" }); expect(retried.taskGraph.tasks.find((candidate) => candidate.id === task.id)?.status).toBe("ready"); });
  it("replays one historical failed validation without making implementation work runnable", async () => { const database = new InMemoryPersistenceDatabase(); const value = input(); const service = new OrchestratorService(database); const original = buildImplementationTaskGraph(value, policy); const validation = original.tasks.find((task) => task.taskType === "validate-unit-tests")!; const raw = { ...original, tasks: original.tasks.map((task) => task.id === validation.id ? { ...task, status: "failed" as const, attempt: 2, maxAttempts: 2, completedAt: "2026-01-01T00:00:00.000Z" } : { ...task, status: "passed" as const, attempt: 1, completedAt: "2026-01-01T00:00:00.000Z" }) }; const withoutChecksum = { ...raw }; delete (withoutChecksum as { graphChecksum?: string }).graphChecksum; const graph = TaskGraphSchema.parse({ ...raw, graphChecksum: checksumPersistedDocument(withoutChecksum) }); await new DocumentRepository(database).save(graph); const replay = await service.reconcileValidationReplay({ projectId: value.projectId, projectVersion: 1, taskId: validation.id, expectedGraphChecksum: graph.graphChecksum!, actor: "test", reason: "VALIDATION_EVIDENCE_REFRESH", sourceChecksum: "a".repeat(64), diagnosticPolicyVersion: "runtime-diagnostics-v3" }); expect(replay.replayed).toBe(true); expect(replay.taskGraph.tasks.find((task) => task.id === validation.id)?.status).toBe("ready"); expect(replay.taskGraph.tasks.filter((task) => task.taskType.startsWith("implement-")).every((task) => task.status === "passed")).toBe(true); const again = await service.reconcileValidationReplay({ projectId: value.projectId, projectVersion: 1, taskId: validation.id, expectedGraphChecksum: replay.taskGraph.graphChecksum!, actor: "test", reason: "VALIDATION_EVIDENCE_REFRESH", sourceChecksum: "a".repeat(64), diagnosticPolicyVersion: "runtime-diagnostics-v3" }); expect(again.replayed).toBe(false); });
  it("schedules one bounded QA policy refresh without resetting normal attempts or implementation history", async () => { const database = new InMemoryPersistenceDatabase(); const value = input(); const service = new OrchestratorService(database); const original = buildImplementationTaskGraph(value, policy); const qa = original.tasks.find((task) => task.taskType === "validate-functional-flow")!; const qaId = qa.id; const raw = { ...original, tasks: original.tasks.map((task) => task.id === qaId ? { ...task, status: "failed" as const, attempt: 1, maxAttempts: 1, completedAt: "2026-01-01T00:00:00.000Z", validationDiagnosticPolicyVersion: "functional-qa-diagnostics-v3" } : { ...task, status: "passed" as const, attempt: 1, completedAt: "2026-01-01T00:00:00.000Z" }) }; const withoutChecksum = { ...raw }; delete (withoutChecksum as { graphChecksum?: string }).graphChecksum; const graph = TaskGraphSchema.parse({ ...raw, graphChecksum: checksumPersistedDocument(withoutChecksum) }); await new DocumentRepository(database).save(graph); const replay = await service.reconcileQaPolicyRefresh({ projectId: value.projectId, projectVersion: 1, expectedGraphChecksum: graph.graphChecksum!, actor: "test", sourceChecksum: "a".repeat(64), policyVersion: "functional-qa-diagnostics-v4", scenarioChecksum: "b".repeat(64) }); const refreshed = replay.taskGraph.tasks.find((task) => task.id === qaId)!; expect(replay.replayed).toBe(true); expect(refreshed.status).toBe("ready"); expect(refreshed.attempt).toBe(1); expect(refreshed.validationReplayKind).toBe("policy-refresh"); expect(refreshed.validationReplayBaseAttempt).toBe(1); expect(replay.taskGraph.tasks.filter((task) => task.taskType.startsWith("implement-")).every((task) => task.status === "passed")).toBe(true); });
  it("appends a late targetable repair as READY with passed canonical dependencies and deduplicates it", async () => { const database = new InMemoryPersistenceDatabase(); const value = input(); const service = new OrchestratorService(database); const original = buildImplementationTaskGraph(value, policy); const qa = original.tasks.find((task) => task.taskType === "validate-functional-flow")!; const raw = { ...original, tasks: original.tasks.map((task) => task.id === qa.id ? { ...task, status: "failed" as const, completedAt: "2026-01-01T00:00:00.000Z", safeFailureCode: "QA_ROUTE_MISSING", validationDiagnostics: [{ category: "QA_ROUTE_MISSING", relativePath: "src/app/termin/page.tsx", route: "/termin", candidateOwnership: ["implement-page"], classification: "IMPLEMENTATION_DEFECT", safeMessage: "The planned route is missing." }] } : { ...task, status: "passed" as const, attempt: 1, completedAt: "2026-01-01T00:00:00.000Z" }) }; const withoutChecksum = { ...raw }; delete (withoutChecksum as { graphChecksum?: string }).graphChecksum; const graph = TaskGraphSchema.parse({ ...raw, graphChecksum: checksumPersistedDocument(withoutChecksum) }); await new DocumentRepository(database).save(graph); const repair = await service.createTargetedRepairTask({ projectId: value.projectId, projectVersion: 1, failedTaskId: qa.id, failureCode: "QA_ROUTE_MISSING", failureSummary: "The planned /termin route is missing.", expectedCorrection: "Restore src/app/termin/page.tsx.", revalidationTaskIds: [qa.id], expectedGraphChecksum: graph.graphChecksum!, actor: "test", fileScopes: ["src/app/termin/page.tsx"], repairIdentity: `${qa.id}:QA_ROUTE_MISSING:src/app/termin/page.tsx:functional-qa-diagnostics-v13` }); expect(repair.status).toBe("ready"); expect(repair.dependencies.every((dependency) => graph.tasks.find((task) => task.id === dependency)?.status === "passed")).toBe(true); const again = await service.createTargetedRepairTask({ projectId: value.projectId, projectVersion: 1, failedTaskId: qa.id, failureCode: "QA_ROUTE_MISSING", failureSummary: "The planned /termin route is missing.", expectedCorrection: "Restore src/app/termin/page.tsx.", revalidationTaskIds: [qa.id], expectedGraphChecksum: (await new DocumentRepository(database).get(value.projectId, 1, "task-graph") as { graphChecksum?: string })!.graphChecksum!, actor: "test", fileScopes: ["src/app/termin/page.tsx"], repairIdentity: repair.repairIdentity }); expect(again.id).toBe(repair.id); });
});
