export type CodebaseMemoryErrorCode =
  | "CODEBASE_MEMORY_TOOL_NOT_ALLOWED" | "CODEBASE_MEMORY_WORKSPACE_INVALID"
  | "CODEBASE_MEMORY_OPERATION_NOT_ALLOWED" | "CODEBASE_MEMORY_CONFIGURATION_INVALID"
  | "CODEBASE_MEMORY_UNAVAILABLE" | "CODEBASE_MEMORY_TIMEOUT" | "CODEBASE_MEMORY_CANCELLED"
  | "CODEBASE_MEMORY_CONCURRENCY_LIMIT_REACHED" | "CODEBASE_MEMORY_INDEX_STALE"
  | "CODEBASE_MEMORY_INDEX_FAILED" | "CODEBASE_MEMORY_QUERY_INVALID"
  | "CODEBASE_MEMORY_SCOPE_EXPANSION_REQUIRED" | "IDEMPOTENCY_CONFLICT";
export class CodebaseMemoryError extends Error { constructor(public readonly code: CodebaseMemoryErrorCode, message: string, public readonly cause?: unknown) { super(message); this.name = "CodebaseMemoryError"; } }
