import { createHash } from "node:crypto";
import { lstat, mkdir, readFile, rename, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import type { AgentTask } from "@/domain/tasks/schema";
import { ImplementationChangeProposalSchema, type ImplementationChangeProposal, type ExecutionPolicy } from "./contracts";
import { ImplementationError } from "./errors";
import { isWithinTaskScope } from "./scope";
import { ownershipForTask } from "@/domain/tasks/ownership";

const sha = (value: Buffer) => createHash("sha256").update(value).digest("hex");
const pathPattern = (pattern: string, value: string) => { const escaped = pattern.replaceAll("\\", "/").replace(/\*\*/g, "§§").replace(/\*/g, "[^/]*").replace(/[.+?^${}()|[\]\\]/g, "\\$&").replaceAll("§§", ".*"); return new RegExp(`^${escaped}$`, "i").test(value); };
const fileNameUnsafe = (value: string) => value.startsWith("/") || /^[A-Za-z]:/.test(value) || value.includes("\0") || value.split("/").includes("..") || value.split("/").some((part) => /^(con|prn|aux|nul|com[1-9]|lpt[1-9])(?:\..*)?$/i.test(part));
const forbidden = (value: string) => value === ".git" || value.startsWith(".git/") || value === ".factory" || value.startsWith(".factory/") || /(^|\/)\.env(?:\.|$)/i.test(value) && value !== ".env.example" || value.startsWith("node_modules/") || value.startsWith(".next/") || value.startsWith("dist/") || value.startsWith("coverage/") || /(^|\/)(pnpm-lock\.yaml|pnpm-workspace\.yaml|yarn\.lock|bun\.lockb?)$/i.test(value) || /\.(zip|tar|gz|7z|rar|exe|dll)$/i.test(value);
const secretLike = /(sk-[A-Za-z0-9]{12,}|AKIA[A-Z0-9]{12,}|BEGIN .*PRIVATE KEY|DATABASE_URL\s*[:=]|password\s*[:=])/i;
export function validateProposal(task: AgentTask, proposal: ImplementationChangeProposal, root: string, policy: ExecutionPolicy) {
  try { ImplementationChangeProposalSchema.parse(proposal); } catch (error) { throw new ImplementationError("IMPLEMENTATION_INPUT_INVALID", "Change proposal does not match the strict contract.", error); }
  if (proposal.projectId !== task.projectId || proposal.projectVersion !== task.projectVersion || proposal.taskId !== task.id || proposal.taskAttempt !== task.attempt) throw new ImplementationError("IMPLEMENTATION_GRAPH_STALE", "Change proposal does not match the authorized task attempt.");
  if (proposal.operations.length > policy.maxProposalOperations) throw new ImplementationError("IMPLEMENTATION_CONTENT_LIMIT_EXCEEDED", "Proposal operation limit was exceeded.");
  if (new Set(proposal.operations.map((operation) => operation.relativePath)).size !== proposal.operations.length) throw new ImplementationError("IMPLEMENTATION_OPERATION_CONFLICT", "Proposal contains duplicate file operations.");
  for (const operation of proposal.operations) { const relative = operation.relativePath.replaceAll("\\", "/"); if (fileNameUnsafe(relative)) throw new ImplementationError("IMPLEMENTATION_PATH_INVALID", "Proposal path is unsafe."); if (forbidden(relative)) throw new ImplementationError("IMPLEMENTATION_FORBIDDEN_FILE", "Proposal targets a forbidden file."); const scopes = task.taskType === "implement-project-foundation" ? [...new Set([...task.fileScopes, ...(ownershipForTask(task.taskType)?.scopes ?? [])])] : task.fileScopes; if (!scopes.some((scope) => isWithinTaskScope(scope, relative))) throw new ImplementationError("IMPLEMENTATION_SCOPE_VIOLATION", `Proposal path is outside task scope: path=${relative}; operation=${operation.type}; scopes=${scopes.join(",")}.`); if (operation.encoding !== "utf-8") throw new ImplementationError("IMPLEMENTATION_BINARY_UNSUPPORTED", "Only UTF-8 text operations are supported."); const content = operation.type === "patch-text" ? operation.newText : operation.type === "delete-file" ? "" : operation.content; if (Buffer.byteLength(content, "utf8") > policy.maxOperationContentBytes || secretLike.test(content)) throw new ImplementationError("IMPLEMENTATION_CONTENT_LIMIT_EXCEEDED", "Proposal content is too large or contains secret-like data."); if (relative === "package.json" && operation.type !== "delete-file") { let parsed: unknown; try { parsed = JSON.parse(content); } catch (error) { throw new ImplementationError("PACKAGE_JSON_INVALID", "package.json content is invalid.", error); } if (typeof parsed !== "object" || parsed === null || Array.isArray(parsed)) throw new ImplementationError("PACKAGE_JSON_INVALID", "package.json must contain a JSON object."); const value = parsed as Record<string, unknown>; if (typeof value.packageManager === "string" && !/^npm(?:@|$)/i.test(value.packageManager)) throw new ImplementationError("PACKAGE_MANAGER_POLICY_VIOLATION", "Only npm is permitted."); } }
  return true;
}

export interface AppliedChanges { changedFiles: string[]; createdFiles: string[]; deletedFiles: string[]; beforeChecksums: Record<string, string>; afterChecksums: Record<string, string>; }
export class AtomicChangeApplier {
  async apply(task: AgentTask, proposal: ImplementationChangeProposal, rootDirectory: string, policy: ExecutionPolicy, isCancelled: () => boolean = () => false): Promise<AppliedChanges> {
    validateProposal(task, proposal, rootDirectory, policy); const root = path.resolve(rootDirectory); const transaction = path.join(root, policy.transactionDirectoryName, proposal.proposalId); await mkdir(transaction, { recursive: true }); const backups = new Map<string, Buffer | null>(); const beforeChecksums: Record<string, string> = {}; const touched = proposal.operations.map((operation) => operation.relativePath.replaceAll("\\", "/"));
    try { for (const operation of proposal.operations) { if (isCancelled()) throw new ImplementationError("IMPLEMENTATION_CANCELLED", "Implementation was cancelled before file application."); const target = path.resolve(root, operation.relativePath); if (!target.toLowerCase().startsWith(`${root.toLowerCase()}${path.sep}`)) throw new ImplementationError("IMPLEMENTATION_PATH_INVALID", "Resolved proposal path escapes the staging workspace."); let previous: Buffer | null = null; try { const info = await lstat(target); if (info.isSymbolicLink() || !info.isFile()) throw new ImplementationError("IMPLEMENTATION_WORKSPACE_TAMPERED", "A target path is not a regular file."); previous = await readFile(target); } catch (error) { if (error instanceof ImplementationError) throw error; if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error; } backups.set(operation.relativePath, previous); if (previous) beforeChecksums[operation.relativePath] = sha(previous); if (operation.expectedPriorChecksum && operation.expectedPriorChecksum !== (previous ? sha(previous) : undefined)) throw new ImplementationError("IMPLEMENTATION_CHECKSUM_MISMATCH", "A proposal prior checksum is stale."); let next: Buffer | null; if (operation.type === "delete-file") next = null; else if (operation.type === "patch-text") { if (!previous) throw new ImplementationError("IMPLEMENTATION_EXPECTED_FILE_MISSING", "Patch target does not exist."); const current = previous.toString("utf8"); const occurrences = current.split(operation.oldText).length - 1; if (occurrences !== 1) throw new ImplementationError("IMPLEMENTATION_OPERATION_CONFLICT", "Patch text must match exactly once."); next = Buffer.from(current.replace(operation.oldText, operation.newText), "utf8"); } else next = Buffer.from(operation.content, "utf8"); if (next && sha(next) !== operation.expectedResultChecksum) throw new ImplementationError("IMPLEMENTATION_RESULT_CHECKSUM_MISMATCH", "Operation result checksum does not match."); if (next) { await mkdir(path.dirname(target), { recursive: true }); const temp = path.join(transaction, `${touched.indexOf(operation.relativePath)}.tmp`); await writeFile(temp, next, { flag: "wx", mode: 0o600 }); await rename(temp, target); } else await rm(target, { force: false }); }
      const afterChecksums: Record<string, string> = {}; const createdFiles: string[] = []; const deletedFiles: string[] = []; for (const operation of proposal.operations) { const target = path.resolve(root, operation.relativePath); try { const bytes = await readFile(target); afterChecksums[operation.relativePath] = sha(bytes); if (!backups.get(operation.relativePath)) createdFiles.push(operation.relativePath); } catch (error) { if ((error as NodeJS.ErrnoException).code === "ENOENT") deletedFiles.push(operation.relativePath); else throw error; } } await rm(transaction, { recursive: true, force: true }); return { changedFiles: touched, createdFiles, deletedFiles, beforeChecksums, afterChecksums }; }
    catch (error) { for (const [relative, previous] of backups) { const target = path.resolve(root, relative); if (previous === null) await rm(target, { force: true }).catch(() => undefined); else { await mkdir(path.dirname(target), { recursive: true }); await writeFile(target, previous, { flag: "w", mode: 0o600 }); } } await rm(transaction, { recursive: true, force: true }).catch(() => undefined); if (error instanceof ImplementationError) throw error; throw new ImplementationError("IMPLEMENTATION_WORKSPACE_TAMPERED", "Atomic proposal application failed and was rolled back.", error); }
  }
}
