import { createHash, randomUUID } from "node:crypto";
import { mkdtemp, mkdir, readFile, rm, symlink, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { describe, expect, it } from "vitest";
import { AgentTaskSchema } from "@/domain/tasks/schema";
import { DEFAULT_EXECUTION_POLICY, ImplementationChangeProposalSchema } from "./contracts";
import type { ImplementationContext } from "./contracts";
import { StoragePlanSchema } from "@/agents/planner/contracts";
import { assertBackendTaskRequired, canonicalFormFieldIdentity, formFieldValidationDiagnostic, validateBackendProposal, validateNoHiddenFallback, type BackendPlans } from "./backend";
import { validateTaskResult } from "./validators";
import { DeterministicImplementationProvider } from "./provider";
import { AtomicChangeApplier } from "./applier";
const task = (taskType: string) => AgentTaskSchema.parse({ id: randomUUID(), projectId: randomUUID(), projectVersion: 1, role: "implementation", taskType, title: taskType, objective: taskType, inputs: [], expectedOutputs: [], allowedSkills: [], allowedTools: ["filesystem-read", "filesystem-write"], fileScopes: ["**/*"], dependencies: [], status: "ready", attempt: 0, maxAttempts: 3, createdAt: "2026-01-01T00:00:00.000Z" });
const storagePlan = (projectId: string) => StoragePlanSchema.parse({ schemaVersion: 1, documentType: "storage-plan", projectId, projectVersion: 1, createdAt: "2026-01-01T00:00:00.000Z", updatedAt: "2026-01-01T00:00:00.000Z", decision: "supabase-storage", assetCategories: ["Runtime user uploads"], uploadActors: ["Authenticated users"], acceptedFormats: ["Images"], sizeLimits: ["5 MB"], validation: ["MIME, extension, size, ownership"], access: "private", buckets: ["approved-uploads"], bucketId: "approved-uploads", policyIdentity: "runtime-owner-scoped-storage", ownerSource: "authenticated-user-id", objectPathStrategy: "user-id-prefix", objectPathTemplate: "{userId}/{objectName}", allowedOperations: ["SELECT", "INSERT", "UPDATE", "DELETE"], directClientAccess: false, signedUrl: { enabled: true, operations: ["SELECT", "INSERT"], expirySeconds: 60 }, ownershipTransfer: "forbidden", serverPrivilegedAccess: false, retention: "Pending", deletionBehavior: "Owner deletion", policies: ["Bucket-scoped authenticated Storage ownership policies"], traceability: [{ decisionId: randomUUID(), category: "storage", requirementReferences: ["brief:storageDecision"], systemConstraintReferences: [], rationale: "Typed storage contract", confidence: "high", userConfirmationRequired: false }] });
const proposal = (currentTask: ReturnType<typeof task>, relativePath: string, content: string) => ImplementationChangeProposalSchema.parse({ proposalId: randomUUID(), projectId: currentTask.projectId, projectVersion: 1, taskId: currentTask.id, taskAttempt: 0, summary: "backend", operations: [{ type: "create-file", relativePath, expectedResultChecksum: createHash("sha256").update(content).digest("hex"), encoding: "utf-8", reason: "planned", requirementReferences: [], planningReferences: [], selectedDesignReferences: [], content }], expectedChangedFiles: [relativePath], expectedCreatedFiles: [relativePath], expectedDeletedFiles: [], validationPlan: [currentTask.taskType], requirementReferences: [], planningReferences: [], selectedDesignReferences: [], providerMetadata: { provider: "test" }, generatedAt: "2026-01-01T00:00:00.000Z" });
const formPlans: BackendPlans = { brief: { forms: ["contact"] }, planning: { forms: { forms: [{ fields: [{ name: "name", required: true }] }] } } };
const providerContext = (taskType: string): ImplementationContext => { const currentTask = task(taskType); return { task: currentTask, acceptanceCriteria: [], requirementReferences: [], planningReferences: [], selectedDesignReferences: [], architectureExcerpt: {}, contentExcerpt: {}, assetExcerpt: {}, ...(taskType === "implement-storage" ? { storagePlan: storagePlan(currentTask.projectId) } : {}), files: [], skills: [], skillContextIdentity: "none", allowedTools: [], conventions: [], contextChecksum: "a".repeat(64) }; };
const atomicOperation = (type: "create-file" | "replace-file", relativePath: string, content: string, expectedPriorChecksum?: string) => ({ type, relativePath, ...(expectedPriorChecksum ? { expectedPriorChecksum } : {}), expectedResultChecksum: createHash("sha256").update(content).digest("hex"), encoding: "utf-8" as const, reason: "cg-16 atomic recovery evidence", requirementReferences: [], planningReferences: [], selectedDesignReferences: [], content });
const atomicProposal = (currentTask: ReturnType<typeof task>, operations: Array<ReturnType<typeof atomicOperation>>) => ImplementationChangeProposalSchema.parse({ proposalId: randomUUID(), projectId: currentTask.projectId, projectVersion: currentTask.projectVersion, taskId: currentTask.id, taskAttempt: currentTask.attempt, summary: "cg-16 atomic recovery regression", operations, expectedChangedFiles: operations.map((operation) => operation.relativePath), expectedCreatedFiles: [], expectedDeletedFiles: [], validationPlan: ["atomic-application-recovery"], requirementReferences: [], planningReferences: [], selectedDesignReferences: [], providerMetadata: { provider: "test" }, generatedAt: "2026-01-01T00:00:00.000Z" });
const atomicFixture = async () => { const root = await mkdtemp(path.join(os.tmpdir(), "factory-cg16-applier-")); await mkdir(path.join(root, "src"), { recursive: true }); return { root, currentTask: task("implement-project-foundation") }; };
describe("backend implementation policies", () => {
  it("rejects backend tasks that are not required", () => { expect(() => assertBackendTaskRequired(task("implement-authentication"), { brief: { authenticationDecision: "no-authentication-guest-first" } })).toThrowError(/do not require/); });
  it("accepts planned forms and rejects unplanned fields", () => { const current = task("implement-form"); expect(() => validateBackendProposal(current, proposal(current, "src/forms/contact.tsx", "import { z } from 'zod'; const schema = z.object({ name: z.string() });"), formPlans)).not.toThrow(); expect(() => validateBackendProposal(current, proposal(current, "src/forms/contact.tsx", "<input name=\"phone\" />"), formPlans)).toThrowError(/unplanned field/); });
  it("keeps client-only form implementation local and rejects network or server boundaries", () => { const current = task("implement-form"); const plans: BackendPlans = { brief: { forms: ["contact"] }, planning: { forms: { forms: [{ submissionMechanism: "client-only", fields: [{ fieldId: "message", label: "Message", required: true, validation: ["Required"] }] }] } } }; const local = "import { z } from 'zod'; const schema = z.object({ message: z.string().min(1) }); function onSubmit(message: string) { const parsed = schema.safeParse({ message }); return parsed.success ? 'simulated-success' : 'validation-error'; } <textarea name=\"message\" />"; expect(() => validateBackendProposal(current, proposal(current, "src/forms/contact.tsx", local), plans)).not.toThrow(); expect(() => validateBackendProposal(current, proposal(current, "src/forms/contact.tsx", `${local} fetch('/api/contact')`), plans)).toThrowError(/client-only|server|network/i); });
  it("normalizes only explicit form field aliases and ignores submit controls", () => { const current = task("implement-form"); const plans: BackendPlans = { planning: { forms: { forms: [{ fields: [{ name: "E-Mail", required: true }, { name: "Fahrradtyp", required: true }] }] } } }; expect(canonicalFormFieldIdentity("email")).toBe("email"); expect(canonicalFormFieldIdentity("E-Mail")).toBe("email"); expect(canonicalFormFieldIdentity("bikeType")).toBe("fahrradtyp"); expect(() => validateBackendProposal(current, proposal(current, "src/forms/contact.tsx", "import { z } from 'zod'; const schema = z.object({ email: z.string(), bikeType: z.string() }); <input name=\"email\" /><input name=\"bikeType\" /><button name=\"submit\">Senden</button>"), plans)).not.toThrow(); });
  it("reports deterministic raw, canonical, and approved field identities", () => { const plans: BackendPlans = { planning: { forms: { forms: [{ fields: [{ name: "Fahrradtyp", required: true }, { name: "Beschreibung des Problems", required: true }] }] } } }; expect(formFieldValidationDiagnostic("bikeType", plans)).toEqual({ raw: "bikeType", canonical: "fahrradtyp", approvedCanonical: "fahrradtyp", approvedAliases: ["fahrradtyp", "bicycletype", "bicycle-type", "bikeType"] }); expect(formFieldValidationDiagnostic("phone", plans)).toEqual({ raw: "phone", canonical: "phone" }); expect(canonicalFormFieldIdentity("bicycleType")).toBe("fahrradtyp"); expect(canonicalFormFieldIdentity("problemDescription")).toBe("beschreibungdesproblems"); });
  it("compares new FormPlan fieldIds directly and keeps localized labels out of identity", () => { const current = task("implement-form"); const plans: BackendPlans = { planning: { forms: { forms: [{ fields: [{ fieldId: "bikeType", label: "Fahrradtyp", required: true, validation: ["Required"] }, { fieldId: "problemDescription", label: "Beschreibung des Problems", required: true, validation: ["Required"] }] }] } } }; const source = "import { z } from 'zod'; const schema = z.object({ bikeType: z.string(), problemDescription: z.string() }); <input name=\"bikeType\" /><textarea name=\"problemDescription\" />"; expect(() => validateBackendProposal(current, proposal(current, "src/forms/contact.tsx", source), plans)).not.toThrow(); expect(formFieldValidationDiagnostic("bikeType", plans)).toEqual({ raw: "bikeType", canonical: "bikeType", approvedCanonical: "bikeType" }); expect(formFieldValidationDiagnostic("Fahrradtyp", plans).approvedCanonical).toBeUndefined(); });
  it("reports missing planned Zod validation precisely", () => { const current = task("implement-form"); const plans: BackendPlans = { planning: { forms: { forms: [{ fields: [{ fieldId: "bikeType", label: "Fahrradtyp", required: true, validation: ["Required"] }] }] } } }; expect(() => validateBackendProposal(current, proposal(current, "src/forms/contact.tsx", "<input name=\"bikeType\" />"), plans)).toThrowError(/planned Zod validation.*bikeType/); });
  it("requires validation and authorization patterns", () => { const current = task("implement-server-action"); expect(() => validateBackendProposal(current, proposal(current, "src/actions/save.ts", "\"use server\"; export async function save() {}"))).toThrowError(); });
  it("rejects hidden successful fallbacks in server implementation catch paths", () => {
    const hiddenFallback = `"use server"; import { z } from "zod"; const schema = z.object({}); export async function save(input: unknown) { const parsed = schema.safeParse(input); if (!parsed.success) return { ok: false }; try { await persist(parsed.data); } catch { return { ok: true }; } }`;
    expect(() => validateNoHiddenFallback(hiddenFallback)).toThrowError(/hidden|fallback|successful/i);
    const current = task("implement-server-action");
    expect(() => validateBackendProposal(current, proposal(current, "src/actions/save.ts", hiddenFallback))).toThrowError(/hidden|fallback|successful/i);
  });
  it("keeps migrations safe and under the migration directory", () => { const current = task("implement-database-schema"); expect(() => validateBackendProposal(current, proposal(current, "src/db.ts", "drop table users;"))).toThrowError(/migration/); expect(() => validateBackendProposal(current, proposal(current, "supabase/migrations/20260807120000_create.sql", "drop table users;"))).toThrowError(/prohibited|Destructive/); expect(() => validateBackendProposal(current, proposal(current, "supabase/migrations/20260807120000_create.sql", "create table contacts (id uuid primary key, user_id uuid not null references auth.users(id));"), { planning: { dataModel: { entities: [{ name: "contacts" }] } } })).not.toThrow(); });
  it("rejects broad RLS and unsafe storage", () => { const rls = task("implement-rls-policy"); expect(() => validateBackendProposal(rls, proposal(rls, "supabase/migrations/rls.sql", "alter table x enable row level security; create policy p on x using (true);"))).toThrowError(/Broad/); const storage = task("implement-storage"); expect(() => validateBackendProposal(storage, proposal(storage, "src/storage.ts", "bucket(req.bucket);"), { brief: { storageDecision: "needed" }, planning: { storage: storagePlan(storage.projectId) } })).toThrowError(/unsafe|STORAGE/i); });
  it("rejects generic proxies and undeclared environment variables", () => { const route = task("implement-route-handler"); expect(() => validateBackendProposal(route, proposal(route, "src/app/api/x/route.ts", "export async function POST(){ return fetch('https://example.com'); }"))).toThrowError(/proxy|validation/); const action = task("implement-server-action"); expect(() => validateBackendProposal(action, proposal(action, "src/actions/x.ts", "\"use server\"; import { getAuthenticatedUser } from '@/lib/supabase/auth'; const x=process.env.UNKNOWN; const s=z.object({}); export async function x(){ const user=await getAuthenticatedUser(); if(!user) return {ok:false}; const ownerId=user.id; return s.parse({ ownerId }); }"), { planning: { architecture: { serverActions: ["x"], environment: { variables: [] } } } })).toThrowError(/environment|undeclared/); });
  it("requires authenticated ownership for generated handlers and RLS", () => { const action = task("implement-server-action"); const unsafe = "\"use server\"; import { z } from 'zod'; const schema=z.object({}); export async function save(input: unknown){ const parsed=schema.safeParse(input); return parsed.success ? { ok: true } : { ok: false }; }"; expect(() => validateBackendProposal(action, proposal(action, "src/actions/x.ts", unsafe))).toThrowError(/authenticated|AUTHENTICATION/); const rls = task("implement-rls-policy"); const unsafeRls = "alter table x enable row level security; create policy p on x for select to authenticated using (auth.uid() is not null);"; expect(() => validateBackendProposal(rls, proposal(rls, "supabase/migrations/rls.sql", unsafeRls))).toThrowError(/RLS|ownership|Broad/); });
  it("generates and accepts the complete authenticated ownership contract", async () => { const provider = new DeterministicImplementationProvider(); const generated = new Map<string, string>(); for (const taskType of ["implement-authentication", "implement-server-action", "implement-route-handler", "implement-database-schema", "implement-rls-policy"]) { const result = await provider.proposeTaskChanges(providerContext(taskType)); const operation = result.operations[0]; if (!operation || !("content" in operation)) throw new Error(`Missing generated content for ${taskType}`); generated.set(taskType, operation.content); } expect(generated.get("implement-authentication")).toMatch(/createServerClient|auth\.getUser/); expect(generated.get("implement-server-action")).toMatch(/getAuthenticatedUser|user\.id/); expect(generated.get("implement-route-handler")).toMatch(/getAuthenticatedUser|user\.id/); expect(generated.get("implement-database-schema")).toMatch(/user_id.*references auth\.users/i); expect(generated.get("implement-rls-policy")).toMatch(/auth\.uid\(\)\s*=\s*user_id/i); const authTask = task("implement-authentication"); expect(() => validateBackendProposal(authTask, proposal(authTask, "src/lib/supabase/auth.ts", generated.get("implement-authentication")!), { brief: { authenticationDecision: "authentication-required" }, planning: { architecture: { environment: { variables: [{ name: "NEXT_PUBLIC_SUPABASE_URL", serverOnly: true, secret: false }, { name: "NEXT_PUBLIC_SUPABASE_ANON_KEY", serverOnly: true, secret: false }] } } } })).not.toThrow(); const schemaTask = task("implement-database-schema"); expect(() => validateBackendProposal(schemaTask, proposal(schemaTask, "supabase/migrations/schema.sql", generated.get("implement-database-schema")!), { planning: { dataModel: { entities: [{ name: "approved_records" }] } } })).not.toThrow(); const rlsTask = task("implement-rls-policy"); expect(() => validateBackendProposal(rlsTask, proposal(rlsTask, "supabase/migrations/rls.sql", generated.get("implement-rls-policy")!))).not.toThrow(); });
  it("accepts environment declarations from the generated PlanningPackage shape", async () => { const provider = new DeterministicImplementationProvider(); const generated = await provider.proposeTaskChanges(providerContext("implement-authentication")); const authTask = task("implement-authentication"); const source = generated.operations.find((operation) => operation.relativePath === "src/lib/supabase/auth.ts"); if (!source || !("content" in source)) throw new Error("Missing generated authentication source"); expect(() => validateBackendProposal(authTask, proposal(authTask, "src/lib/supabase/auth.ts", source.content), { brief: { authenticationDecision: "authentication-required" }, planning: { architecture: { environmentVariables: [{ name: "NEXT_PUBLIC_SUPABASE_URL", serverOnly: false, secret: false }, { name: "NEXT_PUBLIC_SUPABASE_ANON_KEY", serverOnly: false, secret: false }] } } })).not.toThrow(); });
  it("keeps shared-component provider output inside its assigned scope", async () => { const provider = new DeterministicImplementationProvider(); const sharedTask = AgentTaskSchema.parse({ ...task("implement-shared-component"), fileScopes: ["src/components/shared/profile/**"] }); const result = await provider.proposeTaskChanges({ ...providerContext("implement-shared-component"), task: sharedTask }); expect(result.operations[0]?.relativePath).toBe("src/components/shared/profile/index.tsx"); });
  it("keeps page provider output inside the assigned route scope", async () => { const provider = new DeterministicImplementationProvider(); const pageTask = AgentTaskSchema.parse({ ...task("implement-page"), fileScopes: ["src/app/dashboard/**"] }); const result = await provider.proposeTaskChanges({ ...providerContext("implement-page"), task: pageTask }); expect(result.operations[0]?.relativePath).toBe("src/app/dashboard/page.tsx"); });
  it("accepts a protected page authorized by its canonical route planning reference", async () => { const pageTask = AgentTaskSchema.parse({ ...task("implement-page"), fileScopes: ["src/app/dashboard/**"], planningReferences: ["route-dashboard"] }); const result = await new DeterministicImplementationProvider().proposeTaskChanges({ ...providerContext("implement-page"), task: pageTask }); expect(() => validateTaskResult(pageTask, result, {})).not.toThrow(); });
  it("keeps SEO provider output inside the metadata scope", async () => { const seoTask = AgentTaskSchema.parse({ ...task("implement-seo"), fileScopes: ["src/app/**/metadata.*"] }); const result = await new DeterministicImplementationProvider().proposeTaskChanges({ ...providerContext("implement-seo"), task: seoTask }); expect(result.operations[0]?.relativePath).toBe("src/app/seo/metadata.ts"); });
  it("emits non-placeholder test artifacts in their assigned scopes", async () => { const provider = new DeterministicImplementationProvider(); const unit = await provider.proposeTaskChanges(providerContext("write-unit-tests")); const integration = await provider.proposeTaskChanges({ ...providerContext("write-integration-tests"), task: AgentTaskSchema.parse({ ...task("write-integration-tests"), fileScopes: ["tests/integration/**"] }) }); const e2e = await provider.proposeTaskChanges({ ...providerContext("write-e2e-tests"), task: AgentTaskSchema.parse({ ...task("write-e2e-tests"), fileScopes: ["tests/e2e/**"] }) }); const database = await provider.proposeTaskChanges({ ...providerContext("write-database-tests"), task: AgentTaskSchema.parse({ ...task("write-database-tests"), fileScopes: ["supabase/tests/**"] }) }); const unitContent = unit.operations[0] && "content" in unit.operations[0] ? unit.operations[0].content : ""; const e2eContent = e2e.operations[0] && "content" in e2e.operations[0] ? e2e.operations[0].content : ""; const databaseContent = database.operations.find((operation) => operation.relativePath.includes("security")) && "content" in database.operations.find((operation) => operation.relativePath.includes("security"))! ? (database.operations.find((operation) => operation.relativePath.includes("security")) as { content: string }).content : ""; expect(unitContent).not.toMatch(/expect\(true\)/); expect(e2eContent).not.toMatch(/@playwright\/test|expect\(true\)/); expect(databaseContent).toContain("OWNER: PRIVILEGED cannot read rows outside its approved scope"); expect(databaseContent).not.toContain("OWNER_OR_ROLE: PRIVILEGED is allowed by the trusted role authority"); expect(integration.operations[0]?.relativePath).toBe("tests/integration/factory-integration.integration.test.ts"); });
  it("keeps storage helper generation inside the backend source boundary", async () => { const provider = new DeterministicImplementationProvider(); const storageTask = task("implement-storage"); const result = await provider.proposeTaskChanges(providerContext("implement-storage")); const source = result.operations.find((item) => item.relativePath.endsWith("uploads.ts")); if (!source || !("content" in source)) throw new Error("Missing generated storage helper"); const plans = { brief: { storageDecision: "needed" }, planning: { storage: storagePlan(storageTask.projectId) } } satisfies BackendPlans; expect(result.operations.some((item) => item.relativePath.endsWith(".sql"))).toBe(false); expect(() => validateBackendProposal(storageTask, result, plans)).not.toThrow(); expect(source.content).toMatch(/getAuthenticatedUser|user\.id/); expect(source.content).toMatch(/createSignedUploadUrl[\s\S]*validateUpload/); expect(source.content).toMatch(/createSignedUrl/); });
  it("rejects a storage task that attempts to write a database migration", async () => { const provider = new DeterministicImplementationProvider(); const storageTask = task("implement-storage"); const result = await provider.proposeTaskChanges(providerContext("implement-storage")); const source = result.operations[0]; if (!source || !("content" in source)) throw new Error("Missing generated storage helper"); const policyContent = "alter table storage.objects enable row level security;"; const policy = { ...source, relativePath: "supabase/migrations/20260905000000_storage.sql", content: policyContent, expectedResultChecksum: createHash("sha256").update(policyContent).digest("hex") }; const forged = ImplementationChangeProposalSchema.parse({ ...result, operations: [source, policy], expectedChangedFiles: [source.relativePath, policy.relativePath], expectedCreatedFiles: [source.relativePath, policy.relativePath] }); expect(() => validateBackendProposal(storageTask, forged, { brief: { storageDecision: "needed" }, planning: { storage: storagePlan(storageTask.projectId) } })).toThrowError(/scope|STORAGE|migration/i); });
  it("rejects storage contracts that can be forged across owners", async () => { const provider = new DeterministicImplementationProvider(); const storageTask = task("implement-storage"); const result = await provider.proposeTaskChanges(providerContext("implement-storage")); const operation = result.operations[0]; if (!operation || !("content" in operation)) throw new Error("Missing generated storage content"); const unsafe = operation.content.replace(/isOwnedObjectPath\(user\.id, objectPath\)/g, "true"); expect(() => validateBackendProposal(storageTask, proposal(storageTask, "src/lib/storage/uploads.ts", unsafe), { brief: { storageDecision: "needed" }, planning: { storage: storagePlan(storageTask.projectId) } })).toThrowError(/ownership|path|STORAGE/i); });
});

describe("atomic implementation failure and recovery evidence", () => {
  it("rolls back earlier operations when a later operation fails, then accepts a fresh recovery candidate", async () => {
    const f = await atomicFixture();
    try {
      await writeFile(path.join(f.root, "src", "first.ts"), "before-first");
      await writeFile(path.join(f.root, "src", "second.ts"), "before-second");
      const failedProposal = atomicProposal(f.currentTask, [
        atomicOperation("replace-file", "src/first.ts", "after-first", createHash("sha256").update("before-first").digest("hex")),
        { ...atomicOperation("replace-file", "src/second.ts", "after-second", createHash("sha256").update("before-second").digest("hex")), expectedResultChecksum: "f".repeat(64) },
      ]);
      const applier = new AtomicChangeApplier();
      await expect(applier.apply(f.currentTask, failedProposal, f.root, DEFAULT_EXECUTION_POLICY)).rejects.toMatchObject({ code: "IMPLEMENTATION_RESULT_CHECKSUM_MISMATCH" });
      expect(await readFile(path.join(f.root, "src", "first.ts"), "utf8")).toBe("before-first");
      expect(await readFile(path.join(f.root, "src", "second.ts"), "utf8")).toBe("before-second");
      const recoveryProposal = atomicProposal(f.currentTask, [
        atomicOperation("replace-file", "src/first.ts", "recovered-first", createHash("sha256").update("before-first").digest("hex")),
        atomicOperation("replace-file", "src/second.ts", "recovered-second", createHash("sha256").update("before-second").digest("hex")),
      ]);
      await expect(applier.apply(f.currentTask, recoveryProposal, f.root, DEFAULT_EXECUTION_POLICY)).resolves.toMatchObject({ changedFiles: ["src/first.ts", "src/second.ts"] });
      expect(await readFile(path.join(f.root, "src", "first.ts"), "utf8")).toBe("recovered-first");
      expect(await readFile(path.join(f.root, "src", "second.ts"), "utf8")).toBe("recovered-second");
    } finally { await rm(f.root, { recursive: true, force: true }); }
  });

  it("rolls back already-applied operations when cancellation arrives between operations", async () => {
    const f = await atomicFixture();
    try {
      await writeFile(path.join(f.root, "src", "first.ts"), "before-first");
      await writeFile(path.join(f.root, "src", "second.ts"), "before-second");
      const proposalValue = atomicProposal(f.currentTask, [
        atomicOperation("replace-file", "src/first.ts", "after-first", createHash("sha256").update("before-first").digest("hex")),
        atomicOperation("replace-file", "src/second.ts", "after-second", createHash("sha256").update("before-second").digest("hex")),
      ]);
      let checks = 0;
      await expect(new AtomicChangeApplier().apply(f.currentTask, proposalValue, f.root, DEFAULT_EXECUTION_POLICY, () => checks++ > 0)).rejects.toMatchObject({ code: "IMPLEMENTATION_CANCELLED" });
      expect(await readFile(path.join(f.root, "src", "first.ts"), "utf8")).toBe("before-first");
      expect(await readFile(path.join(f.root, "src", "second.ts"), "utf8")).toBe("before-second");
    } finally { await rm(f.root, { recursive: true, force: true }); }
  });

  it("rejects unsafe and symlink targets without mutating the workspace", async () => {
    const f = await atomicFixture();
    try {
      const unsafe = atomicProposal(f.currentTask, [atomicOperation("create-file", "../outside.ts", "unsafe")]);
      await expect(new AtomicChangeApplier().apply(f.currentTask, unsafe, f.root, DEFAULT_EXECUTION_POLICY)).rejects.toMatchObject({ code: "IMPLEMENTATION_PATH_INVALID" });
      const outside = path.join(f.root, "outside-dir");
      const linked = path.join(f.root, "src", "linked.ts");
      await mkdir(outside);
      await writeFile(path.join(outside, "marker.ts"), "outside");
      await symlink(outside, linked, "junction");
      const symlinkProposal = atomicProposal(f.currentTask, [atomicOperation("replace-file", "src/linked.ts", "mutated", createHash("sha256").update("outside").digest("hex"))]);
      await expect(new AtomicChangeApplier().apply(f.currentTask, symlinkProposal, f.root, DEFAULT_EXECUTION_POLICY)).rejects.toMatchObject({ code: "IMPLEMENTATION_WORKSPACE_TAMPERED" });
      expect(await readFile(path.join(outside, "marker.ts"), "utf8")).toBe("outside");
    } finally { await rm(f.root, { recursive: true, force: true }); }
  });

  it("rejects stale prior checksums before mutation", async () => {
    const f = await atomicFixture();
    try {
      const target = path.join(f.root, "src", "checksum.ts");
      await writeFile(target, "current");
      const stale = atomicProposal(f.currentTask, [atomicOperation("replace-file", "src/checksum.ts", "new", createHash("sha256").update("stale").digest("hex"))]);
      await expect(new AtomicChangeApplier().apply(f.currentTask, stale, f.root, DEFAULT_EXECUTION_POLICY)).rejects.toMatchObject({ code: "IMPLEMENTATION_CHECKSUM_MISMATCH" });
      expect(await readFile(target, "utf8")).toBe("current");
    } finally { await rm(f.root, { recursive: true, force: true }); }
  });
});
