import { mkdtemp, mkdir, readFile, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { randomUUID, createHash } from "node:crypto";
import { describe, expect, it } from "vitest";
import { RequirementSpecificationSchema } from "@/domain/requirements/schema";
import { TechnicalArchitectureSchema } from "@/domain/architecture/schema";
import { ContentPlanSchema } from "@/domain/content/schema";
import { AssetManifestSchema } from "@/domain/assets/schema";
import { FactoryProjectSchema } from "@/domain/project/schema";
import { TaskGraphSchema, AgentTaskSchema } from "@/domain/tasks/schema";
import { DocumentRepository, ProjectRepository, ProjectVersionRepository } from "@/persistence/database/repositories";
import { InMemoryPersistenceDatabase } from "@/persistence/database/fake";
import type { PersistenceDatabase } from "@/persistence/database/types";
import { PersistenceError } from "@/persistence/database/errors";
import { checksumPersistedDocument } from "@/persistence/database/serialization";
import { ImplementationAgentService } from "./service";
import { DEFAULT_EXECUTION_POLICY, ImplementationChangeProposalSchema } from "./contracts";
import type { ImplementationProvider } from "./contracts";
import { AtomicChangeApplier, validateProposal } from "./applier";
import { cleanBriefV3 } from "@/domain/requirements/v3/fixtures";
import { CanonicalBriefV3Schema } from "@/domain/requirements/v3/schema";
import { canonicalBriefChecksum } from "@/domain/requirements/v3/normalize";
import { computeSourceManifest } from "@/integrations/codebase-memory/policy";
import { TaskContextAssembler, context7ImplementationTopic } from "./policy";

const id = () => randomUUID(); const sha = (v: string) => createHash("sha256").update(v).digest("hex"); const roots: string[] = [];
const task = (overrides: Record<string, unknown> = {}) => AgentTaskSchema.parse({ id: id(), projectId: id(), projectVersion: 1, role: "implementation", taskType: "implement-project-foundation", title: "Foundation", objective: "Prepare foundation", requirementReferences: ["requirement:foundation"], planningReferences: ["decision:foundation"], selectedDesignReferences: [], inputs: [], expectedOutputs: ["foundation"], acceptanceCriteria: ["Foundation files exist"], allowedSkills: [], allowedTools: ["filesystem-read", "filesystem-write"], deniedTools: [], fileScopes: ["src/app/**", "eslint.config.mjs"], dependencies: [], status: "ready", priority: "high", executionMode: "exclusive-write", attempt: 0, maxAttempts: 3, createdAt: "2026-01-01T00:00:00.000Z", blockingFailure: true, estimatedContextBytes: 1000, expectedArtifactTypes: ["source"], ...overrides });
const docs = (projectId: string) => { const brief = RequirementSpecificationSchema.parse({ schemaVersion: 1, documentType: "requirements", projectId, projectVersion: 1, createdAt: "2026-01-01T00:00:00.000Z", updatedAt: "2026-01-01T00:00:00.000Z", projectSummary: "A site", protectedFunctionalityRequired: false, imagesRequired: false, businessGoals: ["Explain"], targetAudiences: ["Visitors"], pages: [{ slug: "home", purpose: "Explain" }], userRoles: [], features: [], forms: [], contentRequirements: [], backendRequirements: [], supabaseRequirements: [], authenticationDecision: "no-authentication-guest-first", storageDecision: "not-needed", emailDecision: "not-needed", administrationDecision: "not-needed", seoRequirements: [], localization: { locales: ["en"], defaultLocale: "en" }, imageSourceDecision: "user-supplied", suppliedBrandInformation: { status: "missing" }, suppliedLogoLocation: { status: "missing" }, technicalConstraints: [], explicitExclusions: [], userAcceptanceCriteria: ["Explain"], unresolvedItems: [], approval: { approved: true, approvedRequirementsChecksum: "a".repeat(64) }, briefStatus: "approved", briefVersion: 1 }); const architecture = TechnicalArchitectureSchema.parse({ schemaVersion: 1, documentType: "architecture", projectId, projectVersion: 1, createdAt: brief.createdAt, updatedAt: brief.updatedAt, applicationProfile: "marketing-site", packageManager: "npm", routes: [{ path: "/", responsibility: "Home" }], componentBoundaries: [], componentDecisions: [], serverActions: [], routeHandlers: [], backendPriority: ["server-actions", "route-handlers", "supabase-services"], supabaseDatabaseRequirements: [], schemaPlan: [], rlsRequirements: [], authenticationPlan: "none", storagePlan: "not-required", emailPlan: "not-required", environmentVariables: [], dependencies: [], npmScripts: { build: "next build" }, testStrategy: [], securityControls: [], rejectedInfrastructure: [], acceptance: { accepted: true } }); const content = ContentPlanSchema.parse({ schemaVersion: 1, documentType: "content-plan", projectId, projectVersion: 1, createdAt: brief.createdAt, updatedAt: brief.updatedAt, userProvidedFacts: ["Explain"], approvedGeneratedCopy: [], missingFactualContent: [], legalContentRequiringConfirmation: [], approvedPlaceholders: [], suppliedContentNotes: [] }); const assets = AssetManifestSchema.parse({ schemaVersion: 1, documentType: "asset-manifest", projectId, projectVersion: 1, createdAt: brief.createdAt, updatedAt: brief.updatedAt, entries: [] }); const selected = { schemaVersion: 1 as const, documentType: "selected-design" as const, projectId, projectVersion: 1, createdAt: brief.createdAt, updatedAt: brief.updatedAt, directionSetId: id(), selectedDirectionId: id(), selectedAt: brief.createdAt, selectedBy: "user", selectionNotes: "Selected", selectedDirectionChecksum: "b".repeat(64) }; return { brief, architecture, content, assets, selected }; };
async function fixture(taskOverrides: Record<string, unknown> = {}) { const projectId = id(); const value = docs(projectId); const t = task({ projectId, ...taskOverrides }); const base = { schemaVersion: 1 as const, documentType: "task-graph" as const, projectId, projectVersion: 1, createdAt: t.createdAt, updatedAt: t.createdAt, tasks: [t], validation: { valid: true, errors: [], warnings: [] }, checkpoint: "implementation-started" as const }; const graph = TaskGraphSchema.parse({ ...base, graphChecksum: checksumPersistedDocument(base) }); const root = await mkdtemp(path.join(os.tmpdir(), "factory-implementation-")); roots.push(root); await mkdir(path.join(root, "src", "app"), { recursive: true }); const project = FactoryProjectSchema.parse({ schemaVersion: 1, documentType: "factory-project", projectId, projectVersion: 1, createdAt: t.createdAt, updatedAt: t.createdAt, id: t.projectId, slug: `fixture-${projectId.slice(0, 8)}`, originalPrompt: "fixture", currentVersion: 1, workflowState: "IMPLEMENTING" }); const db = new InMemoryPersistenceDatabase(); await new ProjectRepository(db).create(project); await new ProjectVersionRepository(db).create({ id: id(), projectId, versionNumber: 1, state: "IMPLEMENTING", memoryRootPath: root, requirementsChecksum: null, selectedDesignChecksum: null, architectureChecksum: null, releasedAt: null, immutable: false, createdAt: t.createdAt, updatedAt: t.createdAt, rowVersion: 1 }); await new DocumentRepository(db).save(graph); const input = { projectId, projectVersion: 1, taskId: t.id, expectedTaskState: "ready" as const, expectedTaskRowVersion: 1, expectedProjectWorkflowState: "IMPLEMENTING" as const, taskGraphChecksum: graph.graphChecksum!, approvedBriefChecksum: checksumPersistedDocument(value.brief), acceptedPlanningChecksum: "c".repeat(64), selectedDesignChecksum: checksumPersistedDocument(value.selected), architectureChecksum: checksumPersistedDocument(value.architecture), workspaceReservationId: "reservation-1", stagingWorkspacePath: root, approvedSkillSnapshotChecksum: "d".repeat(64), toolPolicyVersion: "tool-policy-v1", orchestrationPolicyVersion: "orchestrator-v1", executionPolicyVersion: "implementation-v1", idempotencyKey: id(), cancellation: { requested: false }, task: t, taskGraph: graph, approvedBrief: value.brief, acceptedPlanningPackage: {}, selectedDesign: value.selected, technicalArchitecture: value.architecture, contentPlan: value.content, assetManifest: value.assets, approvedSkillRegistrySnapshot: { schemaVersion: 1 as const, checksum: "d".repeat(64), skills: [] }, projectImmutable: false }; const service = new ImplementationAgentService(db, { workspace: { verifyStaging: async () => true } }); return { db, input, root, task: t, service }; }

describe("Implementation Agent execution foundation", () => {
  it("keeps Context7 implementation queries on fixed library topics", () => { expect(context7ImplementationTopic("daisyui")).toBe("daisyUI Tailwind v4 plugin configuration"); expect(context7ImplementationTopic("next")).not.toContain("customer"); });
  it("executes exactly one deterministic READY foundation task and unlocks no unrelated task", async () => { const f = await fixture(); const result = await f.service.executeImplementationTask(f.input); expect(result.status).toBe("passed"); expect(await readFile(path.join(f.root, "src/app/layout.tsx"), "utf8")).toContain("RootLayout"); expect((await f.service.getNewlyReadyTasks(f.input.projectId, 1)).some((t) => t.id === f.task.id)).toBe(false); });
  it("records the mandatory DesignSystemChecklist before frontend handoff", async () => { const f = await fixture({ taskType: "implement-page", implementationDomain: "FRONTEND", specialistProfileId: "frontend-implementation", fileScopes: ["src/app/page.tsx"] }); const result = await f.service.executeImplementationTask(f.input); expect(result.status).toBe("passed"); expect(result.designChecklist).toMatchObject({ verdict: "PASS", designChecksum: f.input.selectedDesignChecksum, designFidelity: "PASS", surfaces: "PASS", uxStates: "PASS" }); expect(result.validationResults.some((validation) => validation.name === "design-system-checklist")).toBe(true); });
  it("blocks a frontend handoff on a checklist violation and rolls back the candidate", async () => { const f = await fixture({ taskType: "implement-page", implementationDomain: "FRONTEND", specialistProfileId: "frontend-implementation", fileScopes: ["src/app/page.tsx"] }); const deterministic = new (await import("./provider")).DeterministicImplementationProvider(); const violating = new ImplementationAgentService(f.db, { workspace: { verifyStaging: async () => true }, provider: { proposeTaskChanges: async (context) => { const proposal = await deterministic.proposeTaskChanges(context); return ImplementationChangeProposalSchema.parse({ ...proposal, operations: proposal.operations.map((operation) => "content" in operation ? { ...operation, content: `${operation.content}<p>testimonial from our customer</p>\n`, expectedResultChecksum: sha(`${operation.content}<p>testimonial from our customer</p>\n`) } : operation) }); } } }); await expect(violating.executeImplementationTask(f.input)).rejects.toMatchObject({ code: "IMPLEMENTATION_DESIGN_VIOLATION" }); await expect(readFile(path.join(f.root, "src/app/page.tsx"))).rejects.toMatchObject({ code: "ENOENT" }); const runs = await new DocumentRepository(f.db).get(f.input.projectId, 1, "implementation-runs"); expect(runs?.documentType).toBe("implementation-runs"); if (runs?.documentType === "implementation-runs") expect(runs.runs[0]?.designChecklist).toMatchObject({ verdict: "BLOCK" }); });
  it("allows full execution to remain the sole TaskGraph persistence owner", async () => { const f = await fixture(); const service = new ImplementationAgentService(f.db, { workspace: { verifyStaging: async () => true }, taskGraphOwner: "full-execution" }); const result = await service.executeImplementationTask(f.input); expect(result.status).toBe("passed"); const persisted = await new DocumentRepository(f.db).get(f.input.projectId, 1, "task-graph"); expect(persisted?.documentType).toBe("task-graph"); if (persisted?.documentType === "task-graph") expect(persisted.tasks[0]?.status).toBe("ready"); expect((await new DocumentRepository(f.db).get(f.input.projectId, 1, "implementation-runs"))?.documentType).toBe("implementation-runs"); });
  it("preserves committed canonical output when only the derived memory projection fails", async () => { const f = await fixture(); const service = new ImplementationAgentService(f.db, { workspace: { verifyStaging: async () => true }, memory: { writeSnapshot: async () => { throw new Error("synthetic-memory-failure"); } } }); const result = await service.executeImplementationTask(f.input); expect(result.status).toBe("passed"); expect(await readFile(path.join(f.root, "src/app/layout.tsx"), "utf8")).toContain("RootLayout"); const persisted = await new DocumentRepository(f.db).get(f.input.projectId, 1, "task-graph"); expect(persisted?.documentType).toBe("task-graph"); if (persisted?.documentType === "task-graph") expect(persisted.tasks[0]?.status).toBe("passed"); });
  it("reconciles an ambiguous canonical commit before deciding whether workspace rollback is safe", async () => { const f = await fixture(); let raised = false; const ambiguous: PersistenceDatabase = { transaction: async (work) => { const result = await f.db.transaction(work); if (!raised && (await new DocumentRepository(f.db).get(f.input.projectId, 1, "implementation-runs"))?.documentType === "implementation-runs") { raised = true; throw new PersistenceError("PERSISTENCE_COMMIT_AMBIGUOUS", "Synthetic lost COMMIT acknowledgement."); } return result; } }; const service = new ImplementationAgentService(ambiguous, { workspace: { verifyStaging: async () => true } }); const result = await service.executeImplementationTask(f.input); expect(result.status).toBe("passed"); expect(await readFile(path.join(f.root, "src/app/layout.tsx"), "utf8")).toContain("RootLayout"); });
  it("generates the runtime foundation manifest with the approved QA start script", async () => { const f = await fixture({ fileScopes: ["package.json", "package-lock.json", "src/app/**", "eslint.config.mjs"], requiredArtifacts: ["package.json", "package-lock.json"] }); const result = await f.service.executeImplementationTask(f.input); expect(result.status).toBe("passed"); expect(JSON.parse((await readFile(path.join(f.root, "package.json"))).toString()).scripts["start:test"]).toBe("next start"); });
  it("rejects stale graph, non-current versions, wrong role, incomplete dependencies and unsupported types", async () => { const f = await fixture(); await expect(f.service.executeImplementationTask({ ...f.input, taskGraphChecksum: "e".repeat(64) })).rejects.toMatchObject({ code: "IMPLEMENTATION_GRAPH_STALE" }); const stale = await fixture(); const staleProject = stale.db.projects.get(stale.input.projectId); expect(staleProject).toBeDefined(); stale.db.projects.set(stale.input.projectId, { ...staleProject!, current_version: 2 }); await expect(stale.service.executeImplementationTask(stale.input)).rejects.toMatchObject({ code: "IMPLEMENTATION_WORKFLOW_STATE_INVALID" }); const unsupported = await fixture({ taskType: "implement-form" }); await expect(unsupported.service.executeImplementationTask(unsupported.input)).rejects.toMatchObject({ code: "IMPLEMENTATION_TASK_TYPE_UNSUPPORTED" }); const wrong = await fixture({ role: "qa-release" }); await expect(wrong.service.executeImplementationTask(wrong.input)).rejects.toMatchObject({ code: "IMPLEMENTATION_ROLE_INVALID" }); });
  it("is idempotent and does not apply the same proposal twice", async () => { const f = await fixture(); const first = await f.service.executeImplementationTask(f.input); const second = await f.service.executeImplementationTask(f.input); expect(second.executionId).toBe(first.executionId); });
  it("accepts a canonical V3 Brief checksum bound through the implementation graph", async () => { const f = await fixture(); const canonicalBrief = cleanBriefV3; const result = await f.service.executeImplementationTask({ ...f.input, approvedBriefChecksum: canonicalBriefChecksum(canonicalBrief), canonicalBrief }); expect(result.status).toBe("passed"); });
  it("rejects AST patching when the task capability binding is invalid", async () => { const f = await fixture(); const operation = { type: "ast-patch" as const, operationId: id(), operationVersion: "1.0.0" as const, relativePath: "src/app/layout.tsx", expectedFileChecksum: sha("source"), expectedResultChecksum: sha("result"), encoding: "utf-8" as const, taskId: f.task.id, projectId: f.task.projectId, projectVersion: 1, taskContractId: id(), taskContractChecksum: "a".repeat(64), taskGraphChecksum: f.input.taskGraphChecksum, reason: "narrow patch", requirementReferences: ["r"], planningReferences: ["p"], selectedDesignReferences: [], selector: { selectorKind: "function" as const, name: "Page", exported: true, defaultExport: false }, patchKind: "REPLACE_NODE_BODY" as const, payload: { body: "{ return null; }" }, resultValidation: { parseRequired: true as const, validationVersion: "1" as const } }; const proposal = ImplementationChangeProposalSchema.parse({ proposalId: id(), projectId: f.task.projectId, projectVersion: 1, taskId: f.task.id, taskAttempt: f.task.attempt, summary: "AST patch", operations: [operation], expectedChangedFiles: [operation.relativePath], expectedCreatedFiles: [], expectedDeletedFiles: [], validationPlan: ["parse"], requirementReferences: ["r"], planningReferences: ["p"], selectedDesignReferences: [], providerMetadata: { provider: "test" }, generatedAt: new Date().toISOString() }); expect(() => validateProposal(f.task, proposal, f.root, DEFAULT_EXECUTION_POLICY, {}, undefined, { taskGraphChecksum: f.input.taskGraphChecksum })).toThrowError(expect.objectContaining({ code: "AST_PATCH_UNAUTHORIZED_CAPABILITY" })); });
  it("rejects unsafe proposal paths and rolls back partial application", async () => { const f = await fixture(); const provider: ImplementationProvider = { proposeTaskChanges: async (context) => ImplementationChangeProposalSchema.parse({ proposalId: id(), projectId: context.task.projectId, projectVersion: 1, taskId: context.task.id, taskAttempt: 1, summary: "unsafe", operations: [{ type: "create-file", relativePath: "../outside.ts", expectedResultChecksum: sha("x"), encoding: "utf-8", reason: "unsafe", requirementReferences: ["r"], planningReferences: ["p"], selectedDesignReferences: [], content: "x" }], expectedChangedFiles: ["../outside.ts"], expectedCreatedFiles: ["../outside.ts"], expectedDeletedFiles: [], validationPlan: ["test"], requirementReferences: ["r"], planningReferences: ["p"], selectedDesignReferences: [], providerMetadata: { provider: "test" }, generatedAt: new Date().toISOString() }) }; const unsafe = new ImplementationAgentService(f.db, { workspace: { verifyStaging: async () => true }, provider }); await expect(unsafe.executeImplementationTask(f.input)).rejects.toMatchObject({ code: "IMPLEMENTATION_PATH_INVALID" }); const applier = new AtomicChangeApplier(); const valid = { ...f.task, attempt: 1, status: "running" as const, startedAt: new Date().toISOString() }; const proposal = await new (await import("./provider")).DeterministicImplementationProvider().proposeTaskChanges({ task: valid, acceptanceCriteria: [], requirementReferences: ["r"], planningReferences: ["p"], selectedDesignReferences: [], architectureExcerpt: {}, contentExcerpt: {}, assetExcerpt: {}, files: [], skills: [], allowedTools: ["filesystem-write"], conventions: [], contextChecksum: "a".repeat(64) }); await expect(applier.apply(valid, { ...proposal, operations: [{ ...proposal.operations[0]!, expectedResultChecksum: "f".repeat(64) }] }, f.root, { version: "implementation-v1", maxContextBytes: 100, maxContextFiles: 2, maxSourceFileBytes: 1000, maxProposalOperations: 2, maxChangedFiles: 2, maxOperationContentBytes: 1000, supportedEncodings: ["utf-8"], transactionDirectoryName: ".factory-transaction", lockExpiryMs: 1000, providerTimeoutMs: 1000, maxEventBytes: 1000, defaultTaskAttempts: 3 })).rejects.toMatchObject({ code: "IMPLEMENTATION_RESULT_CHECKSUM_MISMATCH" }); });
  it("rejects an invalid real-provider workspace marker before applying it", async () => { const f = await fixture({ taskType: "prepare-workspace", title: "Prepare workspace", fileScopes: ["src/app/**"] }); const deterministic = new (await import("./provider")).DeterministicImplementationProvider(); const provider: ImplementationProvider = { proposeTaskChanges: async (context) => { const proposal = await deterministic.proposeTaskChanges(context); return ImplementationChangeProposalSchema.parse({ ...proposal, operations: proposal.operations.map((operation) => "content" in operation ? { ...operation, content: "hello\n", expectedResultChecksum: sha("hello\n") } : operation) }); } }; const invalid = new ImplementationAgentService(f.db, { workspace: { verifyStaging: async () => true }, provider }); await expect(invalid.executeImplementationTask(f.input)).rejects.toMatchObject({ code: "IMPLEMENTATION_EXPECTED_FILE_MISSING" }); });
  it("blocks secret-like context and cancellation before apply", async () => { const f = await fixture(); await writeFile(path.join(f.root, "src", "app", "secret.ts"), "const password = 'secret';\n"); await expect(f.service.executeImplementationTask(f.input)).rejects.toMatchObject({ code: "IMPLEMENTATION_SECRET_EXPOSURE_BLOCKED" }); const cancelled = await fixture(); await expect(cancelled.service.executeImplementationTask({ ...cancelled.input, cancellation: { requested: true, reason: "user" } })).rejects.toMatchObject({ code: "IMPLEMENTATION_CANCELLED" }); });
  it("blocks real form side effects before provider execution when explicit approval is absent", async () => { const f = await fixture({ taskType: "implement-server-action", title: "Real form processing" }); const canonicalBrief = CanonicalBriefV3Schema.parse({ ...cleanBriefV3, decisions: { ...cleanBriefV3.decisions, form: { ...cleanBriefV3.decisions.form, mode: "REAL", transmissionMode: "EMAIL" } } }); let providerCalls = 0; const service = new ImplementationAgentService(f.db, { workspace: { verifyStaging: async () => true }, provider: { proposeTaskChanges: async () => { providerCalls += 1; throw new Error("PROVIDER_MUST_NOT_RUN"); } } }); await expect(service.executeImplementationTask({ ...f.input, canonicalBrief })).rejects.toMatchObject({ code: "FORM_PLAN_VIOLATION" }); expect(providerCalls).toBe(0); });
  it("assembles specialist context by allowlisted category rather than passing Design, migration, or UI internals across domains", async () => {
    const database = await fixture({ taskType: "implement-database-schema", implementationDomain: "DATABASE", specialistProfileId: "database-implementation", fileScopes: ["supabase/migrations/**"] });
    const backend = await fixture({ taskType: "implement-server-action", implementationDomain: "BACKEND", specialistProfileId: "backend-implementation", fileScopes: ["src/actions/**"] });
    const frontend = await fixture({ taskType: "implement-page", implementationDomain: "FRONTEND", specialistProfileId: "frontend-implementation", fileScopes: ["src/app/**/page.*"] });
    for (const fixtureValue of [database, backend, frontend]) {
      fixtureValue.input.technicalArchitecture = TechnicalArchitectureSchema.parse({ ...fixtureValue.input.technicalArchitecture, componentBoundaries: ["PRIVATE_UI_LAYOUT"], serverActions: ["PRIVATE_SERVER_OPERATION"], schemaPlan: ["RAW_MIGRATION_HISTORY"] });
      fixtureValue.input.contentPlan = ContentPlanSchema.parse({ ...fixtureValue.input.contentPlan, userProvidedFacts: ["PRIVATE_MARKETING_COPY"] });
    }
    database.input.acceptedPlanningPackage = { dataModel: { entities: [{ name: "records" }] } };
    backend.input.acceptedPlanningPackage = { architecture: { serverActions: ["approved-action"] } };
    const databaseContext = await new TaskContextAssembler({ maxContextBytes: 120000, maxContextFiles: 40, maxSourceFileBytes: 200000 }, { workspace: { verifyStaging: async () => true } }).assemble(database.input);
    const backendContext = await new TaskContextAssembler({ maxContextBytes: 120000, maxContextFiles: 40, maxSourceFileBytes: 200000 }, { workspace: { verifyStaging: async () => true } }).assemble(backend.input);
    const frontendContext = await new TaskContextAssembler({ maxContextBytes: 120000, maxContextFiles: 40, maxSourceFileBytes: 200000 }, { workspace: { verifyStaging: async () => true } }).assemble(frontend.input);
    expect(JSON.stringify(databaseContext)).not.toContain("PRIVATE_UI_LAYOUT");
    expect(JSON.stringify(databaseContext)).not.toContain("PRIVATE_MARKETING_COPY");
    expect(JSON.stringify(backendContext)).not.toContain("PRIVATE_UI_LAYOUT");
    expect(JSON.stringify(backendContext)).not.toContain("PRIVATE_MARKETING_COPY");
    expect(JSON.stringify(frontendContext)).not.toContain("RAW_MIGRATION_HISTORY");
    expect(frontendContext.selectedDesignContract).toBeUndefined();
  });
  it("rejects caller-supplied task mutations against the persisted canonical task", async () => { const f = await fixture(); await new DocumentRepository(f.db).save(f.input.taskGraph); let providerCalls = 0; const service = new ImplementationAgentService(f.db, { workspace: { verifyStaging: async () => true }, provider: { proposeTaskChanges: async () => { providerCalls += 1; throw new Error("PROVIDER_MUST_NOT_RUN"); } } }); await expect(service.executeImplementationTask({ ...f.input, task: { ...f.input.task, fileScopes: ["src/**"], allowedTools: ["filesystem-read"] } })).rejects.toMatchObject({ code: "IMPLEMENTATION_GRAPH_STALE" }); expect(providerCalls).toBe(0); });
  it("fails closed before provider or graph writes when the persisted TaskGraph is missing", async () => { const f = await fixture(); await new DocumentRepository(f.db).delete(f.input.projectId, 1, "task-graph"); let providerCalls = 0; const service = new ImplementationAgentService(f.db, { workspace: { verifyStaging: async () => true }, provider: { proposeTaskChanges: async () => { providerCalls += 1; throw new Error("PROVIDER_MUST_NOT_RUN"); } } }); await expect(service.executeImplementationTask(f.input)).rejects.toMatchObject({ code: "IMPLEMENTATION_GRAPH_STALE" }); expect(providerCalls).toBe(0); expect(await new DocumentRepository(f.db).get(f.input.projectId, 1, "task-graph")).toBeNull(); });
  it("rejects a stale capability binding before the provider runs", async () => { const f = await fixture({ requiredCapabilities: ["edit.ast-patch"] }); let providerCalls = 0; const service = new ImplementationAgentService(f.db, { workspace: { verifyStaging: async () => true }, provider: { proposeTaskChanges: async () => { providerCalls += 1; throw new Error("PROVIDER_MUST_NOT_RUN"); } } }); await expect(service.executeImplementationTask(f.input)).rejects.toMatchObject({ code: "IMPLEMENTATION_CAPABILITY_BINDING_INVALID" }); expect(providerCalls).toBe(0); const persisted = await new DocumentRepository(f.db).get(f.input.projectId, 1, "task-graph"); expect(persisted?.documentType).toBe("task-graph"); if (persisted?.documentType === "task-graph") expect(persisted.tasks[0]?.status).toBe("ready"); });
  it("rejects an active exclusive shared-file claim before provider or workspace-worker execution", async () => { const f = await fixture(); const competing = AgentTaskSchema.parse({ ...f.task, id: id(), status: "running", startedAt: "2026-01-01T00:01:00.000Z", attempt: 1, fileScopes: ["eslint.config.mjs"] }); const base = { ...f.input.taskGraph, tasks: [...f.input.taskGraph.tasks, competing], updatedAt: "2026-01-01T00:01:00.000Z" }; delete (base as { graphChecksum?: string }).graphChecksum; const graph = TaskGraphSchema.parse({ ...base, graphChecksum: checksumPersistedDocument(base) }); await new DocumentRepository(f.db).save(graph); f.input = { ...f.input, taskGraph: graph, taskGraphChecksum: graph.graphChecksum!, expectedTaskRowVersion: 2 }; let providerCalls = 0; let workspaceCalls = 0; const service = new ImplementationAgentService(f.db, { workspace: { verifyStaging: async () => { workspaceCalls += 1; return true; } }, provider: { proposeTaskChanges: async () => { providerCalls += 1; throw new Error("PROVIDER_MUST_NOT_RUN"); } } }); await expect(service.executeImplementationTask(f.input)).rejects.toMatchObject({ code: "IMPLEMENTATION_SCOPE_VIOLATION" }); expect(providerCalls).toBe(0); expect(workspaceCalls).toBe(0); });
  it("rejects a specialist ownership violation before provider or workspace-worker execution", async () => { const f = await fixture({ taskType: "implement-page", implementationDomain: "FRONTEND", specialistProfileId: "frontend-implementation", fileScopes: ["package.json"] }); let providerCalls = 0; let workspaceCalls = 0; const service = new ImplementationAgentService(f.db, { workspace: { verifyStaging: async () => { workspaceCalls += 1; return true; } }, provider: { proposeTaskChanges: async () => { providerCalls += 1; throw new Error("PROVIDER_MUST_NOT_RUN"); } } }); await expect(service.executeImplementationTask(f.input)).rejects.toMatchObject({ code: "IMPLEMENTATION_SCOPE_VIOLATION" }); expect(providerCalls).toBe(0); expect(workspaceCalls).toBe(0); });
  it("rolls back applied workspace changes when final graph persistence loses its CAS race", async () => { const f = await fixture(); const deterministic = new (await import("./provider")).DeterministicImplementationProvider(); let graphMutated = false; const service = new ImplementationAgentService(f.db, { workspace: { verifyStaging: async () => true }, provider: { proposeTaskChanges: async (context) => { const current = await new DocumentRepository(f.db).get(f.input.projectId, 1, "task-graph"); if (!current || current.documentType !== "task-graph") throw new Error("TASK_GRAPH_MISSING"); const nextBase = { ...current, updatedAt: "2026-01-01T00:05:00.000Z" }; delete (nextBase as { graphChecksum?: string }).graphChecksum; await new DocumentRepository(f.db).save(TaskGraphSchema.parse({ ...nextBase, graphChecksum: checksumPersistedDocument(nextBase) })); graphMutated = true; return deterministic.proposeTaskChanges(context); } } }); await expect(service.executeImplementationTask(f.input)).rejects.toMatchObject({ code: "PERSISTENCE_CONFLICT" }); expect(graphMutated).toBe(true); await expect(readFile(path.join(f.root, "src/app/layout.tsx"))).rejects.toMatchObject({ code: "ENOENT" }); });
  it("bounds Codebase Memory traceability references without changing the canonical task", async () => {
    const f = await fixture({
      allowedTools: ["filesystem-read", "filesystem-write", "codebase-memory-read"],
      requirementReferences: Array.from({ length: 25 }, (_, index) => `requirement:${index}`),
    });
    const workspacePath = path.join(f.root, "v1");
    await mkdir(workspacePath, { recursive: true });
    const scope = { projectId: f.input.projectId, projectVersion: 1, workspacePath, generatedProjectsRoot: f.root, workspaceManagerReference: `${path.basename(f.root)}:v1` };
    const manifest = await computeSourceManifest(scope);
    let captured: string[] = [];
    const assembler = new TaskContextAssembler(
      { maxContextBytes: 120000, maxContextFiles: 40, maxSourceFileBytes: 200000 },
      {
        workspace: { verifyStaging: async () => true },
        codebaseMemory: {
          scope: () => scope,
          port: {
            ensureIndex: async () => ({ indexId: "index", scope, workspaceIdentity: "fixture", manifestChecksum: manifest.checksum, policyVersion: "test", adapterVersion: "test", status: "READY", updatedAt: new Date().toISOString() }),
            findSymbol: async (plan: { queryId: string; requirementReferences: string[] }) => {
              captured = plan.requirementReferences;
              return { queryId: plan.queryId, operation: "findSymbol", index: { indexId: "index", scope, workspaceIdentity: "fixture", manifestChecksum: manifest.checksum, policyVersion: "test", adapterVersion: "test", status: "READY", updatedAt: new Date().toISOString() }, symbols: [], relationships: [], excerpts: [], cache: "miss", totalBytes: 0 };
            },
          } as never,
        },
      },
    );
    const context = await assembler.assemble(f.input);
    expect(captured).toEqual(f.input.task.requirementReferences?.slice(0, 20));
    expect(context.requirementReferences).toHaveLength(25);
  });
});
