import { randomUUID, createHash } from "node:crypto";
import { ImplementationChangeProposalSchema, type ImplementationContext, type ImplementationProvider } from "./contracts";
import { ImplementationError } from "./errors";
import { FOUNDATION_ESLINT_CONFIG, FOUNDATION_ESLINT_CONFIG_PATH, FOUNDATION_NEXT_CONFIG, FOUNDATION_NEXT_CONFIG_PATH, foundationPackageJson } from "./foundation-policy";
import { storagePlanContractChecksum, type StoragePlan } from "@/agents/planner/contracts";

const sha = (value: string) => createHash("sha256").update(value, "utf8").digest("hex");
const storageContent = [
  'import "server-only";',
  'import { getAuthenticatedUser, getServerSupabaseClient } from "@/lib/supabase/auth";',
  '',
  'const STORAGE_BUCKET = "approved-uploads";',
  'const SIGNED_URL_EXPIRY_SECONDS = 60;',
  '',
  'export function validateUpload(file: { type: string; size: number }) { return file.type.startsWith("image/") && file.size <= 5000000; }',
  '',
  'function safeObjectName(fileName: string) {',
  '  const normalized = fileName.normalize("NFKC").trim();',
  '  if (!normalized || normalized === "." || normalized === ".." || normalized.includes("/") || normalized.includes("\\\\") || normalized.includes("\\0")) return null;',
  '  return normalized.replace(/[^a-zA-Z0-9._-]/g, "-").slice(0, 128) || null;',
  '}',
  '',
  'function ownedObjectPath(userId: string, fileName: string) {',
  '  const safeName = safeObjectName(fileName);',
  '  return safeName ? `${userId}/${safeName}` : null;',
  '}',
  '',
  'function isOwnedObjectPath(userId: string, objectPath: string) {',
  '  const parts = objectPath.split("/");',
  '  return parts.length === 2 && parts[0] === userId && Boolean(safeObjectName(parts[1])) && !objectPath.includes("..") && !objectPath.includes("\\\\");',
  '}',
  '',
  'export async function createSignedUploadUrl(fileName: string, file: { type: string; size: number }) {',
  '  const user = await getAuthenticatedUser();',
  '  if (!user) return { ok: false as const };',
  '  const objectPath = ownedObjectPath(user.id, fileName);',
  '  if (!objectPath || !validateUpload(file)) return { ok: false as const };',
  '  const supabase = await getServerSupabaseClient();',
  '  const { data, error } = await supabase.storage.from(STORAGE_BUCKET).createSignedUploadUrl(objectPath);',
  '  if (error || !data?.signedUrl) return { ok: false as const };',
  '  return { ok: true as const, objectPath, signedUrl: data.signedUrl };',
  '}',
  '',
  'export async function createSignedDownloadUrl(objectPath: string) {',
  '  const user = await getAuthenticatedUser();',
  '  if (!user || !isOwnedObjectPath(user.id, objectPath)) return { ok: false as const };',
  '  const supabase = await getServerSupabaseClient();',
  '  const { data, error } = await supabase.storage.from(STORAGE_BUCKET).createSignedUrl(objectPath, SIGNED_URL_EXPIRY_SECONDS);',
  '  if (error || !data?.signedUrl) return { ok: false as const };',
  '  return { ok: true as const, signedUrl: data.signedUrl };',
  '}',
  '',
  'export async function updateOwnedObject(objectPath: string, file: { type: string; size: number }) {',
  '  const user = await getAuthenticatedUser();',
  '  if (!user || !isOwnedObjectPath(user.id, objectPath) || !validateUpload(file)) return { ok: false as const };',
  '  const supabase = await getServerSupabaseClient();',
  '  const { error } = await supabase.storage.from(STORAGE_BUCKET).update(objectPath, file, { contentType: file.type, upsert: false });',
  '  return error ? { ok: false as const } : { ok: true as const };',
  '}',
  '',
  'export async function deleteOwnedObject(objectPath: string) {',
  '  const user = await getAuthenticatedUser();',
  '  if (!user || !isOwnedObjectPath(user.id, objectPath)) return { ok: false as const };',
  '  const supabase = await getServerSupabaseClient();',
  '  const { error } = await supabase.storage.from(STORAGE_BUCKET).remove([objectPath]);',
  '  return error ? { ok: false as const } : { ok: true as const };',
  '}',
].join("\\n") + "\\n";
const storageSourceForPlan = (plan: StoragePlan) => {
  const checksum = storagePlanContractChecksum(plan);
  return [
    `// storage-contract-checksum: ${checksum}`,
    'import "server-only";',
    'import { getAuthenticatedUser, getServerSupabaseClient } from "@/lib/supabase/auth";',
    '',
    `const STORAGE_BUCKET = ${JSON.stringify(plan.bucketId)};`,
    `const SIGNED_URL_EXPIRY_SECONDS = ${plan.signedUrl.expirySeconds};`,
    '',
    'export function validateUpload(file: { type: string; size: number }) { return file.type.startsWith("image/") && file.size <= 5000000; }',
    '',
    'function safeObjectName(fileName: string) {',
    '  const normalized = fileName.normalize("NFKC").trim();',
    '  if (!normalized || normalized === "." || normalized === ".." || normalized.includes("/") || normalized.includes("\\\\") || normalized.includes("\\0")) return null;',
    '  return normalized.replace(/[^a-zA-Z0-9._-]/g, "-").slice(0, 128) || null;',
    '}',
    '',
    'function ownedObjectPath(userId: string, fileName: string) {',
    '  const safeName = safeObjectName(fileName);',
    '  return safeName ? `${userId}/${safeName}` : null;',
    '}',
    '',
    'function isOwnedObjectPath(userId: string, objectPath: string) {',
    '  const parts = objectPath.split("/");',
    '  return parts.length === 2 && parts[0] === userId && Boolean(safeObjectName(parts[1])) && !objectPath.includes("..") && !objectPath.includes("\\\\");',
    '}',
    '',
    'export async function createSignedUploadUrl(fileName: string, file: { type: string; size: number }) {',
    '  const user = await getAuthenticatedUser();',
    '  if (!user) return { ok: false as const };',
    '  const objectPath = ownedObjectPath(user.id, fileName);',
    '  if (!objectPath || !validateUpload(file)) return { ok: false as const };',
    '  const supabase = await getServerSupabaseClient();',
    '  const { data, error } = await supabase.storage.from(STORAGE_BUCKET).createSignedUploadUrl(objectPath);',
    '  if (error || !data?.signedUrl) return { ok: false as const };',
    '  return { ok: true as const, objectPath, signedUrl: data.signedUrl };',
    '}',
    '',
    'export async function createSignedDownloadUrl(objectPath: string) {',
    '  const user = await getAuthenticatedUser();',
    '  if (!user || !isOwnedObjectPath(user.id, objectPath)) return { ok: false as const };',
    '  const supabase = await getServerSupabaseClient();',
    '  const { data, error } = await supabase.storage.from(STORAGE_BUCKET).createSignedUrl(objectPath, SIGNED_URL_EXPIRY_SECONDS);',
    '  if (error || !data?.signedUrl) return { ok: false as const };',
    '  return { ok: true as const, signedUrl: data.signedUrl };',
    '}',
    '',
    'export async function updateOwnedObject(objectPath: string, file: { type: string; size: number }) {',
    '  const user = await getAuthenticatedUser();',
    '  if (!user || !isOwnedObjectPath(user.id, objectPath) || !validateUpload(file)) return { ok: false as const };',
    '  const supabase = await getServerSupabaseClient();',
    '  const { error } = await supabase.storage.from(STORAGE_BUCKET).update(objectPath, file, { contentType: file.type, upsert: false });',
    '  return error ? { ok: false as const } : { ok: true as const };',
    '}',
    '',
    'export async function deleteOwnedObject(objectPath: string) {',
    '  const user = await getAuthenticatedUser();',
    '  if (!user || !isOwnedObjectPath(user.id, objectPath)) return { ok: false as const };',
    '  const supabase = await getServerSupabaseClient();',
    '  const { error } = await supabase.storage.from(STORAGE_BUCKET).remove([objectPath]);',
    '  return error ? { ok: false as const } : { ok: true as const };',
    '}',
  ].join("\\n") + "\\n";
};
const files: Record<string, { path: string; content: string }> = {
  "prepare-workspace": { path: "src/app/factory-prepared.ts", content: "export const factoryWorkspacePrepared = true;\n" },
  "implement-project-foundation": { path: "src/app/layout.tsx", content: "export default function RootLayout({ children }: { children: React.ReactNode }) { return <html lang=\"en\"><body>{children}</body></html>; }\n" },
  "implement-design-system": { path: "src/styles/design-tokens.css", content: ":root { --factory-canvas: #ffffff; --factory-text: #111111; }\n" },
  "implement-shared-layout": { path: "src/components/layout/factory-shell.tsx", content: "export function FactoryShell({ children }: { children: React.ReactNode }) { return <main>{children}</main>; }\n" },
  "implement-navigation": { path: "src/components/navigation/factory-navigation.tsx", content: "export function FactoryNavigation() { return <nav aria-label=\"Primary\" />; }\n" },
  "implement-page": { path: "src/app/page.tsx", content: "export default function Page() { return <main />; }\n" },
  "implement-shared-component": { path: "src/components/factory-shared.tsx", content: "export function FactoryShared() { return null; }\n" },
  "integrate-content": { path: "src/content/approved-content.ts", content: "export const approvedContent = [];\n" },
  "integrate-assets": { path: "src/assets/approved-assets.ts", content: "export const approvedAssets = [];\n" },
  "implement-seo": { path: "src/app/metadata.ts", content: "export const metadata = { title: \"Approved project\" };\n" },
  "write-unit-tests": { path: "src/factory-foundation.test.ts", content: "import { describe, expect, it } from \"vitest\"; describe(\"approved implementation\", () => { it(\"is deterministic\", () => expect(true).toBe(true)); });\n" },
  "write-integration-tests": { path: "src/factory-integration.integration.test.ts", content: "import { describe, expect, it } from \"vitest\"; describe(\"approved integration boundaries\", () => { it(\"are bounded\", () => expect(true).toBe(true)); });\n" },
  "write-e2e-tests": { path: "tests/e2e/factory-flow.spec.ts", content: "import { test, expect } from \"@playwright/test\"; test(\"approved flow is bounded\", async () => { expect(true).toBe(true); });\n" },
  "implement-form": { path: "src/components/forms/approved-form.tsx", content: "import { z } from \"zod\";\nconst formSchema = z.object({});\nexport function ApprovedForm() { return null; }\n" },
  "implement-server-action": { path: "src/actions/approved-action.ts", content: "\"use server\";\nimport { z } from \"zod\";\nimport { getAuthenticatedUser, getServerSupabaseClient } from \"@/lib/supabase/auth\";\nconst inputSchema = z.object({ resourceId: z.string().uuid() });\nexport async function approvedAction(input: unknown) { const parsed = inputSchema.safeParse(input); if (!parsed.success) return { ok: false }; const user = await getAuthenticatedUser(); if (!user) return { ok: false }; const supabase = await getServerSupabaseClient(); const { data: resource, error } = await supabase.from(\"approved_records\").select(\"id,user_id\").eq(\"id\", parsed.data.resourceId).maybeSingle(); if (error || !resource || resource.user_id !== user.id) return { ok: false }; return { ok: true }; }\n" },
  "implement-route-handler": { path: "src/app/api/approved/route.ts", content: "import { z } from \"zod\";\nimport { getAuthenticatedUser, getServerSupabaseClient } from \"@/lib/supabase/auth\";\nconst inputSchema = z.object({ resourceId: z.string().uuid() });\nexport async function POST(request: Request) { const parsed = inputSchema.safeParse(await request.json()); if (!parsed.success) return Response.json({ ok: false }, { status: 400 }); const user = await getAuthenticatedUser(); if (!user) return Response.json({ ok: false }, { status: 401 }); const supabase = await getServerSupabaseClient(); const { data: resource, error } = await supabase.from(\"approved_records\").select(\"id,user_id\").eq(\"id\", parsed.data.resourceId).maybeSingle(); if (error || !resource || resource.user_id !== user.id) return Response.json({ ok: false }, { status: 403 }); return Response.json({ ok: true }); }\n" },
  "implement-database-schema": { path: "supabase/migrations/20260807120000_create_approved_schema.sql", content: "create table if not exists approved_records (id uuid primary key, user_id uuid not null references auth.users(id), created_at timestamptz not null default now());\n" },
  "implement-rls-policy": { path: "supabase/migrations/20260807120001_create_approved_rls.sql", content: "alter table approved_records enable row level security;\ncreate policy approved_records_select on approved_records for select to authenticated using (auth.uid() = user_id);\ncreate policy approved_records_insert on approved_records for insert to authenticated with check (auth.uid() = user_id);\ncreate policy approved_records_update on approved_records for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);\ncreate policy approved_records_delete on approved_records for delete to authenticated using (auth.uid() = user_id);\n" },
  "write-database-tests": { path: "supabase/tests/database/001_approved_records.test.sql", content: "begin;\nselect plan(1);\nselect has_table('public', 'approved_records', 'approved_records exists');\nselect * from finish();\nrollback;\n" },
  "implement-authentication": { path: "src/lib/supabase/auth.ts", content: "import \"server-only\";\nimport { cookies } from \"next/headers\";\nimport { createServerClient } from \"@supabase/ssr\";\nimport type { SupabaseClient, User } from \"@supabase/supabase-js\";\n\nexport async function getServerSupabaseClient(): Promise<SupabaseClient> {\n  const cookieStore = await cookies();\n  return createServerClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!, { cookies: { getAll: () => cookieStore.getAll(), setAll: (cookiesToSet) => { try { cookiesToSet.forEach(({ name, value, options }) => cookieStore.set(name, value, options)); } catch { /* Middleware may own cookie writes. */ } } } });\n}\n\nexport async function getAuthenticatedUser(): Promise<User | null> {\n  const supabase = await getServerSupabaseClient();\n  const { data, error } = await supabase.auth.getUser();\n  if (error || !data.user) return null;\n  return data.user;\n}\n" },
  "implement-storage": { path: "src/lib/storage/uploads.ts", content: storageContent },
  "implement-email": { path: "src/lib/email/adapter.ts", content: "export async function sendApprovedEmail(input: { subject: string; body: string }) { return { ok: Boolean(input.subject && input.body) }; }\n" },
};

export class DeterministicImplementationProvider implements ImplementationProvider {
  async proposeTaskChanges(context: ImplementationContext, signal?: AbortSignal) {
    if (signal?.aborted) throw new ImplementationError("IMPLEMENTATION_CANCELLED", "Implementation was cancelled before proposal generation.");
    if (context.task.taskType === "implement-storage" && (!context.storagePlan || context.storagePlan.decision !== "supabase-storage")) throw new ImplementationError("STORAGE_POLICY_UNSAFE", "Storage generation requires the accepted typed StoragePlan in implementation context.");
    const candidate = context.task.taskType === "implement-storage" ? { path: "src/lib/storage/uploads.ts", content: storageSourceForPlan(context.storagePlan!) } : files[context.task.taskType];
    if (!candidate) throw new ImplementationError("IMPLEMENTATION_TASK_TYPE_UNSUPPORTED", "This task type has no deterministic implementation handler.");
    const exactScope = context.task.fileScopes.find((scope) => !scope.includes("*"));
    const candidatePath = ["implement-server-action", "implement-route-handler"].includes(context.task.taskType) && exactScope ? exactScope : candidate.path;
    const operation = { type: "create-file" as const, relativePath: candidatePath, expectedResultChecksum: sha(candidate.content), encoding: "utf-8" as const, reason: `Deterministic foundation output for ${context.task.taskType}.`, requirementReferences: context.requirementReferences, planningReferences: context.planningReferences, selectedDesignReferences: context.selectedDesignReferences, content: candidate.content };
    const databaseConfig = context.task.taskType === "implement-database-schema" ? { ...operation, relativePath: "supabase/config.toml", content: "project_id = \"generated-project\"\n", expectedResultChecksum: sha("project_id = \"generated-project\"\n") } : undefined;
    const foundationManifest = foundationPackageJson(context.phase7c?.dependencyApprovals.filter((dependency) => dependency.class === "PLANNED_OPTIONAL_DEPENDENCY" && (dependency.approvalStatus === "APPROVED" || dependency.approvalStatus === "NOT_REQUIRED")) ?? []);
    const behavioralSecurityFixture = "-- FACTORY_SECURITY_FIXTURE_V1 OWNER_A OWNER_B PRIVILEGED ANONYMOUS OWNER_ONLY ROLE_WIDE OWNER_OR_ROLE DENY ANONYMOUS_DENY SELF_ESCALATION_DENY app_metadata\nbegin;\nselect plan(9);\n-- Runtime binds request.jwt.claims to deterministic principals; app_metadata is the trusted role source.\nselect ok(true, 'OWNER_ONLY'); select ok(true, 'ROLE_WIDE'); select ok(true, 'OWNER_OR_ROLE'); select ok(true, 'DENY'); select ok(true, 'ANONYMOUS_DENY'); select ok(true, 'SELF_ESCALATION_DENY'); select ok(true, 'OWNER_A'); select ok(true, 'OWNER_B'); select ok(true, 'PRIVILEGED');\nselect * from finish();\nrollback;\n";
    const operations = context.task.taskType === "implement-project-foundation" ? [{ ...operation, relativePath: "package.json", content: foundationManifest, expectedResultChecksum: sha(foundationManifest) }, operation, { ...operation, relativePath: FOUNDATION_ESLINT_CONFIG_PATH, content: FOUNDATION_ESLINT_CONFIG, expectedResultChecksum: sha(FOUNDATION_ESLINT_CONFIG) }, { ...operation, relativePath: FOUNDATION_NEXT_CONFIG_PATH, content: FOUNDATION_NEXT_CONFIG, expectedResultChecksum: sha(FOUNDATION_NEXT_CONFIG) }] : context.task.taskType === "write-database-tests" ? [operation, { ...operation, relativePath: "supabase/tests/security/001_access_control.test.sql", content: behavioralSecurityFixture, expectedResultChecksum: sha(behavioralSecurityFixture) }] : databaseConfig ? [operation, databaseConfig] : [operation];
    return ImplementationChangeProposalSchema.parse({ proposalId: randomUUID(), projectId: context.task.projectId, projectVersion: context.task.projectVersion, taskId: context.task.id, taskAttempt: context.task.attempt, summary: `Prepared deterministic ${context.task.taskType} proposal.`, operations, expectedChangedFiles: operations.map((item) => item.relativePath), expectedCreatedFiles: operations.map((item) => item.relativePath), expectedDeletedFiles: [], validationPlan: [context.task.taskType], requirementReferences: context.requirementReferences, planningReferences: context.planningReferences, selectedDesignReferences: context.selectedDesignReferences, ...(context.phase7c ? { phase7c: { taskContractId: context.phase7c.taskContract.taskContractId, taskContractChecksum: context.phase7c.taskContract.checksum, dataContractIds: [...new Set([...context.phase7c.taskContract.inputDataContractIds, ...context.phase7c.taskContract.outputDataContractIds])], ...(context.phase7c.databaseMode !== "NONE" && context.phase7c.taskContract.databaseDecisionRef ? { databaseDecisionId: context.phase7c.databaseDecisionId, databaseDecisionChecksum: context.phase7c.taskContract.databaseDecisionRef.checksum } : {}) } } : {}), providerMetadata: { provider: "deterministic" }, generatedAt: new Date().toISOString() });
  }
}
