import { createHash, randomUUID } from "node:crypto";
import { mkdir, mkdtemp, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { describe, expect, it } from "vitest";
import { AgentTaskSchema } from "@/domain/tasks/schema";
import { ownershipForTask, UNIT_TEST_ARTIFACT_POLICY_VERSION } from "@/domain/tasks/ownership";
import { ImplementationChangeProposalSchema } from "./contracts";
import { validateTaskResult } from "./validators";

const task = (scopes = ownershipForTask("write-unit-tests")!.scopes) => AgentTaskSchema.parse({ id: randomUUID(), projectId: randomUUID(), projectVersion: 1, role: "implementation", taskType: "write-unit-tests", title: "Write unit tests", objective: "Cover approved behavior", requirementReferences: ["requirement:approved"], planningReferences: ["planning:approved"], selectedDesignReferences: [], inputs: ["approved behavior"], expectedOutputs: ["unit tests"], acceptanceCriteria: ["A real test exists"], allowedSkills: [], allowedTools: ["filesystem-read", "filesystem-write"], deniedTools: [], fileScopes: [...scopes], requiredArtifactCount: 1, taskAcceptancePolicyVersion: UNIT_TEST_ARTIFACT_POLICY_VERSION, dependencies: [], status: "ready", executionMode: "parallel-safe", attempt: 0, maxAttempts: 2, createdAt: "2026-01-01T00:00:00.000Z", blockingFailure: true, expectedArtifactTypes: ["unit-tests"] });
const proposal = (taskValue: ReturnType<typeof task>, relativePath: string, content: string) => ImplementationChangeProposalSchema.parse({ proposalId: randomUUID(), projectId: taskValue.projectId, projectVersion: 1, taskId: taskValue.id, taskAttempt: 0, summary: "test", operations: content ? [{ type: "create-file", relativePath, expectedResultChecksum: createHash("sha256").update(content).digest("hex"), encoding: "utf-8", reason: "approved unit behavior", requirementReferences: ["requirement:approved"], planningReferences: ["planning:approved"], selectedDesignReferences: [], content }] : [], expectedChangedFiles: content ? [relativePath] : [], expectedCreatedFiles: content ? [relativePath] : [], expectedDeletedFiles: [], validationPlan: ["write-unit-tests"], requirementReferences: ["requirement:approved"], planningReferences: ["planning:approved"], selectedDesignReferences: [], providerMetadata: { provider: "test" }, generatedAt: "2026-01-01T00:00:00.000Z" });

describe("canonical generated unit-test artifacts", () => {
  it("owns one canonical Vitest source layout", () => expect(ownershipForTask("write-unit-tests")?.scopes).toEqual(["src/*.test.ts", "src/*.test.tsx"]));
  it("rejects an empty proposal", () => { const t = task(); expect(() => validateTaskResult(t, proposal(t, "", ""))).toThrow(); });
  it("rejects a test outside the canonical layout", () => { const t = task(); expect(() => validateTaskResult(t, proposal(t, "tests/appointment.test.ts", "import { describe, it } from 'vitest'; describe('approved', () => it('works', () => expect(1).toBe(1)));"))).toThrow(); });
  it("accepts a real canonical test artifact after atomic application", async () => { const root = await mkdtemp(path.join(process.env.TEMP ?? process.cwd(), "factory-test-artifact-")); try { const t = task(); const content = "import { describe, expect, it } from 'vitest'; describe('approved', () => it('works', () => expect(1).toBe(1)));"; await mkdir(path.join(root, "src"), { recursive: true }); await writeFile(path.join(root, "src", "appointment.test.ts"), content); expect(validateTaskResult(t, proposal(t, "src/appointment.test.ts", content), {}, root)[0]?.status).toBe("passed"); } finally { await rm(root, { recursive: true, force: true }); } });
  it("rejects trivial placeholder tests", async () => { const root = await mkdtemp(path.join(process.env.TEMP ?? process.cwd(), "factory-test-placeholder-")); try { const t = task(); const content = "import { describe, expect, it } from 'vitest'; describe('approved', () => it('works', () => expect(true).toBe(true)));"; await mkdir(path.join(root, "src"), { recursive: true }); await writeFile(path.join(root, "src", "placeholder.test.ts"), content); expect(() => validateTaskResult(t, proposal(t, "src/placeholder.test.ts", content), {}, root)).toThrow(); } finally { await rm(root, { recursive: true, force: true }); } });
});
