import { z } from "zod";

const SafeDiagnosticTokenSchema = z.string().min(1).max(160).regex(/^[A-Za-z0-9][A-Za-z0-9._:/-]*$/);
const SafeDiagnosticPathSchema = z.string().min(1).max(240).regex(/^[A-Za-z0-9_$.[\]/:-]+$/);
const SafeDiagnosticChecksumSchema = z.string().regex(/^[a-f0-9]{64}$/);
const SafeDiagnosticMessageSchema = z.string().min(1).max(500);
export const ProviderTransportPhaseSchema = z.enum([
  "CLIENT_INITIALIZATION",
  "DNS",
  "CONNECT",
  "TLS",
  "REQUEST_SEND",
  "WAITING_FOR_RESPONSE",
  "RESPONSE_HEADERS",
  "RESPONSE_BODY",
  "UNKNOWN",
]);
export type ProviderTransportPhase = z.infer<typeof ProviderTransportPhaseSchema>;
export const ProviderTransportFailureClassSchema = z.enum([
  "DNS_RESOLUTION_FAILED",
  "CONNECT_FAILED",
  "TLS_HANDSHAKE_FAILED",
  "CONNECT_TIMEOUT",
  "RESPONSE_TIMEOUT",
  "CONNECTION_RESET",
  "REQUEST_ABORTED",
  "HTTP_ERROR_RESPONSE",
  "RESPONSE_STREAM_FAILED",
  "PROVIDER_CLIENT_INITIALIZATION_FAILED",
  "UNKNOWN_TRANSPORT_FAILURE",
]);
export type ProviderTransportFailureClass = z.infer<typeof ProviderTransportFailureClassSchema>;
export const KnownTransportCauseCodeSchema = z.enum([
  "ENOTFOUND",
  "EAI_AGAIN",
  "ECONNREFUSED",
  "ECONNRESET",
  "ETIMEDOUT",
  "EHOSTUNREACH",
  "ENETUNREACH",
  "UND_ERR_CONNECT_TIMEOUT",
  "UND_ERR_HEADERS_TIMEOUT",
  "UND_ERR_BODY_TIMEOUT",
  "UND_ERR_SOCKET",
  "ABORT_ERR",
  "ERR_STREAM_PREMATURE_CLOSE",
  "ERR_TLS_HANDSHAKE_TIMEOUT",
  "ERR_TLS_CERT_ALTNAME_INVALID",
  "DEPTH_ZERO_SELF_SIGNED_CERT",
  "UNABLE_TO_VERIFY_LEAF_SIGNATURE",
  "CERT_HAS_EXPIRED",
]);
export type KnownTransportCauseCode = z.infer<typeof KnownTransportCauseCodeSchema>;
export const ProviderTransportElapsedBucketSchema = z.enum(["LT_10_MS", "LT_100_MS", "LT_1_S", "LT_10_S", "LT_60_S", "GTE_60_S"]);
export type ProviderTransportElapsedBucket = z.infer<typeof ProviderTransportElapsedBucketSchema>;
const SafeZodIssueSchema = z.object({
  path: SafeDiagnosticPathSchema,
  code: SafeDiagnosticTokenSchema,
  expected: SafeDiagnosticTokenSchema.optional(),
  received: SafeDiagnosticTokenSchema.optional(),
  message: z.string().min(1).max(240),
}).strict();

export const ProviderFailureDiagnosticSchema = z.object({
  version: z.literal(1),
  category: z.enum([
    "AUTHENTICATION",
    "MODEL_ACCESS",
    "RATE_LIMIT",
    "PROVIDER_UNAVAILABLE",
    "NETWORK",
    "TIMEOUT",
    "CANCELLED",
    "REQUEST_REJECTED",
    "REQUEST_CONSTRUCTION",
    "STRUCTURED_OUTPUT",
    "UNKNOWN",
  ]),
  stage: z.enum(["REQUEST_CONSTRUCTION", "REQUEST_TRANSPORT", "PROVIDER_RESPONSE", "STRUCTURED_OUTPUT", "PROVIDER_MAPPING", "UNKNOWN"]),
  requestAttempted: z.boolean(),
  responseReceived: z.boolean().optional(),
  structuredParsingReached: z.boolean().optional(),
  retryabilityHint: z.boolean().optional(),
  provider: SafeDiagnosticTokenSchema,
  model: SafeDiagnosticTokenSchema.optional(),
  httpStatus: z.number().int().min(100).max(599).optional(),
  requestId: SafeDiagnosticTokenSchema.optional(),
  sdkErrorClass: SafeDiagnosticTokenSchema.optional(),
  providerErrorCode: SafeDiagnosticTokenSchema.optional(),
  providerErrorType: SafeDiagnosticTokenSchema.optional(),
  providerErrorParam: SafeDiagnosticTokenSchema.optional(),
  safeProviderMessage: SafeDiagnosticMessageSchema.optional(),
  transportPhase: ProviderTransportPhaseSchema.optional(),
  transportFailureClass: ProviderTransportFailureClassSchema.optional(),
  transportCauseCode: KnownTransportCauseCodeSchema.optional(),
  endpointClass: SafeDiagnosticTokenSchema.optional(),
  timeoutConfiguredMs: z.number().int().positive().max(86_400_000).optional(),
  configuredMaxRetries: z.number().int().nonnegative().max(8).optional(),
  elapsedBucket: ProviderTransportElapsedBucketSchema.optional(),
  requestSizeBytes: z.number().int().nonnegative().max(20_000_000).optional(),
  inputBytes: z.number().int().nonnegative().max(20_000_000).optional(),
  schemaSizeBytes: z.number().int().nonnegative().max(20_000_000).optional(),
  errorCode: SafeDiagnosticTokenSchema.optional(),
  schemaName: SafeDiagnosticTokenSchema.optional(),
  choicesCount: z.number().int().nonnegative().optional(),
  finishReason: SafeDiagnosticTokenSchema.nullable().optional(),
  refusalPresent: z.boolean().optional(),
  contentPresent: z.boolean().optional(),
  outputComplete: z.boolean().optional(),
  inputTokens: z.number().int().nonnegative().optional(),
  outputTokens: z.number().int().nonnegative().optional(),
  totalTokens: z.number().int().nonnegative().optional(),
  maxCompletionTokens: z.number().int().positive().optional(),
  reasoningEffort: z.literal("xhigh").optional(),
  rawContentBytes: z.number().int().nonnegative().optional(),
  rawContentChecksum: SafeDiagnosticChecksumSchema.optional(),
  jsonParseSucceeded: z.boolean().optional(),
  zodIssueCount: z.number().int().nonnegative().optional(),
  zodIssuesTruncated: z.boolean().optional(),
  completeZodIssuesChecksum: SafeDiagnosticChecksumSchema.optional(),
  zodIssuesBounded: z.array(SafeZodIssueSchema).max(20).optional(),
  contextCapacity: z.object({
    budgetProfile: SafeDiagnosticTokenSchema,
    requestBytes: z.number().int().nonnegative().max(20_000_000),
    requestTokens: z.number().int().nonnegative().max(5_000_000),
    schemaBytes: z.number().int().nonnegative().max(20_000_000),
    schemaTokens: z.number().int().nonnegative().max(5_000_000),
    totalBytesWithReserve: z.number().int().nonnegative().max(20_000_000),
    totalTokensWithReserve: z.number().int().nonnegative().max(5_000_000),
    maxBytes: z.number().int().positive().max(20_000_000),
    maxTokens: z.number().int().positive().max(5_000_000),
    canonicalRequirementBytes: z.number().int().nonnegative().max(20_000_000),
    supportingContextBytes: z.number().int().nonnegative().max(20_000_000),
  }).strict().optional(),
}).strict();

export type ProviderFailureDiagnostic = z.infer<typeof ProviderFailureDiagnosticSchema>;
