import { randomUUID } from "node:crypto";
import { describe, expect, it } from "vitest";
import { RequirementSpecificationSchema, type RequirementSpecification } from "@/domain/requirements/schema";
import { FactoryProjectSchema } from "@/domain/project/schema";
import { ProjectRepository, ProjectVersionRepository, DocumentRepository } from "@/persistence/database/repositories";
import { InMemoryPersistenceDatabase } from "@/persistence/database/fake";
import { checksumPersistedDocument } from "@/persistence/database/serialization";
import { buildPlanningPackage } from "@/agents/planner/deterministic";
import type { PlannerAgentInput, PlanningPackage } from "@/agents/planner/contracts";
import { PlannerArchitectService } from "@/agents/planner/service";
import { FakePlannerMemoryPort } from "@/agents/planner/memory";
import { architectureReviewerAgentDefinition } from "@/agents/catalog";
import { rolePrompt } from "@/integrations/openai/prompts";
import { ArchitectureReviewOrchestrationService } from "@/orchestration/architecture-review/service";
import { ARCHITECTURE_REVIEW_POLICY_VERSION, FACTORY_ARCHITECTURE_STACK, type ArchitectureReviewInput } from "./contracts";
import { ArchitectureReviewError } from "./errors";
import { deterministicArchitectureReview } from "./deterministic";
import { ArchitectureReviewService } from "./service";

const id = () => randomUUID();
const baseBrief = (overrides: Partial<RequirementSpecification> = {}): RequirementSpecification => RequirementSpecificationSchema.parse({ schemaVersion: 1, documentType: "requirements", projectId: id(), projectVersion: 1, createdAt: "2026-01-01T00:00:00.000Z", updatedAt: "2026-01-01T00:00:00.000Z", projectSummary: "A public information site", protectedFunctionalityRequired: false, imagesRequired: false, businessGoals: ["Explain the service"], targetAudiences: ["Visitors"], pages: [{ slug: "home", purpose: "Explain the service" }], userRoles: [], features: [], forms: [], contentRequirements: [], backendRequirements: [], supabaseRequirements: [], authenticationDecision: "no-authentication-guest-first", storageDecision: "not-needed", emailDecision: "not-needed", administrationDecision: "not-needed", seoRequirements: [], localization: { locales: ["en"], defaultLocale: "en" }, imageSourceDecision: "placeholders", suppliedBrandInformation: { status: "missing" }, suppliedLogoLocation: { status: "missing" }, technicalConstraints: [], explicitExclusions: [], userAcceptanceCriteria: ["Home loads"], unresolvedItems: [], approval: { approved: true, approvedAt: "2026-01-01T00:00:00.000Z", approvedBy: "user" }, briefStatus: "approved", briefVersion: 1, ...overrides });
const plannerInput = (brief: RequirementSpecification): PlannerAgentInput => ({ projectId: brief.projectId, projectVersion: 1, approvedBrief: brief, approvedBriefChecksum: checksumPersistedDocument(brief), originalPromptReference: "original-prompt.md", clarificationEvidenceReferences: [], currentWorkflowState: "AWAITING_DESIGN_SELECTION", existingDecisions: [], suppliedFiles: [], allowedSkills: [], idempotencyKey: id(), expectedRowVersion: 1 });
const acceptedPlanning = (brief: RequirementSpecification, changes: Partial<PlanningPackage> = {}) => { const planning = buildPlanningPackage(plannerInput(brief)); return { ...planning, ...changes, accepted: true, acceptance: { acceptedAt: "2026-01-01T00:00:00.000Z", acceptedBy: "user", checksum: checksumPersistedDocument(planning) }, architecture: { ...planning.architecture, acceptance: { accepted: true, acceptedAt: "2026-01-01T00:00:00.000Z", acceptedBy: "user" } } } as PlanningPackage; };
const reviewInput = (brief: RequirementSpecification, planning: PlanningPackage, overrides: Partial<ArchitectureReviewInput> = {}): ArchitectureReviewInput => ({ projectId: brief.projectId, projectVersion: 1, approvedBrief: brief, approvedBriefChecksum: checksumPersistedDocument(brief), acceptedPlanningPackage: planning, acceptedPlanningChecksum: checksumPersistedDocument(planning), factoryArchitecturePolicy: { policyVersion: "factory-architecture-v1", stack: [...FACTORY_ARCHITECTURE_STACK], prohibitedTechnologies: ["redis", "nestjs"], serverActionPreference: "preferred", routeHandlerPreference: "second", packageManager: "npm" }, relevantProjectConstraints: [], idempotencyKey: id(), expectedRowVersion: 1, ...overrides });
async function projectInReview(database: InMemoryPersistenceDatabase, projectId: string) { const project = FactoryProjectSchema.parse({ schemaVersion: 1, documentType: "factory-project", projectId, projectVersion: 1, createdAt: "2026-01-01T00:00:00.000Z", updatedAt: "2026-01-01T00:00:00.000Z", id: projectId, slug: "review-fixture", originalPrompt: "review fixture", currentVersion: 1, workflowState: "ARCHITECTURE_REVIEW" }); await new ProjectRepository(database).create(project); await new ProjectVersionRepository(database).create({ id: id(), projectId, versionNumber: 1, state: "ARCHITECTURE_REVIEW", memoryRootPath: null, requirementsChecksum: null, selectedDesignChecksum: null, architectureChecksum: null, releasedAt: null, immutable: false, createdAt: project.createdAt, updatedAt: project.updatedAt, rowVersion: 1 }); }

describe("Architecture Reviewer", () => {
  it("has a valid read-only catalog definition with its approved procedure", () => { expect(architectureReviewerAgentDefinition.role).toBe("review"); expect(architectureReviewerAgentDefinition.capabilities).toEqual(["review.architecture"]); expect(architectureReviewerAgentDefinition.allowedTools).toEqual(["openai-generation"]); expect(architectureReviewerAgentDefinition.allowedSkillIds).toEqual(["module-boundaries-fb20497b5c35"]); expect(architectureReviewerAgentDefinition.readOnly).toBe(true); expect(architectureReviewerAgentDefinition.executionPolicy.concurrencyClass).not.toBe("exclusive-write"); });
  it("prompt reviews rather than redesigning", () => { const prompt = rolePrompt("architecture-reviewer", {}); expect(prompt.promptVersion).toBe("architecture-reviewer.v1"); expect(prompt.system).toMatch(/review architecture/i); expect(prompt.system).toMatch(/do not invent requirements/i); expect(prompt.system).toMatch(/fixed Factory stack/i); expect(prompt.system).toMatch(/stable English internal identifiers/i); expect(prompt.system).toMatch(/evidence-backed findings/i); expect(prompt.system).toMatch(/do not.*write project state/i); });
  it("approves a minimal valid architecture", () => { const brief = baseBrief(); const result = deterministicArchitectureReview(reviewInput(brief, acceptedPlanning(brief))); expect(result.verdict).toBe("APPROVED"); });
  it("requires persistence architecture for persistent requirements", () => { const brief = baseBrief({ backendRequirements: ["Persist submitted requests"] }); const planning = acceptedPlanning(brief, { dataModel: { ...acceptedPlanning(brief).dataModel, entities: [] }, supabase: { ...acceptedPlanning(brief).supabase, postgres: false } }); expect(deterministicArchitectureReview(reviewInput(brief, planning)).findings.some((item) => item.category === "DATA_ARCHITECTURE")).toBe(true); });
  it("rejects unnecessary auth and infrastructure for a static site", () => { const brief = baseBrief(); const original = acceptedPlanning(brief); const planning = { ...original, authentication: { ...original.authentication, decision: "supabase-auth", required: true }, supabase: { ...original.supabase, auth: true } } as PlanningPackage; const result = deterministicArchitectureReview(reviewInput(brief, planning)); expect(result.verdict).toBe("CHANGES_REQUIRED"); expect(result.findings.some((item) => item.category === "UNNECESSARY_COMPLEXITY")).toBe(true); });
  it("detects localized content reused as an internal identity", () => { const brief = baseBrief({ forms: ["Contact form"], pages: [{ slug: "contact", purpose: "Contact" }] }); const original = acceptedPlanning(brief); const form = original.forms.forms[0]; const planning = { ...original, forms: { ...original.forms, forms: form ? [{ ...form, fields: form.fields.map((field) => "fieldId" in field ? { ...field, fieldId: field.label } : field) }] : [] } } as PlanningPackage; expect(deterministicArchitectureReview(reviewInput(brief, planning)).findings.some((item) => item.category === "IDENTITY_MODEL")).toBe(true); });
  it("blocks stale or structurally invalid canonical input before provider work", async () => { const brief = baseBrief(); const planning = acceptedPlanning(brief); const database = new InMemoryPersistenceDatabase(); await projectInReview(database, brief.projectId); const service = new ArchitectureReviewService(database, { provider: { promptVersion: "architecture-reviewer.v1", review: async () => { throw new Error("provider must not run"); } } }); await expect(service.review(reviewInput(brief, planning, { approvedBriefChecksum: "a".repeat(64) }))).rejects.toMatchObject({ code: "ARCHITECTURE_REVIEW_BLOCKED" }); });
  it("persists and reuses an idempotent review result", async () => { const brief = baseBrief(); const planning = acceptedPlanning(brief); const database = new InMemoryPersistenceDatabase(); await projectInReview(database, brief.projectId); const service = new ArchitectureReviewService(database); const input = reviewInput(brief, planning, { idempotencyKey: "same-review" }); const first = await service.review(input); const second = await service.review(input); expect(second).toEqual(first); expect(await new DocumentRepository(database).get(brief.projectId, 1, "architecture-review")).toBeTruthy(); expect((await service.getCurrentReview(brief.projectId, 1, input.approvedBriefChecksum, input.acceptedPlanningChecksum))?.result.verdict).toBe("APPROVED"); });
  it("normalizes exact duplicate findings and prevents invented evidence", async () => { const brief = baseBrief(); const planning = acceptedPlanning(brief); const database = new InMemoryPersistenceDatabase(); await projectInReview(database, brief.projectId); const item = { findingId: "minimality-warning", category: "UNNECESSARY_COMPLEXITY" as const, severity: "WARNING" as const, summary: "The architecture could be simpler.", evidenceRefs: ["planning:architecture"], affectedArtifacts: ["planning:architecture"], recommendedAction: "Keep only justified boundaries." }; const service = new ArchitectureReviewService(database, { provider: { promptVersion: "architecture-reviewer.v1", review: async () => ({ verdict: "APPROVED" as const, findings: [item, item], reviewedArtifactRefs: ["planning:architecture"], policyVersion: ARCHITECTURE_REVIEW_POLICY_VERSION }) } }); const result = await service.review(reviewInput(brief, planning)); expect(result.findings).toHaveLength(1); const blockedDatabase = new InMemoryPersistenceDatabase(); const blockedBrief = baseBrief(); const blockedPlanning = acceptedPlanning(blockedBrief); await projectInReview(blockedDatabase, blockedBrief.projectId); const blocked = new ArchitectureReviewService(blockedDatabase, { provider: { promptVersion: "architecture-reviewer.v1", review: async () => ({ verdict: "APPROVED" as const, findings: [{ ...item, evidenceRefs: ["planning:invented"], affectedArtifacts: ["planning:invented"] }], reviewedArtifactRefs: ["planning:architecture"], policyVersion: ARCHITECTURE_REVIEW_POLICY_VERSION }) } }); await expect(blocked.review(reviewInput(blockedBrief, blockedPlanning))).rejects.toMatchObject({ code: "ARCHITECTURE_REVIEW_OUTPUT_INVALID" }); });
  it("lets the orchestration boundary, not the reviewer, unlock Design", async () => { const brief = baseBrief(); const planning = acceptedPlanning(brief); const database = new InMemoryPersistenceDatabase(); await projectInReview(database, brief.projectId); const coordinator = new ArchitectureReviewOrchestrationService(database); const result = await coordinator.reviewAndRoute(reviewInput(brief, planning)); expect(result.projectState).toBe("AWAITING_DESIGN_SELECTION"); expect((await new ProjectRepository(database).getWithVersion(brief.projectId))?.project.workflowState).toBe("AWAITING_DESIGN_SELECTION"); });
  it("enforces bounded correction cycles", async () => { const service = new ArchitectureReviewService(new InMemoryPersistenceDatabase()); const projectId = id(); service.recordCorrectionCycle(projectId, 1); service.recordCorrectionCycle(projectId, 1); expect(() => service.recordCorrectionCycle(projectId, 1)).toThrowError(ArchitectureReviewError); });
  it("routes structured changes back to Planner without changing the Brief", async () => { const brief = baseBrief(); const planning = acceptedPlanning(brief); const database = new InMemoryPersistenceDatabase(); await projectInReview(database, brief.projectId); const planner = new PlannerArchitectService({ database, memory: new FakePlannerMemoryPort(), provider: { plan: async () => planning } }); const review = { verdict: "CHANGES_REQUIRED" as const, findings: [{ findingId: "missing-decision", category: "MISSING_DECISION" as const, severity: "ERROR" as const, summary: "A decision is missing.", evidenceRefs: ["planning:architecture"], affectedArtifacts: ["planning:architecture"], recommendedAction: "Add the minimal decision." }], reviewedArtifactRefs: ["planning:architecture"], policyVersion: ARCHITECTURE_REVIEW_POLICY_VERSION }; const result = await planner.correctAfterArchitectureReview({ ...plannerInput(brief), currentPlanningPackage: planning, currentPlanningChecksum: checksumPersistedDocument(planning), architectureReview: review }); expect(result.projectState).toBe("AWAITING_DESIGN_SELECTION"); expect(result.approvedBrief).toEqual(brief); expect((await new ProjectRepository(database).getWithVersion(brief.projectId))?.project.workflowState).toBe("AWAITING_DESIGN_SELECTION"); });
});
