import { z } from "zod";
import { ShadcnRegistryError } from "./errors";
export const RegistryIdSchema = z.literal("official-shadcn");
export const RegistryFileSchema = z.object({ suggestedPath: z.string().min(1).max(300), type: z.enum(["component", "style", "config", "other"]), content: z.string().min(1).max(50_000), checksum: z.string().regex(/^[a-f0-9]{64}$/), byteSize: z.number().int().positive().max(50_000), frameworkRelevance: z.string().min(1).max(300) }).strict();
export type RegistryFile = z.infer<typeof RegistryFileSchema>;
export const ShadcnComponentReferenceSchema = z.object({ registryId: RegistryIdSchema, componentName: z.string().min(1).max(160), registryReference: z.string().min(1).max(500), title: z.string().min(1).max(300), description: z.string().min(1).max(2_000), files: z.array(RegistryFileSchema).max(20), dependencies: z.array(z.string().max(160)).max(50), devDependencies: z.array(z.string().max(160)).max(50), cssVariables: z.array(z.string().max(160)).max(100), registryDependencies: z.array(z.string().max(160)).max(50), sourceMetadata: z.object({ source: z.literal("official-shadcn"), trustStatus: z.literal("trusted"), reviewStatus: z.literal("approved") }).strict(), retrievedAt: z.string().datetime(), checksum: z.string().regex(/^[a-f0-9]{64}$/), compatibility: z.enum(["compatible", "adaptation-required", "incompatible"]), compatibilityNotes: z.array(z.string().max(500)).max(20), adaptationNotes: z.array(z.string().max(500)).max(20), truncationState: z.enum(["complete", "files-truncated", "bytes-truncated"]) }).strict();
export type ShadcnComponentReference = z.infer<typeof ShadcnComponentReferenceSchema>;
export const ShadcnRegistryDefinitionSchema = z.object({ id: RegistryIdSchema, type: z.literal("official"), baseIdentity: z.literal("https://ui.shadcn.com"), trustStatus: z.literal("trusted"), reviewStatus: z.literal("approved"), allowlistVersion: z.literal(1), permittedNamespaces: z.array(z.string()), maxFiles: z.number().int().positive(), maxBytes: z.number().int().positive(), dependencyPolicy: z.literal("approved-or-fixed-stack"), scriptPolicy: z.literal("reject") }).strict();
export type ShadcnRegistryDefinition = z.infer<typeof ShadcnRegistryDefinitionSchema>;
export const ShadcnComponentQueryPlanSchema = z.object({ queryId: z.string().uuid(), registryId: RegistryIdSchema, componentName: z.string().regex(/^[a-z0-9-]+$/), taskId: z.string().uuid(), taskType: z.string().min(1), reason: z.string().min(8).max(500), requirementReferences: z.array(z.string()), planningReferences: z.array(z.string()), selectedDesignReferences: z.array(z.string()), expectedComponentRole: z.string().min(3).max(160), maxFiles: z.number().int().positive().max(20), maxBytes: z.number().int().positive().max(50000), allowedDependencyNames: z.array(z.string()), targetAdaptationNotes: z.array(z.string()), dependencyPlanNames: z.array(z.string()), selectedDesignChecksum: z.string().regex(/^[a-f0-9]{64}$/), dependencyPlanChecksum: z.string().regex(/^[a-f0-9]{64}$/), createdAt: z.string().datetime() }).strict();
export type ShadcnComponentQueryPlan = z.infer<typeof ShadcnComponentQueryPlanSchema>;
export type ShadcnRegistryTransport = (request: { registryId: "official-shadcn"; componentName: string; signal: AbortSignal }) => Promise<string>;
export type ShadcnRegistryInput = { registryId: string; componentName: string; requesterRole: "implementation"; taskType: string; projectId: string; projectVersion: number; taskId: string; selectedDesignChecksum: string; dependencyPlanChecksum: string; maxFiles: number; maxBytes: number; cancellation?: AbortSignal; reason: string; requirementReferences: string[]; planningReferences: string[]; selectedDesignReferences: string[]; expectedComponentRole: string; targetAdaptationNotes: string[]; allowedDependencyNames: string[]; dependencyPlanNames: string[]; designMetadata?: { colorStrategy?: string; typographyStrategy?: string; radiusPolicy?: string; spacingCharacter?: string; density?: string; motionPolicy?: string } };
export type ShadcnReferenceResult = { reference: ShadcnComponentReference; cache: "hit" | "miss" };
export const ShadcnReferenceResultSchema = z.object({ reference: ShadcnComponentReferenceSchema, cache: z.enum(["hit", "miss"]) }).strict();
export interface ShadcnRegistryPort { resolveRegistry(registryId: string): Promise<ShadcnRegistryDefinition>; resolveComponent(input: ShadcnRegistryInput): Promise<ShadcnComponentQueryPlan>; fetchComponentReference(input: { plan: ShadcnComponentQueryPlan; cancellation?: AbortSignal; idempotencyKey: string; designMetadata?: ShadcnRegistryInput["designMetadata"] }): Promise<ShadcnReferenceResult>; }
export function assertShadcnPermission(allowedTools: string[]) { if (!allowedTools.includes("shadcn-registry-read")) throw new ShadcnRegistryError("SHADCN_TOOL_NOT_ALLOWED", "The task does not allow shadcn-registry-read."); }
