import { describe, expect, it } from "vitest";
import { mkdtemp, mkdir, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { randomUUID } from "node:crypto";
import { readCodebaseMemoryConfig } from "./config";
import { CodebaseMemoryError } from "./errors";
import { CodebaseMemoryService } from "./service";
import { computeSourceManifest, validateWorkspaceScope } from "./policy";
import { UPSTREAM_READ_ONLY_ALLOWLIST } from "./transport";
const config=readCodebaseMemoryConfig({ CODEBASE_MEMORY_ENABLED:"true" });
async function fixture(){const root=await mkdtemp(path.join(os.tmpdir(),"cbm-test-"));const workspace=path.join(root,"project","v1");await mkdir(path.join(workspace,"src"),{recursive:true});await writeFile(path.join(workspace,"src","index.ts"),"export function ContactForm() { return true; }\n");await writeFile(path.join(workspace,".env"),"SECRET=x");await mkdir(path.join(workspace,"node_modules"));return {root,workspace,scope:{projectId:randomUUID(),projectVersion:1,workspacePath:workspace,generatedProjectsRoot:root,workspaceManagerReference:"project:v1"}};}
describe("Codebase Memory controlled port",()=>{
 it("is disabled by default and server-only",()=>{expect(readCodebaseMemoryConfig().enabled).toBe(false);try { readCodebaseMemoryConfig({NEXT_PUBLIC_CODEBASE_MEMORY_ENABLED:"true"}); throw new Error("expected"); } catch (error) { expect(error).toMatchObject({code:"CODEBASE_MEMORY_CONFIGURATION_INVALID"}); }});
 it("rejects broad roots",async()=>{const f=await fixture();expect(()=>validateWorkspaceScope({...f.scope,workspacePath:f.root})).toThrow(/exact generated project version/);});
 it("creates deterministic manifest with exclusions",async()=>{const f=await fixture();const a=await computeSourceManifest(f.scope);const b=await computeSourceManifest(f.scope);expect(a.checksum).toBe(b.checksum);expect(a.files.map(x=>x.relativePath)).toEqual(["src/index.ts"]);});
 it("indexes, normalizes symbol results and detects source staleness",async()=>{const f=await fixture();const transport=async(tool:string)=>tool==="index_repository"?{status:"indexed"}:{results:[{name:"ContactForm",label:"Function",file:"src/index.ts",signature:"function ContactForm"}]};const service=new CodebaseMemoryService(transport,config);const index=await service.ensureIndex(f.scope);const plan={queryId:randomUUID(),projectId:f.scope.projectId,projectVersion:1,taskId:randomUUID(),requesterRole:"implementation" as const,operation:"findSymbol" as const,symbol:"ContactForm",reason:"Find the current component definition.",requirementReferences:["r"],taskReferences:["t"],maxResults:5,maxBytes:1000,sourceManifestChecksum:index.manifestChecksum,workspaceScope:f.scope};const result=await service.findSymbol(plan);expect(result.symbols[0]).toMatchObject({symbol:"ContactForm",file:"src/index.ts"});await writeFile(path.join(f.workspace,"src","new.ts"),"export const x=1;");expect((await service.getIndexStatus(f.scope)).status).toBe("STALE");});
 it("rejects unsafe and unknown operations",()=>{expect(UPSTREAM_READ_ONLY_ALLOWLIST.has("manage_adr" as never)).toBe(false);expect(()=>new CodebaseMemoryError("CODEBASE_MEMORY_OPERATION_NOT_ALLOWED","x")).not.toThrow();});
 it("enforces query idempotency and current index",async()=>{const f=await fixture();const transport=async(tool:string)=>tool==="index_repository"?{}:{results:[]};const service=new CodebaseMemoryService(transport,config);const index=await service.ensureIndex(f.scope);const base={queryId:randomUUID(),projectId:f.scope.projectId,projectVersion:1,taskId:"t",requesterRole:"implementation" as const,operation:"findSymbol" as const,symbol:"x",reason:"Find a narrow symbol reference.",requirementReferences:[],taskReferences:[],maxResults:2,maxBytes:1000,sourceManifestChecksum:index.manifestChecksum,workspaceScope:f.scope};await service.findSymbol(base);await expect(service.findSymbol({...base,symbol:"different"})).rejects.toMatchObject({code:"IDEMPOTENCY_CONFLICT"});});
});
