import { mkdtemp, rm } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { loadFactoryCliEnv } from "./cli-env";
import { ShadcnRegistryCache } from "../src/integrations/shadcn/cache";
import { readShadcnRegistryConfig } from "../src/integrations/shadcn/config";
import { ShadcnRegistryService, syntheticShadcnTransport } from "../src/integrations/shadcn/service";
loadFactoryCliEnv();
async function main() { if (process.env.ALLOW_REAL_SHADCN_SMOKE !== "true") { console.error("REAL_SHADCN_SMOKE_PENDING: explicit opt-in is required."); process.exitCode = 1; return; } const root = await mkdtemp(path.join(os.tmpdir(), "shadcn-smoke-")); try { const config = { ...readShadcnRegistryConfig({ SHADCN_REGISTRY_ENABLED: "true" }), enabled: true }; const service = new ShadcnRegistryService(syntheticShadcnTransport(), config, new ShadcnRegistryCache(root, 60, 2)); const plan = await service.resolveComponent({ registryId: "official-shadcn", componentName: "button", requesterRole: "implementation", taskType: "implement-page", projectId: "00000000-0000-0000-0000-000000000001", projectVersion: 1, taskId: "00000000-0000-0000-0000-000000000002", selectedDesignChecksum: "a".repeat(64), dependencyPlanChecksum: "b".repeat(64), maxFiles: 4, maxBytes: 4000, reason: "Synthetic button smoke query", requirementReferences: [], planningReferences: [], selectedDesignReferences: [], expectedComponentRole: "page", targetAdaptationNotes: ["Adapt selected design"], allowedDependencyNames: ["react"], dependencyPlanNames: [] }); const result = await service.fetchComponentReference({ plan, idempotencyKey: "shadcn-smoke" }); console.log(JSON.stringify({ registry: result.reference.registryId, component: result.reference.componentName, files: result.reference.files.length, bytes: result.reference.files.reduce((sum, file) => sum + file.byteSize, 0), compatibility: result.reference.compatibility })); } finally { await rm(root, { recursive: true, force: true }); } }
void main();
