import { mkdtemp, rm } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { AgentTaskSchema, TaskGraphSchema, type AgentTask, type TaskGraph } from "../src/domain/tasks/schema";
import { QualityCheckSchema } from "../src/domain/quality/schema";
import { checksumPersistedDocument } from "../src/persistence/database/serialization";
import { FullTaskGraphExecutor, graphChecksum, type ExecutionStatePort, type ExecutionSummary, type FullExecutionSnapshot, type TaskExecutorPort } from "../src/orchestration/execution";

const projectId = "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa"; const ids = ["aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa1", "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa2", "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa3", "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa4", "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa5", "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa6", "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa7"]; const checksum = "a".repeat(64); const createdAt = "2026-01-01T00:00:00.000Z";
const task = (id: string, type: string, dependencies: string[], status: AgentTask["status"], role: AgentTask["role"] = type.startsWith("validate") ? "qa-release" : "implementation") => AgentTaskSchema.parse({ id, projectId, projectVersion: 1, role, taskType: type, title: type, objective: `Fake ${type}`, requirementReferences: ["requirement:smoke"], planningReferences: ["planning:smoke"], selectedDesignReferences: [], inputs: ["fake input"], expectedOutputs: ["fake output"], acceptanceCriteria: ["fake acceptance"], allowedSkills: [], allowedTools: type === "validate-functional-flow" ? ["filesystem-read", "Playwright-functional"] : ["filesystem-read", ...(role === "implementation" ? ["filesystem-write"] : [])], deniedTools: ["git-write", "shell-restricted"], fileScopes: role === "implementation" ? [`src/${type}/**`] : [], dependencies, status, executionMode: role === "implementation" ? "exclusive-write" : "validation-only", attempt: 0, maxAttempts: 1, createdAt, blockingFailure: true, estimatedContextBytes: 1000, expectedArtifactTypes: ["smoke"] });
const makeGraph = (): TaskGraph => { const tasks = [task(ids[0]!, "implement-project-foundation", [], "ready"), task(ids[1]!, "validate-lint", [ids[0]!], "pending"), task(ids[2]!, "validate-typecheck", [ids[1]!], "pending"), task(ids[3]!, "validate-unit-tests", [ids[2]!], "pending"), task(ids[4]!, "validate-build", [ids[3]!], "pending"), task(ids[5]!, "validate-functional-flow", [ids[4]!], "pending"), task(ids[6]!, "prepare-release", [ids[5]!], "pending", "qa-release")]; const raw = { schemaVersion: 1, documentType: "task-graph" as const, projectId, projectVersion: 1, createdAt, updatedAt: createdAt, tasks, checkpoint: "execution-ready" as const, readyForExecution: true, blockingReasons: [], warnings: [] }; return TaskGraphSchema.parse({ ...raw, graphChecksum: checksumPersistedDocument(raw) }); };
class FakeState implements ExecutionStatePort { snapshot: FullExecutionSnapshot; summary?: ExecutionSummary; constructor(graph: TaskGraph) { this.snapshot = { graph, graphRowVersion: 1, graphDocumentChecksum: checksumPersistedDocument(graph), workflowState: "IMPLEMENTING", projectImmutable: false, workspaceValid: true, sourceDocumentChecksums: { brief: checksum }, currentDocumentChecksums: { brief: checksum }, toolPolicyVersion: "tools-v1", activeRunIds: [], qualityChecks: [], runDocumentRowVersion: null, runDocumentChecksum: null }; } async load() { return this.snapshot; } async save(input: Parameters<ExecutionStatePort["save"]>[0]) { if (this.snapshot.graphRowVersion !== input.expectedGraphRowVersion || this.snapshot.graphDocumentChecksum !== input.expectedGraphDocumentChecksum || this.snapshot.runDocumentRowVersion !== input.expectedRunDocumentRowVersion || this.snapshot.runDocumentChecksum !== input.expectedRunDocumentChecksum) throw new Error("PERSISTENCE_CONFLICT"); this.snapshot.graph = input.graph; this.snapshot.graphRowVersion++; this.snapshot.graphDocumentChecksum = checksumPersistedDocument(input.graph); this.snapshot.workflowState = input.workflowState; this.snapshot.activeRunIds = input.run.status === "completed" ? [] : [input.run.runId]; this.snapshot.qualityChecks = input.run.qualityGateSummary; this.snapshot.executionRun = input.run; this.snapshot.executionRequestChecksum = input.requestChecksum; this.snapshot.runDocumentRowVersion = (this.snapshot.runDocumentRowVersion ?? 0) + 1; this.snapshot.runDocumentChecksum = checksumPersistedDocument({ requestChecksum: input.requestChecksum, run: input.run }); } async saveSummary(summary: ExecutionSummary) { this.summary = summary; } async appendEvent() {} }
const quality = (name: "lint" | "typecheck" | "unit-tests" | "build" | "e2e") => QualityCheckSchema.parse({ name, status: "passed", startedAt: createdAt, completedAt: createdAt, resultSummary: `${name} passed`, attempt: 0, required: true, command: `fake ${name}` });
async function main() { const root = await mkdtemp(path.join(os.tmpdir(), "taskgraph-smoke-")); try { const graph = makeGraph(); const state = new FakeState(graph); const executors: TaskExecutorPort = { implementation: async ({ task }) => ({ taskId: task.id, status: "passed", classification: "retryable-task", repairable: false }), runtimeValidation: async ({ task }, operation) => ({ taskId: task.id, status: "passed", classification: "retryable-task", repairable: false, runtimeValidationRunId: "bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb", qualityChecks: [quality(operation === "tests" ? "unit-tests" : operation)] }), functionalQa: async ({ task }) => ({ taskId: task.id, status: "passed", classification: "retryable-task", repairable: false, qaRunId: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa", qualityChecks: [quality("e2e")] }) }; const executor = new FullTaskGraphExecutor(state, executors); const run = await executor.execute({ projectId, projectVersion: 1, idempotencyKey: "taskgraph-smoke", graph, expectedGraphChecksum: graphChecksum(graph), workflowState: "IMPLEMENTING", projectImmutable: false, workspaceValid: true, sourceDocumentChecksums: { brief: checksum }, currentDocumentChecksums: { brief: checksum }, toolPolicyVersion: "tools-v1" }); if (run.status !== "completed" || !state.summary?.releaseEligible) throw new Error(JSON.stringify({ message: "Fake full execution did not become release eligible.", runStatus: run.status, blockers: state.summary?.blockers, qualityGates: state.summary?.qualityGates.map((check) => ({ name: check.name, status: check.status, evidence: check.evidence })) })); console.log(JSON.stringify({ status: run.status, releaseEligible: state.summary.releaseEligible, passedTasks: state.summary.passed, repairs: state.summary.repairsAttempted, network: false, npm: false, browser: false })); } finally { await rm(root, { recursive: true, force: true }); } }
void main().catch((error) => { console.error(`TASKGRAPH_SMOKE_FAILED: ${error instanceof Error ? error.message : "safe failure"}`); process.exitCode = 1; });
