import type { AgentTask } from "../domain/tasks/schema";
import type { ImplementationOperation, ImplementationChangeProposal } from "./contracts";
import { ImplementationError } from "./errors";

export const BACKEND_TASK_TYPES = new Set(["implement-form", "implement-server-action", "implement-route-handler", "implement-database-schema", "implement-rls-policy", "implement-authentication", "implement-storage", "implement-email"]);
export type BackendPlans = { brief?: { forms?: string[]; authenticationDecision?: string; storageDecision?: string; emailDecision?: string }; planning?: { forms?: { forms?: Array<{ id?: string; fields?: Array<{ name: string; required: boolean; validation?: string[] }> }> }; architecture?: { serverActions?: string[]; routeHandlers?: string[]; dependencies?: Array<{ name: string }>; environment?: { variables?: Array<{ name: string; serverOnly: boolean; secret: boolean }> } }; dataModel?: { entities?: Array<{ name: string; fields?: Array<{ name: string; required: boolean }> }> }; authentication?: { decision?: string; passwordReset?: string; signInMethods?: string[] }; supabase?: { policies?: string[]; clientBoundaries?: string[] }; storage?: { decision?: string; buckets?: Array<{ name?: string; access?: string; acceptedFormats?: string[]; sizeLimits?: string[] }> }; email?: { decision?: string; triggers?: string[]; environmentVariables?: string[] } } };
const text = (operation: ImplementationOperation) => operation.type === "delete-file" ? "" : operation.type === "patch-text" ? operation.newText : operation.content;
const allText = (proposal: ImplementationChangeProposal) => proposal.operations.map(text).join("\n");
const fieldNames = (plans: BackendPlans) => new Set((plans.planning?.forms?.forms ?? []).flatMap((form) => (form.fields ?? []).map((field) => field.name)));
export interface ImplementationTaskHandler { supports(taskType: string): boolean; deriveContextRequirements(task: AgentTask): string[]; deriveDocumentationNeeds(task: AgentTask): string[]; deriveRegistryNeeds(task: AgentTask): string[]; validateProposal(task: AgentTask, proposal: ImplementationChangeProposal, plans: BackendPlans): void; validateAppliedResult(task: AgentTask, changedFiles: string[], plans: BackendPlans): void; }
export function assertBackendTaskRequired(task: AgentTask, plans: BackendPlans) {
  const planning = plans.planning; const brief = plans.brief;
  if (!BACKEND_TASK_TYPES.has(task.taskType)) return;
  const required = task.taskType === "implement-form" ? Boolean(brief?.forms?.length || planning?.forms?.forms?.length) : task.taskType === "implement-server-action" ? Boolean(planning?.architecture?.serverActions?.length) : task.taskType === "implement-route-handler" ? Boolean(planning?.architecture?.routeHandlers?.length) : task.taskType === "implement-database-schema" ? Boolean(planning?.dataModel?.entities?.length) : task.taskType === "implement-rls-policy" ? Boolean(planning?.supabase?.policies?.length) : task.taskType === "implement-authentication" ? (brief?.authenticationDecision === "authentication-required" || planning?.authentication?.decision === "supabase-auth") : task.taskType === "implement-storage" ? (brief?.storageDecision === "needed" || planning?.storage?.decision === "supabase-storage") : (brief?.emailDecision === "needed" || planning?.email?.decision === "required-configured-provider");
  if (!required) throw new ImplementationError("IMPLEMENTATION_TASK_NOT_REQUIRED", `The approved plans do not require ${task.taskType}.`);
}
export function validateBackendProposal(task: AgentTask, proposal: ImplementationChangeProposal, plans: BackendPlans = {}) {
  if (Object.keys(plans).length > 0) assertBackendTaskRequired(task, plans); const content = allText(proposal); const paths = proposal.operations.map((operation) => operation.relativePath.replaceAll("\\", "/"));
  if (task.taskType === "implement-form") { const planned = fieldNames(plans); const mentioned = [...content.matchAll(/name=["']([A-Za-z0-9_-]+)["']/g)].map((match) => match[1]); if (mentioned.some((field) => !planned.has(field))) throw new ImplementationError("FORM_FIELD_UNAPPROVED", "The form contains an unplanned field."); if (planned.size && !/zod|safeParse|parse\(/i.test(content)) throw new ImplementationError("FORM_VALIDATION_INCOMPLETE", "The form lacks planned Zod validation."); if (/password/i.test(content) && plans.brief?.authenticationDecision !== "authentication-required") throw new ImplementationError("FORM_DATA_COLLECTION_EXCESSIVE", "Password collection is not approved."); }
  if (task.taskType === "implement-server-action") { if (!paths.some((path) => path.includes("actions/")) || !/use server/i.test(content)) throw new ImplementationError("SERVER_ACTION_PLAN_VIOLATION", "Server Action output is outside the planned action boundary."); if (!/zod|safeParse|parse\(/i.test(content)) throw new ImplementationError("SERVER_ACTION_INPUT_UNVALIDATED", "Server Action input validation is missing."); if (/user\.id|ownerId|authorization/i.test(content) && !/authorize|ownership|role|rls/i.test(content)) throw new ImplementationError("SERVER_ACTION_AUTHORIZATION_MISSING", "Protected Server Action authorization is incomplete."); if (/service_role|SUPABASE_SERVICE_ROLE_KEY|sk-[A-Za-z0-9]/i.test(content)) throw new ImplementationError("SERVER_ACTION_SECRET_EXPOSURE", "Server Action exposes a privileged secret."); }
  if (task.taskType === "implement-route-handler") { if (!paths.some((path) => /app\/api\/.*route\.(ts|tsx)$/.test(path))) throw new ImplementationError("ROUTE_HANDLER_NOT_PLANNED", "Route Handler output is outside the approved API boundary."); if (!/GET|POST|PUT|PATCH|DELETE|export\s+async/i.test(content)) throw new ImplementationError("ROUTE_HANDLER_METHOD_NOT_ALLOWED", "Route Handler has no supported HTTP method."); if (!/zod|safeParse|parse\(/i.test(content)) throw new ImplementationError("ROUTE_HANDLER_VALIDATION_MISSING", "Route Handler validation is missing."); if (/fetch\s*\([\s\S]*https?:\/\//i.test(content)) throw new ImplementationError("ROUTE_HANDLER_PROXY_FORBIDDEN", "Generic proxy behavior is forbidden."); }
  if (task.taskType === "implement-database-schema") validateMigration(content, paths, plans);
  if (task.taskType === "implement-rls-policy") { if (!/enable\s+row\s+level\s+security/i.test(content)) throw new ImplementationError("DATABASE_RLS_REQUIRED", "RLS migration does not enable row-level security."); if (/using\s*\(\s*true\s*\)|with\s+check\s*\(\s*true\s*\)/i.test(content)) throw new ImplementationError("RLS_POLICY_TOO_BROAD", "Broad RLS policy is not allowed."); if (/auth\.uid\s*\(\)\s+is\s+null/i.test(content)) throw new ImplementationError("RLS_ANON_ACCESS_UNAPPROVED", "Anonymous access is not approved."); }
  if (task.taskType === "implement-authentication") { if (plans.brief?.authenticationDecision !== "authentication-required" && plans.planning?.authentication?.decision !== "supabase-auth") throw new ImplementationError("AUTH_METHOD_UNAPPROVED", "Authentication method is not approved."); if (/service_role|SUPABASE_SERVICE_ROLE_KEY/i.test(content) && /use client|"use client"/i.test(content)) throw new ImplementationError("AUTH_SECRET_EXPOSURE", "Privileged Auth client crosses into browser code."); if (/if\s*\(\s*user\s*\)/i.test(content) && /owner|admin|role/i.test(content)) throw new ImplementationError("AUTHORIZATION_INCOMPLETE", "Authentication alone does not satisfy authorization."); }
  if (task.taskType === "implement-storage") { if (/from\s+['"]user|bucket\s*\(|bucketName.*req|\.\.\//i.test(content)) throw new ImplementationError("STORAGE_PATH_UNSAFE", "Storage path or bucket is user-controlled or unsafe."); if (!/mime|contentType|size|fileSize/i.test(content)) throw new ImplementationError("STORAGE_UPLOAD_VALIDATION_MISSING", "Storage upload validation is missing."); if (/public.*upload|upload.*public/i.test(content)) throw new ImplementationError("STORAGE_POLICY_UNSAFE", "Unrestricted public upload is not allowed."); }
  if (task.taskType === "implement-email") { if (plans.brief?.emailDecision !== "needed" && plans.planning?.email?.decision !== "required-configured-provider") throw new ImplementationError("EMAIL_PROVIDER_PENDING", "Email provider is not resolved."); if (/from\s*:\s*user|replyTo\s*:\s*input|\r|\n.*subject/i.test(content)) throw new ImplementationError("EMAIL_TEMPLATE_UNSAFE", "Email input may permit header injection."); if (/process\.env\.[A-Z_]+/i.test(content) && !/server|email/i.test(paths.join(" "))) throw new ImplementationError("EMAIL_SECRET_EXPOSURE", "Email secret is used outside a server boundary."); }
  if (/\b(Prisma|Drizzle|Sequelize|TypeORM|Express|NestJS|Redis|BullMQ)\b/i.test(content)) throw new ImplementationError("UNAPPROVED_DEPENDENCY", "Backend proposal introduces a prohibited dependency."); if (/process\.env\.([A-Z0-9_]+)/g.test(content)) { const declared = new Set(plans.planning?.architecture?.environment?.variables?.map((variable) => variable.name) ?? []); const names = [...content.matchAll(/process\.env\.([A-Z0-9_]+)/g)].map((match) => match[1]); if (names.some((name) => !declared.has(name))) throw new ImplementationError("ENV_VARIABLE_UNPLANNED", "Backend code references an undeclared environment variable."); }
}
function validateMigration(content: string, paths: string[], plans: BackendPlans) { if (!paths.every((path) => path.startsWith("supabase/migrations/") && path.endsWith(".sql"))) throw new ImplementationError("DATABASE_MIGRATION_UNSAFE", "Customer migrations must remain under supabase/migrations."); if (/drop\s+(database|schema|table)|truncate|alter\s+system|copy\s+.*program|disable\s+row\s+level\s+security|security\s+definer|grant\s+all|database_url|service_role|sk-[A-Za-z0-9]/i.test(content)) throw new ImplementationError("DATABASE_MIGRATION_UNSAFE", "Migration contains a prohibited SQL construct."); if (/\b(drop|truncate|delete|update)\b/i.test(content)) throw new ImplementationError("DATABASE_DESTRUCTIVE_CHANGE_UNAPPROVED", "Destructive migration changes require explicit approval."); if (plans.planning?.dataModel?.entities?.length && !/create\s+table/i.test(content)) throw new ImplementationError("DATABASE_ENTITY_UNAPPROVED", "Migration does not create a planned entity."); }
export class DefaultBackendTaskHandler implements ImplementationTaskHandler { supports(taskType: string) { return BACKEND_TASK_TYPES.has(taskType); } deriveContextRequirements(task: AgentTask) { return [`approved plans for ${task.taskType}`, "bounded existing backend files", "server/client boundary rules"]; } deriveDocumentationNeeds(task: AgentTask) { return task.taskType === "implement-server-action" ? ["Next.js Server Actions", "Zod input validation"] : task.taskType === "implement-route-handler" ? ["Next.js Route Handlers", "Zod request validation"] : task.taskType.startsWith("implement-") ? ["Supabase SSR and task-specific API guidance"] : []; } deriveRegistryNeeds(task: AgentTask) { return task.taskType === "implement-form" ? ["form", "input", "textarea", "select", "button"] : []; } validateProposal(task: AgentTask, proposal: ImplementationChangeProposal, plans: BackendPlans) { validateBackendProposal(task, proposal, plans); } validateAppliedResult(task: AgentTask, changedFiles: string[], plans: BackendPlans) { if (task.taskType === "implement-database-schema" && changedFiles.some((file) => !file.startsWith("supabase/migrations/"))) throw new ImplementationError("DATABASE_MIGRATION_UNSAFE", "Applied migration task changed a non-migration file."); assertBackendTaskRequired(task, plans); } }
