import { z } from "zod";
import { AssetManifestSchema } from "../domain/assets/schema";
import { TechnicalArchitectureSchema } from "../domain/architecture/schema";
import { ContentPlanSchema } from "../domain/content/schema";
import { SelectedDesignSchema } from "../domain/design/schema";
import { RequirementSpecificationSchema } from "../domain/requirements/schema";
import { AgentTaskSchema, TaskGraphSchema } from "../domain/tasks/schema";
import { ImplementationExecutionRunSchema } from "../domain/implementation/schema";
import { ApprovedSkillSnapshotSchema } from "../orchestrator/contracts";

export const ExecutionPolicySchema = z.object({ version: z.string().min(1), maxContextBytes: z.number().int().positive(), maxContextFiles: z.number().int().positive(), maxSourceFileBytes: z.number().int().positive(), maxProposalOperations: z.number().int().positive(), maxChangedFiles: z.number().int().positive(), maxOperationContentBytes: z.number().int().positive(), supportedEncodings: z.array(z.literal("utf-8")), transactionDirectoryName: z.string().regex(/^\.[a-z0-9-]+$/), lockExpiryMs: z.number().int().positive(), providerTimeoutMs: z.number().int().positive(), maxEventBytes: z.number().int().positive(), defaultTaskAttempts: z.number().int().positive() }).strict();
export const DEFAULT_EXECUTION_POLICY = ExecutionPolicySchema.parse({ version: "implementation-v1", maxContextBytes: 120000, maxContextFiles: 40, maxSourceFileBytes: 200000, maxProposalOperations: 20, maxChangedFiles: 20, maxOperationContentBytes: 200000, supportedEncodings: ["utf-8"], transactionDirectoryName: ".factory-transaction", lockExpiryMs: 120000, providerTimeoutMs: 30000, maxEventBytes: 12000, defaultTaskAttempts: 3 });
export type ExecutionPolicy = z.infer<typeof ExecutionPolicySchema>;
const CancellationSchema = z.object({ requested: z.boolean(), reason: z.string().max(500).optional() }).strict();
export const ImplementationAgentInputSchema = z.object({ projectId: z.string().uuid(), projectVersion: z.number().int().positive(), taskId: z.string().uuid(), expectedTaskState: z.literal("ready"), expectedTaskRowVersion: z.number().int().positive(), expectedProjectWorkflowState: z.literal("IMPLEMENTING"), taskGraphChecksum: z.string().regex(/^[a-f0-9]{64}$/), approvedBriefChecksum: z.string().regex(/^[a-f0-9]{64}$/), acceptedPlanningChecksum: z.string().regex(/^[a-f0-9]{64}$/), selectedDesignChecksum: z.string().regex(/^[a-f0-9]{64}$/), architectureChecksum: z.string().regex(/^[a-f0-9]{64}$/), workspaceReservationId: z.string().min(1), stagingWorkspacePath: z.string().min(1), approvedSkillSnapshotChecksum: z.string().regex(/^[a-f0-9]{64}$/), toolPolicyVersion: z.string().min(1), orchestrationPolicyVersion: z.string().min(1), executionPolicyVersion: z.string().min(1), idempotencyKey: z.string().min(1), cancellation: CancellationSchema, task: AgentTaskSchema, taskGraph: TaskGraphSchema, approvedBrief: RequirementSpecificationSchema, acceptedPlanningPackage: z.unknown(), selectedDesign: SelectedDesignSchema, technicalArchitecture: TechnicalArchitectureSchema, contentPlan: ContentPlanSchema, assetManifest: AssetManifestSchema, approvedSkillRegistrySnapshot: ApprovedSkillSnapshotSchema, projectImmutable: z.boolean().default(false) }).strict();
export type ImplementationAgentInput = z.input<typeof ImplementationAgentInputSchema>;
export const OperationBaseSchema = z.object({ relativePath: z.string().min(1), expectedPriorChecksum: z.string().regex(/^[a-f0-9]{64}$/).optional(), expectedResultChecksum: z.string().regex(/^[a-f0-9]{64}$/), encoding: z.literal("utf-8"), reason: z.string().min(1).max(500), requirementReferences: z.array(z.string().min(1)), planningReferences: z.array(z.string().min(1)), selectedDesignReferences: z.array(z.string().min(1)) }).strict();
export const ImplementationOperationSchema = z.discriminatedUnion("type", [OperationBaseSchema.extend({ type: z.literal("create-file"), content: z.string() }), OperationBaseSchema.extend({ type: z.literal("replace-file"), content: z.string() }), OperationBaseSchema.extend({ type: z.literal("patch-text"), oldText: z.string(), newText: z.string() }), OperationBaseSchema.extend({ type: z.literal("delete-file") })]);
export const ImplementationChangeProposalSchema = z.object({ proposalId: z.string().uuid(), projectId: z.string().uuid(), projectVersion: z.number().int().positive(), taskId: z.string().uuid(), taskAttempt: z.number().int().nonnegative(), summary: z.string().min(1).max(1000), operations: z.array(ImplementationOperationSchema), expectedChangedFiles: z.array(z.string().min(1)), expectedCreatedFiles: z.array(z.string().min(1)), expectedDeletedFiles: z.array(z.string().min(1)), validationPlan: z.array(z.string().min(1)), requirementReferences: z.array(z.string().min(1)), planningReferences: z.array(z.string().min(1)), selectedDesignReferences: z.array(z.string().min(1)), providerMetadata: z.object({ provider: z.string().min(1), inputTokens: z.number().int().nonnegative().optional(), outputTokens: z.number().int().nonnegative().optional() }).strict(), generatedAt: z.string().datetime() }).strict();
export const ImplementationContextSchema = z.object({ task: AgentTaskSchema, acceptanceCriteria: z.array(z.string()), requirementReferences: z.array(z.string()), planningReferences: z.array(z.string()), selectedDesignReferences: z.array(z.string()), architectureExcerpt: z.unknown(), contentExcerpt: z.unknown(), assetExcerpt: z.unknown(), files: z.array(z.object({ relativePath: z.string(), sha256: z.string(), content: z.string() }).strict()), skills: z.array(z.object({ skillId: z.string(), markdown: z.string(), references: z.array(z.object({ relativePath: z.string(), content: z.string() }).strict()) }).strict()), allowedTools: z.array(z.string()), conventions: z.array(z.string()), contextChecksum: z.string().regex(/^[a-f0-9]{64}$/) }).strict();
export type ImplementationContext = z.infer<typeof ImplementationContextSchema>;
export type ImplementationChangeProposal = z.infer<typeof ImplementationChangeProposalSchema>;
export type ImplementationExecutionRun = z.infer<typeof ImplementationExecutionRunSchema>;
export interface ImplementationProvider { proposeTaskChanges(context: ImplementationContext, signal?: AbortSignal): Promise<ImplementationChangeProposal>; }
