import { mkdtemp, mkdir, readFile, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { randomUUID, createHash } from "node:crypto";
import { describe, expect, it } from "vitest";
import { RequirementSpecificationSchema } from "../domain/requirements/schema";
import { TechnicalArchitectureSchema } from "../domain/architecture/schema";
import { ContentPlanSchema } from "../domain/content/schema";
import { AssetManifestSchema } from "../domain/assets/schema";
import { FactoryProjectSchema } from "../domain/project/schema";
import { TaskGraphSchema, AgentTaskSchema } from "../domain/tasks/schema";
import { ProjectRepository, ProjectVersionRepository } from "../persistence/repositories";
import { InMemoryPersistenceDatabase } from "../persistence/fake";
import { checksumPersistedDocument } from "../persistence/serialization";
import { ImplementationAgentService } from "./service";
import { ImplementationChangeProposalSchema } from "./contracts";
import type { ImplementationProvider } from "./contracts";
import { AtomicChangeApplier } from "./applier";

const id = () => randomUUID(); const sha = (v: string) => createHash("sha256").update(v).digest("hex"); const roots: string[] = [];
const task = (overrides: Record<string, unknown> = {}) => AgentTaskSchema.parse({ id: id(), projectId: id(), projectVersion: 1, role: "implementation", taskType: "implement-project-foundation", title: "Foundation", objective: "Prepare foundation", requirementReferences: ["requirement:foundation"], planningReferences: ["decision:foundation"], selectedDesignReferences: [], inputs: [], expectedOutputs: ["foundation"], acceptanceCriteria: ["Foundation files exist"], allowedSkills: [], allowedTools: ["filesystem-read", "filesystem-write"], deniedTools: [], fileScopes: ["src/app/**"], dependencies: [], status: "ready", priority: "high", executionMode: "exclusive-write", attempt: 0, maxAttempts: 3, createdAt: "2026-01-01T00:00:00.000Z", blockingFailure: true, estimatedContextBytes: 1000, expectedArtifactTypes: ["source"], ...overrides });
const docs = (projectId: string) => { const brief = RequirementSpecificationSchema.parse({ schemaVersion: 1, documentType: "requirements", projectId, projectVersion: 1, createdAt: "2026-01-01T00:00:00.000Z", updatedAt: "2026-01-01T00:00:00.000Z", projectSummary: "A site", protectedFunctionalityRequired: false, imagesRequired: false, businessGoals: ["Explain"], targetAudiences: ["Visitors"], pages: [{ slug: "home", purpose: "Explain" }], userRoles: [], features: [], forms: [], contentRequirements: [], backendRequirements: [], supabaseRequirements: [], authenticationDecision: "no-authentication-guest-first", storageDecision: "not-needed", emailDecision: "not-needed", administrationDecision: "not-needed", seoRequirements: [], localization: { locales: ["en"], defaultLocale: "en" }, imageSourceDecision: "user-supplied", suppliedBrandInformation: { status: "missing" }, suppliedLogoLocation: { status: "missing" }, technicalConstraints: [], explicitExclusions: [], userAcceptanceCriteria: ["Explain"], unresolvedItems: [], approval: { approved: true, approvedRequirementsChecksum: "a".repeat(64) }, briefStatus: "approved", briefVersion: 1 }); const architecture = TechnicalArchitectureSchema.parse({ schemaVersion: 1, documentType: "architecture", projectId, projectVersion: 1, createdAt: brief.createdAt, updatedAt: brief.updatedAt, applicationProfile: "marketing-site", packageManager: "npm", routes: [{ path: "/", responsibility: "Home" }], componentBoundaries: [], componentDecisions: [], serverActions: [], routeHandlers: [], backendPriority: ["server-actions", "route-handlers", "supabase-services"], supabaseDatabaseRequirements: [], schemaPlan: [], rlsRequirements: [], authenticationPlan: "none", storagePlan: "not-required", emailPlan: "not-required", environmentVariables: [], dependencies: [], npmScripts: { build: "next build" }, testStrategy: [], securityControls: [], rejectedInfrastructure: [], acceptance: { accepted: true } }); const content = ContentPlanSchema.parse({ schemaVersion: 1, documentType: "content-plan", projectId, projectVersion: 1, createdAt: brief.createdAt, updatedAt: brief.updatedAt, userProvidedFacts: ["Explain"], approvedGeneratedCopy: [], missingFactualContent: [], legalContentRequiringConfirmation: [], approvedPlaceholders: [], suppliedContentNotes: [] }); const assets = AssetManifestSchema.parse({ schemaVersion: 1, documentType: "asset-manifest", projectId, projectVersion: 1, createdAt: brief.createdAt, updatedAt: brief.updatedAt, entries: [] }); const selected = { schemaVersion: 1 as const, documentType: "selected-design" as const, projectId, projectVersion: 1, createdAt: brief.createdAt, updatedAt: brief.updatedAt, directionSetId: id(), selectedDirectionId: id(), selectedAt: brief.createdAt, selectedBy: "user", selectionNotes: "Selected", selectedDirectionChecksum: "b".repeat(64) }; return { brief, architecture, content, assets, selected }; };
async function fixture(taskOverrides: Record<string, unknown> = {}) { const projectId = id(); const value = docs(projectId); const t = task({ projectId, ...taskOverrides }); const base = { schemaVersion: 1 as const, documentType: "task-graph" as const, projectId, projectVersion: 1, createdAt: t.createdAt, updatedAt: t.createdAt, tasks: [t], validation: { valid: true, errors: [], warnings: [] }, checkpoint: "implementation-started" as const }; const graph = TaskGraphSchema.parse({ ...base, graphChecksum: checksumPersistedDocument(base) }); const root = await mkdtemp(path.join(os.tmpdir(), "factory-implementation-")); roots.push(root); await mkdir(path.join(root, "src", "app"), { recursive: true }); const project = FactoryProjectSchema.parse({ schemaVersion: 1, documentType: "factory-project", projectId, projectVersion: 1, createdAt: t.createdAt, updatedAt: t.createdAt, id: projectId, slug: `fixture-${projectId.slice(0, 8)}`, originalPrompt: "fixture", currentVersion: 1, workflowState: "IMPLEMENTING" }); const db = new InMemoryPersistenceDatabase(); await new ProjectRepository(db).create(project); await new ProjectVersionRepository(db).create({ id: id(), projectId, versionNumber: 1, state: "IMPLEMENTING", memoryRootPath: root, requirementsChecksum: null, selectedDesignChecksum: null, architectureChecksum: null, releasedAt: null, immutable: false, createdAt: t.createdAt, updatedAt: t.createdAt, rowVersion: 1 }); const input = { projectId, projectVersion: 1, taskId: t.id, expectedTaskState: "ready" as const, expectedTaskRowVersion: 1, expectedProjectWorkflowState: "IMPLEMENTING" as const, taskGraphChecksum: graph.graphChecksum!, approvedBriefChecksum: checksumPersistedDocument(value.brief), acceptedPlanningChecksum: "c".repeat(64), selectedDesignChecksum: checksumPersistedDocument(value.selected), architectureChecksum: checksumPersistedDocument(value.architecture), workspaceReservationId: "reservation-1", stagingWorkspacePath: root, approvedSkillSnapshotChecksum: "d".repeat(64), toolPolicyVersion: "tool-policy-v1", orchestrationPolicyVersion: "orchestrator-v1", executionPolicyVersion: "implementation-v1", idempotencyKey: id(), cancellation: { requested: false }, task: t, taskGraph: graph, approvedBrief: value.brief, acceptedPlanningPackage: {}, selectedDesign: value.selected, technicalArchitecture: value.architecture, contentPlan: value.content, assetManifest: value.assets, approvedSkillRegistrySnapshot: { schemaVersion: 1 as const, checksum: "d".repeat(64), skills: [] }, projectImmutable: false }; const service = new ImplementationAgentService(db, { workspace: { verifyStaging: async () => true } }); return { db, input, root, task: t, service }; }

describe("Implementation Agent execution foundation", () => {
  it("executes exactly one deterministic READY foundation task and unlocks no unrelated task", async () => { const f = await fixture(); const result = await f.service.executeImplementationTask(f.input); expect(result.status).toBe("passed"); expect(await readFile(path.join(f.root, "src/app/layout.tsx"), "utf8")).toContain("RootLayout"); expect((await f.service.getNewlyReadyTasks(f.input.projectId, 1)).some((t) => t.id === f.task.id)).toBe(false); });
  it("rejects stale graph, wrong role, incomplete dependencies and unsupported types", async () => { const f = await fixture(); await expect(f.service.executeImplementationTask({ ...f.input, taskGraphChecksum: "e".repeat(64) })).rejects.toMatchObject({ code: "IMPLEMENTATION_GRAPH_STALE" }); const unsupported = await fixture({ taskType: "implement-form" }); await expect(unsupported.service.executeImplementationTask(unsupported.input)).rejects.toMatchObject({ code: "IMPLEMENTATION_TASK_TYPE_UNSUPPORTED" }); const wrong = await fixture({ role: "qa-release" }); await expect(wrong.service.executeImplementationTask(wrong.input)).rejects.toMatchObject({ code: "IMPLEMENTATION_ROLE_INVALID" }); });
  it("is idempotent and does not apply the same proposal twice", async () => { const f = await fixture(); const first = await f.service.executeImplementationTask(f.input); const second = await f.service.executeImplementationTask(f.input); expect(second.executionId).toBe(first.executionId); });
  it("rejects unsafe proposal paths and rolls back partial application", async () => { const f = await fixture(); const provider: ImplementationProvider = { proposeTaskChanges: async (context) => ImplementationChangeProposalSchema.parse({ proposalId: id(), projectId: context.task.projectId, projectVersion: 1, taskId: context.task.id, taskAttempt: 1, summary: "unsafe", operations: [{ type: "create-file", relativePath: "../outside.ts", expectedResultChecksum: sha("x"), encoding: "utf-8", reason: "unsafe", requirementReferences: ["r"], planningReferences: ["p"], selectedDesignReferences: [], content: "x" }], expectedChangedFiles: ["../outside.ts"], expectedCreatedFiles: ["../outside.ts"], expectedDeletedFiles: [], validationPlan: ["test"], requirementReferences: ["r"], planningReferences: ["p"], selectedDesignReferences: [], providerMetadata: { provider: "test" }, generatedAt: new Date().toISOString() }) }; const unsafe = new ImplementationAgentService(f.db, { workspace: { verifyStaging: async () => true }, provider }); await expect(unsafe.executeImplementationTask(f.input)).rejects.toMatchObject({ code: "IMPLEMENTATION_PATH_INVALID" }); const applier = new AtomicChangeApplier(); const valid = { ...f.task, attempt: 1, status: "running" as const, startedAt: new Date().toISOString() }; const proposal = await new (await import("./provider")).DeterministicImplementationProvider().proposeTaskChanges({ task: valid, acceptanceCriteria: [], requirementReferences: ["r"], planningReferences: ["p"], selectedDesignReferences: [], architectureExcerpt: {}, contentExcerpt: {}, assetExcerpt: {}, files: [], skills: [], allowedTools: ["filesystem-write"], conventions: [], contextChecksum: "a".repeat(64) }); await expect(applier.apply(valid, { ...proposal, operations: [{ ...proposal.operations[0]!, expectedResultChecksum: "f".repeat(64) }] }, f.root, { version: "implementation-v1", maxContextBytes: 100, maxContextFiles: 2, maxSourceFileBytes: 1000, maxProposalOperations: 2, maxChangedFiles: 2, maxOperationContentBytes: 1000, supportedEncodings: ["utf-8"], transactionDirectoryName: ".factory-transaction", lockExpiryMs: 1000, providerTimeoutMs: 1000, maxEventBytes: 1000, defaultTaskAttempts: 3 })).rejects.toMatchObject({ code: "IMPLEMENTATION_RESULT_CHECKSUM_MISMATCH" }); });
  it("blocks secret-like context and cancellation before apply", async () => { const f = await fixture(); await writeFile(path.join(f.root, "src", "app", "secret.ts"), "const password = 'secret';\n"); await expect(f.service.executeImplementationTask(f.input)).rejects.toMatchObject({ code: "IMPLEMENTATION_SECRET_EXPOSURE_BLOCKED" }); const cancelled = await fixture(); await expect(cancelled.service.executeImplementationTask({ ...cancelled.input, cancellation: { requested: true, reason: "user" } })).rejects.toMatchObject({ code: "IMPLEMENTATION_CANCELLED" }); });
});
