import { randomUUID, createHash } from "node:crypto";
import { ImplementationChangeProposalSchema, type ImplementationContext, type ImplementationProvider } from "./contracts";
import { ImplementationError } from "./errors";
import { FOUNDATION_ESLINT_CONFIG, FOUNDATION_ESLINT_CONFIG_PATH, FOUNDATION_NEXT_CONFIG, FOUNDATION_NEXT_CONFIG_PATH, FOUNDATION_PACKAGE_JSON } from "./foundation-policy";
const sha = (value: string) => createHash("sha256").update(value, "utf8").digest("hex");
const files: Record<string, { path: string; content: string }> = {
  "prepare-workspace": { path: "src/app/factory-prepared.ts", content: "export const factoryWorkspacePrepared = true;\n" },
  "implement-project-foundation": { path: "src/app/layout.tsx", content: "export default function RootLayout({ children }: { children: React.ReactNode }) { return <html lang=\"en\"><body>{children}</body></html>; }\n" },
  "implement-design-system": { path: "src/styles/design-tokens.css", content: ":root { --factory-canvas: #ffffff; --factory-text: #111111; }\n" },
  "implement-shared-layout": { path: "src/components/layout/factory-shell.tsx", content: "export function FactoryShell({ children }: { children: React.ReactNode }) { return <main>{children}</main>; }\n" },
  "implement-navigation": { path: "src/components/navigation/factory-navigation.tsx", content: "export function FactoryNavigation() { return <nav aria-label=\"Primary\" />; }\n" },
  "implement-page": { path: "src/app/page.tsx", content: "export default function Page() { return <main />; }\n" },
  "implement-shared-component": { path: "src/components/factory-shared.tsx", content: "export function FactoryShared() { return null; }\n" },
  "integrate-content": { path: "src/content/approved-content.ts", content: "export const approvedContent = [];\n" },
  "integrate-assets": { path: "src/assets/approved-assets.ts", content: "export const approvedAssets = [];\n" },
  "implement-seo": { path: "src/app/metadata.ts", content: "export const metadata = { title: \"Approved project\" };\n" },
  "write-unit-tests": { path: "src/factory-foundation.test.ts", content: "import { describe, expect, it } from \"vitest\"; describe(\"approved implementation\", () => { it(\"is deterministic\", () => expect(true).toBe(true)); });\n" },
  "write-integration-tests": { path: "src/factory-integration.integration.test.ts", content: "import { describe, expect, it } from \"vitest\"; describe(\"approved integration boundaries\", () => { it(\"are bounded\", () => expect(true).toBe(true)); });\n" },
  "write-e2e-tests": { path: "tests/e2e/factory-flow.spec.ts", content: "import { test, expect } from \"@playwright/test\"; test(\"approved flow is bounded\", async () => { expect(true).toBe(true); });\n" },
  "implement-form": { path: "src/components/forms/approved-form.tsx", content: "import { z } from \"zod\";\nconst formSchema = z.object({});\nexport function ApprovedForm() { return null; }\n" },
  "implement-server-action": { path: "src/actions/approved-action.ts", content: "\"use server\";\nimport { z } from \"zod\";\nconst inputSchema = z.object({});\nexport async function approvedAction(input: unknown) { const parsed = inputSchema.safeParse(input); if (!parsed.success) return { ok: false }; return { ok: true }; }\n" },
  "implement-route-handler": { path: "src/app/api/approved/route.ts", content: "import { z } from \"zod\";\nconst inputSchema = z.object({});\nexport async function POST(request: Request) { const parsed = inputSchema.safeParse(await request.json()); if (!parsed.success) return Response.json({ ok: false }, { status: 400 }); return Response.json({ ok: true }); }\n" },
  "implement-database-schema": { path: "supabase/migrations/20260807120000_create_approved_schema.sql", content: "create table if not exists approved_records (id uuid primary key, created_at timestamptz not null default now());\n" },
  "implement-rls-policy": { path: "supabase/migrations/20260807120001_create_approved_rls.sql", content: "alter table approved_records enable row level security;\ncreate policy approved_records_select on approved_records for select to authenticated using (auth.uid() is not null);\n" },
  "implement-authentication": { path: "src/lib/supabase/auth.ts", content: "export async function getAuthenticatedUser() { return null; }\n" },
  "implement-storage": { path: "src/lib/storage/uploads.ts", content: "export function validateUpload(file: { type: string; size: number }) { return file.type.startsWith(\"image/\") && file.size <= 5000000; }\n" },
  "implement-email": { path: "src/lib/email/adapter.ts", content: "export async function sendApprovedEmail(input: { subject: string; body: string }) { return { ok: Boolean(input.subject && input.body) }; }\n" },
};
export class DeterministicImplementationProvider implements ImplementationProvider {
  async proposeTaskChanges(context: ImplementationContext, signal?: AbortSignal) { if (signal?.aborted) throw new ImplementationError("IMPLEMENTATION_CANCELLED", "Implementation was cancelled before proposal generation."); const candidate = files[context.task.taskType]; if (!candidate) throw new ImplementationError("IMPLEMENTATION_TASK_TYPE_UNSUPPORTED", "This task type has no deterministic implementation handler."); const operation = { type: "create-file" as const, relativePath: candidate.path, expectedResultChecksum: sha(candidate.content), encoding: "utf-8" as const, reason: `Deterministic foundation output for ${context.task.taskType}.`, requirementReferences: context.requirementReferences, planningReferences: context.planningReferences, selectedDesignReferences: context.selectedDesignReferences, content: candidate.content }; const operations = context.task.taskType === "implement-project-foundation" ? [{ ...operation, relativePath: "package.json", content: FOUNDATION_PACKAGE_JSON, expectedResultChecksum: sha(FOUNDATION_PACKAGE_JSON) }, operation, { ...operation, relativePath: FOUNDATION_ESLINT_CONFIG_PATH, content: FOUNDATION_ESLINT_CONFIG, expectedResultChecksum: sha(FOUNDATION_ESLINT_CONFIG) }, { ...operation, relativePath: FOUNDATION_NEXT_CONFIG_PATH, content: FOUNDATION_NEXT_CONFIG, expectedResultChecksum: sha(FOUNDATION_NEXT_CONFIG) }] : [operation]; return ImplementationChangeProposalSchema.parse({ proposalId: randomUUID(), projectId: context.task.projectId, projectVersion: context.task.projectVersion, taskId: context.task.id, taskAttempt: context.task.attempt, summary: `Prepared deterministic ${context.task.taskType} proposal.`, operations, expectedChangedFiles: operations.map((item) => item.relativePath), expectedCreatedFiles: operations.map((item) => item.relativePath), expectedDeletedFiles: [], validationPlan: [context.task.taskType], requirementReferences: context.requirementReferences, planningReferences: context.planningReferences, selectedDesignReferences: context.selectedDesignReferences, providerMetadata: { provider: "deterministic" }, generatedAt: new Date().toISOString() }); }
}
