import { DocumentRepository, ProjectRepository, WorkflowPersistenceService } from "@/persistence/database/repositories";
import type { PersistenceDatabase } from "@/persistence/database/types";
import type { ContractAuditInput } from "@/agents/reviewers/contracts/contracts";
import { ContractAuditService, type ContractAuditExecutionEvidence } from "@/agents/reviewers/contracts/service";

export class ContractAuditOrchestrationService {
  private readonly workflow: WorkflowPersistenceService;
  private readonly projects: ProjectRepository;
  private readonly documents: DocumentRepository;
  constructor(private readonly database: PersistenceDatabase, private readonly auditor: ContractAuditService = new ContractAuditService(database)) { this.workflow = new WorkflowPersistenceService(database); this.projects = new ProjectRepository(database); this.documents = new DocumentRepository(database); }
  async enterAudit(input: { projectId: string; projectVersion: number; expectedRowVersion: number; idempotencyKey: string }) { const current = await this.projects.getWithVersion(input.projectId); if (!current || current.project.workflowState === "CONTRACT_AUDIT") return { rowVersion: current?.rowVersion ?? input.expectedRowVersion, projectState: "CONTRACT_AUDIT" as const }; const transition = await this.workflow.transition({ projectId: input.projectId, projectVersion: input.projectVersion, expectedState: "READY_FOR_IMPLEMENTATION", expectedRowVersion: input.expectedRowVersion, targetState: "CONTRACT_AUDIT", actor: "orchestrator", reason: "TaskGraph preparation completed; contract audit is required before implementation.", idempotencyKey: input.idempotencyKey }); return { rowVersion: transition.rowVersion, projectState: "CONTRACT_AUDIT" as const }; }
  async auditAndRoute(input: ContractAuditInput, signal?: AbortSignal, execution?: ContractAuditExecutionEvidence) { const result = await this.auditor.audit(input, signal, execution); if (result.verdict !== "APPROVED") return { result, projectState: "CONTRACT_AUDIT" as const, rowVersion: (await this.projects.getWithVersion(input.projectId))?.rowVersion ?? input.expectedRowVersion }; const current = await this.projects.getWithVersion(input.projectId); if (!current || current.project.workflowState !== "CONTRACT_AUDIT") return { result, projectState: current?.project.workflowState ?? "CONTRACT_AUDIT", rowVersion: current?.rowVersion ?? input.expectedRowVersion }; const transition = await this.workflow.transition({ projectId: input.projectId, projectVersion: input.projectVersion, expectedState: "CONTRACT_AUDIT", expectedRowVersion: current.rowVersion, targetState: "READY_FOR_IMPLEMENTATION", actor: "contract-auditor", reason: "Current Contract Audit approved the pre-implementation contract chain.", idempotencyKey: `${input.idempotencyKey}:approved` }); return { result, projectState: "READY_FOR_IMPLEMENTATION" as const, rowVersion: transition.rowVersion }; }
  async getCurrentAudit(projectId: string, projectVersion: number, checksums: Parameters<ContractAuditService["getCurrentAudit"]>[2]) { return this.auditor.getCurrentAudit(projectId, projectVersion, checksums); }
  async getTaskGraph(projectId: string, projectVersion: number) { return this.documents.get(projectId, projectVersion, "task-graph"); }
}
