import { randomUUID } from "node:crypto";
import { Pool, type PoolClient, type QueryResultRow } from "pg";
import { DomainError } from "@/domain/shared/errors";
import { readServerEnvironment, requireDatabaseSsl } from "./env";
import { PersistenceError } from "./errors";
import type { DocumentRow } from "./mapping";
import type { PersistenceDatabase, PersistenceTransaction, ProjectAssetRow, ProjectRow, ProjectVersionRow, WorkflowEvent, CostRecord } from "./types";
import type { DecisionRecord } from "@/domain/workflow/decision";

const safeProviderError = (error: unknown): never => { const providerCode = typeof error === "object" && error && "code" in error && typeof error.code === "string" ? error.code : "unknown"; throw new PersistenceError("PERSISTENCE_PROVIDER_ERROR", "The database operation failed.", { providerCode }, error); };
const value = <T>(result: { rows: QueryResultRow[] }) => result.rows[0] as T | undefined;
const isoTimestamp = (value: unknown): string | null => value == null ? null : value instanceof Date ? value.toISOString() : String(value);
const normalizeProjectRow = (row: ProjectRow) => ({ ...row, row_version: Number(row.row_version) });
const normalizeAssetRow = (row: ProjectAssetRow) => ({ ...row, byteSize: Number(row.byteSize), projectVersion: Number(row.projectVersion), version: Number(row.version), createdAt: isoTimestamp(row.createdAt) as string, updatedAt: isoTimestamp(row.updatedAt) as string });
const normalizeVersionRow = (row: ProjectVersionRow) => ({
  ...row,
  rowVersion: Number(row.rowVersion),
  createdAt: isoTimestamp(row.createdAt) as string,
  updatedAt: isoTimestamp(row.updatedAt) as string,
  releasedAt: isoTimestamp(row.releasedAt),
});

export function createPostgresPool(input: Record<string, string | undefined> = process.env) {
  const environment = readServerEnvironment(input);
  if (!environment.DATABASE_URL) throw new Error("DATABASE_URL is required for the Postgres persistence adapter.");
  return new Pool({ connectionString: requireDatabaseSsl(environment.DATABASE_URL), ssl: { rejectUnauthorized: false }, max: 5, connectionTimeoutMillis: 5000, idleTimeoutMillis: 10000 });
}

export class PostgresPersistenceDatabase implements PersistenceDatabase {
  constructor(private readonly pool: Pool) {}

  async transaction<T>(work: (transaction: PersistenceTransaction) => Promise<T>): Promise<T> {
    const client = await this.pool.connect();
    try { await client.query("BEGIN"); const result = await work(new PostgresTransaction(client)); await client.query("COMMIT"); return result; }
    catch (error) { await client.query("ROLLBACK").catch(() => undefined); if (error instanceof PersistenceError || error instanceof DomainError) throw error; return safeProviderError(error); }
    finally { client.release(); }
  }
}

class PostgresTransaction implements PersistenceTransaction {
  constructor(private readonly db: PoolClient) {}
  private async query<T extends QueryResultRow = QueryResultRow>(text: string, values: unknown[] = []) { try { return await this.db.query<T>(text, values); } catch (error) { return safeProviderError(error); } }
  private async idempotent(operation: string, token: { key: string; payloadHash: string } | undefined, result: unknown) {
    if (!token) return undefined;
    const existing = value<{ payload_hash: string; result: unknown }>(await this.query("SELECT payload_hash, result FROM idempotency_records WHERE operation = $1 AND idempotency_key = $2 FOR UPDATE", [operation, token.key]));
    if (existing && existing.payload_hash !== token.payloadHash) throw new PersistenceError("IDEMPOTENCY_CONFLICT", "The idempotency key was already used with a different payload.");
    if (existing) return existing.result;
    await this.query("INSERT INTO idempotency_records (operation, idempotency_key, payload_hash, result) VALUES ($1, $2, $3, $4)", [operation, token.key, token.payloadHash, result]);
    return undefined;
  }

  async getProject(id: string) { const result = value<ProjectRow>(await this.query("SELECT * FROM factory_projects WHERE id = $1", [id])); return result ? normalizeProjectRow(result) : null; }
  async listProjects() { const result = await this.query<ProjectRow>("SELECT * FROM factory_projects ORDER BY updated_at DESC, id DESC LIMIT 40"); return result.rows.map((row) => normalizeProjectRow(row)); }
  async insertProject(row: ProjectRow, token?: { key: string; payloadHash: string }) { const existing = await this.idempotent("project:create", token, row); if (existing) return normalizeProjectRow(existing as ProjectRow); const result = value<ProjectRow>(await this.query("INSERT INTO factory_projects (id, slug, origin, site_language, title, original_prompt, original_prompt_checksum, current_version, workflow_state, created_at, updated_at, implementation_started_at, completed_at, row_version) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) RETURNING *", [row.id, row.slug, row.origin, row.site_language, row.title, row.original_prompt, row.original_prompt_checksum, row.current_version, row.workflow_state, row.created_at, row.updated_at, row.implementation_started_at, row.completed_at, row.row_version])); if (!result) throw new PersistenceError("PERSISTENCE_PROVIDER_ERROR", "Project insert returned no row."); return normalizeProjectRow(result); }
  async updateProjectState(input: { id: string; expectedState: ProjectRow["workflow_state"]; expectedRowVersion: number; state: ProjectRow["workflow_state"]; updatedAt: string; implementationStartedAt?: string; completedAt?: string }) { const result = value<ProjectRow>(await this.query("UPDATE factory_projects SET workflow_state=$1, updated_at=$2, implementation_started_at=COALESCE($3, implementation_started_at), completed_at=COALESCE($4, completed_at), row_version=row_version+1 WHERE id=$5 AND workflow_state=$6 AND row_version=$7 RETURNING *", [input.state, input.updatedAt, input.implementationStartedAt ?? null, input.completedAt ?? null, input.id, input.expectedState, input.expectedRowVersion])); if (!result) throw new PersistenceError("PERSISTENCE_CONFLICT", "The workflow state is stale."); return normalizeProjectRow(result); }
  async updateProjectSiteLanguage(input: { id: string; siteLanguage: string; updatedAt: string }) { const result = value<ProjectRow>(await this.query("UPDATE factory_projects SET site_language=$1, updated_at=$2 WHERE id=$3 RETURNING *", [input.siteLanguage, input.updatedAt, input.id])); if (!result) throw new PersistenceError("PERSISTENCE_NOT_FOUND", "Project was not found."); return normalizeProjectRow(result); }
  async listAssets(projectId: string) { const result = await this.query<ProjectAssetRow>("SELECT schema_version AS \"schemaVersion\", asset_id AS \"assetId\", project_id AS \"projectId\", project_version AS \"projectVersion\", category, source, safe_display_name AS \"safeDisplayName\", media_type AS \"mediaType\", byte_size AS \"byteSize\", sha256, storage_identity AS \"storageIdentity\", status, created_at AS \"createdAt\", updated_at AS \"updatedAt\", asset_version AS version, currentness, supersedes_asset_id AS \"supersedesAssetId\", rejection_reason AS \"rejectionReason\" FROM factory_project_assets WHERE project_id=$1 ORDER BY created_at DESC, asset_id DESC", [projectId]); return result.rows.map(normalizeAssetRow); }
  async getAsset(projectId: string, assetId: string) { const result = value<ProjectAssetRow>(await this.query("SELECT schema_version AS \"schemaVersion\", asset_id AS \"assetId\", project_id AS \"projectId\", project_version AS \"projectVersion\", category, source, safe_display_name AS \"safeDisplayName\", media_type AS \"mediaType\", byte_size AS \"byteSize\", sha256, storage_identity AS \"storageIdentity\", status, created_at AS \"createdAt\", updated_at AS \"updatedAt\", asset_version AS version, currentness, supersedes_asset_id AS \"supersedesAssetId\", rejection_reason AS \"rejectionReason\" FROM factory_project_assets WHERE project_id=$1 AND asset_id=$2", [projectId, assetId])); return result ? normalizeAssetRow(result) : null; }
  async insertAsset(row: ProjectAssetRow) { const result = value<ProjectAssetRow>(await this.query("INSERT INTO factory_project_assets (schema_version, asset_id, project_id, project_version, category, source, safe_display_name, media_type, byte_size, sha256, storage_identity, status, created_at, updated_at, asset_version, currentness, supersedes_asset_id, rejection_reason) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18) RETURNING schema_version AS \"schemaVersion\", asset_id AS \"assetId\", project_id AS \"projectId\", project_version AS \"projectVersion\", category, source, safe_display_name AS \"safeDisplayName\", media_type AS \"mediaType\", byte_size AS \"byteSize\", sha256, storage_identity AS \"storageIdentity\", status, created_at AS \"createdAt\", updated_at AS \"updatedAt\", asset_version AS version, currentness, supersedes_asset_id AS \"supersedesAssetId\", rejection_reason AS \"rejectionReason\"", [row.schemaVersion, row.assetId, row.projectId, row.projectVersion, row.category, row.source, row.safeDisplayName, row.mediaType, row.byteSize, row.sha256, row.storageIdentity, row.status, row.createdAt, row.updatedAt, row.version, row.currentness, row.supersedesAssetId ?? null, row.rejectionReason ?? null])); if (!result) throw new PersistenceError("PERSISTENCE_PROVIDER_ERROR", "Asset insert returned no row."); return normalizeAssetRow(result); }
  async updateAsset(row: ProjectAssetRow) { const result = value<ProjectAssetRow>(await this.query("UPDATE factory_project_assets SET project_version=$1, category=$2, safe_display_name=$3, media_type=$4, byte_size=$5, sha256=$6, storage_identity=$7, status=$8, updated_at=$9, asset_version=$10, currentness=$11, supersedes_asset_id=$12, rejection_reason=$13 WHERE project_id=$14 AND asset_id=$15 RETURNING schema_version AS \"schemaVersion\", asset_id AS \"assetId\", project_id AS \"projectId\", project_version AS \"projectVersion\", category, source, safe_display_name AS \"safeDisplayName\", media_type AS \"mediaType\", byte_size AS \"byteSize\", sha256, storage_identity AS \"storageIdentity\", status, created_at AS \"createdAt\", updated_at AS \"updatedAt\", asset_version AS version, currentness, supersedes_asset_id AS \"supersedesAssetId\", rejection_reason AS \"rejectionReason\"", [row.projectVersion, row.category, row.safeDisplayName, row.mediaType, row.byteSize, row.sha256, row.storageIdentity, row.status, row.updatedAt, row.version, row.currentness, row.supersedesAssetId ?? null, row.rejectionReason ?? null, row.projectId, row.assetId])); if (!result) throw new PersistenceError("PERSISTENCE_NOT_FOUND", "Asset was not found."); return normalizeAssetRow(result); }
  async getVersion(projectId: string, version: number) { const row = (value(await this.query("SELECT id, project_id AS \"projectId\", version_number AS \"versionNumber\", state, memory_root_path AS \"memoryRootPath\", requirements_checksum AS \"requirementsChecksum\", selected_design_checksum AS \"selectedDesignChecksum\", architecture_checksum AS \"architectureChecksum\", released_at AS \"releasedAt\", immutable, created_at AS \"createdAt\", updated_at AS \"updatedAt\", row_version AS \"rowVersion\" FROM project_versions WHERE project_id=$1 AND version_number=$2", [projectId, version])) as ProjectVersionRow | undefined); return row ? normalizeVersionRow(row) : null; }
  async listVersions(projectId: string) { const result = await this.query("SELECT id, project_id AS \"projectId\", version_number AS \"versionNumber\", state, memory_root_path AS \"memoryRootPath\", requirements_checksum AS \"requirementsChecksum\", selected_design_checksum AS \"selectedDesignChecksum\", architecture_checksum AS \"architectureChecksum\", released_at AS \"releasedAt\", immutable, created_at AS \"createdAt\", updated_at AS \"updatedAt\", row_version AS \"rowVersion\" FROM project_versions WHERE project_id=$1 ORDER BY version_number", [projectId]); return result.rows.map((row) => normalizeVersionRow(row as ProjectVersionRow)); }
  async reserveNextVersion(projectId: string, token?: { key: string; payloadHash: string }) {
    const existing = token ? value<{ payload_hash: string; result: ProjectVersionRow }>(await this.query("SELECT payload_hash, result FROM idempotency_records WHERE operation='version:reserve' AND idempotency_key=$1 FOR UPDATE", [token.key])) : undefined;
    if (existing && existing.payload_hash !== token?.payloadHash) throw new PersistenceError("IDEMPOTENCY_CONFLICT", "The idempotency key was already used with a different payload.");
    if (existing) return existing.result;
    const project = value<ProjectRow>(await this.query("SELECT * FROM factory_projects WHERE id=$1 FOR UPDATE", [projectId])); if (!project) throw new PersistenceError("PERSISTENCE_NOT_FOUND", "Project was not found.");
    const current = Number(project.current_version); const currentExists = value<{ exists: boolean }>(await this.query("SELECT exists(select 1 from project_versions where project_id=$1 and version_number=$2)", [projectId, current]))?.exists ?? false; const versionNumber = currentExists ? current + 1 : current; const now = new Date().toISOString();
    const row: ProjectVersionRow = { id: randomUUID(), projectId, versionNumber, state: project.workflow_state, memoryRootPath: null, requirementsChecksum: null, selectedDesignChecksum: null, architectureChecksum: null, releasedAt: null, immutable: false, createdAt: now, updatedAt: now, rowVersion: 1 };
    const inserted = await this.insertVersion(row); await this.query("UPDATE factory_projects SET current_version=$1, updated_at=$2 WHERE id=$3", [versionNumber, now, projectId]); if (token) await this.query("INSERT INTO idempotency_records(operation,idempotency_key,payload_hash,result) VALUES('version:reserve',$1,$2,$3)", [token.key, token.payloadHash, inserted]); return inserted;
  }
  async insertVersion(row: ProjectVersionRow, token?: { key: string; payloadHash: string }) { const existing = await this.idempotent("version:create", token, row); if (existing) return normalizeVersionRow(existing as ProjectVersionRow); const result = value(await this.query("INSERT INTO project_versions (id, project_id, version_number, state, memory_root_path, requirements_checksum, selected_design_checksum, architecture_checksum, released_at, immutable, created_at, updated_at, row_version) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) RETURNING id, project_id AS \"projectId\", version_number AS \"versionNumber\", state, memory_root_path AS \"memoryRootPath\", requirements_checksum AS \"requirementsChecksum\", selected_design_checksum AS \"selectedDesignChecksum\", architecture_checksum AS \"architectureChecksum\", released_at AS \"releasedAt\", immutable, created_at AS \"createdAt\", updated_at AS \"updatedAt\", row_version AS \"rowVersion\"", [row.id, row.projectId, row.versionNumber, row.state, row.memoryRootPath, row.requirementsChecksum, row.selectedDesignChecksum, row.architectureChecksum, row.releasedAt, row.immutable, row.createdAt, row.updatedAt, row.rowVersion])); if (!result) throw new PersistenceError("PERSISTENCE_PROVIDER_ERROR", "Version insert returned no row."); return normalizeVersionRow(result as ProjectVersionRow); }
  async updateVersionImmutable(projectId: string, version: number, releasedAt: string) { const result = value(await this.query("UPDATE project_versions SET state='PROJECT_READY', released_at=$1, immutable=true, updated_at=$1, row_version=row_version+1 WHERE project_id=$2 AND version_number=$3 AND immutable=false RETURNING id, project_id AS \"projectId\", version_number AS \"versionNumber\", state, memory_root_path AS \"memoryRootPath\", requirements_checksum AS \"requirementsChecksum\", selected_design_checksum AS \"selectedDesignChecksum\", architecture_checksum AS \"architectureChecksum\", released_at AS \"releasedAt\", immutable, created_at AS \"createdAt\", updated_at AS \"updatedAt\", row_version AS \"rowVersion\"", [releasedAt, projectId, version])); if (!result) throw new PersistenceError("PERSISTENCE_IMMUTABLE", "Project version is missing or immutable."); return normalizeVersionRow(result as ProjectVersionRow); }
  async saveDocument(row: DocumentRow, token?: { key: string; payloadHash: string }) { const existing = await this.idempotent(`document:${row.projectId}:${row.projectVersion}:${row.documentType}`, token, row); if (existing) return existing as DocumentRow; const result = value(await this.query("INSERT INTO workflow_documents (project_id, project_version, document_type, schema_version, checksum, payload, created_at, updated_at, row_version) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,1) ON CONFLICT (project_id, project_version, document_type) DO UPDATE SET schema_version=EXCLUDED.schema_version, checksum=EXCLUDED.checksum, payload=EXCLUDED.payload, updated_at=EXCLUDED.updated_at, row_version=workflow_documents.row_version+1 RETURNING project_id AS \"projectId\", project_version AS \"projectVersion\", document_type AS \"documentType\", schema_version AS \"schemaVersion\", checksum, payload, created_at AS \"createdAt\", updated_at AS \"updatedAt\", row_version AS \"rowVersion\"", [row.projectId, row.projectVersion, row.documentType, row.schemaVersion, row.checksum, row.payload, row.createdAt, row.updatedAt])); if (!result) throw new PersistenceError("PERSISTENCE_PROVIDER_ERROR", "Document save returned no row."); return result as DocumentRow; }
  async getDocument(projectId: string, version: number, documentType: string) { return (value(await this.query("SELECT project_id AS \"projectId\", project_version AS \"projectVersion\", document_type AS \"documentType\", schema_version AS \"schemaVersion\", checksum, payload, created_at AS \"createdAt\", updated_at AS \"updatedAt\", row_version AS \"rowVersion\" FROM workflow_documents WHERE project_id=$1 AND project_version=$2 AND document_type=$3", [projectId, version, documentType])) as DocumentRow | undefined) ?? null; }
  async deleteDocument(projectId: string, version: number, documentType: string) { await this.query("DELETE FROM workflow_documents WHERE project_id=$1 AND project_version=$2 AND document_type=$3", [projectId, version, documentType]); }
  async appendDecision(projectId: string, version: number, record: DecisionRecord) { const result = value<DecisionRecord>(await this.query("INSERT INTO decision_records (id, project_id, project_version, timestamp, actor_type, actor_identifier, category, decision, rationale, affected_documents, requirement_change, user_approval_required, user_approval_status, supersedes_decision_id) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) RETURNING id, timestamp, actor_type AS \"actorType\", actor_identifier AS \"actorIdentifier\", category, decision, rationale, affected_documents AS \"affectedDocuments\", requirement_change AS \"requirementChange\", user_approval_required AS \"userApprovalRequired\", user_approval_status AS \"userApprovalStatus\", supersedes_decision_id AS \"supersedesDecisionId\"", [record.id, projectId, version, record.timestamp, record.actorType, record.actorIdentifier, record.category, record.decision, record.rationale, JSON.stringify(record.affectedDocuments), record.requirementChange, record.userApprovalRequired, record.userApprovalStatus, record.supersedesDecisionId ?? null])); if (!result) throw new PersistenceError("PERSISTENCE_PROVIDER_ERROR", "Decision insert returned no row."); return result; }
  async listDecisions(projectId: string, version: number) { const result = await this.query<DecisionRecord>("SELECT id, timestamp, actor_type AS \"actorType\", actor_identifier AS \"actorIdentifier\", category, decision, rationale, affected_documents AS \"affectedDocuments\", requirement_change AS \"requirementChange\", user_approval_required AS \"userApprovalRequired\", user_approval_status AS \"userApprovalStatus\", supersedes_decision_id AS \"supersedesDecisionId\" FROM decision_records WHERE project_id=$1 AND project_version=$2 ORDER BY timestamp, id", [projectId, version]); return result.rows; }
  async appendWorkflowEvent(event: WorkflowEvent) { await this.query("INSERT INTO workflow_events (id, project_id, project_version, from_state, to_state, actor, reason, created_at, idempotency_key) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)", [event.id, event.projectId, event.projectVersion, event.fromState, event.toState, event.actor, event.reason, event.createdAt, event.idempotencyKey ?? null]); return event; }
  async saveCost(record: CostRecord) { await this.query("INSERT INTO cost_records (id, project_id, project_version, role, task_id, provider, model, input_tokens, cached_input_tokens, output_tokens, estimated_cost, created_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)", [record.id, record.projectId, record.projectVersion, record.role, record.taskId ?? null, record.provider, record.model, record.inputTokens, record.cachedInputTokens, record.outputTokens, record.estimatedCost, record.createdAt]); return record; }
}
