import { z } from "zod";
import { DocumentBaseSchema, IsoDateTimeSchema, NonEmptyStringSchema, UuidSchema } from "../shared/schemas";
import { DesignCapabilityPackageSchema, DirectionDesignCapabilitySchema, SelectedDesignContractBindingSchema } from "./capability";

const ColorRolesSchema = z.object({ canvas: NonEmptyStringSchema, surface: NonEmptyStringSchema, primaryText: NonEmptyStringSchema, secondaryText: NonEmptyStringSchema, brandPrimary: NonEmptyStringSchema, brandSecondary: NonEmptyStringSchema, accent: NonEmptyStringSchema, success: NonEmptyStringSchema, warning: NonEmptyStringSchema, danger: NonEmptyStringSchema, border: NonEmptyStringSchema }).strict();
export const DesignDirectionSchema = z.object({
  id: UuidSchema, label: NonEmptyStringSchema, concept: NonEmptyStringSchema, rationale: NonEmptyStringSchema, mood: NonEmptyStringSchema, colorStrategy: NonEmptyStringSchema, typographyStrategy: NonEmptyStringSchema, layoutStrategy: NonEmptyStringSchema, heroStrategy: NonEmptyStringSchema, sectionRhythm: NonEmptyStringSchema, componentCharacter: NonEmptyStringSchema, imageArtDirection: NonEmptyStringSchema, motionPolicy: NonEmptyStringSchema, responsivePrinciples: z.array(NonEmptyStringSchema), antiTemplateRules: z.array(NonEmptyStringSchema), advantages: z.array(NonEmptyStringSchema), risks: z.array(NonEmptyStringSchema), requirementReferences: z.array(UuidSchema),
  shortName: NonEmptyStringSchema.optional(), businessRationale: NonEmptyStringSchema.optional(), audienceFit: NonEmptyStringSchema.optional(), visualPersonality: NonEmptyStringSchema.optional(), gridStrategy: NonEmptyStringSchema.optional(), navigationCharacter: NonEmptyStringSchema.optional(), cardPolicy: NonEmptyStringSchema.optional(), formCharacter: NonEmptyStringSchema.optional(), ctaCharacter: NonEmptyStringSchema.optional(), logoUsageRules: NonEmptyStringSchema.optional(), iconographyDirection: NonEmptyStringSchema.optional(), decorativeLanguage: NonEmptyStringSchema.optional(), mobileCharacter: NonEmptyStringSchema.optional(), contentDensity: NonEmptyStringSchema.optional(), whitespaceStrategy: NonEmptyStringSchema.optional(), imageSourceDecision: z.enum(["ai-generated", "user-supplied", "ai-plus-user-supplied", "placeholders", "custom", "pending"]).optional(), implementationComplexity: z.enum(["low", "medium", "high"]).optional(), suitabilitySummary: NonEmptyStringSchema.optional(), prohibitedInterpretations: z.array(NonEmptyStringSchema).optional(), approvedRequirementReferences: z.array(NonEmptyStringSchema).optional(), planningReferences: z.array(NonEmptyStringSchema).optional(), colorRoles: ColorRolesSchema.optional(), imageArtDirectionDetails: z.object({ subjectCharacter: NonEmptyStringSchema, composition: NonEmptyStringSchema, lighting: NonEmptyStringSchema, cameraPerspective: NonEmptyStringSchema, colorTreatment: NonEmptyStringSchema, consistencyRules: z.array(NonEmptyStringSchema), safeTextZones: NonEmptyStringSchema, aspectRatioIntent: NonEmptyStringSchema, peopleUse: NonEmptyStringSchema, environmentUse: NonEmptyStringSchema, consistencyGroups: z.array(NonEmptyStringSchema) }).strict().optional(), motionDetails: z.object({ navigationTransitions: NonEmptyStringSchema, sectionEntrance: NonEmptyStringSchema, microinteractions: NonEmptyStringSchema, modalDrawer: NonEmptyStringSchema, feedbackStates: NonEmptyStringSchema, reducedMotionFallback: NonEmptyStringSchema, prohibitedPatterns: z.array(NonEmptyStringSchema) }).strict().optional(), responsiveDetails: z.object({ desktop: NonEmptyStringSchema, tablet: NonEmptyStringSchema, mobileReadingOrder: NonEmptyStringSchema, navigation: NonEmptyStringSchema, hero: NonEmptyStringSchema, density: NonEmptyStringSchema, imageCropping: NonEmptyStringSchema, forms: NonEmptyStringSchema, ctaPlacement: NonEmptyStringSchema }).strict().optional(), genericTemplateRisk: z.enum(["low", "medium", "high"]).optional(),
  professionalDesign: DirectionDesignCapabilitySchema.optional(),
}).strict();
export const DesignDirectionSetSchema = DocumentBaseSchema.extend({ documentType: z.literal("design-directions"), setId: UuidSchema, directions: z.array(DesignDirectionSchema).length(3), generatedAt: IsoDateTimeSchema, generatedBy: NonEmptyStringSchema, readyForSelection: z.boolean(), approvedBriefChecksum: z.string().regex(/^[a-f0-9]{64}$/).optional(), acceptedPlanningChecksum: z.string().regex(/^[a-f0-9]{64}$/).optional(), generationIdempotencyKey: NonEmptyStringSchema.optional(), blockingReasons: z.array(NonEmptyStringSchema).optional(), warnings: z.array(NonEmptyStringSchema).optional(), directionSetChecksum: z.string().regex(/^[a-f0-9]{64}$/).optional(), provider: z.object({ name: NonEmptyStringSchema, used: z.boolean(), model: NonEmptyStringSchema.optional(), requestId: NonEmptyStringSchema.optional(), responseReceived: z.boolean().optional(), finishReason: NonEmptyStringSchema.nullable().optional(), refusalPresent: z.boolean().optional(), parsedPresent: z.boolean().optional(), inputTokens: z.number().int().nonnegative().optional(), outputTokens: z.number().int().nonnegative().optional(), totalTokens: z.number().int().nonnegative().optional(), rawContentBytes: z.number().int().nonnegative().optional(), rawContentChecksum: z.string().regex(/^[a-f0-9]{64}$/).optional() }).strict().optional(), professionalCapability: DesignCapabilityPackageSchema.optional(), supersedesSetId: UuidSchema.optional(), supersededAt: IsoDateTimeSchema.optional() }).strict().superRefine((value, context) => {
  if (new Set(value.directions.map((direction) => direction.id)).size !== 3) context.addIssue({ code: "custom", path: ["directions"], message: "Directions must have unique IDs" });
});
export const SelectedDesignSchema = DocumentBaseSchema.extend({ documentType: z.literal("selected-design"), directionSetId: UuidSchema, selectedDirectionId: UuidSchema, selectedAt: IsoDateTimeSchema, selectedBy: NonEmptyStringSchema, selectionNotes: z.string(), selectedDirectionChecksum: z.string().regex(/^[a-f0-9]{64}$/), selectionIdempotencyKey: NonEmptyStringSchema.optional(), designContract: SelectedDesignContractBindingSchema.optional(), selectedDirectionContract: DirectionDesignCapabilitySchema.optional() }).strict();
export type DesignDirection = z.infer<typeof DesignDirectionSchema>;
export type DesignDirectionSet = z.infer<typeof DesignDirectionSetSchema>;
export type SelectedDesign = z.infer<typeof SelectedDesignSchema>;
