export type Context7ErrorCode =
  | "CONTEXT7_LIBRARY_NOT_ALLOWED" | "CONTEXT7_LIBRARY_NOT_PLANNED" | "CONTEXT7_TOOL_NOT_ALLOWED"
  | "CONTEXT7_VERSION_CONFLICT" | "CONTEXT7_VERSION_UNRESOLVED" | "CONTEXT7_LIBRARY_RESOLUTION_FAILED"
  | "CONTEXT7_UNSAFE_CONTENT" | "CONTEXT7_OPERATION_NOT_ALLOWED" | "CONTEXT7_UNAVAILABLE"
  | "CONTEXT7_RATE_LIMITED" | "CONTEXT7_TIMEOUT" | "CONTEXT7_CANCELLED" | "CONTEXT7_CONFIGURATION_INVALID"
  | "CONTEXT7_RETRY_EXHAUSTED" | "CONTEXT7_CONCURRENCY_LIMIT_REACHED" | "CONTEXT7_QUERY_INVALID"
  | "IDEMPOTENCY_CONFLICT";

export class Context7Error extends Error {
  constructor(readonly code: Context7ErrorCode, message: string, readonly cause?: unknown) { super(message); this.name = "Context7Error"; }
}
