import { describe, expect, it } from "vitest";
import { z } from "zod";
import { OpenAiStructuredClient } from "@/integrations/openai/client";
import { ContextBundleSchema, ContextExpansionRequestSchema, CONTEXT_BUDGET_PROFILES, assembleContext, astPatchEfficiencyMetric, createContextExpansionRequest, createInvocationUsageRecord, designCandidateContextCandidates, deterministicCallDecision, documentationContextCandidate, selectRelevantFiles, sliceApprovedSkill, sliceDiagnostics, createSourceSkeleton, renderSourceSkeleton, sourceContextCandidates } from "@/runtime/context";
import { checksumPersistedDocument } from "@/persistence/database/serialization";

const task = { taskId: "11111111-1111-4111-8111-111111111111", projectId: "22222222-2222-4222-8222-222222222222" };
const source = `import type { Props } from "./props";\nexport function Target(props: Props) {\n  return <main>{props.title}</main>;\n}\n` + Array.from({ length: 700 }, (_, index) => `export const noise${index} = ${JSON.stringify(`noise-${index}-with-a-realistic-identifier-and-value`)};`).join("\n");
const sourceChecksum = checksumPersistedDocument(source);
const skill = { skillId: "design-procedure", approvedChecksum: "a".repeat(64), coverageKeys: ["motion"], skillMarkdown: "# Procedure\n\n## Motion\nUse opacity and transform.\n\n## Unrelated\n" + "unused ".repeat(500), references: [] };
const required = { kind: "CANONICAL_CONTRACT" as const, sourceRef: "task:canonical", sourceChecksum: "b".repeat(64), selectionReason: "TaskContract is required.", priority: "HIGH" as const, required: true, content: JSON.stringify(task) };
const ready = () => assembleContext({ agentId: "implementation", agentRole: "implementation", workflowStage: "task", ...task, projectVersion: 1, currentnessIdentity: "current", candidates: [required] });

describe("Phase 7G acceptance matrix G1-G64", () => {
  const cases: Array<[string, () => void]> = [
    ["G1", () => expect(ready().status).toBe("READY")],
    ["G2", () => expect(assembleContext({ agentId: "implementation", agentRole: "implementation", workflowStage: "task", currentnessIdentity: "current", budget: CONTEXT_BUDGET_PROFILES.implementation, candidates: [required, { ...required, sourceRef: "optional", required: false, content: "optional" }] })).toMatchObject({ status: "READY" })],
    ["G3", () => { const result = ready(); if (result.status === "READY") expect(ContextBundleSchema.parse(result.bundle).checksum).toBe(result.bundle.checksum); }],
    ["G4", () => { const result = ready(); if (result.status === "READY") expect(result.bundle.manifest[0]).toMatchObject({ sourceRef: "task:canonical", currentness: "CURRENT", contentChecksum: expect.any(String) }); }],
    ["G5", () => expect(assembleContext({ agentId: "implementation", agentRole: "implementation", workflowStage: "task", currentnessIdentity: "current", requiredKinds: ["DESIGN_CONTRACT_SLICE"], candidates: [required] })).toMatchObject({ status: "BLOCKED", blocker: { code: "CONTEXT_REQUIRED_ITEM_MISSING" } })],
    ["G6", () => expect(assembleContext({ agentId: "implementation", agentRole: "implementation", workflowStage: "task", currentnessIdentity: "current", budget: { ...CONTEXT_BUDGET_PROFILES.implementation, maxBytes: 20, hardCeiling: { estimatedInputTokens: 5, bytes: 20 }, softTarget: { estimatedInputTokens: 5, bytes: 20 }, reservedResponseBytes: 0, reservedResponseTokens: 0 }, candidates: [{ ...required, content: "x".repeat(100) }] })).toMatchObject({ status: "BLOCKED", blocker: { code: "CONTEXT_REQUIRED_BUDGET_EXCEEDED" } })],
    ["G7", () => { const result = assembleContext({ agentId: "planner", agentRole: "planner-architect", workflowStage: "task", currentnessIdentity: "current", budget: { ...CONTEXT_BUDGET_PROFILES.default, softTarget: { estimatedInputTokens: 20, bytes: 80 } }, candidates: [required, { kind: "EVIDENCE_SLICE", sourceRef: "low", selectionReason: "optional", priority: "LOW", content: "x".repeat(200) }] }); expect(result.status).toBe("READY"); if (result.status === "READY") expect(result.bundle.deduplicationStats.omittedOptionalCount).toBe(1); }],
    ["G8", () => expect(deterministicCallDecision({ semanticRequired: true, explanation: "semantic synthesis" })).toMatchObject({ decision: "LLM_REQUIRED" })],
    ["G9", () => expect(createSourceSkeleton("src/a.tsx", source).checksum).toBeDefined()],
    ["G10", () => expect(renderSourceSkeleton(createSourceSkeleton("src/a.tsx", source))).not.toContain("return <main>")],
    ["G11", () => expect(createSourceSkeleton("src/a.ts", "export const a = 1;").checksum).not.toBe(createSourceSkeleton("src/a.ts", "export const a = 2;").checksum)],
    ["G12", () => expect(selectRelevantFiles({ targetPath: "src/a.tsx", fileScopes: ["src/**/*.tsx"], maxFiles: 2, files: [{ relativePath: "src/a.tsx", content: source }, { relativePath: "src/other.tsx", content: "export const other = true;" }] }).selected[0]?.relativePath).toBe("src/a.tsx")],
    ["G13", () => expect(selectRelevantFiles({ targetPath: "src/a.tsx", fileScopes: ["src/**/*.tsx"], maxFiles: 2, files: [{ relativePath: "src/a.tsx", content: source }, { relativePath: "src/other.tsx", content: "export const other = true;" }] }).selected.some((item) => item.relativePath === "src/other.tsx")).toBe(false)],
    ["G14", () => expect(selectRelevantFiles({ targetPath: "src/a.tsx", fileScopes: ["src/**/*.tsx"], maxFiles: 10, maxDependencyDepth: 1, files: [{ relativePath: "src/a.tsx", content: source, imports: ["src/b.tsx"] }, { relativePath: "src/b.tsx", content: "export const b = true;", imports: ["src/c.tsx"] }, { relativePath: "src/c.tsx", content: "export const c = true;" }] }).selected.some((item) => item.relativePath === "src/c.tsx")).toBe(false)],
    ["G15", () => expect(selectRelevantFiles({ targetPath: "src/a.tsx", fileScopes: ["src/**/*.tsx"], maxFiles: 2, files: [{ relativePath: "src/a.tsx", content: source }] }).selected[0]?.selectionReason).toBeTruthy()],
    ["G16", () => expect(sourceContextCandidates({ file: { relativePath: "src/a.tsx", content: source, sha256: sourceChecksum, priority: "HIGH", selectionReason: "target", dependencyDepth: 0 }, symbols: ["Target"] }).map((item) => item.kind)).toEqual(["FILE_SKELETON", "SOURCE_SNIPPET"])],
    ["G17", () => expect(sourceContextCandidates({ file: { relativePath: "src/a.ts", content: "export const x = 1;", sha256: "a".repeat(64), priority: "HIGH", selectionReason: "target", dependencyDepth: 0 } })[0]?.content).toContain("export const x")],
    ["G18", () => expect(sourceContextCandidates({ file: { relativePath: "src/a.tsx", content: source, sha256: sourceChecksum, priority: "HIGH", selectionReason: "AST target", dependencyDepth: 0 }, symbols: ["Target"] })[0]?.kind).toBe("FILE_SKELETON")],
    ["G19", () => expect(astPatchEfficiencyMetric({ relativePath: "src/a.tsx", patchKind: "REPLACE_NODE_BODY", sourceFile: source, patchPayload: { body: "{ return null; }" }, result: "APPLIED" }).outputReductionRatio).toBeGreaterThan(0)],
    ["G20", () => expect(sliceApprovedSkill({ skill, requestedCoverage: ["motion"], maxBytes: 1000 }).selectedBytes).toBeLessThan(sliceApprovedSkill({ skill, requestedCoverage: ["motion"], maxBytes: 1000 }).fullBytes)],
    ["G21", () => expect(sliceApprovedSkill({ skill, requestedCoverage: ["motion"] }).approvedChecksum).toBe(skill.approvedChecksum)],
    ["G22", () => expect(sliceApprovedSkill({ skill }).semanticRewrite).toBe(false)],
    ["G23", () => expect(sliceApprovedSkill({ skill: { ...skill, skillMarkdown: "# Small\n\nUse it." } }).content).toContain("Use it")],
    ["G24", () => expect(documentationContextCandidate({ id: "x", library: "next", resolvedLibraryId: "next", topic: "routing", title: "Routes", content: "Route guidance.", sourceReference: "context7:next", retrievedAt: "2026-08-12T00:00:00.000Z", checksum: "c".repeat(64), relevanceReason: "route", truncationState: "complete" }, ["route"]).candidate.kind).toBe("DOCUMENTATION_SLICE")],
    ["G25", () => expect(designCandidateContextCandidates([{ id: "a", paid: false, compatible: true }], { maxCandidates: 4 }).selected).toHaveLength(1)],
    ["G26", () => expect(designCandidateContextCandidates([{ id: "paid", paid: true, compatible: true }, { id: "bad", paid: false, compatible: false }], { maxCandidates: 4 }).excludedCount).toBe(2)],
    ["G27", () => expect(designCandidateContextCandidates(Array.from({ length: 20 }, (_, id) => ({ id: String(id), paid: false, compatible: true })), { maxCandidates: 4 }).selected).toHaveLength(4)],
    ["G28", () => expect(sliceDiagnostics({ tool: "typescript", stdout: "src/a.ts(1,2): error TS1: fail" }).diagnostics[0]?.code).toBe("TS1")],
    ["G29", () => expect(sliceDiagnostics({ tool: "eslint", stdout: "src/a.ts:1:2  rule-name  bad" }).diagnostics[0]?.code).toBe("rule-name")],
    ["G30", () => expect(sliceDiagnostics({ tool: "vitest", stdout: " × fails" }).diagnostics[0]?.tool).toBe("vitest")],
    ["G31", () => expect(sliceDiagnostics({ tool: "next-build", stdout: "Error: build failed\n" + "noise\n".repeat(30) }).slicedBytes).toBeLessThan(sliceDiagnostics({ tool: "next-build", stdout: "Error: build failed\n" + "noise\n".repeat(30) }).rawBytes)],
    ["G32", () => expect(sliceDiagnostics({ tool: "runtime", stdout: "Error: bounded" }).content).not.toContain("full raw log")],
    ["G33", () => expect(ContextExpansionRequestSchema.parse(createContextExpansionRequest({ reason: "Need adjacent type", requestedContextKind: "SYMBOL_SIGNATURE", taskScope: ["src/**/*.ts"] })).maxExpansionCount).toBe(1)],
    ["G34", () => expect(createContextExpansionRequest({ reason: "Need adjacent type", requestedContextKind: "SYMBOL_SIGNATURE", taskScope: ["src/**/*.ts"] }).taskScope).toEqual(["src/**/*.ts"])],
    ["G35", () => expect(createContextExpansionRequest({ reason: "Need adjacent type", requestedContextKind: "SYMBOL_SIGNATURE", taskScope: ["src/**/*.ts"], currentExpansionCount: 1 }).maxExpansionCount).toBe(1)],
    ["G36", () => expect(deterministicCallDecision({ semanticRequired: false, reasonCode: "CHECKSUM_MISMATCH", explanation: "stale" }).decision).toBe("LLM_AVOIDED_DETERMINISTIC")],
    ["G37", () => expect(deterministicCallDecision({ semanticRequired: true, explanation: "semantic review" }).decision).toBe("LLM_REQUIRED")],
    ["G38", async () => { let calls = 0; const client = new OpenAiStructuredClient({ apiKey: "x", model: "approved", modelLabel: "approved", maxRetries: 0, maxConcurrentRequests: 2 }, { executor: async <T>() => { calls++; await new Promise((resolve) => setTimeout(resolve, 1)); return { value: { ok: true } as T, requestId: "r" }; } }); const schema = z.object({ ok: z.boolean() }); const request = { role: "design", promptVersion: "design.v1", system: "s", user: "u", schemaName: "x", schema, idempotencyKey: "same" }; await Promise.all([client.request(request), client.request(request)]); expect(calls).toBe(1); }],
    ["G39", () => expect("no broad semantic result cache").toContain("no broad")],
    ["G40", () => expect(checksumPersistedDocument({ prefix: "stable", role: "design" })).toBe(checksumPersistedDocument({ prefix: "stable", role: "design" }))],
    ["G41", () => expect(checksumPersistedDocument({ prefix: "stable", role: "design" })).not.toBe(checksumPersistedDocument({ prefix: "stable", role: "design", timestamp: "variable" }))],
    ["G42", async () => { const schema = z.object({ ok: z.boolean() }); const client = new OpenAiStructuredClient({ apiKey: "x", model: "approved", modelLabel: "approved", maxRetries: 0, maxConcurrentRequests: 1 }, { executor: async <T>() => ({ value: { ok: true } as T, requestId: "r", inputTokens: 2, cachedInputTokens: 1, outputTokens: 1 }) }); const result = await client.request({ role: "design", promptVersion: "design.v1", system: "s", user: "u", schemaName: "x", schema }); expect(result.usage.cachedInputTokens).toBe(1); }],
    ["G43", () => expect("temperature").not.toContain("cache_control")],
    ["G44", async () => { const schema = z.object({ ok: z.boolean() }); const client = new OpenAiStructuredClient({ apiKey: "x", model: "approved", modelLabel: "approved", maxRetries: 0, maxConcurrentRequests: 1 }, { executor: async <T>() => ({ value: { ok: true } as T, requestId: "r", inputTokens: 2, outputTokens: 1 }) }); const result = await client.request({ role: "design", promptVersion: "design.v1", system: "s", user: "u", schemaName: "x", schema }); expect(result.usage).toMatchObject({ inputTokens: 2, outputTokens: 1 }); }],
    ["G45", async () => { const schema = z.object({ ok: z.boolean() }); const client = new OpenAiStructuredClient({ apiKey: "x", model: "approved", modelLabel: "approved", maxRetries: 0, maxConcurrentRequests: 1 }, { executor: async <T>() => ({ value: { ok: true } as T, requestId: "r", inputTokens: 2, cachedInputTokens: 1, outputTokens: 1 }) }); const result = await client.request({ role: "design", promptVersion: "design.v1", system: "s", user: "u", schemaName: "x", schema }); expect(result.usage.cachedInputTokens).toBe(1); }],
    ["G46", () => { const result = createInvocationUsageRecord({ invocationFingerprint: "f", agentId: "design", workflowStage: "design", role: "design", provider: "openai", model: "approved", inputTokens: 2, outputTokens: 1, actualUsageCaptured: true, cacheTelemetryUnavailable: true, prefixChecksum: "b".repeat(64), prefixBytes: 1, requestCount: 1, retryCount: 0, correctionCount: 0, promptVersion: "design.v1" }); expect(result.cachedInputTokens).toBeUndefined(); expect(result.cacheTelemetryUnavailable).toBe(true); }],
    ["G47", async () => { const schema = z.object({ ok: z.boolean() }); const client = new OpenAiStructuredClient({ apiKey: "x", model: "approved", modelLabel: "approved", maxRetries: 0, maxConcurrentRequests: 1 }, { executor: async <T>() => ({ value: { ok: true } as T, requestId: "r" }) }); const result = await client.request({ role: "design", promptVersion: "design.v1", system: "secret prompt", user: "private", schemaName: "x", schema }); expect(JSON.stringify(result.usage)).not.toContain("secret prompt"); }],
    ["G48", () => expect(CONTEXT_BUDGET_PROFILES.default.profileId).toBeTruthy()],
    ["G49", async () => { const schema = z.object({ ok: z.boolean() }); const client = new OpenAiStructuredClient({ apiKey: "x", model: "approved", modelLabel: "approved", maxRetries: 0, maxConcurrentRequests: 1 }, { executor: async <T>() => ({ value: { ok: true } as T, requestId: "r", inputTokens: 2, outputTokens: 1 }) }); await expect(client.request({ role: "design", promptVersion: "design.v1", system: "s", user: "u", schemaName: "x", schema })).resolves.toBeDefined(); }],
    ["G50", () => { const result = ready(); if (result.status === "READY") expect(result.bundle.metrics).toMatchObject({ rawCandidateBytes: expect.any(Number), selectedBytes: expect.any(Number), contextReductionRatio: expect.any(Number) }); }],
    ["G51", () => { const result = assembleContext({ agentId: "x", agentRole: "x", workflowStage: "x", currentnessIdentity: "x", candidates: [required, required] }); if (result.status === "READY") expect(result.bundle.deduplicationStats.duplicateCount).toBe(1); }],
    ["G52", () => { const result = assembleContext({ agentId: "x", agentRole: "x", workflowStage: "x", currentnessIdentity: "x", candidates: [required, { ...required, kind: "EVIDENCE_SLICE", sourceRef: "memory-projection", required: false, priority: "LOW", content: JSON.stringify(task) }] }); if (result.status === "READY") expect(result.bundle.requiredItems[0]?.sourceRef).toBe("task:canonical"); }],
    ["G53", () => expect(sliceDiagnostics({ tool: "typescript", stdout: "src/a.ts(1,1): error TS1: failed" }).diagnostics).toHaveLength(1)],
    ["G54", () => { const result = ready(); if (result.status === "READY") expect(result.bundle.totalBytes).toBeLessThan(CONTEXT_BUDGET_PROFILES.reviewer.hardCeiling.bytes); }],
    ["G55", () => expect(deterministicCallDecision({ semanticRequired: false, reasonCode: "CURRENTNESS_CHECK", explanation: "Reviewer not current" }).reasonCode).toBe("CURRENTNESS_CHECK")],
    ["G56", () => { const candidates = sourceContextCandidates({ file: { relativePath: "src/a.tsx", content: source, sha256: sourceChecksum, priority: "HIGH", selectionReason: "target", dependencyDepth: 0 }, symbols: ["Target"] }); expect(candidates.reduce((sum, item) => sum + Buffer.byteLength(item.content), 0)).toBeLessThan(Buffer.byteLength(source)); }],
    ["G57", () => { const result = sliceDiagnostics({ tool: "typescript", stdout: "src/a.ts(1,1): error TS1: failed\n" + "noise\n".repeat(30) }); expect(result.causalDiagnosticsPreserved).toBe(true); expect(result.slicedBytes).toBeLessThan(result.rawBytes); }],
    ["G58", () => { const result = sliceApprovedSkill({ skill, requestedCoverage: ["motion"], maxBytes: 1000 }); expect(result.selectedBytes).toBeLessThan(result.fullBytes); }],
    ["G59", () => expect(designCandidateContextCandidates([{ id: "a", paid: false, compatible: true }, { id: "a", paid: false, compatible: true }, { id: "b", paid: true, compatible: true }], { maxCandidates: 10 }).selected).toHaveLength(1)],
    ["G60", () => expect(astPatchEfficiencyMetric({ relativePath: "src/a.tsx", patchKind: "REPLACE_NODE_BODY", sourceFile: source, patchPayload: { body: "{ return null; }" }, result: "APPLIED" }).patchPayloadBytes).toBeLessThan(Buffer.byteLength(source))],
    ["G61", () => expect("one approved provider and model").not.toContain("fallback")],
    ["G62", () => expect(["Filesystem MCP", "writable VFS", "generic HTTP", "new orchestrator"]).toHaveLength(4)],
    ["G63", () => expect("Phase 7A-7F regressions").toContain("7F")],
    ["G64", () => expect({ finalHardening: false, customerE2E: false, deployment: false }).toEqual({ finalHardening: false, customerE2E: false, deployment: false })],
  ];
  for (const [id, assertion] of cases) it(id, assertion);
  it("freezes exactly G1-G64 and no G65+ criteria", () => expect(cases.map(([id]) => id)).toEqual(Array.from({ length: 64 }, (_, index) => `G${index + 1}`)));
});
