-- Durable host-owned execution state for the isolated Planning Recovery boundary.
create table if not exists planning_recovery_runs (
  run_id uuid primary key,
  operation_key text not null check (length(operation_key) between 1 and 180),
  project_id uuid not null references factory_projects(id),
  project_version integer not null check (project_version > 0),
  foreign key (project_id, project_version) references project_versions(project_id, version_number),
  version_id uuid not null references project_versions(id),
  expected_source_head text,
  recovery_plan_checksum char(64) not null check (recovery_plan_checksum ~ '^[a-f0-9]{64}$'),
  recovery_plan jsonb not null check (jsonb_typeof(recovery_plan) = 'object'),
  project_row_version integer not null check (project_row_version > 0),
  project_version_row_version integer not null check (project_version_row_version > 0),
  brief_row_version integer not null check (brief_row_version > 0),
  brief_semantic_checksum char(64) not null check (brief_semantic_checksum ~ '^[a-f0-9]{64}$'),
  brief_document_checksum char(64) not null check (brief_document_checksum ~ '^[a-f0-9]{64}$'),
  planning_row_version integer not null check (planning_row_version > 0),
  planning_semantic_checksum char(64) not null check (planning_semantic_checksum ~ '^[a-f0-9]{64}$'),
  planning_document_checksum char(64) not null check (planning_document_checksum ~ '^[a-f0-9]{64}$'),
  provider_budget integer not null check (provider_budget >= 0),
  provider_attempt_count integer not null default 0 check (provider_attempt_count >= 0),
  state text not null check (state in ('CREATED','PROVIDER_CALL_STARTED','PROVIDER_RETURNED','ADMISSION_STARTED','ADMISSION_PASSED','PERSISTENCE_STARTED','COMMITTED','COMMITTED_RECONCILED','PROVIDER_FAILED','PROVIDER_SEMANTIC_FAILED','ADMISSION_FAILED','CURRENTNESS_FAILED','PERSISTENCE_FAILED','CANCELLED','ABANDONED','OUTCOME_INDETERMINATE')),
  provider_result_checksum char(64) check (provider_result_checksum is null or provider_result_checksum ~ '^[a-f0-9]{64}$'),
  provider_result jsonb check (provider_result is null or jsonb_typeof(provider_result) = 'object'),
  provider_request_id text,
  provider_model text,
  provider_error_class text,
  provider_error_code text,
  diagnostic_stage text,
  diagnostic_code text,
  diagnostic_message text check (diagnostic_message is null or length(diagnostic_message) <= 500),
  lease_owner text,
  lease_expires_at timestamptz,
  terminal_outcome text check (terminal_outcome is null or terminal_outcome in ('COMMITTED','COMMITTED_RECONCILED','PROVIDER_FAILED','PROVIDER_SEMANTIC_FAILED','ADMISSION_FAILED','CURRENTNESS_FAILED','PERSISTENCE_FAILED','CANCELLED','ABANDONED','OUTCOME_INDETERMINATE')),
  committed_evidence_id uuid references planning_recovery_evidence(id),
  project_memory_status text not null default 'PENDING' check (project_memory_status in ('PENDING','SYNCED','FAILED')),
  project_memory_failure_code text,
  project_memory_failure_message text check (project_memory_failure_message is null or length(project_memory_failure_message) <= 500),
  created_at timestamptz not null,
  updated_at timestamptz not null,
  unique(project_id, project_version, operation_key),
  check (provider_attempt_count <= provider_budget),
  check ((state = 'CREATED' and provider_attempt_count = 0 and lease_owner is null and lease_expires_at is null) or (state not in ('CREATED','COMMITTED','COMMITTED_RECONCILED','PROVIDER_FAILED','PROVIDER_SEMANTIC_FAILED','ADMISSION_FAILED','CURRENTNESS_FAILED','PERSISTENCE_FAILED','CANCELLED','ABANDONED','OUTCOME_INDETERMINATE') and lease_owner is not null and lease_expires_at is not null) or (state in ('COMMITTED','COMMITTED_RECONCILED','PROVIDER_FAILED','PROVIDER_SEMANTIC_FAILED','ADMISSION_FAILED','CURRENTNESS_FAILED','PERSISTENCE_FAILED','CANCELLED','ABANDONED','OUTCOME_INDETERMINATE') and lease_owner is null and lease_expires_at is null)),
  check ((provider_result_checksum is null and provider_result is null) or (provider_result_checksum is not null and provider_result is not null)),
  check ((state in ('COMMITTED','COMMITTED_RECONCILED','PROVIDER_FAILED','PROVIDER_SEMANTIC_FAILED','ADMISSION_FAILED','CURRENTNESS_FAILED','PERSISTENCE_FAILED','CANCELLED','ABANDONED','OUTCOME_INDETERMINATE') and terminal_outcome is not null) or (state not in ('COMMITTED','COMMITTED_RECONCILED','PROVIDER_FAILED','PROVIDER_SEMANTIC_FAILED','ADMISSION_FAILED','CURRENTNESS_FAILED','PERSISTENCE_FAILED','CANCELLED','ABANDONED','OUTCOME_INDETERMINATE') and terminal_outcome is null)),
  check ((state in ('COMMITTED','COMMITTED_RECONCILED') and committed_evidence_id is not null) or (state not in ('COMMITTED','COMMITTED_RECONCILED') and committed_evidence_id is null))
);
create index if not exists planning_recovery_runs_project_idx on planning_recovery_runs(project_id, project_version, created_at, run_id);
create index if not exists planning_recovery_runs_active_idx on planning_recovery_runs(state, lease_expires_at) where state not in ('COMMITTED','COMMITTED_RECONCILED','PROVIDER_FAILED','PROVIDER_SEMANTIC_FAILED','ADMISSION_FAILED','CURRENTNESS_FAILED','PERSISTENCE_FAILED','CANCELLED','ABANDONED','OUTCOME_INDETERMINATE');
alter table planning_recovery_runs enable row level security;
