import { describe, expect, it } from "vitest";
import { AgentTaskSchema, TaskGraphSchema, type AgentTask, type TaskGraph } from "../domain/tasks/schema";
import { QualityCheckSchema } from "../domain/quality/schema";
import { checksumPersistedDocument } from "../persistence/serialization";
import { FullExecutionError } from "./errors";
import { FullTaskGraphExecutor, reconcileFullExecution } from "./service";
import { graphChecksum, taskCategory, validateFullExecutionReadiness } from "./policy";
import type { ExecutionSummary, FullExecutionSnapshot, TaskExecutionOutcome, TaskExecutorPort, ExecutionStatePort, TaskGraphExecutionRun } from "./contracts";

const projectId = "11111111-1111-4111-8111-111111111111"; const ids = { foundation: "22222222-2222-4222-8222-222222222222", lint: "33333333-3333-4333-8333-333333333333", typecheck: "44444444-4444-4444-8444-444444444444", tests: "55555555-5555-4555-8555-555555555555", build: "66666666-6666-4666-8666-666666666666", qa: "77777777-7777-4777-8777-777777777777", release: "88888888-8888-4888-8888-888888888888" };
const checksum = "a".repeat(64); const lock = "b".repeat(64); const createdAt = "2026-01-01T00:00:00.000Z";
const base = (id: string, taskType: string, dependencies: string[], status: AgentTask["status"], role: AgentTask["role"] = taskType.startsWith("validate") ? "qa-release" : "implementation", allowedTools = taskType === "validate-functional-flow" ? ["filesystem-read", "Playwright-functional"] : ["filesystem-read", ...(role === "implementation" ? ["filesystem-write"] : [])]): AgentTask => AgentTaskSchema.parse({ id, projectId, projectVersion: 1, role, taskType, title: taskType, objective: `Execute ${taskType}`, requirementReferences: ["requirement:approved"], planningReferences: ["planning:approved"], selectedDesignReferences: [], inputs: ["approved input"], expectedOutputs: ["bounded outcome"], acceptanceCriteria: ["Approved behavior"], allowedSkills: [], allowedTools, deniedTools: ["git-write", "shell-restricted"], fileScopes: role === "implementation" ? [`src/${taskType}/**`] : [], dependencies, status, priority: "normal", executionMode: role === "implementation" ? "exclusive-write" : "validation-only", attempt: 0, maxAttempts: 2, createdAt, blockingFailure: true, estimatedContextBytes: 1000, expectedArtifactTypes: ["task-output"] });
function graph(includeAll = true): TaskGraph { const tasks = [base(ids.foundation, "implement-project-foundation", [], "ready"), base(ids.lint, "validate-lint", [ids.foundation], "pending"), ...(includeAll ? [base(ids.typecheck, "validate-typecheck", [ids.lint], "pending"), base(ids.tests, "validate-unit-tests", [ids.typecheck], "pending"), base(ids.build, "validate-build", [ids.tests], "pending"), base(ids.qa, "validate-functional-flow", [ids.build], "pending")] : []), base(ids.release, "prepare-release", [includeAll ? ids.qa : ids.lint], "pending", "qa-release")]; const raw = { schemaVersion: 1, documentType: "task-graph" as const, projectId, projectVersion: 1, createdAt, updatedAt: createdAt, tasks, checkpoint: "execution-ready" as const, readyForExecution: true, blockingReasons: [], warnings: [] }; return TaskGraphSchema.parse({ ...raw, graphChecksum: checksumPersistedDocument(raw) }); }
class MemoryState implements ExecutionStatePort { snapshot: FullExecutionSnapshot; summaries: ExecutionSummary[] = []; events: Array<{ type: string }> = []; constructor(initial: TaskGraph) { this.snapshot = { graph: initial, workflowState: "IMPLEMENTING", projectImmutable: false, workspaceValid: true, sourceDocumentChecksums: { brief: checksum }, currentDocumentChecksums: { brief: checksum }, toolPolicyVersion: "tools-v1", activeRunIds: [], qualityChecks: [] }; } async load() { return this.snapshot; } async save(input: { run: TaskGraphExecutionRun; graph: TaskGraph; workflowState: string }) { this.snapshot.graph = input.graph; this.snapshot.workflowState = input.workflowState; this.snapshot.activeRunIds = input.run.status === "completed" || input.run.status === "failed" || input.run.status === "cancelled" || input.run.status === "paused" ? [] : [input.run.runId]; this.snapshot.qualityChecks = input.run.qualityGateSummary; } async saveSummary(summary: ExecutionSummary) { this.summaries.push(summary); } async appendEvent(event: { runId: string; type: string; taskId?: string; safeCode?: string; timestamp: string }) { this.events.push(event); } }
const check = (name: "lint" | "typecheck" | "unit-tests" | "build" | "e2e", status: "passed" | "failed") => QualityCheckSchema.parse({ name, status, startedAt: createdAt, completedAt: createdAt, resultSummary: `${name} ${status}`, attempt: 0, required: true, command: `fake ${name}` });
function outcome(task: AgentTask, status: TaskExecutionOutcome["status"] = "passed", failure?: Partial<TaskExecutionOutcome>): TaskExecutionOutcome { return { taskId: task.id, status, classification: status === "passed" ? "retryable-task" : failure?.classification ?? "blocking-nonrepairable", repairable: Boolean(failure?.repairable), ...(failure ?? {}), ...(status === "passed" && task.taskType.startsWith("validate-") ? { qualityChecks: [check(task.taskType === "validate-functional-flow" ? "e2e" : task.taskType === "validate-unit-tests" ? "unit-tests" : task.taskType.replace("validate-", "") as "lint" | "typecheck" | "build", "passed")] } : {}) }; }
function input(g: TaskGraph, overrides: Partial<Parameters<typeof validateFullExecutionReadiness>[0]> = {}) { return { projectId, projectVersion: 1, idempotencyKey: "run-1", graph: g, expectedGraphChecksum: graphChecksum(g), workflowState: "IMPLEMENTING", projectImmutable: false, workspaceValid: true, sourceDocumentChecksums: { brief: checksum }, currentDocumentChecksums: { brief: checksum }, toolPolicyVersion: "tools-v1", activeRunIds: [], ...overrides }; }

describe("controlled full TaskGraph execution", () => {
  it("rejects stale, immutable, non-IMPLEMENTING, and conflicting starts", () => { const g = graph(false); expect(() => validateFullExecutionReadiness(input(g, { workflowState: "DRAFT" }))).toThrow(FullExecutionError); expect(() => validateFullExecutionReadiness(input(g, { projectImmutable: true }))).toThrow("Immutable"); expect(() => validateFullExecutionReadiness(input(g, { expectedGraphChecksum: lock }))).toThrow("stale"); expect(() => validateFullExecutionReadiness(input(g, { activeRunIds: [ids.foundation] }))).toThrow("active"); });
  it("routes tasks by category and executes only READY tasks", async () => { expect(taskCategory("implement-page")).toBe("implementation"); expect(taskCategory("validate-lint")).toBe("runtime-validation"); expect(taskCategory("validate-functional-flow")).toBe("functional-qa"); expect(taskCategory("unknown")).toBe("unsupported"); const g = graph(false); const state = new MemoryState(g); const calls: string[] = []; const executors: TaskExecutorPort = { implementation: async (context) => { calls.push(`implementation:${context.task.taskType}`); return outcome(context.task); }, runtimeValidation: async (context, operation) => { calls.push(`runtime:${operation}`); return outcome(context.task); } }; const run = await new FullTaskGraphExecutor(state, executors).execute(input(g)); expect(run.status).toBe("completed"); expect(calls).toEqual(["implementation:implement-project-foundation", "runtime:lint"]); expect(state.summaries[0]?.finalWorkflowState).toBe("VALIDATING"); });
  it("performs a targeted repair, reruns only the failed validation, and becomes release eligible", async () => { const g = graph(false); const state = new MemoryState(g); let failedOnce = false; const calls: string[] = []; const executors: TaskExecutorPort = { implementation: async (context) => { calls.push(context.task.taskType); return outcome(context.task); }, runtimeValidation: async (context) => { calls.push(context.task.taskType); if (!failedOnce) { failedOnce = true; return outcome(context.task, "failed", { classification: "repairable", repairable: true, safeFailureCode: "QUALITY_LINT_FAILED", safeFailureSummary: "Fake lint failure." }); } return outcome(context.task); } }; const run = await new FullTaskGraphExecutor(state, executors).execute(input(g)); expect(run.status).toBe("completed"); expect(run.repairCycles[0]?.status).toBe("passed"); expect(calls).toEqual(["implement-project-foundation", "validate-lint", "repair-targeted-failure", "validate-lint"]); expect(state.summaries[0]?.releaseEligible).toBe(true); });
  it("enforces the repair limit and reconciles orphan/stale runs", async () => { const g = graph(false); const state = new MemoryState(g); const executors: TaskExecutorPort = { implementation: async (context) => outcome(context.task), runtimeValidation: async (context) => outcome(context.task, "failed", { classification: "repairable", repairable: true, safeFailureCode: "QUALITY_LINT_FAILED" }) }; const run = await new FullTaskGraphExecutor(state, executors, undefined, { version: "test", maxConcurrency: 1, maxSchedulerIterations: 20, maxRepairCyclesPerTask: 0, maxTotalRepairCycles: 0, retryableTaskTypes: [], releaseBoundaryTaskTypes: ["prepare-release"], mandatoryQualityCheckNames: ["lint"], stopOnBlockingFailure: true }).execute(input(g)); expect(run.status).toBe("failed"); expect(run.safeFailureCode).toBe("FULL_EXECUTION_REPAIR_LIMIT_EXCEEDED"); const issues = reconcileFullExecution({ run, snapshot: state.snapshot, schedulerActive: false, activeTaskIds: [], qualityCheckPresent: false }); expect(issues.some((issue) => issue.code === "FULL_EXECUTION_QUALITY_STALE")).toBe(false); });
  it("supports cancellation without deleting the workspace and preserves completed work", async () => { const g = graph(false); const state = new MemoryState(g); const controller = new AbortController(); const executors: TaskExecutorPort = { implementation: async (context) => { const result = outcome(context.task); controller.abort(); return result; }, runtimeValidation: async (context) => outcome(context.task) }; const run = await new FullTaskGraphExecutor(state, executors).execute(input(g, { signal: controller.signal })); expect(run.status).toBe("cancelled"); expect(run.passedTaskIds).toContain(ids.foundation); expect(state.snapshot.workspaceValid).toBe(true); });
});
